<div id="container">
<?php if (!$this->allow()) : ?>
	<div class="grid_12 t_a_bottom">
		<?php echo $this->translator->translator('Member_Access_deny_desc'); ?>
	</div>
<?php else : 

$this->headTitle()->headTitle($this->translator->translator('tours_frontend_list_add_page_name'),'SET');

echo $this->headScript()->setFile($this->baseUrl().'/js/jquery/jquery.scrollTo.js');

$front_template = Zend_Registry::get('front_template');

$this->proForm->setEditor($this->serverUrl().$this->baseUrl());
$this->proForm->getEditor();

$tab_base_link = Zend_Controller_Front::getInstance()->getRequest()->getRequestUri();

$locale_direction = Eicra_Global_Variable::getSession()->site_direction;
$locale = Eicra_Global_Variable::getSession()->sess_lang;

$global_conf = Zend_Registry::get('global_conf');
$currency = new Zend_Currency($global_conf['default_locale']);

$frontController = Zend_Controller_Front::getInstance();
$param_group_id = $frontController->getRequest()->getParam('group_id');

$original_tab_counter = 6;
$list_page_route = 'Members-Tour-List/*';
?>

<script type="text/javascript">
var settingObj = {
					tab_base_link: '<?php echo $tab_base_link; ?>',
					template_folder: '<?php echo $front_template['theme_folder']; ?>',
					form_action : {
										form_id: 'formItem',
										hasTinyMCE: true,											
										currency_symbol:	"<?php echo $currency->getSymbol(); ?>",
										common_msg_field_id: 'actionMessage',
										dialog_container_id:	'dialog_container',
										dialog_progressbar_id:	'progressbar',
										field_toggle_action: [
											{
												from_field_tag	: 'input',
												from_field_id 	: 'billing_user_places_order_email_enable',
												to_field_id 	: 'billing_user_places_order_email_address',
												active_value	: 'yes',												
											},
											{
												from_field_tag	: 'input',
												from_field_id 	: 'billing_user_pay_invoice_email_enable',
												to_field_id 	: 'billing_user_pay_invoice_email_address',
												active_value	: 'yes',												
											},
											{
												from_field_tag	: 'input',
												from_field_id 	: 'billing_user_cancel_order_email_enable',
												to_field_id 	: 'billing_user_cancel_order_email_address',
												active_value	: 'yes',												
											}
										],										
										extra_field_for_reset: [
											{field_id : 'categoryTree', field_value: '' , field_type : 'html'},
											{field_id : 'selected_file_tours_image', field_value: '' , field_type : 'html'},
											{field_id : 'selected_file_spots_photo_gallery', field_value: '' , field_type : 'html'},
											{field_id : 'tours_parent', field_value: '0' , field_type : 'val'},
											{field_id : 'tours_image', field_value: '' , field_type : 'val'},
											{field_id : 'spots_photo_gallery', field_value: '' , field_type : 'val'},
											{field_id : 'dataId', field_value: '<?php echo $this->translator->translator("tours_tree_root"); ?> (0)' , field_type : 'html'}
										],
										extra_function_for_reset: function(){
											if(tinyMCE.get('tours_desc'))
											{
												tinyMCE.get('tours_desc').setContent('');
											}
											if(tinyMCE.get('transportation'))
											{
												tinyMCE.get('transportation').setContent('');
											}
											if(tinyMCE.get('feature_google_map'))
											{
												tinyMCE.get('feature_google_map').setContent('');
											}
											if(tinyMCE.get('tour_highlights'))
											{
												tinyMCE.get('tour_highlights').setContent('');
											}
											if(tinyMCE.get('itinerary_desc'))
											{
												tinyMCE.get('itinerary_desc').setContent('');
											}
											if(tinyMCE.get('payment_desc'))
											{
												tinyMCE.get('payment_desc').setContent('');
											}
											if(tinyMCE.get('trams_and_condition'))
											{
												tinyMCE.get('trams_and_condition').setContent('');
											}
											if(tinyMCE.get('tour_policy'))
											{
												tinyMCE.get('tour_policy').setContent('');
											}
											$('#billing_user_places_order_email_address').removeAttr('disabled');	
											$('#billing_user_pay_invoice_email_address').removeAttr('disabled');
											$('#billing_user_cancel_order_email_address').removeAttr('disabled');										
											$('a.back_btn_link').attr('href','<?php echo $this->url( array("module" => "Tours","controller" => "members", "action"  => "list" ,"group" => $param_group_id), $list_page_route,    true) ?>');
											commonRemoveTabs(settingObj);
										},
										category_tree:{
											category_tree_id: 'categoryTree',
											category_tree_input_field_id : 'tours_parent',
											category_tree_input_html_id : 'dataId',
											category_tree_dest_url: "<?php echo $this->url( array('module' => 'Tours','controller' => 'backend', 'action'     => 'parent' ), 'adminrout',    true) ?>",
											tree_view: {
												dragAndDrop : true,
												template: "<label><input type=\"radio\" name=\"radio\" />#= item.text #</label>",
												dataBound	: function(obj){
																													
															var treeView = $("#"+settingObj.form_action.category_tree.category_tree_id).data('kendoTreeView');
															var getitem = treeView.dataSource.get("<?php echo (!empty($this->category_info['id'])) ? $this->category_info['id'] : '0'; ?>");
															if(getitem)
															{
																var selectitem = treeView.findByUid(getitem.uid);
																treeView.select(selectitem);
															}
												},
												dataSource :  {
													transport: {
															read: {
																url: "<?php echo $this->url( array('module' => 'Tours','controller' => 'backendpro', 'action'     => 'toursgroup' ), 'adminrout',    true) ?>",
																dataType: "json",
																type: "POST",
																data : {expanded : true}, // true is enable null is disable
																complete: function(e) {																		
																	var json_arr = $.parseJSON(e.responseText);	
																	if(json_arr.status == 'ok')
																	{	
																		$.each(json_arr.TreeDataSource, function(key, arr_obj){
																			if(arr_obj['id'] == '0')
																			{																		
																				commonDynamicFieldGenrator(json_arr.dynamic_field_arr, settingObj);
																				<?php if($this->auth->getIdentity()->access_file_image_manager != '1'){ ?>
																					uploadSettingsStart(json_arr);
																				<?php } ?>	
																				var business_type = json_arr.businessType_options;
																				var option = '<option value=""><?php echo $this->translator->translator("tours_select_businessType"); ?></option>';
																				if(business_type)
																				{							
																					$.each(business_type, function(key, arr){ option += '<option value="'+arr.id+'">'+commonStripslashes(arr.business_type)+'</option>'; });						
																				}
																				$('#tours_type').html(option);
																			}
																		});																			
																	}
																	else
																	{
																	   commonMsgDialog(settingObj, json.msg);
																	   <?php if($this->auth->getIdentity()->access_file_image_manager != '1'){ ?>
																			uploadSettingsEnd();			
																		<?php } ?>															
																	}
																}
															}
														},
														schema: {
															data: 'TreeDataSource',
															model: {
																id : 'id',
																text : 'text' ,
																hasChildren: 'hasChildren'  
															}
														}	
												}
											}
										},
										dynamic_field_generator: {
											has_tab	: true,
											tab_id	: 'tabs',
											html_input_id: 'dynamic_fields',												
											uploader_upload_url: '<?php echo $this->url( array('module' => 'Portfolio','controller' => 'frontend', 'action'     => 'upload'), 'adminrout',    true) ?>',
											uploader_remove_url: '<?php echo $this->url( array('module' => 'Portfolio','controller' => 'frontend', 'action'     => 'remove'), 'adminrout',    true) ?>',
											constants: {
													DYNAMIC_FIELD_GROUP_TITLE 		: 	'<?php echo Eicra_File_Constants::DYNAMIC_FIELD_GROUP_TITLE; ?>',
													DYNAMIC_FIELD_GROUP_ELEMENTS	:	'<?php echo Eicra_File_Constants::DYNAMIC_FIELD_GROUP_ELEMENTS; ?>',
													DATE							:	'<?php echo Eicra_File_Constants::DATE; ?>',
													PRICE							:	'<?php echo Eicra_File_Constants::PRICE; ?>'
											},
											langueges:{
												common_go_top_title: "<?php echo html_entity_decode($this->translator->translator('common_go_top_title'), ENT_QUOTES, 'UTF-8'); ?>",
											},
											after_add_function : function(){
												//qToolTipFunctions();
											}

										}
								},
					dynamic_list_action: [
																{
																	list_id:'country_id',
																	sub_list: {
																		list_id:'state_id',
																		list_dest_url: '<?php echo $this->url( array('module' =>'Tours','controller' => 'backendpro', 'action' => 'states' ), 'adminrout',    true) ?>',
																		list_any_value: '<?php echo html_entity_decode($this->translator->translator("tours_select_state"), ENT_QUOTES, 'UTF-8'); ?>',
																		list_input_value_field: 'state_id',
																		list_input_option_field: 'state_name',
																		list_return_field: 'states',
																		list_loader_info : {
																					loader_id : 'state_id_loader',
																					loader_img : 'application/modules/Administrator/layouts/scripts/images/loader/ajax_loader.gif',
																					on_loading : [
																									{id : 'state_id', type:'html', loading_lang: '<?php echo html_entity_decode($this->translator->translator("common_loading_language"), ENT_QUOTES, 'UTF-8'); ?>', normal_lang: '<?php echo html_entity_decode($this->translator->translator("tours_select_state"), ENT_QUOTES, 'UTF-8'); ?>'},
																									{id : 'area_id', type:'html', loading_lang: '<?php echo html_entity_decode($this->translator->translator("tours_select_area"), ENT_QUOTES, 'UTF-8'); ?>', normal_lang: '<?php echo html_entity_decode($this->translator->translator("tours_select_area"), ENT_QUOTES, 'UTF-8'); ?>'}
																								]
																			},
																		sub_list:{
																			list_id:'area_id',
																			list_dest_url: '<?php echo $this->url( array('module' =>'Tours','controller' => 'backendpro', 'action' => 'areas' ), 'adminrout',    true) ?>',
																			list_any_value: '<?php echo html_entity_decode($this->translator->translator("tours_select_area"), ENT_QUOTES, 'UTF-8'); ?>',
																			list_input_value_field: 'city_id',
																			list_input_option_field: 'city',
																			list_return_field: 'cities',
																			list_loader_info : {
																						loader_id : 'area_id_loader',
																						loader_img : 'application/modules/Administrator/layouts/scripts/images/loader/ajax_loader.gif',
																						on_loading : [
																										{id : 'area_id', type:'html', loading_lang: '<?php echo html_entity_decode($this->translator->translator("common_loading_language"), ENT_QUOTES, 'UTF-8'); ?>', normal_lang: '<?php echo html_entity_decode($this->translator->translator("tours_select_area"), ENT_QUOTES, 'UTF-8'); ?>'}
																									]
																				}
																		}
																	}
																}
														],
					calendar:	{
									calendar_include_time: true,	
									calendar_img_link: 'application/layouts/scripts/<?php echo $front_template['theme_folder']; ?>/images/mod_img/calendar-small.png',
									monthNamesShort: <?php echo $this->translator->translator("common_calender_monthNamesShort"); ?>,
									monthNames:		<?php echo $this->translator->translator("common_calender_monthNames"); ?>,
									dayNamesMin:		<?php echo $this->translator->translator("common_calender_dayNamesMin"); ?>,
									buttonText:		'calendar',
									dateFormat:		'yy-mm-dd',
									dateTimeFormat:     "yyyy-MM-dd HH:mm:ss tt",
									culture: "<?php echo str_ireplace('_', '-', $locale); ?>",
									value: ''
					},
					messages: {
									display				: 	'<?php echo $this->translator->translator("portfolio_pagination_messages_display", '', 'Portfolio'); ?>',
									empty				:	'<?php echo $this->translator->translator("portfolio_pagination_messages_empty", '', 'Portfolio'); ?>',
									page				:	'<?php echo $this->translator->translator("portfolio_pagination_messages_page", '', 'Portfolio'); ?>',
									of					:	'<?php echo $this->translator->translator("portfolio_pagination_messages_of", '', 'Portfolio'); ?>',
									itemsPerPage		:	'<?php echo $this->translator->translator("portfolio_pagination_messages_items_per_page", '', 'Portfolio'); ?>',
									first				:	'<?php echo $this->translator->translator("portfolio_pagination_messages_first", '', 'Portfolio'); ?>',
									previous			:	'<?php echo $this->translator->translator("portfolio_pagination_messages_previous", '', 'Portfolio'); ?>',
									next				:	'<?php echo $this->translator->translator("portfolio_pagination_messages_next", '', 'Portfolio'); ?>',
									last				:	'<?php echo $this->translator->translator("portfolio_pagination_messages_last", '', 'Portfolio'); ?>',
									refresh				:	'<?php echo $this->translator->translator("portfolio_pagination_messages_refresh", '', 'Portfolio'); ?>',
									
									common_msg_dialog_id 		:	'dialog_msg',
									common_confirn_dialog_id	:	'dialog-confirm',
									common_ok					:	"<?php echo html_entity_decode($this->translator->translator('common_ok'), ENT_QUOTES, 'UTF-8'); ?>",
									common_delete_selected		:	"<?php echo html_entity_decode($this->translator->translator("common_delete_selected"), ENT_QUOTES, 'UTF-8'); ?>",
									common_cancel				:	"<?php echo html_entity_decode($this->translator->translator("common_cancel"), ENT_QUOTES, 'UTF-8'); ?>",										
									common_publish_title		:	"<?php echo $this->translator->translator("common_publish_title"); ?>",
									common_unpublish_title		:	"<?php echo $this->translator->translator("common_unpublish_title"); ?>",										
									common_publish_selected		:	"<?php echo $this->translator->translator("common_publish_selected"); ?>",
									common_unpublish_selected	:	"<?php echo $this->translator->translator("common_unpublish_selected"); ?>",
									common_publish_perm	 		:	"<?php echo $this->translator->translator("common_publish_perm"); ?>"
								}
					};
					
<?php
	if($this->auth->getIdentity()->allow_to_change_ownership == '1')
	{
?>
	$(function() {
		$( "#tours_operator" ).combobox();
	})
<?php
	}
?>

$(function() {
	$("#tabs").tabs().find(".ui-tabs-nav").sortable({axis:'xy'});
});

$(document).ready(function() {
	
	commonDynamicListAction(settingObj);
	commonFieldToggle(settingObj);	
	
	/**********Scrolling Tools Start****************/
	$.easing.elasout = function(x, t, b, c, d) {
		var s=1.70158;var p=0;var a=c;
		if (t==0) return b;  if ((t/=d)==1) return b+c;  if (!p) p=d*.3;
		if (a < Math.abs(c)) { a=c; var s=p/4; }
		else var s = p/(2*Math.PI) * Math.asin (c/a);
		return a*Math.pow(2,-10*t) * Math.sin( (t*d-s)*(2*Math.PI)/p ) + c + b;
	};
	
	$('#toc a').click(function(){//$.scrollTo works EXACTLY the same way, but scrolls the whole screen
		$.scrollTo( this.hash, 1500, { easing:'swing' });
		$(this.hash).find('span.message').text( this.title );
		return false;
	});
	
	$('span.top-go a').click(function(){//$.scrollTo works EXACTLY the same way, but scrolls the whole screen
		$.scrollTo( this.hash, 1500, { easing:'swing' });		
		return false;
	});	
	/**********Scrolling Tools END****************/
		
	
	$("#upload-form").dialog({
		autoOpen: false,
		width: 760,
		height: 610,
		show: 'fade',
		modal: true
	});

	$('a.upload_btn').click(function() {
		var self = this;
		var src = $("#i-upload-form").attr("src");
		$("#i-upload-form").attr("src", 'application/modules/Administrator/layouts/scripts/images/loader/manager_loader.gif');
		
		var group_id = $("#group_id").val();
		$('input[name="primary_id_field_value"]').val(group_id);
		
		var rel = $(self).attr('rel');		
		var file_suffix = rel;	
		var file_content = $('#'+file_suffix).val();
		
		$('input[name="file_path_field"]').val('file_path_'+rel);
		$('input[name="file_content"]').val(file_content);		
		$('input[name="primary_file_field"]').val(file_suffix);		
		
		if(group_id != null && group_id != "")
		{
			$("#popupForm").attr("action", "<?php echo $this->url( array('module' => 'Portfolio','controller' => 'frontend', 'action' => 'manager' ), 'adminrout',    true) ?>");			
			$('#upload-form').dialog('open');
			$('#popupForm').submit();
		}
		else
		{
			msg = "<?php echo $this->translator->translator("group_id_selected_err"); ?>";
			commonMsgDialog(settingObj, msg);
		}
	});

	$('a.select_file_btn').click(function() {

			var currentIFrame = $('#i-upload-form');
			var selected_files = currentIFrame.contents().find("input[name='selected_files']").val();
			var primary_file_field = currentIFrame.contents().find("input[name='primary_file_field']").val();
			var file_path	=	currentIFrame.contents().find("input[name='file_path']").val();
			var selected_files_arr = (selected_files != '') ? selected_files.split(',') : new Array();	
			if(selected_files_arr.length == '0')
			{
				var msg = "<?php echo $this->translator->translator("insert_selected_file_err"); ?>";				
				commonMsgDialog(settingObj, msg);
			}
			else
			{
				var img_code = '';
				var file_name = '';
				for(var i=0;i < selected_files_arr.length;i++)
				{
					var ext = getCommonFileExtension(selected_files_arr[i]);
					var img_path = commonFilePath(file_path, selected_files_arr[i]);
										
					var checked = (i == 0)? ' checked="checked" ' : '';
					var img_type = 	(i == 0) ? "<span class='main'><?php echo $this->translator->translator('gallery_img_main', '', 'Gallery'); ?></span>" : "<span class='related'><?php echo $this->translator->translator('gallery_img_related', '', 'Gallery'); ?></span>";
					var primary_file_field_radio =	(primary_file_field == 'tours_image') ? 'traveler_photos'	: 'feature_primary_floor_image';						
					var primary =  '<input class="radio_style" type="radio" name="'+primary_file_field_radio+'" id="'+primary_file_field_radio+'" '+checked+' value="'+selected_files_arr[i]+'" title="<?php echo $this->translator->translator("traveler_photos"); ?>" />';
					var del_link = '<a href="javascript:void(0)" class="delete_image_lnk" rel="'+selected_files_arr[i]+'"><?php echo html_entity_decode($this->translator->translator("common_delete"), ENT_QUOTES, "UTF-8"); ?></a>'+primary;
					
					img_code += '<div class="upload-img box">'+img_type+'<br /><span><div class="thumb"><img src="'+img_path+'" width="30" height="20" class="bdr" /></div><br />'+del_link+'&nbsp;</span></div>';
					file_name = (i == 0)? selected_files_arr[i] : file_name+','+selected_files_arr[i];					
				}			
				var file_suffix = primary_file_field;		
				$('#selected_file_'+file_suffix).html(img_code);		
				$('#'+file_suffix).val(file_name);		
				$("#i-upload-form").attr("src", 'application/modules/Administrator/layouts/scripts/images/loader/manager_loader.gif'); 						
				$("#upload-form").dialog('option','hide','explode').dialog('close');				
				deleteFiles("<?php echo $this->translator->translator('gallery_img_main', '', 'Gallery'); ?>", "<?php echo $this->translator->translator('gallery_img_related', '', 'Gallery'); ?>", "<?php echo $this->url( array('module' => 'Portfolio','controller' => 'frontend', 'action'     => 'remove' ), 'adminrout',    true) ?>", "<?php echo $this->translator->translator('common_delete_title'); ?>");	
				commonImageThumbnil();
			}
		});

	$('a.close_dialog_btn').click(function() {
		$("#i-upload-form").attr("src", "");
		$("#i-upload-form").html('');
		$("#upload-form").dialog('option','hide','explode').dialog('close');
	});
		
	$('a.reset_btn').click(function() {			
		 commonResetFormFields(settingObj);	
		 commonRemoveFormError(settingObj);	
		 <?php if($this->auth->getIdentity()->access_file_image_manager != '1'){ ?>
			  uploadSettingsEnd();			
		  <?php } ?>			 
	});
	
	$('a.add_tours_btn').click(function() {

		var formData = commonGetFormData(settingObj.form_action.form_id, settingObj.form_action.hasTinyMCE);

		$.ajax({
			url: "<?php echo $this->url( array('module' => 'Tours','controller' => 'backendpro', 'action'     => 'add' ), 'adminrout',    true) ?>",
			  	type: 'POST',
			  	data: formData,
				beforeSend: function(){
						commonRemoveFormError(settingObj);
						commonOpenLoaderDialog(settingObj);
					 },
				success: function(response){
					//alert(response);
					var json_arr = eval("("+response+")");
					commonCloseLoaderDialog(settingObj);
					if(json_arr.status == 'ok')
					{
						$('#actionMessage').html(succMsgDesign(json_arr.msg));
						commonResetFormFields(settingObj);	
						<?php if($this->auth->getIdentity()->access_file_image_manager != '1'){ ?>
							uploadSettingsEnd();			
						<?php } ?>	
					}
					else if(json_arr.status == 'errV')
					{
						$('#actionMessage').html(errMsgDesign("<?php echo $this->translator->translator('common_err'); ?>"));

						for(var i= 0; i < json_arr.msg.length; i++)
						{
							commonAddFormError(json_arr.msg[i].key,json_arr.msg[i].value);
						}
						openFirstErrTab(json_arr.msg, 'tabs', 'tabs-');
					}
					else
					{
						$('#actionMessage').html(errMsgDesign(json_arr.msg));
					}
				},
				error: function(xhr, status, error){
					commonCloseLoaderDialog(settingObj);
					var msg = "Error! " + xhr.status + " " + error;
					$('#actionMessage').html(msg);
				}
		});
	});
	
/***********************************Get Tours Group***************************************/
	$('select[name="group_id"]').change(function() {		
		var group_id = $('#group_id').val();
		$("#"+settingObj.form_action.category_tree.category_tree_input_html_id).html('<?php echo $this->translator->translator("common_tree_root"); ?> (0)');
		$("#"+settingObj.form_action.category_tree.category_tree_input_field_id).val('0');
		commonRemoveTabs(settingObj);
		if(group_id != '')
		{
			settingObj.form_action.category_tree.tree_view.dataSource.transport.read.data['grp_id'] = group_id;
			$('a.back_btn_link').attr('href','Members-Tour-List/group/'+group_id);
			commonKendoTreeGen(settingObj);
		}
		else
		{	
			<?php if($this->auth->getIdentity()->access_file_image_manager != '1'){ ?>
				uploadSettingsEnd();			
			<?php } ?>	
			var option = '<option value=""><?php echo $this->translator->translator("tours_select_businessType"); ?></option>';
			$('#tours_type').html(option);
			commonDestroyKendoTreeGen(settingObj);					
			$('a.back_btn_link').attr('href','Members-Tour-List');
		}		
		$('#group_id_err').html('');		
	});	
});


/***********************************************************************UPLOAD FUNCTIONS START********************************************************/

function uploadSettingsStart(json_arr)
{
	uploadSettingsEnd();
		
	$('#tours_image_block').prepend('<input type="file" name="tours_image_upload" id="tours_image_upload" />');	
	var thumb_setting_param = json_arr.param_fields;
	thumb_setting_param['file_path_field'] = 'file_path_tours_image';	
	var thumb_setting_info = getSettingInfo(json_arr.group_info, thumb_setting_param);							
	dynamicUploader('tours_image_upload', 'tours_image', thumb_setting_info, languageArray(), "<?php echo $this->url( array('module' => 'Portfolio','controller' => 'frontend', 'action'     => 'upload'), 'adminrout',    true) ?>", "<?php echo $this->url( array('module' => 'Portfolio','controller' => 'frontend', 'action'     => 'remove'), 'adminrout',    true) ?>", true);
	
	$('#spots_photo_gallery_block').prepend('<input type="file" name="spots_photo_gallery_upload" id="spots_photo_gallery_upload" />');	
	var file_setting_param = json_arr.param_fields;		
	thumb_setting_param['file_path_field'] = 'file_path_spots_photo_gallery';	
	var file_setting_info = getSettingInfo(json_arr.group_info, file_setting_param);							
	dynamicUploader('spots_photo_gallery_upload', 'spots_photo_gallery', file_setting_info, languageArray(), "<?php echo $this->url( array('module' => 'Portfolio','controller' => 'frontend', 'action'     => 'upload'), 'adminrout',    true) ?>", "<?php echo $this->url( array('module' => 'Portfolio','controller' => 'frontend', 'action'     => 'remove'), 'adminrout',    true) ?>", true);
	
	$('#tours_image_err').html("");
	$('#spots_photo_gallery_err').html("");
}

function uploadSettingsEnd()
{	
	$('#tours_image_upload').parents('div.k-upload').remove();	
	$('#spots_photo_gallery_upload').parents('div.k-upload').remove();	
	$('#tours_image_err').html("<?php echo $this->translator->translator("group_id_selected_err"); ?>");
	$('#spots_photo_gallery_err').html("<?php echo $this->translator->translator("group_id_selected_err"); ?>");
}

function languageArray()
{
	var language_array = [];
	language_array['portfolio_upload_dy_text_select'] 					= "<?php echo html_entity_decode($this->translator->translator("portfolio_upload_dy_text_select", '', 'Portfolio'), ENT_QUOTES, 'UTF-8'); ?>";
	language_array['portfolio_upload_text_cancel'] 						= "<?php echo html_entity_decode($this->translator->translator("portfolio_upload_text_cancel", '', 'Portfolio'), ENT_QUOTES, 'UTF-8'); ?>";
	language_array['portfolio_upload_text_dropFilesHere'] 				= "<?php echo html_entity_decode($this->translator->translator("portfolio_upload_text_dropFilesHere", '', 'Portfolio'), ENT_QUOTES, 'UTF-8'); ?>";
	language_array['portfolio_upload_text_remove'] 						= "<?php echo html_entity_decode($this->translator->translator("portfolio_upload_text_remove", '', 'Portfolio'), ENT_QUOTES, 'UTF-8'); ?>";
	language_array['portfolio_upload_text_retry'] 						= "<?php echo html_entity_decode($this->translator->translator("portfolio_upload_text_retry", '', 'Portfolio'), ENT_QUOTES, 'UTF-8'); ?>";
	language_array['portfolio_upload_text_statusFailed'] 				= "<?php echo html_entity_decode($this->translator->translator("portfolio_upload_text_statusFailed", '', 'Portfolio'), ENT_QUOTES, 'UTF-8'); ?>";
	language_array['portfolio_upload_text_statusUploaded'] 				= "<?php echo html_entity_decode($this->translator->translator("portfolio_upload_text_statusUploaded", '', 'Portfolio'), ENT_QUOTES, 'UTF-8'); ?>";
	language_array['portfolio_upload_text_statusUploading'] 			= "<?php echo html_entity_decode($this->translator->translator("portfolio_upload_text_statusUploading", '', 'Portfolio'), ENT_QUOTES, 'UTF-8'); ?>";
	language_array['portfolio_upload_text_uploadSelectedFiles'] 		= "<?php echo html_entity_decode($this->translator->translator("portfolio_upload_text_uploadSelectedFiles", '', 'Portfolio'), ENT_QUOTES, 'UTF-8'); ?>";
	language_array['portfolio_file_extension_dy_support'] 				= "<?php echo $this->translator->translator("portfolio_file_extension_dy_support", '', 'Portfolio'); ?>";
	language_array['portfolio_file_no_ext_dy_support'] 					= "<?php echo $this->translator->translator("portfolio_file_no_ext_dy_support", '', 'Portfolio'); ?>";
	language_array['portfolio_file_extension_dy_not_supportable_ext1'] 	= "<?php echo $this->translator->translator("portfolio_file_extension_dy_not_supportable_ext1", '', 'Portfolio'); ?>";
	language_array['portfolio_file_extension_dy_not_supportable_ext2']  = "<?php echo $this->translator->translator("portfolio_file_extension_dy_not_supportable_ext2", '', 'Portfolio'); ?>";
	language_array['portfolio_file_size_dy_support'] 					= "<?php echo $this->translator->translator("portfolio_file_size_dy_support", '', 'Portfolio'); ?>";
	language_array['portfolio_file_upload_err'] 						= "<?php echo $this->translator->translator("portfolio_file_upload_err", '', 'Portfolio'); ?>";
	return language_array;
}


function successFileDecoretion(fileObj, serverData, upload_field, upload_value_field)
{
		var extension = fileObj.extension;
		var ext = extension.replace('.','');	
		
		var img_path = commonFilePath(serverData.file_path, fileObj.name);
				
		var img_code = '<div class="thumb"><img src="'+img_path+'" title="'+fileObj.name+'" width="30" height="20" /></div>';		 
		var down_link = (!isImage(fileObj)) ? '<br /><a href="'+serverData.file_path+'/'+fileObj.name+'"><?php echo $this->translator->translator("common_download", "", "Projects"); ?></a>' : '';
		
		var checked = '';
		var primary = '&nbsp;&nbsp;&nbsp;';	
		var block = 'selected_file_'+upload_value_field;
		var img_type = '';	
		var primary_file_field_radio = '';		
		switch(upload_value_field)
		{
			case 'tours_image':	
					checked = ($('#'+upload_value_field).val() == '') ? ' checked="checked" ' : '';	
					primary_file_field_radio =	 'traveler_photos';						
					img_type = 	($('#'+upload_value_field).val() == '') ? "<span class='main'><?php echo $this->translator->translator('gallery_img_main', '', 'Gallery'); ?></span><br />" : "<span class='related'><?php echo $this->translator->translator('gallery_img_related', '', 'Gallery'); ?></span><br />";				
					primary = '<input class="radio_style" type="radio" name="'+primary_file_field_radio+'" id="'+primary_file_field_radio+'" '+checked+' value="'+fileObj.name+'" title="<?php echo $this->translator->translator("traveler_photos"); ?>" />';
				break;
			case 'spots_photo_gallery':
					checked = ($('#'+upload_value_field).val() == '') ? ' checked="checked" ' : '';		
					primary_file_field_radio =	'feature_primary_floor_image';	
					img_type = 	($('#'+upload_value_field).val() == '') ? "<span class='main'><?php echo $this->translator->translator('gallery_img_main', '', 'Gallery'); ?></span><br />" : "<span class='related'><?php echo $this->translator->translator('gallery_img_related', '', 'Gallery'); ?></span><br />";		
					primary = '<input class="radio_style" type="radio" name="'+primary_file_field_radio+'" id="'+primary_file_field_radio+'" '+checked+' value="'+fileObj.name+'" title="<?php echo $this->translator->translator("tours_primary_floor_image"); ?>" />';
				break;
		}
		
		var del_link = '<a href="javascript:void(0)" class="delete_uploaded_image_link" field_name="'+upload_value_field+'" file_name="'+fileObj.name+'" file_path="'+serverData.file_path+'"><?php echo $this->translator->translator("common_delete_title"); ?></a>'+primary +  down_link;
		
		if(serverData.multi)
		{		
			$('#'+block).append('<div class="upload-img box">'+img_type+'<span>'+img_code+'<br />&nbsp;'+del_link+'&nbsp;</span></div>');				 
			var file_val = ($('#'+upload_value_field).val() == '') ? fileObj.name :  $('#'+upload_value_field).val()+','+fileObj.name;	
		}
		else
		{
			$('#'+block).html('<div class="upload-img box">'+img_type+'<span>'+img_code+'<br />&nbsp;'+del_link+'&nbsp;</span></div>');				 
			var file_val = fileObj.name;
		}
		$('#'+upload_value_field).val(file_val);
		deleteFiles("<?php echo $this->translator->translator('gallery_img_main', '', 'Gallery'); ?>", "<?php echo $this->translator->translator('gallery_img_related', '', 'Gallery'); ?>", "<?php echo $this->url( array('module' => 'Portfolio','controller' => 'frontend', 'action'     => 'remove' ), 'adminrout',    true) ?>", "<?php echo $this->translator->translator('common_delete_title'); ?>");	
		commonImageThumbnil();	
}

function onComplete(e) {
			
}

function onCancel(e) {
	
}

function onProgress(e) {
					
}

/***********************************************************************UPLOAD FUNCTIONS END********************************************************/
$(function() {
		$("#availabe_from").datepicker({
			showOn: 'button',
			buttonImage: 'application/layouts/scripts/<?php echo $front_template['theme_folder']; ?>/images/mod_img/calendar-small.png',
			buttonImageOnly: true,
			showAnim: 'slide',
			buttonText: 'Calender',
			dateFormat:'yy-mm-dd',
			autoSize:false,
			showButtonPanel:false,
			changeMonth: true,
			changeYear: true
		});
		$("#available_to").datepicker({
			showOn: 'button',
			buttonImage: 'application/layouts/scripts/<?php echo $front_template['theme_folder']; ?>/images/mod_img/calendar-small.png',
			buttonImageOnly: true,
			showAnim: 'blind',
			buttonText: 'Calender',
			dateFormat:'yy-mm-dd',
			autoSize:false,
			showButtonPanel:false,
			changeMonth: true,
			changeYear: true
		});
		$("#available_expire_date").datepicker({
			showOn: 'button',
			buttonImage: 'application/layouts/scripts/<?php echo $front_template['theme_folder']; ?>/images/mod_img/calendar-small.png',
			buttonImageOnly: true,
			showAnim: 'fadeIn',
			buttonText: 'Calender',
			dateFormat:'yy-mm-dd',
			autoSize:false,
			showButtonPanel:false,
			changeMonth: true,
			changeYear: true
		});
		$("#journey_start_date").datepicker({
			showOn: 'button',
			buttonImage: 'application/layouts/scripts/<?php echo $front_template['theme_folder']; ?>/images/mod_img/calendar-small.png',
			buttonImageOnly: true,
			showAnim: 'fold',
			buttonText: 'Calender',
			dateFormat:'yy-mm-dd',
			autoSize:false,
			showButtonPanel:false,
			changeMonth: true,
			changeYear: true
		});
		
		
		$("img[class='ui-datepicker-trigger']").each(function(){
			$(this).attr('style', '');
		 });
	});
</script>


<div class="title-container">
	<div class="products-add"><h1><?php echo $this->translator->translator('tours_frontend_list_add_page_name'); ?></h1></div>
    
    <div class="button-container">
        <span class="button ui-widget-content-1"><a href="<?php echo $this->url( array('module' => 'Tours','controller' => 'members', 'action'     => 'list' ,'group' => $param_group_id), $list_page_route,    true) ?>" class="back_btn_link"><span class="icon back"><?php echo $this->translator->translator('common_back'); ?></span></a></span>
        <span class="button ui-widget-content-1"><a href="javascript:  void(0);" class="reset_btn"><span class="icon reset"><?php echo $this->translator->translator('common_reset'); ?></span></a></span>
        <span class="button ui-widget-content-1"><a href="javascript: void(0);" class="add_tours_btn"><span class="icon save"><?php echo $this->translator->translator('common_save'); ?></span></a></span>
    </div>
</div>

<div class="content-container clear" id="topGo">
	<div id="sidebar-inner">
    	<div id="nav" class="member-block <?php if($locale_direction == 'rtl'){ ?>k-rtl<?php } ?>">
    		<div class="block-heading"><div class="symbol"><?php echo $this->translator->translator('tours_tree'); ?></div></div>
    		<div id="categoryTree" class="block-body">
           		&nbsp;	
            </div>
       	</div>
    </div>
    
    <div id="content-inner">
    	<div id="actionMessage"></div>
        <div id="button_top_bar"></div>
        <form name="formItem" id="formItem" method="post">
        	<div id="generalInfo">
            	<div id="tabs">
                	<ul>
                        <li><a href="<?php echo $tab_base_link; ?>#tabs-1"><?php echo $this->translator->translator('tours_general_info'); ?></a></li>
                        <li><a href="<?php echo $tab_base_link; ?>#tabs-2"><?php echo $this->translator->translator('tours_page_page_image'); ?></a></li>
                        <li><a href="<?php echo $tab_base_link; ?>#tabs-3"><?php echo $this->translator->translator('tours_page_amenities'); ?></a></li>
                        <li><a href="<?php echo $tab_base_link; ?>#tabs-4"><?php echo $this->translator->translator('tours_page_feature'); ?></a></li>
                        <li><a href="<?php echo $tab_base_link; ?>#tabs-5"><?php echo $this->translator->translator('tours_page_page_Other'); ?></a></li>
                        <li><a href="<?php echo $tab_base_link; ?>#tabs-6"><?php echo $this->translator->translator('tours_page_page_invoice_billing'); ?></a></li>
                    </ul>
                    
                    <div id="tabs-1">
                        <fieldset class="fieldset">
                            <legend class="legend"><?php echo $this->translator->translator('tours_page_page_info'); ?></legend>
                            <span class="top-go right-float"><a href="#topGo"><img src="application/layouts/scripts/<?php echo $front_template['theme_folder']; ?>/images/mod_img/top.png" border="0" alt="<?php echo $this->translator->translator('common_go_top_title'); ?>" title="<?php echo $this->translator->translator('common_go_top_title'); ?>" /></a></span>
                            <div>
                                <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->tours_name->getLabel();  if($this->proForm->tours_name->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">
                                    <div class="form-field">
                                        <?php  echo $this->proForm->tours_name; ?><br /><div class="input-errors" id="tours_name_err"></div>
                                    </div>
                                    <?php if($this->proForm->tours_name->getAttrib('title')) : ?>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->tours_name->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                    <?php endif; ?>
                                </div>
                                
                                <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->tours_title->getLabel();  if($this->proForm->tours_title->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">
                                    <div class="form-field">
                                        <?php  echo $this->proForm->tours_title;  ?><br /><div class="input-errors" id="tours_title_err"></div>	
                                    </div>
                                    <?php if($this->proForm->tours_title->getAttrib('title')) : ?>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->tours_title->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                    <?php endif; ?>
                                </div>                     
                                
                                <?php
								if($this->auth->getIdentity()->allow_to_change_ownership == '1')
								{
								?>
								<div class="form-label-container">
									<div class="label_class">
										<?php echo $this->proForm->tours_operator->getLabel();  if($this->proForm->tours_operator->isRequired()){ ?><span class="required">*</span><?php } ?>
									</div>
								</div>
                                <div class="form-field-container">  
									<div class="form-field">
										<?php echo $this->proForm->tours_operator;  ?><br /><div class="input-errors" id="tours_operator_err"></div>
									</div>
                                    <?php if($this->proForm->tours_operator->getAttrib('title')) : ?>
                                    <div class="form-field-info">
                                    	<div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->tours_operator->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
									</div>	
                                    <?php endif; ?>
								</div>
								<?php
								}
								?>
                                
                                <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->group_id->getLabel();  if($this->proForm->group_id->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">   
                                    <div class="form-field">
                                        <div class="left-float"><?php echo $this->proForm->group_id; ?></div><span id="group_id_loader"></span><br /><div class="input-errors" id="group_id_err"></div>
                                    </div>
                                    <?php if($this->proForm->group_id->getAttrib('title')) : ?>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->group_id->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                    <?php endif; ?>
                                </div>
                                
                                <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->tours_type->getLabel();  if($this->proForm->tours_type->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                 </div> 
                                <div class="form-field-container">   
                                    <div class="form-field">
                                        <?php echo $this->proForm->tours_type; ?><br /><div class="input-errors" id="tours_type_err"></div>
                                    </div>
                                    <?php if($this->proForm->tours_type->getAttrib('title')) : ?>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->tours_type->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                    <?php endif; ?>
                                </div> 
                                
                                <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->category_id->getLabel(); ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">     
                                    <div class="form-field">
                                        <span id="dataId"><?php echo $this->translator->translator("tours_tree_root"); ?> (0)</span><?php echo $this->proForm->category_id; ?>
                                    </div>
                                </div>
                                
                                <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->tours_desc->getLabel();  if($this->proForm->tours_desc->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">    
                                    <div class="form-field">
                                        <div class="editor"><?php echo $this->proForm->tours_desc; ?><br /><div class="input-errors" id="tours_desc_err"></div></div>
                                    </div>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->tours_desc->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                    <span id="loaderLink1"><a href="javascript:void(0);" onClick="loadTinyMCE('tours_desc',1);"><img src="application/modules/Administrator/layouts/scripts/images/common/editors.gif"  border="0" title="<?php echo $this->translator->translator('common_editor_open'); ?>" alt="<?php echo $this->translator->translator('common_editor_open'); ?>" ></a></span>
                                </div>
                            </div>
                        </fieldset>
                        
                        <fieldset class="fieldset">
                            <legend class="legend"><?php echo $this->translator->translator('tours_page_page_payment'); ?></legend>
                            <span class="top-go right-float"><a href="#topGo"><img src="application/layouts/scripts/<?php echo $front_template['theme_folder']; ?>/images/mod_img/top.png" border="0" alt="<?php echo $this->translator->translator('common_go_top_title'); ?>" title="<?php echo $this->translator->translator('common_go_top_title'); ?>" /></a></span>
                            <div>
                                <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->tours_price->getLabel();  if($this->proForm->tours_price->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">    
                                    <div class="form-field">
                                        <?php echo $this->proForm->tours_price.'&nbsp;'.$currency->getSymbol(); ?><br /><div class="input-errors" id="tours_price_err"></div>								
                                    </div>
                                    <?php if($this->proForm->tours_price->getAttrib('title')) : ?>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->tours_price->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                    <?php endif; ?>
                                </div>
                                
                                <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->costs_of_children->getLabel();  if($this->proForm->costs_of_children->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">    
                                    <div class="form-field">
                                        <?php echo $this->proForm->costs_of_children.'&nbsp;'.$currency->getSymbol(); ?><br /><div class="input-errors" id="costs_of_children_err"></div>								
                                    </div>
                                    <?php if($this->proForm->costs_of_children->getAttrib('title')) : ?>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->costs_of_children->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                    <?php endif; ?>
                                </div>
                                
                                <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->single_Room->getLabel();  if($this->proForm->single_Room->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">    
                                    <div class="form-field">
                                        <?php echo $this->proForm->single_Room.'&nbsp;'.$currency->getSymbol(); ?><br /><div class="input-errors" id="single_Room_err"></div>								
                                    </div>
                                    <?php if($this->proForm->single_Room->getAttrib('title')) : ?>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->single_Room->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                    <?php endif; ?>
                                </div>
                                
                                <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->double_room->getLabel();  if($this->proForm->double_room->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">    
                                    <div class="form-field">
                                        <?php echo $this->proForm->double_room.'&nbsp;'.$currency->getSymbol(); ?><br /><div class="input-errors" id="double_room_err"></div>								
                                    </div>
                                    <?php if($this->proForm->double_room->getAttrib('title')) : ?>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->double_room->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                    <?php endif; ?>
                                </div>
                                
                                <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->triple_rooms->getLabel();  if($this->proForm->triple_rooms->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">    
                                    <div class="form-field">
                                        <?php echo $this->proForm->triple_rooms.'&nbsp;'.$currency->getSymbol(); ?><br /><div class="input-errors" id="triple_rooms_err"></div>								
                                    </div>
                                    <?php if($this->proForm->triple_rooms->getAttrib('title')) : ?>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->triple_rooms->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                    <?php endif; ?>
                                </div>
                                
                                <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->extra_nights_per_person->getLabel();  if($this->proForm->extra_nights_per_person->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">    
                                    <div class="form-field">
                                        <?php echo $this->proForm->extra_nights_per_person.'&nbsp;'.$currency->getSymbol(); ?><br /><div class="input-errors" id="extra_nights_per_person_err"></div>								
                                    </div>
                                    <?php if($this->proForm->extra_nights_per_person->getAttrib('title')) : ?>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->extra_nights_per_person->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                    <?php endif; ?>
                                </div>
                                
                                <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->payment_desc->getLabel();  if($this->proForm->payment_desc->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">    
                                    <div class="form-field">
                                        <?php echo $this->proForm->payment_desc; ?><br /><div class="input-errors" id="payment_desc_err"></div>
                                    </div>
                                    <?php if($this->proForm->payment_desc->getAttrib('title')) : ?>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->payment_desc->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                    <?php endif; ?>
                                    <span id="loaderLink5"><a href="javascript:void(0);" onClick="loadTinyMCE('payment_desc',5);"><img src="application/modules/Administrator/layouts/scripts/images/common/editors.gif"  border="0" title="<?php echo $this->translator->translator('common_editor_open'); ?>" alt="<?php echo $this->translator->translator('common_editor_open'); ?>" ></a></span>
                                </div>
                            </div>
                        </fieldset>
                        
                        <fieldset class="fieldset">
                            <legend class="legend"><?php echo $this->translator->translator('tours_page_primary_info'); ?></legend>
                            <span class="top-go right-float"><a href="#topGo"><img src="application/layouts/scripts/<?php echo $front_template['theme_folder']; ?>/images/mod_img/top.png" border="0" alt="<?php echo $this->translator->translator('common_go_top_title'); ?>" title="<?php echo $this->translator->translator('common_go_top_title'); ?>" /></a></span>
                            <div>
                                <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->country_id->getLabel();  if($this->proForm->country_id->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">
                                    <div class="form-field">
                                        <?php  echo $this->proForm->country_id; ?><br /><div class="input-errors" id="country_id_err"></div>
                                    </div>
                                    <?php if($this->proForm->country_id->getAttrib('title')) : ?>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->country_id->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                    <?php endif; ?>
                                </div>
                                
                                <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->state_id->getLabel();  if($this->proForm->state_id->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">
                                    <div class="form-field">
                                        <div class="left-float"><?php  echo $this->proForm->state_id;  ?></div><span id="state_id_loader"></span><br /><div class="input-errors" id="state_id_err"></div>	
                                    </div>
                                    <?php if($this->proForm->state_id->getAttrib('title')) : ?>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->state_id->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                    <?php endif; ?>
                                </div>
                                
                                <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->area_id->getLabel();  if($this->proForm->area_id->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">    
                                    <div class="form-field">
                                        <div class="left-float"><?php echo $this->proForm->area_id; ?></div><span id="area_id_loader"></span><br /><div class="input-errors" id="area_id_err"></div>								
                                    </div>
                                    <?php if($this->proForm->area_id->getAttrib('title')) : ?>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->area_id->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                    <?php endif; ?>
                                </div>
                                
                                <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->post_code->getLabel();  if($this->proForm->post_code->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">    
                                    <div class="form-field">
                                        <?php echo $this->proForm->post_code; ?><br /><div class="input-errors" id="post_code_err"></div>
                                    </div>
                                    <?php if($this->proForm->post_code->getAttrib('title')) : ?>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->post_code->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                    <?php endif; ?>
                                </div>
                                
								<div class="form-label-container">
									<div class="label_class">
										<?php echo $this->proForm->duration->getLabel();  if($this->proForm->duration->isRequired()){ ?><span class="required">*</span><?php } ?>
									</div>
								</div>
                                <div class="form-field-container">  
									<div class="form-field">
										<?php echo $this->proForm->duration;  ?><br /><div class="input-errors" id="duration_err"></div>
									</div>
                                    <?php if($this->proForm->duration->getAttrib('title')) : ?>
                                    <div class="form-field-info">
                                    	<div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->duration->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
									</div>	
                                    <?php endif; ?>
								</div>								
                                
                                <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->rating->getLabel();  if($this->proForm->rating->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">   
                                    <div class="form-field">
                                        <div class="left-float"><?php echo $this->proForm->rating; ?></div><br /><div class="input-errors" id="rating_err"></div>
                                    </div>
                                    <?php if($this->proForm->rating->getAttrib('title')) : ?>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->rating->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                    <?php endif; ?>
                                </div>
                                
                                <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->tours_code->getLabel();  if($this->proForm->tours_code->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                 </div> 
                                <div class="form-field-container">   
                                    <div class="form-field">
                                        <?php echo $this->proForm->tours_code; ?><br /><div class="input-errors" id="tours_code_err"></div>
                                    </div>
                                    <?php if($this->proForm->tours_code->getAttrib('title')) : ?>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->tours_code->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                    <?php endif; ?>
                                </div> 
                                
                                <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->num_of_nights->getLabel();  if($this->proForm->num_of_nights->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">    
                                    <div class="form-field">
                                        <?php echo $this->proForm->num_of_nights; ?><br /><div class="input-errors" id="num_of_nights_err"></div>
                                    </div>
                                    <?php if($this->proForm->num_of_nights->getAttrib('title')) : ?>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->num_of_nights->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                    <?php endif; ?>
                                </div> 
                                
                                <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->num_of_days->getLabel();  if($this->proForm->num_of_days->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">    
                                    <div class="form-field">
                                        <?php echo $this->proForm->num_of_days; ?><br /><div class="input-errors" id="num_of_days_err"></div>
                                    </div>
                                    <?php if($this->proForm->num_of_days->getAttrib('title')) : ?>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->num_of_days->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                    <?php endif; ?>
                                </div> 
                                
                                <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->transportation->getLabel();  if($this->proForm->transportation->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">    
                                    <div class="form-field">
                                        <div class="editor"><?php echo $this->proForm->transportation; ?><br /><div class="input-errors" id="transportation_err"></div></div>
                                    </div>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->transportation->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                    <span id="loaderLink2"><a href="javascript:void(0);" onClick="loadTinyMCE('transportation',2);"><img src="application/modules/Administrator/layouts/scripts/images/common/editors.gif"  border="0" title="<?php echo $this->translator->translator('common_editor_open'); ?>" alt="<?php echo $this->translator->translator('common_editor_open'); ?>" ></a></span>
                                </div>
                            </div>
                        </fieldset>
                    </div>    
                    
                    <div id="tabs-2">
                        <fieldset class="fieldset">
                            <legend class="legend"><?php echo $this->translator->translator('tours_page_page_image'); ?></legend>
                            <span class="top-go right-float"><a href="#topGo"><img src="application/layouts/scripts/<?php echo $front_template['theme_folder']; ?>/images/mod_img/top.png" border="0" alt="<?php echo $this->translator->translator('common_go_top_title'); ?>" title="<?php echo $this->translator->translator('common_go_top_title'); ?>" /></a></span>
                            <div>
                                <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->tours_image->getLabel();  if($this->proForm->tours_image->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">
                                    <div class="form-field">
                                        <?php	
											if($this->auth->getIdentity()->access_file_image_manager == '1')
											{
										?>
										<div class="upload-img">
											<span class="button  ui-widget-content-1"><a href="javascript:  void(0);" class="upload_btn" rel="tours_image"><span class="icon upload"><?php echo $this->translator->translator('common_upload'); ?></span></a></span>
										</div>										
										<?php echo $this->proForm->tours_image; ?>
										<div class="input-errors" id="tours_image_err"></div><div class="input-errors" id="traveler_photos_err"></div>
										
										<?php
											}
											else
											{
										?>
										<div class="upload-img">
											<div id="tours_image_block"><?php echo $this->proForm->tours_image; ?></div>
										</div>
										<div class="input-errors" id="tours_image_err"><?php echo $this->escape($this->translator->translator("group_id_selected_err")); ?></div><div class="input-errors" id="traveler_photos_err"></div>
										<?php
											}
										?>
                                    </div>
                                    <?php if($this->proForm->tours_image->getAttrib('title')) : ?>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->tours_image->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                    <?php endif; ?>
                                </div>
                                
                                <div class="form-label-container">
                                    <div class="label_class">&nbsp;</div>
                                </div> 
                                <div class="form-field-container">
                                    <div class="form-field">&nbsp;
                                        <span id="selected_file_tours_image">&nbsp;</span>
                                    </div>                                   
                                </div>
                                
                                <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->spots_photo_gallery->getLabel();  if($this->proForm->spots_photo_gallery->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">
                                    <div class="form-field">
                                        <?php	
											if($this->auth->getIdentity()->access_file_image_manager == '1')
											{
										?>
										<div class="upload-img">
											<span class="button  ui-widget-content-1"><a href="javascript:  void(0);" class="upload_btn" rel="spots_photo_gallery"><span class="icon upload"><?php echo $this->translator->translator('common_upload'); ?></span></a></span>
										</div>										
										<?php echo $this->proForm->spots_photo_gallery; ?>
										<div class="input-errors" id="spots_photo_gallery_err"></div><div class="input-errors" id="feature_primary_floor_image_err"></div>
										
										<?php
											}
											else
											{
										?>
										<div class="upload-img">
											<div id="spots_photo_gallery_block"><?php echo $this->proForm->spots_photo_gallery; ?></div>
										</div>
										<div class="input-errors" id="spots_photo_gallery_err"><?php echo $this->escape($this->translator->translator("group_id_selected_err")); ?></div><div class="input-errors" id="feature_primary_interior_image_err"></div>
										<?php
											}
										?>
                                    </div>
                                    <?php if($this->proForm->spots_photo_gallery->getAttrib('title')) : ?>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->spots_photo_gallery->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                    <?php endif; ?>
                                </div>
                                
                                <div class="form-label-container">
                                    <div class="label_class">&nbsp;</div>
                                </div> 
                                <div class="form-field-container">
                                    <div class="form-field">&nbsp;
                                        <span id="selected_file_spots_photo_gallery">&nbsp;</span>
                                    </div>                                   
                                </div>                             
                                
                            </div>
                        </fieldset>
                        
                        <fieldset class="fieldset">
                            <legend class="legend"><?php echo $this->translator->translator('tours_product_page_related_items'); ?></legend>
                            <span class="top-go right-float"><a href="#topGo"><img src="application/layouts/scripts/<?php echo $front_template['theme_folder']; ?>/images/mod_img/top.png" border="0" alt="<?php echo $this->translator->translator('common_go_top_title'); ?>" title="<?php echo $this->translator->translator('common_go_top_title'); ?>" /></a></span>
                            <div>
                                <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->related_items->getLabel();  if($this->proForm->related_items->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">
                                    <div class="form-field">
                                        <?php  echo $this->proForm->related_items; ?><br /><div class="input-errors" id="related_items_err"></div>
                                    </div>
                                    <?php if($this->proForm->related_items->getAttrib('title')) : ?>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->related_items->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                    <?php endif; ?>
                                </div>                               
                            </div>
                        </fieldset>
                        
                        <fieldset class="fieldset">
                            <legend class="legend"><?php echo $this->translator->translator('tours_page_page_meta'); ?></legend>
                            <span class="top-go right-float"><a href="#topGo"><img src="application/layouts/scripts/<?php echo $front_template['theme_folder']; ?>/images/mod_img/top.png" border="0" alt="<?php echo $this->translator->translator('common_go_top_title'); ?>" title="<?php echo $this->translator->translator('common_go_top_title'); ?>" /></a></span>
                            <div>
                                <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->meta_title->getLabel();  if($this->proForm->meta_title->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">
                                    <div class="form-field">
                                        <?php  echo $this->proForm->meta_title; ?><br /><div class="input-errors" id="meta_title_err"></div>
                                    </div>
                                    <?php if($this->proForm->meta_title->getAttrib('title')) : ?>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->meta_title->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                    <?php endif; ?>
                                </div>
                                
                                <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->meta_keywords->getLabel();  if($this->proForm->meta_keywords->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">
                                    <div class="form-field">
                                        <?php  echo $this->proForm->meta_keywords;  ?><br /><div class="input-errors" id="meta_keywords_err"></div>	
                                    </div>
                                    <?php if($this->proForm->meta_keywords->getAttrib('title')) : ?>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->meta_keywords->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                    <?php endif; ?>
                                </div>
                                
                                <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->meta_desc->getLabel();  if($this->proForm->meta_desc->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">    
                                    <div class="form-field">
                                        <?php echo $this->proForm->meta_desc; ?><br /><div class="input-errors" id="meta_desc_err"></div>								
                                    </div>
                                    <?php if($this->proForm->meta_desc->getAttrib('title')) : ?>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->meta_desc->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </fieldset>
                    </div>
                    
                    <div id="tabs-3">
                        <fieldset class="fieldset">
                            <legend class="legend"><?php echo $this->translator->translator('tours_page_inclusions'); ?></legend>
                            <span class="top-go right-float"><a href="#topGo"><img src="application/layouts/scripts/<?php echo $front_template['theme_folder']; ?>/images/mod_img/top.png" border="0" alt="<?php echo $this->translator->translator('common_go_top_title'); ?>" title="<?php echo $this->translator->translator('common_go_top_title'); ?>" /></a></span>
                            <div>
                                <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->inclusions->getLabel();  if($this->proForm->inclusions->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">
                                    <div class="form-field">
                                        <div class="tours-features"><?php  echo $this->proForm->inclusions; ?></div><br /><div class="input-errors" id="inclusions_err"></div>
                                    </div>
                                    <?php if($this->proForm->inclusions->getAttrib('title')) : ?>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->inclusions->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                    <?php endif; ?>
                                </div>
                                
                                <div class="form-label-container">
                                    <div class="label_class"><hr /></div>
                                </div> 
                                <div class="form-field-container">
                                    <div class="form-field">
                                        <div style="width:470px"><hr /></div>
                                    </div>                                   
                                </div>
                                
                                <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->exclusions->getLabel();  if($this->proForm->exclusions->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">    
                                    <div class="form-field">
                                        <div class="tours-features"><?php echo $this->proForm->exclusions; ?></div><br /><div class="input-errors" id="exclusions_err"></div>								
                                    </div>
                                    <?php if($this->proForm->exclusions->getAttrib('title')) : ?>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->exclusions->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                    <?php endif; ?>
                                </div>
                                
                            </div>
                        </fieldset>                        
                    </div>
                    
                    <div id="tabs-4">
                        <fieldset class="fieldset">
                            <legend class="legend"><?php echo $this->translator->translator('tours_page_sec_feature'); ?></legend>
                            <span class="top-go right-float"><a href="#topGo"><img src="application/layouts/scripts/<?php echo $front_template['theme_folder']; ?>/images/mod_img/top.png" border="0" alt="<?php echo $this->translator->translator('common_go_top_title'); ?>" title="<?php echo $this->translator->translator('common_go_top_title'); ?>" /></a></span>
                            <div>
                                <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->starting_city->getLabel();  if($this->proForm->starting_city->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">
                                    <div class="form-field">
                                        <?php  echo $this->proForm->starting_city; ?><br /><div class="input-errors" id="starting_city_err"></div>
                                    </div>
                                    <?php if($this->proForm->starting_city->getAttrib('title')) : ?>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->starting_city->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                    <?php endif; ?>
                                </div>
                                
                                <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->ending_city->getLabel();  if($this->proForm->ending_city->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">
                                    <div class="form-field">
                                       <?php  echo $this->proForm->ending_city; ?><br /><div class="input-errors" id="ending_city_err"></div>
                                    </div>
                                    <?php if($this->proForm->ending_city->getAttrib('title')) : ?>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->ending_city->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                    <?php endif; ?>
                                </div>
                                
                                <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->visiting_cities->getLabel();  if($this->proForm->visiting_cities->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">
                                    <div class="form-field">
                                       <?php  echo $this->proForm->visiting_cities; ?><br /><div class="input-errors" id="visiting_cities_err"></div>
                                    </div>
                                    <?php if($this->proForm->visiting_cities->getAttrib('title')) : ?>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->visiting_cities->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                    <?php endif; ?>
                                </div> 
                                
                                <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->scheduled_on->getLabel();  if($this->proForm->scheduled_on->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">
                                    <div class="form-field">
                                       <?php  echo $this->proForm->scheduled_on; ?><br /><div class="input-errors" id="scheduled_on_err"></div>
                                    </div>
                                    <?php if($this->proForm->scheduled_on->getAttrib('title')) : ?>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->scheduled_on->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                    <?php endif; ?>
                                </div> 
                                
                                <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->sightseeing->getLabel();  if($this->proForm->sightseeing->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">
                                    <div class="form-field">
                                       <?php  echo $this->proForm->sightseeing; ?><br /><div class="input-errors" id="sightseeing_err"></div>
                                    </div>
                                    <?php if($this->proForm->sightseeing->getAttrib('title')) : ?>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->sightseeing->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                    <?php endif; ?>
                                </div> 
                                
                                <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->accommodates->getLabel();  if($this->proForm->accommodates->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">
                                    <div class="form-field">
                                       <?php  echo $this->proForm->accommodates; ?><br /><div class="input-errors" id="accommodates_err"></div>
                                    </div>
                                    <?php if($this->proForm->accommodates->getAttrib('title')) : ?>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->accommodates->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                    <?php endif; ?>
                                </div> 
                                
                                <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->multilingual_guide->getLabel();  if($this->proForm->multilingual_guide->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">
                                    <div class="form-field">
                                       <?php  echo $this->proForm->multilingual_guide; ?><br /><div class="input-errors" id="multilingual_guide_err"></div>
                                    </div>
                                    <?php if($this->proForm->multilingual_guide->getAttrib('title')) : ?>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->multilingual_guide->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                    <?php endif; ?>
                                </div> 
                                
                                <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->Pickup_service->getLabel();  if($this->proForm->Pickup_service->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">
                                    <div class="form-field">
                                       <?php  echo $this->proForm->Pickup_service; ?><br /><div class="input-errors" id="Pickup_service_err"></div>
                                    </div>
                                    <?php if($this->proForm->Pickup_service->getAttrib('title')) : ?>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->Pickup_service->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                    <?php endif; ?>
                                </div> 
                                
                                <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->supplementary_room->getLabel();  if($this->proForm->supplementary_room->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">
                                    <div class="form-field">
                                       <?php  echo $this->proForm->supplementary_room; ?><br /><div class="input-errors" id="supplementary_room_err"></div>
                                    </div>
                                    <?php if($this->proForm->supplementary_room->getAttrib('title')) : ?>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->supplementary_room->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                    <?php endif; ?>
                                </div> 
                                
                                <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->drop_off_service->getLabel();  if($this->proForm->drop_off_service->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">
                                    <div class="form-field">
                                       <?php  echo $this->proForm->drop_off_service; ?><br /><div class="input-errors" id="drop_off_service_err"></div>
                                    </div>
                                    <?php if($this->proForm->drop_off_service->getAttrib('title')) : ?>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->drop_off_service->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                    <?php endif; ?>
                                </div> 
                                
                                <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->entertainments->getLabel();  if($this->proForm->entertainments->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">
                                    <div class="form-field">
                                       <?php  echo $this->proForm->entertainments; ?><br /><div class="input-errors" id="entertainments_err"></div>
                                    </div>
                                    <?php if($this->proForm->entertainments->getAttrib('title')) : ?>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->entertainments->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                    <?php endif; ?>
                                </div> 
                                
                                <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->location_type->getLabel();  if($this->proForm->location_type->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">
                                    <div class="form-field">
                                       <?php  echo $this->proForm->location_type; ?><br /><div class="input-errors" id="location_type_err"></div>
                                    </div>
                                    <?php if($this->proForm->location_type->getAttrib('title')) : ?>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->location_type->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                    <?php endif; ?>
                                </div>                                                 
                                
                            </div>
                        </fieldset>
                        
                        <fieldset class="fieldset">
                            <legend class="legend"><?php echo $this->translator->translator('tours_page_page_brochure'); ?></legend>
                            <span class="top-go right-float"><a href="#topGo"><img src="application/layouts/scripts/<?php echo $front_template['theme_folder']; ?>/images/mod_img/top.png" border="0" alt="<?php echo $this->translator->translator('common_go_top_title'); ?>" title="<?php echo $this->translator->translator('common_go_top_title'); ?>" /></a></span>
                            <div>
                                <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->itinerary_title->getLabel();  if($this->proForm->itinerary_title->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">
                                    <div class="form-field">
                                        <?php  echo $this->proForm->itinerary_title; ?><br /><div class="input-errors" id="itinerary_title_err"></div>
                                    </div>
                                    <?php if($this->proForm->itinerary_title->getAttrib('title')) : ?>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->itinerary_title->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                    <?php endif; ?>
                                </div>
                                
                               <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->itinerary_desc->getLabel();  if($this->proForm->itinerary_desc->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">    
                                    <div class="form-field">
                                        <div class="editor"><?php echo $this->proForm->itinerary_desc; ?><br /><div class="input-errors" id="itinerary_desc_err"></div></div>
                                    </div>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->itinerary_desc->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                    <span id="loaderLink6"><a href="javascript:void(0);" onClick="loadTinyMCE('itinerary_desc',6);"><img src="application/modules/Administrator/layouts/scripts/images/common/editors.gif"  border="0" title="<?php echo $this->translator->translator('common_editor_open'); ?>" alt="<?php echo $this->translator->translator('common_editor_open'); ?>" ></a></span>
                                </div> 
                            </div>
                        </fieldset>
                        
                    </div>
                    
                    <div id="tabs-5"> 
                    	<fieldset class="fieldset">
                            <legend class="legend"><?php echo $this->translator->translator('tours_page_page_available'); ?></legend>
                            <span class="top-go right-float"><a href="#topGo"><img src="application/layouts/scripts/<?php echo $front_template['theme_folder']; ?>/images/mod_img/top.png" border="0" alt="<?php echo $this->translator->translator('common_go_top_title'); ?>" title="<?php echo $this->translator->translator('common_go_top_title'); ?>" /></a></span>
                            <div>
                                <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->availabe_from->getLabel();  if($this->proForm->availabe_from->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">    
                                    <div class="form-field">
                                        <?php echo $this->proForm->availabe_from; ?><br /><div class="input-errors" id="availabe_from_err"></div>
                                    </div>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->availabe_from->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                </div>
                                
                                <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->available_to->getLabel();  if($this->proForm->available_to->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">    
                                    <div class="form-field">
                                        <?php echo $this->proForm->available_to; ?><br /><div class="input-errors" id="available_to_err"></div>
                                    </div>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->available_to->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                </div>
                                
                                <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->available_expire_date->getLabel();  if($this->proForm->available_expire_date->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">    
                                    <div class="form-field">
                                        <?php echo $this->proForm->available_expire_date; ?><br /><div class="input-errors" id="available_expire_date_err"></div>
                                    </div>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->available_expire_date->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                </div>
                                
                                <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->journey_start_date->getLabel();  if($this->proForm->journey_start_date->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">    
                                    <div class="form-field">
                                        <?php echo $this->proForm->journey_start_date; ?><br /><div class="input-errors" id="journey_start_date_err"></div>
                                    </div>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->journey_start_date->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                </div>
                            </div>
                        </fieldset>                        
                                               
                        <fieldset class="fieldset">
                            <legend class="legend"><?php echo $this->translator->translator('tours_page_page_meter'); ?></legend>
                            <span class="top-go right-float"><a href="#topGo"><img src="application/layouts/scripts/<?php echo $front_template['theme_folder']; ?>/images/mod_img/top.png" border="0" alt="<?php echo $this->translator->translator('common_go_top_title'); ?>" title="<?php echo $this->translator->translator('common_go_top_title'); ?>" /></a></span>
                            <div>
                            	<div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->feature_google_map->getLabel();  if($this->proForm->feature_google_map->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">    
                                    <div class="form-field">
                                        <div class="editor"><?php echo $this->proForm->feature_google_map; ?><br /><div class="input-errors" id="feature_google_map_err"></div></div>
                                    </div>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->feature_google_map->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                    <span id="loaderLink3"><a href="javascript:void(0);" onClick="loadTinyMCE('feature_google_map',3);"><img src="application/modules/Administrator/layouts/scripts/images/common/editors.gif"  border="0" title="<?php echo $this->translator->translator('common_editor_open'); ?>" alt="<?php echo $this->translator->translator('common_editor_open'); ?>" ></a></span>
                                </div>
                                
                                <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->tour_highlights->getLabel();  if($this->proForm->tour_highlights->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">    
                                    <div class="form-field">
                                        <div class="editor"><?php echo $this->proForm->tour_highlights; ?><br /><div class="input-errors" id="tour_highlights_err"></div></div>
                                    </div>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->tour_highlights->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                    <span id="loaderLink4"><a href="javascript:void(0);" onClick="loadTinyMCE('tour_highlights',4);"><img src="application/modules/Administrator/layouts/scripts/images/common/editors.gif"  border="0" title="<?php echo $this->translator->translator('common_editor_open'); ?>" alt="<?php echo $this->translator->translator('common_editor_open'); ?>" ></a></span>
                                </div>
                                
                                <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->tour_policy->getLabel();  if($this->proForm->tour_policy->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">    
                                    <div class="form-field">
                                        <div class="editor"><?php echo $this->proForm->tour_policy; ?><br /><div class="input-errors" id="tour_policy_err"></div></div>
                                    </div>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->tour_policy->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                    <span id="loaderLink8"><a href="javascript:void(0);" onClick="loadTinyMCE('tour_policy',8);"><img src="application/modules/Administrator/layouts/scripts/images/common/editors.gif"  border="0" title="<?php echo $this->translator->translator('common_editor_open'); ?>" alt="<?php echo $this->translator->translator('common_editor_open'); ?>" ></a></span>
                                </div>
                                
                                <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->trams_and_condition->getLabel();  if($this->proForm->trams_and_condition->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">    
                                    <div class="form-field">
                                        <div class="editor"><?php echo $this->proForm->trams_and_condition; ?><br /><div class="input-errors" id="trams_and_condition_err"></div></div>
                                    </div>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->trams_and_condition->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                    <span id="loaderLink7"><a href="javascript:void(0);" onClick="loadTinyMCE('trams_and_condition',7);"><img src="application/modules/Administrator/layouts/scripts/images/common/editors.gif"  border="0" title="<?php echo $this->translator->translator('common_editor_open'); ?>" alt="<?php echo $this->translator->translator('common_editor_open'); ?>" ></a></span>
                                </div>                        
                            </div>
                        </fieldset>
                    </div>
                    
                    <div id="tabs-6">
                        <fieldset class="fieldset">
                            <legend class="legend"><?php echo $this->translator->translator('tours_page_invoice_billing_info'); ?></legend>
                            <span class="top-go right-float"><a href="#topGo"><img src="application/layouts/scripts/<?php echo $front_template['theme_folder']; ?>/images/mod_img/top.png" border="0" alt="<?php echo $this->translator->translator('common_go_top_title'); ?>" title="<?php echo $this->translator->translator('common_go_top_title'); ?>" /></a></span>
                            <div>
                                <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->billing_user_places_order_email_enable->getLabel();  if($this->proForm->billing_user_places_order_email_enable->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">
                                    <div class="form-field">
                                        <?php  echo $this->proForm->billing_user_places_order_email_enable; ?><br /><div class="input-errors" id="billing_user_places_order_email_enable_err"></div>
                                    </div>
                                    <?php if($this->proForm->billing_user_places_order_email_enable->getAttrib('title')) : ?>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->billing_user_places_order_email_enable->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                    <?php endif; ?>
                                </div>
                                
                                <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->billing_user_places_order_email_address->getLabel();  if($this->proForm->billing_user_places_order_email_address->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">    
                                    <div class="form-field">
                                        <?php echo $this->proForm->billing_user_places_order_email_address; ?><br /><div class="input-errors" id="billing_user_places_order_email_address_err"></div>								
                                    </div>
                                    <?php if($this->proForm->billing_user_places_order_email_address->getAttrib('title')) : ?>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->billing_user_places_order_email_address->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                    <?php endif; ?>
                                </div>
                               
                                <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->billing_user_pay_invoice_email_enable->getLabel();  if($this->proForm->billing_user_pay_invoice_email_enable->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">
                                    <div class="form-field">
                                        <?php  echo $this->proForm->billing_user_pay_invoice_email_enable; ?><br /><div class="input-errors" id="billing_user_pay_invoice_email_enable_err"></div>
                                    </div>
                                    <?php if($this->proForm->billing_user_pay_invoice_email_enable->getAttrib('title')) : ?>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->billing_user_pay_invoice_email_enable->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                    <?php endif; ?>
                                </div>
                               
                                <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->billing_user_pay_invoice_email_address->getLabel();  if($this->proForm->billing_user_pay_invoice_email_address->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">
                                    <div class="form-field">
                                        <?php  echo $this->proForm->billing_user_pay_invoice_email_address; ?><br /><div class="input-errors" id="billing_user_pay_invoice_email_address_err"></div>
                                    </div>
                                    <?php if($this->proForm->billing_user_pay_invoice_email_address->getAttrib('title')) : ?>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->billing_user_pay_invoice_email_address->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                    <?php endif; ?>
                                </div>
                               
                                <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->billing_user_cancel_order_email_enable->getLabel();  if($this->proForm->billing_user_cancel_order_email_enable->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">
                                    <div class="form-field">
                                        <?php  echo $this->proForm->billing_user_cancel_order_email_enable; ?><br /><div class="input-errors" id="billing_user_cancel_order_email_enable_err"></div>
                                    </div>
                                    <?php if($this->proForm->billing_user_cancel_order_email_enable->getAttrib('title')) : ?>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->billing_user_cancel_order_email_enable->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                    <?php endif; ?>
                                </div>
                               
                                <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->billing_user_cancel_order_email_address->getLabel();  if($this->proForm->billing_user_cancel_order_email_address->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">
                                    <div class="form-field">
                                        <?php  echo $this->proForm->billing_user_cancel_order_email_address; ?><br /><div class="input-errors" id="billing_user_cancel_order_email_address_err"></div>
                                    </div>
                                    <?php if($this->proForm->billing_user_cancel_order_email_address->getAttrib('title')) : ?>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->billing_user_cancel_order_email_address->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                    <?php endif; ?>
                                </div>
                               
                                <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->billing_order_payment_email_enable->getLabel();  if($this->proForm->billing_order_payment_email_enable->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">
                                    <div class="form-field">
                                        <?php  echo $this->proForm->billing_order_payment_email_enable; ?><br /><div class="input-errors" id="billing_order_payment_email_enable_err"></div>
                                    </div>
                                    <?php if($this->proForm->billing_order_payment_email_enable->getAttrib('title')) : ?>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->billing_order_payment_email_enable->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                    <?php endif; ?>
                                </div>
                                
                               <div class="form-label-container">
                                    <div class="label_class">
                                        <?php echo $this->proForm->billing_item_desc->getLabel();  if($this->proForm->billing_item_desc->isRequired()){ ?><span class="star_class">*</span><?php } ?>
                                    </div>
                                </div> 
                                <div class="form-field-container">    
                                    <div class="form-field">
                                        <div class="editor"><?php echo $this->proForm->billing_item_desc; ?><br /><div class="input-errors" id="billing_item_desc_err"></div></div>
                                    </div>
                                    <div class="form-field-info">
                                        <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->billing_item_desc->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                    <span id="loaderLink17"><a href="javascript:void(0);" onClick="loadTinyMCE('billing_item_desc',17);"><img src="application/modules/Administrator/layouts/scripts/images/common/editors.gif"  border="0" title="<?php echo $this->translator->translator('common_editor_open'); ?>" alt="<?php echo $this->translator->translator('common_editor_open'); ?>" ></a></span>
                                </div> 
                            </div>
                        </fieldset>
                    </div>
                
                </div>
          	</div>
		</form>
	</div>
    <div class="button-container clear">
        <span class="button ui-widget-content-1"><a href="<?php echo $this->url( array('module' => 'Tours','controller' => 'members', 'action'     => 'list' ,'group' => $param_group_id), $list_page_route,    true) ?>" class="back_btn_link"><span class="icon back"><?php echo $this->translator->translator('common_back'); ?></span></a></span>
        <span class="button ui-widget-content-1"><a href="javascript:  void(0);" class="reset_btn"><span class="icon reset"><?php echo $this->translator->translator('common_reset'); ?></span></a></span>
        <span class="button ui-widget-content-1"><a href="javascript: void(0);" class="add_tours_btn"><span class="icon save"><?php echo $this->translator->translator('common_save'); ?></span></a></span>
    </div>
</div>

<?php endif; ?>	
<div id="dialog_msg" title="<?php echo $this->translator->translator('common_dialog_msg',$this->translator->translator('tours_frontend_list_add_page_name')); ?>">
</div>
<div id="dialog_container" style="display:none" title="<?php echo $this->translator->translator('common_processing_language'); ?>">
	<div id="progressbar" ></div>	
</div>

<div id="upload-form" title="<?php echo $this->translator->translator('tours_page_page_dialog'); ?>">	
	<div>
    	<form id="popupForm" target="i-upload-form" method="post" action="" >
            <input type="hidden" name="table_name" value="tours_group"/>
            <input type="hidden" name="primary_id_field" value="id"/>
            <input type="hidden" name="primary_id_field_value" value=""/>   
            <input type="hidden" name="primary_file_field" value=""/> 
           	<input type="hidden" name="file_content"  value=""/>       
            <input type="hidden" name="file_path_field" value=""/>
            <input type="hidden" name="file_extension_field" value="file_type"/>
            <input type="hidden" name="file_max_size_field" value="file_size_max"/>
    	</form>
    	<iframe id="i-upload-form" name="i-upload-form" src="application/modules/Administrator/layouts/scripts/images/loader/manager_loader.gif" class="iframe-img-upload"></iframe>
    </div>
    
    <div class="button-container">
        <span class="button ui-widget-content-1"><a href="javascript:void(0);" class="select_file_btn"><span class="icon insert"><?php echo $this->translator->translator('tours_page_page_insert'); ?></span></a></span>
        <span class="button ui-widget-content-1"><a href="javascript:void(0);" class="close_dialog_btn"><span class="icon close"><?php echo $this->translator->translator('common_close'); ?></span></a></span>
    </div>
</div>
</div>