<?php
$version = Zend_Registry::get('version');	
echo $this->headScript()->setFile($this->baseUrl().'/js/jquery/table-sorter/jquery.dataTables.js');

$mem_db = new Members_Model_DbTable_MemberList();
$global_conf = Zend_Registry::get('global_conf');
$currency = new Zend_Currency($global_conf['default_locale']);
$currencySymbol = $currency->getSymbol();
$currencyShort = $currency->getShortName();
?>
<script type="text/javascript">

$(document).ready(function() {
	
	floatingbar('#floatingbar',"#content",null);		
		
	/****************************Sorting Table Start*********************/
	var oTable = $("#sortTable").dataTable({
				"bPaginate": false,
				"bDestroy":true,
				"bLengthChange": true,
				"bSearchable": true,
				"bFilter": true,
				"bSort": true,
				"bInfo": false,
				"bAutoWidth": true,
				"bProcessing": false,
				"bSortClasses": true,
				"bStateSave": false,
				"bServerSide": false,
				"aaSorting": [[ 3, "desc" ]],				
				"aoColumnDefs": [ 
						{ "bSortable": false, "bSortClasses": false,  "aTargets": [ 0 ] }
					],
				"oLanguage" : { "sSearch": "<?php echo $this->translator->translator('jquery_filter'); ?>" }
			}); 	
	
	$('td', oTable.fnGetNodes()).hover( function() {		
		$(this).parents("tr:first").children('td').addClass( 'highlighted' );
	}, function() {
		$('td.highlighted').removeClass('highlighted');
	});	
	
	/****************************Sorting Table End*********************/
	
		function stripslashes(str) 
		{
			str=str.replace(/\\'/g,'\'');
			str=str.replace(/\\"/g,'"');
			str=str.replace(/\\0/g,'\0');
			str=str.replace(/\\\\/g,'\\');
			return str;
		}
		
			
		allFunction();		
			
		
		function deleteAll(self)
		{
			var id_str = '';
			for(var i=0;i < $('input.check_btn:checked').length;i++)
			{
				if(i == 0)
				{
					 id_str += $('input.check_btn:checked:eq('+i+')').val();
				}
				else
				{
					id_str += ','+$('input.check_btn:checked:eq('+i+')').val();
				}
			}
			
			$.ajax({
					url: "<?php echo $this->url( array('module'=> 'Flight', 'controller' => 'backend', 'action'     => 'deleteall' ), 'adminrout',    true) ?>",
				 	type: 'POST',
				 	data: { id_st: id_str},
					beforeSend: function(){
						$(self).html('<img src="data/adminImages/commonImages/ajax_loader1.gif" width="22" height="22" border="0" />');
					 },
					success: function(response) 
				 	{
						//alert(response);
						var json_arr = eval("("+response+")");
						if(json_arr.status == 'ok')
						{
							for(var i= ($('input.check_btn:checked').length-1);i >= 0;i--)
							{								
								$('input.check_btn:checked:eq('+i+')').parents("td:first").parents("tr:first").addClass('row_selected');							
							}
							var oTabled = $('#sortTable').dataTable();
							var anSelected = fnGetSelected( oTabled );
							for(var k = 0; k < anSelected.length; k++)
							{
								oTabled.fnDeleteRow( anSelected[k] );
							}
						}
						else
						{							
							openMsgDialog(json_arr.msg);
						}	
						$(self).html('<?php echo html_entity_decode($this->translator->translator("common_delete_selected"), ENT_QUOTES, "UTF-8"); ?>');
					}
			});	
		}
		
	$('a.invoice_btn').each(function()
	   {
		  // We make use of the .each() loop to gain access to each element via the "this" keyword...
		  $(this).qtip(
		  {
			 content: {
				// Set the text to an image HTML string with the correct src URL to the loading image you want to use
				text: '<img class="throbber" src="images/ajax_loader7.gif" alt="Loading..." />',
				ajax: {
				   url: "<?php echo $this->url( array('module'=> 'Flight', 'controller' => 'backend', 'action'     => 'view' , 'invoice_id' => '' ), 'adminrout',    true) ?>"+$(this).attr('rel') // Use the rel attribute of each element for the url to load
				},
				title: {
				   text: "<?php echo $this->translator->translator('flight_invoice_list_invoice_preview'); ?>", // Give the tooltip a title using each elements text
				   button: true
				}
			 },
			 position: {			 	
				at: 'center', // Position the tooltip above the link
				my: 'center',
				target: $(window),
				viewport: $(window) // Keep the tooltip on-screen at all times
			 },
			 show: {
				event: 'click',
				effect: function() { $(this).show(100); } ,
				modal: true,
				solo: true // Only show one tooltip at a time
			 },
			 hide: {
			 	event: 'unfocus',
				effect: function() { $(this).hide(100); }
			 },
			 style: {
				classes: 'ui-tooltip-wiki ui-tooltip-light ui-tooltip-shadow',
				tip: false
			 }
		  })
		  
		  // Make sure it doesn't follow the link when we click it
		  .click(function() { return false; });
	   });

		
		
	$('a.publish_all').click(function() {
		var self = this;
		var bigrel = $(self).attr('rel');
		if($('input.check_btn:checked').length > 0)
		{
			var id_str = '';
			for(var i=0;i < $('input.check_btn:checked').length;i++)
			{
				if(i == 0)
				{
					 id_str += $('input.check_btn:checked:eq('+i+')').val();
				}
				else
				{
					id_str += ','+$('input.check_btn:checked:eq('+i+')').val();
				}
			}
			
			$.ajax({
					url: "<?php echo $this->url( array('module'=> 'Flight', 'controller' => 'backend', 'action'     => 'paid' ), 'adminrout',    true) ?>",
				 	type: 'POST',
				 	data: { id_st: id_str, paction: bigrel},
					beforeSend: function(){
						$(self).html('<img src="data/adminImages/commonImages/ajax_loader1.gif" width="22" height="22" border="0" />');
					 },
					success: function(response) 
				 	{
						//alert(response);
						var json_arr = eval("("+response+")");
						if(json_arr.status == 'ok')
						{
							switch(bigrel)
							{
								case 'paid':
									for(var i=0;i < $('input.check_btn:checked').length;i++)
									{								
										$('input.check_btn:checked:eq('+i+')').parents("td:first").parents("tr:first").children("td:nth-child(7)").html("<?php echo $this->translator->translator('common_paid_language'); ?>");																																
									}
									break;
								case 'unpaid':
									for(var i=0;i < $('input.check_btn:checked').length;i++)
									{								
										$('input.check_btn:checked:eq('+i+')').parents("td:first").parents("tr:first").children("td:nth-child(7)").html("<?php echo $this->translator->translator('common_unpaid_language'); ?>");							
									}
									break;	
								case 'cancel':
									for(var i=0;i < $('input.check_btn:checked').length;i++)
									{								
										$('input.check_btn:checked:eq('+i+')').parents("td:first").parents("tr:first").children("td:nth-child(7)").html("<?php echo $this->translator->translator('common_cancelled_language'); ?>");							
									}
									break;	
							}
						}
						else
						{
							openMsgDialog(json_arr.msg);
						}	
						switch(bigrel)
						{	
							case 'paid':
								$(self).html('<?php echo $this->translator->translator("common_paid_selected"); ?>');
								break;
							case 'unpaid':
								$(self).html('<?php echo $this->translator->translator("common_unpaid_selected"); ?>');
								break;
							case 'cancel':
								$(self).html('<?php echo $this->translator->translator("common_cancel_selected"); ?>');
								break;
						}
					}
			});			
		}
		else
		{
			var msg = "<?php echo $this->translator->translator('flight_selected_err'); ?>";
			openMsgDialog(msg);
		}
	});
		
	$('a.delete_all').click(function() {
		var self = this;
		if($('input.check_btn:checked').length > 0)
		{
			$("#dialog-confirm").html("<?php echo addslashes($this->translator->translator('flight_list_delete_confirm')); ?>").dialog({
					resizable: false,
					width:400,
					height:170,
					modal: true,
					show: 'fade',
					hide: 'explode',
					buttons: {
							'<?php echo html_entity_decode($this->translator->translator("common_delete_selected"), ENT_QUOTES, "UTF-8"); ?>': function() {
							deleteAll(self);
							$(this).dialog('close');
						},
					'<?php echo html_entity_decode($this->translator->translator("common_cancel"), ENT_QUOTES, "UTF-8"); ?>': function() {
							$(this).dialog('close');
						}
					}
				});		
		}
		else
		{
			var msg = "<?php echo $this->translator->translator('flight_selected_err'); ?>";
			openMsgDialog(msg);
		}
	});
	
	$('input.checkAll_btn').click(function() {
		var self = this;
		if($(self).is(':checked'))
		{		
			$('input.check_btn').prop('checked', true);
		}
		else
		{
			$('input.check_btn').attr('checked', false);
		}
	});
	
			
});

function deleteThis(self)
{
	var arr = $(self).attr('rel').split('_');
	$.ajax({
		 url: "<?php echo $this->url( array('module'=> 'Flight', 'controller' => 'price', 'action'     => 'delete' ), 'adminrout',    true) ?>",
		 type: 'POST',
		 data: { id: arr[0], group_id: arr[1]},
		 beforeSend: function(){
				$(self).html('<img src="images/ajax_loader7.gif" border="0" width="24" height="24" />');
			 },
		 success: function(response) 
		 {
			//alert(response);
			var json_arr = eval("("+response+")");
			if(json_arr.status == 'ok')
			{
				$(self).parents("td:first").parents("tr:first").parents("table:first").parents("td:first").parents("tr:first").addClass('row_selected');
				var oTables = $('#sortTable').dataTable();
				var anSelected = fnGetSelected( oTables );
				oTables.fnDeleteRow( anSelected[0] );
			}
		 }
	});
}

/* Get the rows which are currently selected */
function fnGetSelected( oTableLocal )
{
	var aReturn = new Array();
	var aTrs = oTableLocal.fnGetNodes();
	
	for ( var i=0 ; i<aTrs.length ; i++ )
	{
		if ( $(aTrs[i]).hasClass('row_selected') )
		{
			aReturn.push( aTrs[i] );
		}
	}
	return aReturn;
}

function openMsgDialog(msg)
{
$('#dialog_container').html(msg).dialog({
			autoOpen: true,
			modal: false,
			show: 'fade',
			resizable: 'false',				
			buttons: { "<?php echo html_entity_decode($this->translator->translator('common_ok'), ENT_QUOTES, 'UTF-8'); ?>": function() { $(this).dialog('option', 'hide', 'explode').dialog("close"); } },
			open: function(event, ui)
				 {
					setTimeout(function() 
					{									
						if($('#' + event.target.id).dialog('isOpen'))
						{
							$('#' + event.target.id).dialog('option', 'hide', 'explode').dialog('close');										
						}
					}, 10000);
				  }
		});
}

function allFunction()
{			
	$('a.delete_btn').unbind('click');
	$('a.delete_btn').click(function() {
		var self = this;
		$("#dialog-confirm").html("<?php echo addslashes($this->translator->translator('flight_list_delete_confirm')); ?>").dialog({
			resizable: false,
			width:400,
			height:170,
			modal: true,
			show: 'fade',
			hide: 'explode',
			buttons: {
					'<?php echo html_entity_decode($this->translator->translator("common_delete"), ENT_QUOTES, "UTF-8"); ?>': function() {
					deleteThis(self);
					$(this).dialog('close');
				},
			'<?php echo html_entity_decode($this->translator->translator("common_cancel"), ENT_QUOTES, "UTF-8"); ?>': function() {
					$(this).dialog('close');
				}
			}
		});
		
	});			
}
</script>
<style type="text/css">	
	/******************************TABLE SORTER STYLE START******************************************/

	/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
	 * DataTables features
	 */
	
	.dataTables_wrapper {
		position: relative;
		/*min-height: 302px;*/
		clear: both;
		_height: 302px;
		zoom: 1; /* Feeling sorry for IE */
	}
	
	.dataTables_processing {
		position: absolute;
		top: 50%;
		left: 50%;
		width: 250px;
		height: 30px;
		margin-left: -125px;
		margin-top: -15px;
		padding: 14px 0 2px 0;
		border: 1px solid #ddd;
		text-align: center;
		color: #999;
		font-size: 14px;
		background-color: white;
	}
	
	.dataTables_length {
		width: 40%;
		float: right;
	}
	
	.dataTables_filter {
		width: 100%;
		/*float: left;*/
		text-align: left;
		padding-bottom:5px;
	}
	
	.dataTables_info {
		width: 60%;
		float: left;
	}
	
	.dataTables_paginate {
		width: 44px;
		* width: 50px;
		float: right;
		text-align: right;
	}
	
	/* Pagination nested */
	.paginate_disabled_previous, .paginate_enabled_previous, .paginate_disabled_next, .paginate_enabled_next {
		height: 19px;
		width: 19px;
		margin-left: 3px;
		float: left;
	}
	
	.paginate_disabled_previous {
		background-image: url('data/adminImages/commonImages/table-sorter/back_disabled.jpg');
	}
	
	.paginate_enabled_previous {
		background-image: url('data/adminImages/commonImages/table-sorter/back_enabled.jpg');
	}
	
	.paginate_disabled_next {
		background-image: url('data/adminImages/commonImages/table-sorter/forward_disabled.jpg');
	}
	
	.paginate_enabled_next {
		background-image: url('data/adminImages/commonImages/table-sorter/forward_enabled.jpg');
	}
	
	.paging_full_numbers {
		width: 400px;
		height: 22px;
		line-height: 22px;
	}
	
	.paging_full_numbers span.paginate_button,
		.paging_full_numbers span.paginate_active {
		border: 1px solid #aaa;
		-webkit-border-radius: 5px;
		-moz-border-radius: 5px;
		padding: 2px 5px;
		margin: 0 3px;
		cursor: pointer;
		*cursor: hand;
	}
	
	.paging_full_numbers span.paginate_button {
		background-color: #ddd;
	}
	
	.paging_full_numbers span.paginate_button:hover {
		background-color: #ccc;
	}
	
	.paging_full_numbers span.paginate_active {
		background-color: #99B3FF;
	}
	
	/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
	 * DataTables row classes
	 */
	 
	tr.odd {
		background-color: #F7F7F7;
		text-align:center;
	}
	tr.even {
		background-color: #FFFFFF;
		text-align:center;
	}
	
	.highlighted
	{
	   background-color:#FCF5DD;
	}
	
	
	/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
	 * DataTables sorting
	 */
	
	.sorting_asc {
		background: url('data/adminImages/commonImages/table-sorter/sort_asc.png') no-repeat center right;
	}
	
	.sorting_desc {
		background: url('data/adminImages/commonImages/table-sorter/sort_desc.png') no-repeat center right;
	}
	
	.sorting {
		background: url('data/adminImages/commonImages/table-sorter/sort_both.png') no-repeat center right;
	}
	
	.sorting_asc_disabled {
		background: url('data/adminImages/commonImages/table-sorter/sort_asc_disabled.png') no-repeat center right;
	}
	
	.sorting_desc_disabled {
		background: url('data/adminImages/commonImages/table-sorter/sort_desc_disabled.png') no-repeat center right;
	}
	
	
	/*
	 * Sorting classes for columns
	 */
	/* For the standard odd/even */
	tr.odd td.sorting_1 {
		background-color: #D3D6FF;
	}
	
	tr.even td.sorting_1 {
		background-color: #EAEBFF;
	}
	
	/*******************************************************Tooltip Style START********************************************************************/
	.ui-tooltip-wiki
	{
	   max-width: 700px;	   	   	  
	}
	 
   .ui-tooltip-wiki .ui-tooltip-content
   {
	  padding: 10px;	  
	  line-height: 12.5px;
	  width: 600px;
	  height:500px;
	  overflow:auto;
   }
 
   .ui-tooltip-wiki h1{
	  margin: 0 0 7px;
 
	  font-size: 1.5em;
	  line-height: 1em;
   }
 
   .ui-tooltip-wiki img
   { 
	padding: 0 10px 0 0; 
   }
   
   .ui-tooltip-wiki p{ margin-bottom: 9px; }
   .ui-tooltip-wiki .note{ margin-bottom: 0; font-style: italic; color: #888; }


	/*******************************************************Tooltip Style END*********************************************************************/
</style>
<div id="content" style="padding-top:25px;text-align:left;">
<?php if (!$this->allow('list')) : ?>
<div class="grid_12 t_a_bottom">
		<?php echo $this->translator->translator('Member_Access_deny_desc'); ?>
	</div>
<?php else : ?>
<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0">
  <tr>
	<td id="topGo"><table width="98%" border="0" align="center" cellpadding="0" cellspacing="0">
	  <tr>
		<td width="210" valign="top"><?php echo $this->partial('nav_menu.phtml');  ?></td>
		<td valign="top" >
				<table width="98%" border="0" align="center" cellpadding="0" cellspacing="0">
										  <tr>
											<td height="50"><table width="100%" border="0" align="center" cellpadding="0" cellspacing="0">
											  <tr>
												<td height="68" colspan="8" class="title_1">
													<div style="float:left"><img src="data/adminImages/flightImages/invoice.gif"/></div>
														<div style="padding-top:23px; float:left" class="link_6">&nbsp; <?php echo $this->translator->translator('flight_invoice_list_page_name'); ?> </div>
												
												</td>
											  </tr>
											</table></td>
										  </tr>
										  <tr>
											<td height="4" bgcolor="#7EAD21"></td>
										  </tr>
										  <tr>
											<td >&nbsp;</td>
										  </tr>
										  
										  
										  <tr>
											<td>&nbsp;</td>
										  </tr>
										  <tr>
											<td id="topPagination"><table width="100%" border="0" align="center" cellpadding="0" cellspacing="0">
												<tr>
												 <td><?php
														echo $this->paginationControl($this->datas, 'Sliding', 'top_pagination.phtml'); 	 
													?></td>
												</tr>
											</table></td>
										  </tr>
										  <tr>
											<td>&nbsp;</td>
										  </tr>
										  <tr>
											<td class="text_0"><table id="sortTable" width="100%" border="1" align="center" cellpadding="0" cellspacing="0" bordercolor="#CCCCCC" style="border-collapse:collapse;background-color:#EBEBEB;">
												<thead>
												<tr class="bar_bg_1" style="font-weight:bold;">
												 <th width="3%" align="center"><input type="checkbox" name="checkAll" id="checkAll" class="checkAll_btn" /></th>
												 <th width="6%" align="center"><?php echo $this->translator->translator('flight_invoice_list_invoice_id'); ?></th>
												  <th width="30%" align="center"><?php echo $this->translator->translator('flight_invoice_list_client_name'); ?> </th>
												  <th width="12%" align="center"><?php echo $this->translator->translator('flight_invoice_list_invoice_date'); ?> </th>
												   <th width="10%" align="center"><?php echo $this->translator->translator('flight_invoice_list_invoice_total'); ?> </th>
												   
												<th width="14%" align="center"><?php echo $this->translator->translator('flight_invoice_list_invoice_payment'); ?></th>
												  <th width="9%" align="center"><?php echo $this->translator->translator('payment_status'); ?></th>
												 
												  <th width="6%" align="center"><?php echo $this->translator->translator('common_action'); ?></th>
												</tr>
												</thead>
												<tbody>
												<?php								
												$j = 1;												
												foreach ($this->datas as $entry): 
													$member_info = $mem_db->getMemberInfo($entry->user_id);
													if($j % 2 == 0)
													{
														$onmouseout = "this.bgColor='#FFFFFF';";
														$background = '#FFFFFF';
													}
													else
													{
														$onmouseout = "this.bgColor='#F7F7F7';";
														$background = '#F7F7F7';
													}
												?>
												<tr  bgcolor="<?php echo $background; ?>" onmouseover="this.bgColor='#FCF5DD';" onmouseout="<?php echo $onmouseout; ?>">
												 <td valign="middle" align="center"><input type="checkbox" name="checkbtn" id="checkbtn" value="<?php echo $this->escape($entry->id); ?>" class="check_btn" /></td>
												  <td valign="top" class="td_pad" align="center"><?php echo $this->escape($entry->id); ?></td>
												  <td valign="top" align="center" class="td_pad category_link_1"><a href="<?php echo $this->url( array('module'=> 'Flight', 'controller' => 'backend', 'action'     => 'details', 'invoice_id' => $this->escape($entry->id) ), 'adminrout',    true) ?>"><?php echo $this->escape($member_info['title']).' '.$this->escape($member_info['firstName']).' '.$this->escape($member_info['lastName']); ?></a></td>
												  <td valign="middle" align="center" title="<?php echo $this->escape($entry->invoice_create_date); ?>"><?php echo strftime('%d/%m/%Y',strtotime($this->escape($entry->invoice_create_date))); ?></td>
												  <td valign="top" class="td_pad" align="center" >
												  <?php echo $currencySymbol.$this->escape($entry->total).$currencyShort; ?>
												  </td>
												  
												   <td valign="top" class="td_pad" align="center"><?php echo $this->escape($entry->payment_method); ?></td>
												  <td valign="top" class="td_pad" align="center"><?php if($this->escape($entry->status) == '1'){ echo $this->translator->translator('common_paid_language'); }else if($this->escape($entry->status) == '2'){ echo $this->translator->translator('common_unpaid_language'); }else if($this->escape($entry->status) == '0'){ echo $this->translator->translator('common_cancelled_language'); }  ?></td>
												  
												  <td align="center"><table width="100%" border="0" align="center" cellpadding="0" cellspacing="0">
													<tr>
														
													  <td align="center">
													  		<?php if ($this->allow('edit','backendpro','Flight')) : ?>
													  		<a href="<?php echo $this->url( array('module'=> 'Flight', 'controller' => 'price', 'action'     => 'edit', 'id' => $this->escape($entry->id) ), 'adminrout',    true) ?>"><img src="data/adminImages/commonImages/edit.gif" title="<?php echo $this->translator->translator('common_edit_title'); ?>" alt="<?php echo $this->translator->translator('common_edit_title'); ?>"  border="0" /></a>
															<?php endif; ?>
													  </td>									
													  <td  align="center">
													  		<?php if ($this->allow('delete','backendpro','Flight')) : ?>
													  		<a href="javascript:void(0);" class="delete_btn"  rel="<?php echo $this->escape($entry->id); ?>"><img src="data/adminImages/commonImages/delete.gif" title="<?php echo $this->translator->translator('common_delete_title'); ?>" alt="<?php echo $this->translator->translator('common_delete_title'); ?>" border="0" /></a>
															<?php endif; ?>
													  </td>														
													  <td align="center">
															<?php if ($this->allow('view','backend','Flight')) : ?>
															<a href="javascript:void(0);" class="invoice_btn" rel="<?php echo $this->escape($entry->id); ?>"><img src="data/adminImages/commonImages/preview.gif" border="0" title="<?php echo $this->translator->translator('common_preview_title'); ?>" /></a>
															<?php endif; ?>
													  </td>													
													</tr>
												  </table></td>
												</tr>
												<?php 													
													$j++;
													endforeach;	
												  ?>
											   </tbody>
											</table></td>
										  </tr>
										  <tr>
											<td height="1"></td>
										  </tr>
										  <tr>
											<td id="bottomPagination"><table width="100%" border="1" cellspacing="0" cellpadding="0" bgcolor="#F4F4F4" bordercolor="#CCCCCC" style="border-collapse:collapse;">
												<tr>
												  <td height="28">
													<?php
														echo $this->paginationControl($this->datas, 'Sliding', 'pagination.phtml'); 	 
													?>
													</td>
												</tr>
											</table></td>
										  </tr>
										  <tr>
											<td >&nbsp;</td>
										  </tr>
										  <tr>
											<td >&nbsp;</td>
										  </tr>
										  <tr>
											<td  height="4" bgcolor="#7EAD21"></td>
										  </tr>
										  <tr>
											<td height="50"><table width="100%" border="0" align="center" cellpadding="0" cellspacing="0">
											  <tr>
												<td height="60" colspan="8" class="title_1">
													
												
												</td>
												<td width="9%" align="right"><?php if ($this->allow('paid','backend','Flight')) : ?>
											    <div class="extra_btn ui-widget-content-1" align="right"><a href="javascript: void(0);" rel="paid" class="publish_all"><?php echo $this->translator->translator('common_paid_selected'); ?></a></div><?php endif; ?></td>
												<td width="1%" >&nbsp;</td>
												<td width="9%" align="right"><?php if ($this->allow('paid','backend','Flight')) : ?>
											    <div class="extra_btn ui-widget-content-1" align="right"><a href="javascript: void(0);" rel="unpaid" class="publish_all"><?php echo $this->translator->translator('common_unpaid_selected'); ?></a></div><?php endif; ?></td>
												<td width="1%" >&nbsp;</td>
												<td width="9%" align="right"><?php if ($this->allow('delete','backend','Flight')) : ?>
											    <div class="extra_btn ui-widget-content-1" align="right"><a href="javascript: void(0);" class="delete_all"><?php echo html_entity_decode($this->translator->translator("common_delete_selected"), ENT_QUOTES, "UTF-8"); ?></a></div><?php endif; ?></td>
												<td width="1%" >&nbsp;</td>												
												<td width="9%" align="right"><?php if ($this->allow('paid','backend','Flight')) : ?>
											    <div class="extra_btn ui-widget-content-1" align="right"><a href="javascript: void(0);" rel="cancel" class="publish_all"><?php echo $this->translator->translator('common_cancel_selected'); ?></a></div><?php endif; ?></td>
											  </tr>
											</table></td>
										  </tr>
										  
										</table>
		</td>
	  </tr>
	</table></td>
  </tr>
</table>
<div  id="floatingbar">
	<table width="95%" border="0" cellpadding="0" cellspacing="0">
	  <tr>
		<td height="38" class="title_1">			
				&nbsp;<?php echo $this->translator->translator('flight_invoice_list_page_name'); ?>	
		</td>
		<td width="9%" align="right"><?php if ($this->allow('paid','backend','Flight')) : ?>
		<div class="extra_btn ui-widget-content-1" align="right"><a href="javascript: void(0);" rel="paid" class="publish_all"><?php echo $this->translator->translator('common_paid_selected'); ?></a></div><?php endif; ?></td>
		<td width="1%" >&nbsp;</td>
		<td width="9%" align="right"><?php if ($this->allow('paid','backend','Flight')) : ?>
		<div class="extra_btn ui-widget-content-1" align="right"><a href="javascript: void(0);" rel="unpaid" class="publish_all"><?php echo $this->translator->translator('common_unpaid_selected'); ?></a></div><?php endif; ?></td>
		<td width="1%" >&nbsp;</td>
		<td width="9%" align="right"><?php if ($this->allow('delete','backend','Flight')) : ?>
		<div class="extra_btn ui-widget-content-1" align="right"><a href="javascript: void(0);" class="delete_all"><?php echo html_entity_decode($this->translator->translator("common_delete_selected"), ENT_QUOTES, "UTF-8"); ?></a></div><?php endif; ?></td>
		<td width="1%" >&nbsp;</td>		
		<td width="9%" align="right"><?php if ($this->allow('paid','backend','Flight')) : ?>
		<div class="extra_btn ui-widget-content-1" align="right"><a href="javascript: void(0);" rel="cancel" class="publish_all"><?php echo $this->translator->translator('common_cancel_selected'); ?></a></div><?php endif; ?></td>
	   </tr>
	</table>
</div>
<?php endif; ?>
<div id="dialog_container" title="<?php echo $this->translator->translator('common_dialog_msg',$this->translator->translator('flight_page_list_page_name')); ?>"></div>
<div id="dialog-confirm" title="<?php echo $this->translator->translator('common_confirmation',$this->translator->translator('common_delete')); ?>"></div>
</div>