<div id="content" style="padding-top:25px;text-align:left;">
<?php if (!$this->allow('details')) : ?>
<div class="grid_12 t_a_bottom">
		<?php echo $this->translator->translator('Member_Access_deny_desc'); ?>
	</div>
<?php 
	else : 	
	$mem_db = new Members_Model_DbTable_MemberList();
	$country_db = new Eicra_Model_DbTable_Country();
	$mem_info = $mem_db->getMemberInfo($this->quote_arr['user_id']);
	$global_conf = Zend_Registry::get('global_conf');
	$currency = new Zend_Currency($global_conf['default_locale']);
	$currencySymbol = $currency->getSymbol();
	$currencyShort = $currency->getShortName();
?>
<script type="text/javascript">
$(document).ready(function() {		
	
	floatingbar('#floatingbar',"#button_top_bar",null);
		
	function stripslashes(str) 
	{
		str=str.replace(/\\'/g,'\'');
		str=str.replace(/\\"/g,'"');
		str=str.replace(/\\0/g,'\0');
		str=str.replace(/\\\\/g,'\\');
		return str;
	}
	
	
	function openMsgDialog(msg)
	{
		$('#dialog_msg').html(msg).dialog({
			autoOpen: true,
			modal: true,
			show: 'fade',
			resizable: 'false',				
			buttons: { "<?php echo html_entity_decode($this->translator->translator('common_ok'), ENT_QUOTES, 'UTF-8'); ?>": function() { $(this).dialog('option', 'hide', 'explode').dialog("close"); } },
			open: function(event, ui)
				 {
					setTimeout(function() 
					{									
						if($('#' + event.target.id).dialog('isOpen'))
						{
							$('#' + event.target.id).dialog('option', 'hide', 'explode').dialog('close');										
						}
					}, 10000);
				  }
		});
	}
	
	$('a.reset_btn').click(function() {			
		 resetFields();	
		 removeError();	
	});
	
	function resetFields()
	{
		$( "form" )[ 0 ].reset();				
	}
	
	function removeError()
	{
		$('#actionMessage').attr('class','none');
		$('#actionMessage').html('&nbsp;');
		
		var filename = '';
		var filevalue = '';		
		$.each($('form').serializeArray(), function(i, field) {	
				if(field.name.match(/\[\]$/))
				{
					var filearr = field.name.split('[]');
					filename = filearr[0];					
				}
				else
				{
					filename 	= 	field.name;
				} 			
				$('#'+filename).removeClass('ui-state-error');
				$('#'+filename+'_err').html('');									
		});				
	}
	
	function addError(key,errMsg)
	{
		var err_id = key+'_err';
		var field_name = key;
		$('#'+field_name).addClass('ui-state-error');
		$('#'+err_id).append('<span style="color:#FF0000;font-width:bold;" >'+errMsg+"</span>");
	}
	
	function openLoaderDialog()
	{
		$('#dialog_container').dialog({
			autoOpen: true,
			modal: true,
			show: 'fade',
			resizable: 'false',				
			open: function(event, ui)
				 {
					$("#progressbar").progressbar({
						value:100
		
					});							
				  }
		});
	}
	
	function closeLoaderDialog()
	{
		$('#dialog_container').dialog('option','hide','explode').dialog('close');
	}
	
	function getFormData()
	{
		var fieldObj = {};
		var filename = '';
		var filevalue = '';
		$.each($('form').serializeArray(), function(i, field) {	
			if(field.name.match(/\[\]$/))
			{
				var filearr = field.name.split('[]');
				filename = filearr[0];
				filevalue = $('#'+filename).val();
			}
			else
			{
				filename 	= 	field.name;
				filevalue 	= 	field.value;
			}			
			fieldObj[filename] = filevalue;			
		});
		return fieldObj;
	}
	
	$('a.quote_save_btn').click(function() {			
			
		var formData = getFormData();
		formData.quote_id = '<?php echo $this->quote_id; ?>';
		
		$.ajax({
			url: "<?php echo $this->url( array('module' => 'Flight','controller' => 'backend', 'action'     => 'quoteedit' ), 'adminrout',    true) ?>",
			  	type: 'POST',
			  	data: formData,
				beforeSend: function(){						
						removeError();
						openLoaderDialog();				
					 },
				success: function(response){
					//alert(response);					
					var json_arr = eval("("+response+")");					
					closeLoaderDialog();					
					if(json_arr.status == 'ok')
					{
						$('#actionMessage').attr('class','seccMess');
						$('#actionMessage').html(json_arr.msg);								
					}
					else if(json_arr.status == 'errV')
					{
						$('#actionMessage').attr('class','errMess');
						$('#actionMessage').html("<?php echo $this->translator->translator('common_err'); ?>");
												
						for(var i= 0; i < json_arr.msg.length; i++)
						{
							addError(json_arr.msg[i].key,json_arr.msg[i].value);							
						}
					}
					else
					{
						$('#actionMessage').attr('class','errMess');
						$('#actionMessage').html(json_arr.msg);
					}
				}
		});
	});
	
		
	
});

</script>
<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0">
	<tr>
	  <td>
		<table width="98%" border="0" align="center" cellpadding="0" cellspacing="0">
			  <tr>
				<td width="50%" height="58" class="title_1">
					<div style="float:left"><img src="data/adminImages/propertyImages/property-add.gif"  height="51" /></div>
					<div style="padding-top:16px; float:left">&nbsp;<?php echo $this->translator->translator('flight_details_invoice_page_name'); ?></div>
				
				</td>
				<td width="50%"><table width="360" border="0" align="right" cellpadding="0" cellspacing="0">
					<tr>
					  <td width="120"></td>
					  <td width="120"><div class="extra_btn ui-widget-content-1" align="right"><a href="<?php echo $this->url( array('module' => 'Flight','controller' => 'backend', 'action'     => 'quotelist' ), 'adminrout',    true) ?>" class="back_btn_link"><?php echo $this->translator->translator('common_back'); ?></a></div></td>
					  <td width="120"><div class="extra_btn ui-widget-content-1" align="right"><a href="javascript:void(0);" class="quote_save_btn"><?php echo $this->translator->translator('common_save'); ?></a></div></td>
					</tr>
				</table></td>
			  </tr>
		  </table>	
	  </td>
	</tr>
	<tr>
	  <td height="4" bgcolor="#7EAD21" id="button_top_bar"></td>
	</tr>
	<tr>
	  <td height="4"></td>
	</tr>
	<tr>
  		<td>
			<div id="tabs" style="font-size:11px;margin:15px;">
			
				<div id="tabs-1">
					<table width="100%" cellpadding="0">
						<tr>
							<td width="49%">
								<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" style="border:1px solid #CCCCCC;">
									<tr>
									  <td class="bar_bg_1">
										<table cellpadding="0" cellspacing="0" border="0" width="100%">
											<tr>
												<td style="padding-left:5px;" class="title2">
													 <strong><?php echo $this->translator->translator('Flight_details_client_info'); ?></strong>
												</td>
												<td align="right" style="padding-right:5px;text-align:right;">
													
												</td>
											</tr>
										  </table>
										</td>
									</tr>
									<tr>
									  <td>&nbsp;</td>
									</tr>
									<tr>
									  <td><table width="98%" border="0" align="center" cellpadding="5" cellspacing="0" style="font-size:13px; color:#000000; font-family:Arial, Helvetica, sans-serif;">
										<tr>
										  <td width="33%"   valign="top" style="padding-left:5px;"><?php echo $this->translator->translator('Flight_details_client_first_name_title'); ?></td>
										  <td width="67%" valign="top">
											  <?php 					  
												echo $this->escape($mem_info['firstName']); 
											  ?>							  </td>
										</tr>
										
										<tr>
										  <td width="33%"   valign="top" style="padding-left:5px;"><?php echo $this->translator->translator('Flight_details_client_last_name_title'); ?></td>
										  <td width="67%" valign="top">
										  <?php 					  
												echo $this->escape($mem_info['lastName']); 
										  ?>							  </td>
										</tr>
										
										<tr>
										  <td width="33%"   valign="top" style="padding-left:5px;"><?php echo $this->translator->translator('Flight_details_client_company_name_title'); ?></td>
										  <td width="67%" valign="top">
											<?php echo $this->escape($mem_info['companyName']); ?>							  </td>
										</tr>													
													
										<tr>
										  <td width="33%"   valign="top" style="padding-left:5px;"><?php echo $this->translator->translator('Flight_details_client_email_address_title'); ?></td>
										  <td width="67%" valign="top">
											<?php echo $this->escape($mem_info['username']); ?>							  </td>
										</tr>	
														
										<tr>
										  <td width="33%"   valign="top" style="padding-left:5px;"><?php echo $this->translator->translator('Flight_details_client_address_title'); ?></td>
										  <td width="67%" valign="top">
											<?php echo $this->escape($mem_info['address']); ?>							  </td>
										</tr>
													
										<tr>
										  <td width="33%"   valign="top" style="padding-left:5px;"><?php echo $this->translator->translator('Flight_details_client_postalCode_title'); ?></td>
										  <td width="67%" valign="top">
											<?php echo $this->escape($mem_info['postalCode']); ?>							  </td>
										</tr>
													
										<tr>
										  <td width="33%"   valign="top" style="padding-left:5px;"><?php echo $this->translator->translator('Flight_details_client_city_title'); ?></td>
										  <td width="67%" valign="top">
											<?php echo $this->escape($mem_info['city']); ?>							  </td>
										</tr>
														
										<tr>
										  <td width="33%"   valign="top" style="padding-left:5px;"><?php echo $this->translator->translator('Flight_details_client_state_title'); ?></td>
										  <td width="67%" valign="top">
											<?php echo $this->escape($mem_info['state']); ?>							  </td>
										</tr>
													
										<tr>
										  <td width="33%"   valign="top" style="padding-left:5px;"><?php echo $this->translator->translator('Flight_details_client_country_title'); ?></td>
										  <td width="67%" valign="top">
											<?php $country_info = $country_db->getInfo($mem_info['country']); echo $this->escape($country_info['value']); ?>							  </td>
										</tr>
										
									  </table></td>
									</tr>
									
									<tr>
									  <td>&nbsp;</td>
									</tr>
								  </table>
							</td>
							<td width="2%">&nbsp;
								
							</td>
							<td width="49%">
								<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" style="border:1px solid #CCCCCC;">
									<tr>
									  <td class="bar_bg_1">
										<table cellpadding="0" cellspacing="0" border="0" width="100%">
											<tr>
												<td style="padding-left:5px;" class="title2">
													 <strong><?php echo $this->translator->translator('Flight_details_client_billing_info'); ?></strong>
												</td>
												<td align="right" style="padding-right:5px;text-align:right;">
													
												</td>
											</tr>
										  </table>
										</td>
									</tr>
									<tr>
									  <td>&nbsp;</td>
									</tr>
									<tr>
									  <td><table width="98%" border="0" align="center" cellpadding="5" cellspacing="0" style="font-size:13px; color:#000000; font-family:Arial, Helvetica, sans-serif;">
										<tr>
										  <td width="37%"   valign="top" style="padding-left:5px;"><?php echo $this->translator->translator('Flight_details_client_invoice_id_title'); ?></td>
										  <td width="63%" valign="top">
										  <?php echo $this->escape($this->quote_arr['id']); ?>							  </td>
										</tr>
										
										<tr>
										  <td width="37%"   valign="top" style="padding-left:5px;"><?php echo $this->translator->translator('Flight_details_client_paid_title'); ?></td>
										  <td width="63%" valign="top">
										  <?php 					  
												$billing_paid = ($this->quote_arr['total']) ? $this->quote_arr['total'] : '00.00' ; 
												echo $currencySymbol.$billing_paid.$currencyShort;
											  ?>							  </td>
										</tr>
										
										<tr>
										  <td width="37%"   valign="top" style="padding-left:5px;"><?php echo $this->translator->translator('Flight_details_client_unpaid_title'); ?></td>
										  <td width="63%" valign="top">
										  <?php 					  
												$billing_unpaid = ($this->quote_arr['total']) ? $this->quote_arr['total'] : '00.00' ; 
												echo $currencySymbol.$billing_unpaid.$currencyShort;
										  ?>							  </td>
										</tr>
										
										<tr>
										  <td width="37%"   valign="top" style="padding-left:5px;"><?php echo $this->translator->translator('Flight_details_client_cancel_title'); ?></td>
										  <td width="63%" valign="top">
											<?php 
												$billing_cancel = ($this->quote_arr['total']) ? $this->quote_arr['total'] : '00.00' ; 
												echo $currencySymbol.$billing_cancel.$currencyShort;
											 ?>							  </td>
										</tr>													
														
										<tr>
										  <td width="37%"   valign="top" style="padding-left:5px;"><?php echo $this->translator->translator('Flight_details_client_tax_title'); ?></td>
										  <td width="63%" valign="top">
											<?php echo $currencySymbol.$this->escape($this->quote_arr['tax']).$currencyShort; ?>							  </td>
										</tr>
													
										<tr>
										  <td width="37%"   valign="top" style="padding-left:5px;"><?php echo $this->translator->translator('Flight_details_client_total_income_title'); ?></td>
										  <td width="63%" valign="top">
											<?php 
												echo '<b>'.$currencySymbol.($billing_paid + $this->quote_arr['tax']).$currencyShort.'</b>';
											 ?>							  </td>
										</tr>								
													
										<tr>
										  <td width="37%"   valign="top" style="padding-left:5px;"><?php echo $this->translator->translator('Flight_details_client_payment_title'); ?></td>
										  <td width="63%" valign="top">
											<?php echo $this->escape($this->quote_arr['payment_method']); ?>							  </td>
										</tr>
													
										<tr>
										  <td width="37%"   valign="top" style="padding-left:5px;"><?php echo $this->translator->translator('Flight_details_client_invoice_create_date_title'); ?></td>
										  <td width="63%" valign="top">
											<?php echo $this->escape($this->quote_arr['quote_create_date']); ?>							  </td>
										</tr>
														
										<tr>
										  <td width="37%"   valign="top" style="padding-left:5px;"><?php echo $this->translator->translator('Flight_details_client_invoice_updated_date_title'); ?></td>
										  <td width="63%" valign="top">
											<?php echo $this->escape($this->quote_arr['quote_update_date']); ?>							  </td>
										</tr>	
										
									  </table></td>
									</tr>
									
									<tr>
									  <td>&nbsp;</td>
									</tr>
								  </table>
							</td>
						</tr>
						<tr>
							<td>&nbsp;
								
							</td>
						</tr>
						<tr>
							<td colspan="3">
								<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" style="border:1px solid #CCCCCC;">
									<tr>
									  <td class="bar_bg_1">
										<table cellpadding="0" cellspacing="0" border="0" width="100%">
											<tr>
												<td style="padding-left:5px;" class="title2">
													 <strong><?php echo $this->translator->translator('Flight_details_client_invoice_items'); ?></strong>
												</td>
												<td align="right" style="padding-right:5px;text-align:right;">
													
												</td>
											</tr>
										  </table>
										</td>
									</tr>
									<tr>
									  <td>&nbsp;</td>
									</tr>
									<tr>
									  <td align="center">
									  
									  <table width="98%" border="0" cellspacing="0">
										  <tbody>
										  
										<?php
												
													$invoiceItems_db = new Flight_Model_DbTable_QuoteItems();
													$invoiceItems_info = $invoiceItems_db->getQuoteItemsInfo($this->quote_arr['user_id'],$this->quote_arr['id']);
													
										?>
											<tr>
												<td>
													<table width="100%" border="0" cellspacing="0">
														<tbody>
														<tr>
															<td align="left"  style="border:1px solid #cccccc;border-bottom:0px;border-right:0px;padding-left:5px;"><?php echo '<b>'.$this->translator->translator("flight_invoice_id_title").'</b>: #'.$this->quote_arr['id']; ?></td>
															<td  align="right" style="border:1px solid #cccccc;border-bottom:0px;border-left:0px;padding-right:5px;"><?php echo '<b>'.$this->translator->translator("flight_invoice_date_title").'</b>: '.$this->quote_arr['invoice_create_date']; ?></td>
														  </tr>
														<tr>
															<td width="77%" align="center" style="border:1px solid #cccccc;border-bottom:0px;border-right:0px;"><?php echo '<b>'.$this->translator->translator("flight_invoice_desc_title").'</b>'; ?></td>
															<td  align="center" style="border:1px solid #cccccc;border-bottom:0px;"><?php echo '<b>'.$this->translator->translator("flight_invoice_amount_title").'</b>'; ?></td>
														  </tr>
												<?php
																$total_amount = 0;
																$total_tax = 0;		
																foreach($invoiceItems_info as $key => $invoiceItems)
																{
																$item_info = Zend_Json::decode($invoiceItems['object_value']);		
														?>			
																<tr>
																		<td style="border:1px solid #cccccc;border-bottom:0px;border-right:0px;">
																		<table width="100%">
																			<tr>
																				<td><img src="data/frontImages/flight/airlines/<?php echo $item_info['airline_infos']['airlines_pic']; ?>" height="60" title="<?php echo $item_info['airline_infos']['airlines']; ?>" /></td>
																				<td>
																				<?php echo $item_info['FlightInfoExResult'][0]['originName'].', '.$item_info['FlightInfoExResult'][0]['originCity'].' --> '.$item_info['FlightInfoExResult'][0]['destinationName'].', '.$item_info['FlightInfoExResult'][0]['destinationCity']; ?>
																				<br />
																				<?php echo '<strong>'.$this->translator->translator("flight_AirlineFlightSchedules_page_table_depart").' :</strong> '.$item_info['FlightInfoExResult'][0]['filed_departuretime']; ?>
																				<br  />
																				<?php echo '<strong>'.$this->translator->translator("flight_AirlineFlightSchedules_page_table_arive").' :</strong> '.$item_info['FlightInfoExResult'][0]['estimatedarrivaltime']; ?>
																				<br  />
																				<?php echo '<strong>'.$this->translator->translator("flight_AirlineFlightSchedules_page_table_class").' :</strong> '.$item_info['airline_price_info']['classType']; ?>
																				</td>
																			</tr>
																		</table>	
																		<td style="border:1px solid #cccccc;border-bottom:0px;">
																			<table border="0" width="100%">
																				<tr>
																					<td width="22%"><?php echo $this->translator->translator("flight_AirlineFlightSchedules_page_table_adult").' ('.$item_info['airline_price_info']['adult_no'].')'; ?> :</td>
																					<td width="78%"><?php echo $currencySymbol; ?><input type="text" name="adult_price<?php echo $key; ?>" id="adult_price<?php echo $key; ?>" value="<?php echo $invoiceItems['adult_price']; ?>"  /><?php echo $currencyShort.' '.$this->translator->translator("flight_quote_price_per_person"); ?></td>
																				</tr>
																				<tr>
																					<td><?php echo $this->translator->translator("flight_AirlineFlightSchedules_page_table_child").' ('.$item_info['airline_price_info']['child_no'].')'; ?> :</td><td><?php echo $currencySymbol; ?><input type="text" name="child_price<?php echo $key; ?>" id="child_price<?php echo $key; ?>" value="<?php echo $invoiceItems['child_price']; ?>"  /><?php echo $currencyShort.' '.$this->translator->translator("flight_quote_price_per_person"); ?></td>
																				</tr>
																				<tr>
																					<td><?php echo $this->translator->translator("flight_AirlineFlightSchedules_page_table_infant").' ('.$item_info['airline_price_info']['infant_no'].')'; ?> :</td><td><?php echo $currencySymbol; ?><input type="text" name="infant_price<?php echo $key; ?>" id="infant_price<?php echo $key; ?>" value="<?php echo $invoiceItems['infant_price']; ?>"  /><?php echo $currencyShort.' '.$this->translator->translator("flight_quote_price_per_person"); ?></td>
																				</tr>
																			</table>
																		</td>
																	  </tr>
																	  <tr>
																		<td style="border:1px solid #cccccc;border-bottom:0px;border-right:0px;"></td>
																		<td style="border:1px solid #cccccc;border-bottom:0px;">
																			<table border="0" width="100%">
																				<tr>
																					<td width="22%"> <?php echo $this->translator->translator("flight_invoice_total_tax_title"); ?></td>
																				  <td width="78%">&nbsp;&nbsp;<input type="text" name="total_tax<?php echo $key; ?>" id="total_tax<?php echo $key; ?>" value="<?php echo $invoiceItems['taxable']; ?>"  /><?php echo '%'; ?></td>
																				</tr>
																			</table>
																		</td>
																	  </tr>
																		 
												<?php					
															}													
												?>				
																<tr>
																	<td style="border-top:1px solid #cccccc;">&nbsp;</td>
																	<td style="border-top:1px solid #cccccc;">&nbsp;	
																			
																	</td>
																  </tr>																	
																</tbody>
														</table>
												</td>
											</tr>										
										  </tbody>
										</table>
									  
									  </td>
									</tr>
									
									<tr>
									  <td>&nbsp;</td>
									</tr>
								  </table>
							</td>
						</tr>
						<tr>
							<td>&nbsp;</td>
						</tr>
						<tr>
							<td colspan="3">
								<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0" style="border:1px solid #CCCCCC;">
									<tr>
									  <td class="bar_bg_1">
										<table cellpadding="0" cellspacing="0" border="0" width="100%">
											<tr>
												<td style="padding-left:5px;" class="title2">
													 <strong><?php echo $this->translator->translator('Flight_quote_notes_title'); ?></strong>
												</td>
												<td align="right" style="padding-right:5px;text-align:right;">
													
												</td>
											</tr>
										  </table>
										</td>
									</tr>
									<tr>
									  <td>&nbsp;</td>
									</tr>
									<tr>
									  <td align="center">
									  	<table width="100%" cellpadding="0" cellspacing="0">
											<tr>
												<td align="right"><?php echo $this->translator->translator('Flight_quote_customer_notes'); ?></td><td><textarea name="quote_customer_notes" id="quote_customer_notes" cols="70" rows="5"><?php echo $this->escape($this->quote_arr['quote_customer_notes']); ?></textarea></td>
											</tr>
											<tr>
												<td align="right"><?php echo $this->translator->translator('Flight_quote_admin_notes'); ?></td><td><textarea name="quote_admin_notes" id="quote_admin_notes" cols="70" rows="5"><?php echo $this->escape($this->quote_arr['quote_admin_notes']); ?></textarea></td>
											</tr>
										</table>
									 </td>
									</tr>
									<tr>
									  <td>&nbsp;</td>
									</tr>
								</table>
							</td>
						</tr>
					</table>
				</div>				
			</div>
		</td>
	</tr>
	<tr>
	  <td height="4"></td>
	</tr>
	<tr>
	  <td height="4" bgcolor="#7EAD21"></td>
	</tr>
	<tr>
	  <td>
		<table width="98%" border="0" align="center" cellpadding="0" cellspacing="0">
			  <tr>
				<td width="50%" height="58">				
				</td>
				<td width="50%"><table width="360" border="0" align="right" cellpadding="0" cellspacing="0">
					<tr>
					  <td width="120"></td>
					  <td width="120"><div class="extra_btn ui-widget-content-1" align="right"><a href="<?php echo $this->url( array('module' => 'Flight','controller' => 'backend', 'action'     => 'quotelist' ), 'adminrout',    true) ?>" class="back_btn_link"><?php echo $this->translator->translator('common_back'); ?></a></div></td>
					  <td width="120"><div class="extra_btn ui-widget-content-1" align="right"><a href="javascript:void(0);" class="quote_save_btn"><?php echo $this->translator->translator('common_save'); ?></a></div></td>
					</tr>
				</table></td>
			  </tr>
		  </table>	
	  </td>
	</tr>
</table>
<div  id="floatingbar">
	<table width="95%" border="0" cellpadding="0" cellspacing="0">
		<tr>
			<td>
				<?php echo $this->translator->translator('flight_details_invoice_page_name'); ?>
			</td>
			<td align="right" style="padding-top:7px;">
				<table width="360" border="0" align="right" cellpadding="0" cellspacing="0">
					<tr>
					  <td width="120" id="showPosition"></td>
					  <td width="120"><div class="extra_btn ui-widget-content-1" align="right"><a href="<?php echo $this->url( array('module' => 'Flight','controller' => 'backend', 'action'     => 'quotelist' ), 'adminrout',    true) ?>" class="back_btn_link"><?php echo $this->translator->translator('common_back'); ?></a></div></td>
					  <td width="120"><div class="extra_btn ui-widget-content-1" align="right"><a href="javascript:void(0);" class="quote_save_btn"><?php echo $this->translator->translator('common_save'); ?></a></div></td>
					</tr>
				</table>
			</td>
		</tr>
	</table>
</div>
<div id="dialog_msg" title="<?php echo $this->translator->translator('common_dialog_msg',$this->translator->translator('flight_page_add_page_name')); ?>"></div>
<div id="dialog_container" title="<?php echo $this->translator->translator('common_processing_language'); ?>">
	<div id="progressbar" ></div>	
</div>
<?php endif; ?>
</div>