<?php
$version = Zend_Registry::get('version'); 
$tab_base_link = Zend_Controller_Front::getInstance()->getRequest()->getRequestUri();
$front_template = Zend_Registry::get('front_template');
echo $this->headScript()->setFile($this->baseUrl().'/js/jquery/BookingCalendar/js/jquery.dop.BookingCalendar.js');
echo $this->headLink()->setStylesheet($this->baseUrl().'/js/jquery/BookingCalendar/css/jquery.dop.BookingCalendar.css');
echo $this->headScript()->setFile($this->baseUrl().'/js/jquery/raty/js/jquery.raty.js');
echo $this->headScript()->setFile($this->baseUrl().'/js/jquery/gallery/jquery.ad-gallery.js'); 
echo $this->headLink()->setStylesheet($this->baseUrl().'/js/jquery/gallery/jquery.ad-gallery.css');
echo $this->headScript()->setFile($this->baseUrl().'/js/jquery/jquery.scrollTo.js');

$meta_Title = $this->tours_Form->meta_title->getValue();
$meta_keywords = $this->tours_Form->meta_keywords->getValue();
$meta_description = $this->tours_Form->meta_desc->getValue();
$property_name = $this->tours_Form->tours_name->getValue();
$global_conf = Zend_Registry::get('global_conf');
// 1ist param options are : like, inline, plus_minus, horizontal, triangle
$vote = new Vote_Controller_Helper_ShowVoteButton('inline','tours_page' );
if(!empty($property_name)) { $this->headTitle()->headTitle($this->escape($property_name),'SET')->setSeparator(' - ')->headTitle($meta_Title); }
if(!empty($meta_keywords)){ $this->headMeta()->setName('keywords',$meta_keywords); }
if(!empty($meta_description)) { $this->headMeta()->setName('description',$meta_description); }

function isnot_int($tours_operator)
{
	$r = true;			
	if(is_numeric($tours_operator))
	{ 
		if(is_int((int)$tours_operator))
		{
			$r = false;
		}				
	}
	return $r;
}

$auth = Zend_Auth::getInstance ();
$hasIdentity = $auth->hasIdentity ();
$feature_facilities_arr = explode(',', $this->view_datas['inclusions']); 
$item_id = $this->tours_Form->id->getValue();
$group_id = $this->tours_Form->group_id->getValue();
$nextTours = $this->tours_database->getNextTours($item_id,$group_id, null);
$prevTours = $this->tours_database->getPrevTours($item_id,$group_id, null);
$country_id = $this->tours_Form->country_id->getValue();
$state_id = $this->tours_Form->state_id->getValue();
$area_id = $this->tours_Form->area_id->getValue();
$display_related_item_limit = 10 ;
$multi_space = ' ';
$maximum_rating_digit = $this->translator->translator('maximum_rating_digit');

if($area_id)
{												
	try

	{
		$area_db = new Tours_Model_DbTable_Area();

		$area_info = $area_db->getAreaInfo($area_id);		

	}
	catch(Exception $e)
	{
		echo $e->getMessage() ;
	}
}

if($state_id)
{
	try

	{

		$state_db = new Tours_Model_DbTable_State();
		$state_info = $state_db->getStateInfo($state_id);
	}
	catch(Exception $e)
	{
		echo $e->getMessage() ;
	}
}

if($country_id)

{
	try

	{

		$country_db = new Tours_Model_DbTable_Country();
		$country_info = $country_db->getCountryName($country_id);
	}

	catch(Exception $e)

	{
		echo $e->getMessage() ;
	}
} 
?>
<script type="text/javascript">
function scrolling(class_name)

{
	$.easing.elasout = function(x, t, b, c, d) {
		var s=1.70158;var p=0;var a=c;
		if (t==0) return b;  if ((t/=d)==1) return b+c;  if (!p) p=d*.3;
		if (a < Math.abs(c)) { a=c; var s=p/4; }

		else var s = p/(2*Math.PI) * Math.asin (c/a);
		return a*Math.pow(2,-10*t) * Math.sin( (t*d-s)*(2*Math.PI)/p ) + c + b;
	};

	$('a.'+class_name).click(function(){//$.scrollTo works EXACTLY the same way, but scrolls the whole screen

		var rel = $(this).attr('rel');
		var id_arr = rel.split('-');
		var id_no = parseInt(id_arr[1]);
		$('#tabs').tabs({ active: --id_no });
		$.scrollTo( rel , 1500, { easing:'swing' });		
		return false;
	});
}

function changeImageScrolling()
{
	$.easing.elasout = function(x, t, b, c, d) {

		var s=1.70158;var p=0;var a=c;

		if (t==0) return b;  if ((t/=d)==1) return b+c;  if (!p) p=d*.3;

		if (a < Math.abs(c)) { a=c; var s=p/4; }

		else var s = p/(2*Math.PI) * Math.asin (c/a);

		return a*Math.pow(2,-10*t) * Math.sin( (t*d-s)*(2*Math.PI)/p ) + c + b;
	};

	 $("a.change_img").click(function(){

			var self = this;

			var src = $(self).children("img:nth-child(1)").attr('src');			

			$("div.ad-image").children("img:nth-child(1)").attr('src',src);							

			$.scrollTo( '#gallery' , 1500, { easing:'swing' });			

			return false;
		});
}

 $(function() {				

				var galleries = $('.ad-gallery').adGallery({

					slideshow: {

                       enable: true,

                       autostart: true,

                       speed: 5000,

                       start_label: 'Start',

                       stop_label: 'Stop',

                       stop_on_scroll: true,

                       countdown_prefix: '(',

                       countdown_sufix: ')',

                       onStart: false,

                       onStop: false

                     }

					 });

				$('#switch-effect').change(

				  function() {

					galleries[0].settings.effect = $(this).val();

					return false;

				  }

				);

				$('#toggle-slideshow').click(

				  function() {

					galleries[0].slideshow.toggle();

					return false;

				  }

				);

				$('#toggle-description').click(

				  function() {

					if(!galleries[0].settings.description_wrapper) {

					  galleries[0].settings.description_wrapper = $('#descriptions');

					} else {

					  galleries[0].settings.description_wrapper = false;

					}

					return false;

				  }

				);

			  });

$(function() {

		$('#slickbox').hide();

		$('a.slick-slidetoggle').click(function() {

			$('#slickbox').slideToggle(400);

			return false;

		  });

		 <?php if($this->tab == '4'){ ?>			 

				$('#dialog_calendar').DOPBookingCalendar({'Type':'FrontEnd', 'DataURL':'<?php echo $this->url( array("module"=> "Tours", "controller" => "frontend", "action"     => "load", "id" => $this->escape($this->view_datas["id"]) ), "adminrout",    true) ?>','Currency':'<?php echo $this->currency->getSymbol(); ?>'});

		<?php  } ?>

		$("#tabs").tabs({ 
				active: <?php echo $this->tab; ?>,
				select: function(event, ui) { 					  					      

						$('#dialog_calendar').DOPBookingCalendar({'Type':'FrontEnd', 'DataURL':'<?php echo $this->url( array("module"=> "Tours", "controller" => "frontend", "action"     => "load", "id" => $this->escape($this->view_datas["id"]) ), "adminrout",    true) ?>','Currency':'<?php echo $this->currency->getSymbol(); ?>'});

					}

				}).find(".ui-tabs-nav").sortable({axis:'xy'});
		$("#matchTabs").tabs().find(".ui-tabs-nav").sortable({axis:'xy'});

		changeImageScrolling();

		scrolling('review_btn');

		scrolling('calendar_btn');

	});










$(function() {
	$( "#tours_operator" ).combobox();		
	autoSuggestion('tours_name', "<?php echo $this->url( array('module'=> 'Tours', 'controller' => 'backendpro', 'action'     => 'searchname' ), 'adminrout',    true) ?>", {'tours_name': ''}, ['tours_primary_image', 'tours_image', 'tours_name', 'tours_name', 'post_code', 'owner_name', 'num_of_days','tours_postcode' ,'ending_city', 'tours_location'], 'data/frontImages/tours/tours_image', 2);	
	autoSuggestion('post_code', "<?php echo $this->url( array('module'=> 'Tours', 'controller' => 'backendpro', 'action'     => 'searchname' ), 'adminrout',    true) ?>", {'post_code': ''}, ['tours_primary_image', 'tours_image', 'tours_name', 'post_code', 'owner_name', 'num_of_days','tours_postcode' ,'ending_city', 'tours_location'], 'data/frontImages/tours/tours_image', 2);	
	autoSuggestion('tours_price', "<?php echo $this->url( array('module'=> 'Tours', 'controller' => 'backendpro', 'action'     => 'searchname' ), 'adminrout',    true) ?>", {'post_code': ''}, ['tours_primary_image', 'tours_image', 'tours_name', 'price', 'owner_name', 'num_of_days','tours_postcode', 'tours_price', 'ending_city', 'tours_location'], 'data/frontImages/tours/tours_image', 2);		
});


function stripslashes(str)
{
	str=str.replace(/\\'/g,'\'');
	str=str.replace(/\\"/g,'"');
	str=str.replace(/\\0/g,'\0');
	str=str.replace(/\\\\/g,'\\');
	return str;
}




$(document).ready(function() {	



	function openMsgDialog(msg)
	{
		$('#dialog_container').html(msg).dialog({
					autoOpen: true,
					modal: false,
					show: 'explode',
					resizable: true,	
					buttons: [{ text: "<?php echo html_entity_decode($this->translator->translator('common_ok'), ENT_QUOTES, 'UTF-8'); ?>", click: function() { $(this).dialog('option', 'hide', 'explode').dialog("close"); } } ],
					open: function(event, ui)
						 {
							setTimeout(function() 
							{
								if($('#' + event.target.id).dialog('isOpen'))
								{
									$('#' + event.target.id).dialog('option', 'hide', 'explode').dialog('close');	
								}
							}, 10000);
						  }
				});
	}



	



	$('a.save_tours_btn').click(function() {



		var self = this;



		var id = $(self).attr('rel');



		$.ajax({



			  url: "<?php echo $this->url( array('module' =>'Tours','controller' => 'frontend', 'action'     => 'save' ), 'adminrout',    true) ?>",



			  type: 'POST',



			  data: { id: id },



			  beforeSend: function(){						



						$(self).html('<img src="application/layouts/scripts/<?php echo $front_template['theme_folder']; ?>/images/loader/mod-loader.gif" border="0" height="12" />');	



					 },



			  success: function(response){



				//alert(response);



				var json_arr = eval("("+response+")");							



				if(json_arr.status == 'ok')



				{



					openMsgDialog(json_arr.msg);



				}



				else



				{



					openMsgDialog(json_arr.msg);



				}



				$(self).html('<?php echo $this->translator->translator("tours_front_page_save_tours"); ?>');



			  }



		});



	});



	



	$('#country_id_H').change(function() {	

			if($('#country_id_H option:selected').val() == 'any' || $('#country_id_H option:selected').val() =='')

			{

				$('#area_id_H').html('<option value="any"><?php echo $this->translator->translator("tours_select_area"); ?></option>');	

				$('#state_id_H').html('<option value="any"><?php echo $this->translator->translator("tours_select_state"); ?></option>');

			}

			else

			{	

				$.ajax({

					  url: "<?php echo $this->url( array('module' =>'Tours','controller' => 'frontend', 'action'     => 'states' ), 'adminrout',    true) ?>",

					  type: 'POST',

					  data: { id: $('#country_id_H option:selected').val() },

					  beforeSend: function(){						

								$('#state_id_H').html('<option value="any"><?php echo $this->translator->translator("common_loading_language"); ?></option>');

								$('#area_id_H').html('<option value="any"><?php echo $this->translator->translator("tours_select_area"); ?></option>');			

								$('#state_id_err').html('<img src="application/layouts/scripts/<?php echo $front_template['theme_folder']; ?>/images/loader/mod-loader.gif" border="0" height="15" />');	

							 },

					  success: function(response){

						//alert(response);

						var json_arr = eval("("+response+")");

						var option = '<option value="any"><?php echo $this->translator->translator("tours_select_state"); ?></option>';				

						if(json_arr.status == 'ok')

						{

							for(var i = 0;i<json_arr.states.length;i++)

							{

								option += '<option value="'+json_arr.states[i].state_id+'" >'+stripslashes(json_arr.states[i].state_name)+'</option>';

							}

							$('#state_id_H').html(option);

						}

						else

						{

							$('#state_id_H').html('<option value="any">'+json_arr.msg+'</option>');

						}

						$('#state_id_err').html('');

					  }

				});

			}

		});

		

		$('#state_id_H').change(function() {		

					

			if($('#state_id_H option:selected').val() == 'any' || $('#state_id_H option:selected').val() == '')

			{

				$('#area_id_H').html('<option value="any"><?php echo $this->translator->translator("tours_select_area"); ?></option>');

			}

			else

			{

				$.ajax({

					  url: "<?php echo $this->url( array('module' => 'Tours', 'controller' => 'frontend', 'action'     => 'areas' ), 'adminrout',    true) ?>",

					  type: 'POST',

					  data: { id: $('#state_id_H option:selected').val() },

					  beforeSend: function(){						

							$('#area_id_H').html('<option value="any"><?php echo $this->translator->translator("common_loading_language"); ?></option>');

							$('#area_id_err').html('<img src="application/layouts/scripts/<?php echo $front_template['theme_folder']; ?>/images/loader/mod-loader.gif" border="0" height="15" />');	

							},

					  success: function(response){

						//alert(response);

						var json_arr = eval("("+response+")");

						var option = '<option value="any"><?php echo $this->translator->translator("tours_select_area"); ?></option>';				

						if(json_arr.status == 'ok')

						{

							for(var i = 0;i<json_arr.cities.length;i++)

							{

								option += '<option value="'+json_arr.cities[i].city_id+'" >'+stripslashes(json_arr.cities[i].city)+'</option>';

							}

							$('#area_id_H').html(option);

						}

						else

						{

							$('#area_id_H').html('<option value="any">'+json_arr.msg+'</option>');

						}

						$('#area_id_err').html('');

					  }

				});

			}

		});	



	



	



	



	$('a.print_vr').click(function (event){							



                       var width = 1200;



              		   var height = 700;



                       var left = parseInt((screen.availWidth/2) - (width/2));



                       var top = parseInt((screen.availHeight/2) - (height/2));



                       var windowSizeArray = ["width="+width+",height="+height+",left="+left+",top="+top+"screenX=" + left + ",screenY=" + top + ",scrollbars=yes","width="+width+",height="+height+",scrollbars=yes" ];



                       var url = "<?php echo $this->url(array('module' =>'Tours','controller' =>'frontend', 'action' => 'print','tours_title'=> $this->escape($this->tours_Form->tours_title->getValue())),'Tours-print/:tours_title',true); ?>";



                       var windowName = "popUp";



                       var windowSize = windowSizeArray[$(this).attr("rel")];



                       window.open(url, windowName, windowSize);



                       event.preventDefault();







             	});



	



	



		



});







function raty (id, start_point)



{



	$('#'+id+'_star').raty({



	  path: 'js/jquery/raty/img/',						  



	  hintList:		"<?php echo $this->translator->translator("common_rating_hintList"); ?>",



	  number:     <?php $hint_arr = explode(', ',str_replace('[', '', str_replace(']', '', $this->translator->translator('common_rating_hintList')))); echo count($hint_arr); ?>,



	  start: start_point,



	  readOnly:   true					 



	});



}				





function text_truncate()

{

	$('span.jTruncate').jTruncate({  

		length:  90,  

		minTrail: 0,  

		moreText: "[<?php echo html_entity_decode($this->translator->translator('common_see_all'), ENT_QUOTES, "UTF-8"); ?>]",  

		lessText: "[<?php echo html_entity_decode($this->translator->translator('common_hide'), ENT_QUOTES, "UTF-8"); ?>]",  

		ellipsisText: "",  

		moreAni: "fast",  

		lessAni: 2000  

	});

}

</script>

<?php 
$allow_obj = new Tours_View_Helper_Allow();
if (!$allow_obj->allowRule('details',null,null,$this->group_datas['role_id'])) : ?>
	<?php echo $this->translator->translator('Member_Access_deny_desc'); ?>
<?php else : ?>
<?php if($this->view_datas['active'] == '1') : ?>

<div class="mod mod-details">
	<!-- Top Bar Start -->
    <div class="nav-bar">
        <div class="nav-row">
            <div class="nav-col first"> 
            <?php
				if(!empty($prevTours))
				{
			?>
            <span class="prev"><a href="<?php echo 'Tours-details/'.$this->escape($prevTours['tours_title']); ?>"><?php echo $this->translator->translator('tours_front_page_prev_tours'); ?></a></span>
            <?php
				}
				else
				{
			?>
            <span class="no-link"><?php echo $this->translator->translator('tours_front_page_prev_tours'); ?></span>
            <?php
                }
            ?>
            </div>
            <div class="nav-col"><span class="search"><a href="#" class="slick-slidetoggle"><?php echo $this->translator->translator('tours_front_page_new_search'); ?></a></span></div>
            <div class="nav-col">
            <?php
			if ($hasIdentity)
				{
			?>
            <span class="save"><a  href="javascript:void(0);" class="save_tours_btn" rel="<?php echo $this->escape($item_id); ?>"><?php echo $this->translator->translator('tours_front_page_save_tours'); ?></a></span>
            <?php
                }
            ?>
            </div>
            <div class="nav-col last">
            <?php
				if(!empty($nextTours))
				{
			?>
            <span class="next"><a href="<?php echo 'Tours-details/'.$this->escape($nextTours['tours_title']); ?>"><?php echo $this->translator->translator('tours_front_page_next_tours'); ?></a></span>
            <?php
                }
                else
                {
            ?>
            <span class="no-link"><?php echo $this->translator->translator('tours_front_page_next_tours'); ?></span>
            <?php
                }
            ?>
            </div>
        </div>
    </div>
    <!-- Top Bar End -->
  
  	<!-- Tour Slick Search Start -->
   	<div id="slickbox" class="mod-container mod-advance-search">
        <form id="formSearch" name="formSearch" method="post" action="<?php echo $this->url( array('module' => 'Tours', 'controller' => 'search', 'action'     => 'items' ), 'Tours-Search',    true) ?>">
          	<input type="hidden" name="group_id_=" id="group_id" value="<?php echo $this->escape($this->group_datas['id']); ?>" />
          	<input type="hidden" name="active_=" id="active" value="1" />
         	<div class="col clear">
            	<p><?php echo $this->translator->translator('tours_list_page_search_name'); ?></p>
            	<input type="text" name="tours_name_LIKE" id="tours_name" value="" class="mod-field tour-field-big" />
          	</div>
            
          	<div class="col">
            	<p><?php echo $this->translator->translator('tours_list_page_search_category'); ?></p>
            	<?php
					$cat_data = $this->cat_Info->getOptions($this->group_datas['id']);
				?>
            <select name="category_id_=" id="category_id">
              <option value="any"><?php echo $this->translator->translator('common_any_language'); ?></option>
              <?php
                                    foreach($cat_data as $info)
                                    {
                                ?>
              <option value="<?php echo $info['id']; ?>"><?php echo $this->escape($info['category_name']); ?></option>
              <?php
                                    }
                                ?>
            </select>
          </div>
          
          <div class="col">
          	<p><?php echo $this->translator->translator('tours_list_page_search_price'); ?></p>
            <input type="text" name="tours_price_LIKE" id="tours_price" value="" class="small" />
            <?php echo $this->currency->getSymbol(); ?>
          </div>
          
          <div class="col"> 
          	<p><?php echo $this->translator->translator('tours_list_page_search_pro_type'); ?></p>
            <?php
                                    $type_info = $this->business_type_db->getOptions($this->group_datas['id']);
                                ?>
            <select name="tours_type_=" id="tours_type" class="medium">
              <option value="any"><?php echo $this->translator->translator('common_any_language'); ?></option>
              <?php
                                        foreach($type_info as $info)
                                        {
                                    ?>
              <option value="<?php echo $info['id']; ?>"><?php echo $this->escape($info['business_type']); ?></option>
              <?php
                                        }
                                    ?>
            </select>
          </div>
          
          <div class="col">
          	<p><?php echo $this->translator->translator('tours_list_page_search_price_min'); ?></p>
            <?php
                                    $min_price_arr = $this->tours_database->getPrice('ASC');
                                ?>
            <select name="tours_price_>=" id="tours_price" class="small">
              <option value="any"><?php echo $this->translator->translator('common_any_language'); ?></option>
              <?php
                                        foreach($min_price_arr as $key=>$value)
                                        {
                                            if(!empty($value['tours_price']))
                                            {										
                                    ?>
              <option value="<?php echo $this->price($value['tours_price']); ?>"><?php echo $this->price($this->escape($value['tours_price'])).' '.$this->currency->getSymbol(); ?></option>
              <?php
                                            }
                                        }
                                    ?>
            </select>
          </div>
          <div class="col">
          	<p><?php echo $this->translator->translator('tours_list_page_search_price_max'); ?></p>
            <?php
                                        $max_price_arr = $this->tours_database->getPrice('DESC');
                                    ?>
            <select name="tours_price_<=" id="tours_price" class="small">
              <option value="any"><?php echo $this->translator->translator('common_any_language'); ?></option>
              <?php
                                        foreach($max_price_arr as $key=>$value)
                                        {
                                            if(!empty($value['tours_price']))
                                            {
                                    ?>
              <option value="<?php echo $this->price($value['tours_price']); ?>"><?php echo $this->price($this->escape($value['tours_price'])).' '.$this->currency->getSymbol(); ?></option>
              <?php
                                        }
                                    }
                                    ?>
            </select>
          </div>
          <div class="col">
          	<p><?php echo $this->translator->translator('tours_list_page_search_postcode'); ?></p>
            <input type="text" name="post_code_LIKE" id="post_code" class="small"/>
          </div>
          <div class="col clear">
          	<p><?php echo $this->translator->translator('tours_list_page_search_country'); ?></p>
            <?php
                                    $country_db = new Tours_Model_DbTable_Country();
                                    $country_data = $country_db->getCountryInfo();
                                ?>
            <select name="country_id_=" id="country_id_H" class="country_id">
              <option value="any"><?php echo $this->translator->translator('common_any_language'); ?></option>
              <?php
                                        foreach($country_data as $key=>$value)
                                        {
                                    ?>
              <option value="<?php echo $key; ?>"><?php echo $this->escape($value); ?></option>
              <?php
                                        }
                                    ?>
            </select>
          </div>
          <div class="col">
          	<p><?php echo $this->translator->translator('tours_list_page_search_state'); ?></p>
            <select name="state_id_=" id="state_id_H" class="state_id">
              <option value="any"><?php echo $this->translator->translator('tours_select_state'); ?></option>
            </select>
            <span id="state_id_err"></span>
          </div>
          <div class="col">
          	<p><?php echo $this->translator->translator('tours_list_page_search_area'); ?></p>
            <select name="area_id_=" id="area_id_H" class="area_id area">
              <option value="any"><?php echo $this->translator->translator('tours_select_area'); ?></option>
            </select>
            <span id="area_id_err"></span> </div>
           <div class="col clear">
		   	<p><?php echo $this->translator->translator('tours_list_page_search_operator'); ?></p>
            <?php
                                    $mem_data = $this->agent_list->getAllMembers();
                                ?>
            <span class="ui-widget">
            <select name="tours_operator_=" id="tours_operator">
              <option value="any"><?php echo $this->translator->translator('common_any_language'); ?></option>
              <?php
                                        foreach($mem_data as $key=>$value)
                                        {
                                    ?>
              <option value="<?php echo $key; ?>"><?php echo $this->escape($value); ?></option>
              <?php
                                        }
                                    ?>
            </select>
            </span> </div>
          <div class="col">
          	<p><?php echo $this->translator->translator('tours_list_page_search_room'); ?></p>
            <select name="ending_city_>=" id="ending_city">
              <option value="any"><?php echo $this->translator->translator('common_any_language'); ?></option>
              <?php
                                        for($i = 1; $i<=200;$i++)
                                        {
                                    ?>
              <option value="<?php echo $i; ?>"><?php echo $this->escape($i); ?></option>
              <?php
                                        }
                                    ?>
            </select>
          </div>
          <div class="col"> <p><?php echo $this->translator->translator('tours_list_page_search_bathroom'); ?></p>
            <select name="sightseeing_>=" id="sightseeing">
              <option value="any"><?php echo $this->translator->translator('common_any_language'); ?></option>
              <?php
                                        for($i = 1; $i<=200;$i++)
                                        {
                                            $selected = ($this->postValue['sightseeing_>='] == $i) ? ' selected="selected" ' : '';
                                    ?>
              <option value="<?php echo $i; ?>"<?php echo $selected; ?>><?php echo $this->escape($i); ?></option>
              <?php
                                        }
                                    ?>
            </select>
          </div>
          <div class="clear"></div>
          <div class="clear btn-container">
            <input type="submit" name="Submit" value="<?php echo $this->translator->translator('tours_front_page_search_button'); ?>"/>
          </div>
        </form>
   	</div>
  	<!-- Tour Slick Search End -->
  	
    <div class="clear">&nbsp;</div>
  	<h1><?php echo $this->escape($this->tours_Form->tours_name->getValue()); ?></h1>
  	<div class="products-type"><?php echo strtoupper($this->escape($this->businessTypeInfo['business_type'])); ?></div>
    
    <div class="clear">&nbsp;</div>
    
  	<!-- Tour Info Start -->
  	<div class="products-info">
        <div class="products-stars">
          	<?php               
			  $hotel_rating = (int) $this->escape($this->view_datas['rating']);
	
			  for($i = 1; $i < $maximum_rating_digit ; $i++)
			  {
	
				 $print_rating = ($i <= $hotel_rating )  ? "<img src='application/layouts/scripts/".$front_template['theme_folder']."/images/mod_tour_img/star-active.png' border='0' />" : "<img src='application/layouts/scripts/".$front_template['theme_folder']."/images/mod_tour_img/star-inactive.png' border='0' />";
				 echo $print_rating.'&nbsp;';
			  }
			?>
        </div>
    	<div class="products-desc">
			<span class="mod-title"><?php echo $this->tours_Form->tours_code->getAttrib('font_end_label'); ?></span>&nbsp;<?php echo $this->escape($this->tours_Form->tours_code->getValue()); ?><br /><span class="mod-title"><?php echo $this->tours_Form->duration->getAttrib('font_end_label'); ?></span>&nbsp;<?php echo $this->escape($this->tours_Form->duration->getValue()); ?>&nbsp;<br />
      		<span class="mod-title"><?php echo $this->tours_Form->starting_city->getAttrib('font_end_label'); ?></span>&nbsp;<?php echo $this->escape($this->tours_Form->starting_city->getValue()); ?><br /><span class="mod-title"><?php echo $this->tours_Form->ending_city->getAttrib('font_end_label'); ?></span>&nbsp;<?php echo $this->escape( $this->tours_Form->ending_city->getValue()); ?>
		</div>
        <div class="clear">&nbsp;</div>
        
        <ul class="products-options">
          	<?php 
				if (in_array ('Complimentary Breakfast' , $feature_facilities_arr)){
			?>
          	<li class="breakfast"><?php echo $this->translator->translator('tours_front_page_list_allow_breakfast'); ?></li>
          	<?php }?>
          	<?php
			  if (in_array ('Cab Facilities' , $feature_facilities_arr)){
			?>
          	<li class="cab"><?php echo $this->translator->translator('tours_front_page_list_cab_availability'); ?></li>
          	<?php 
				}
				if (in_array ('Guides / Assistance' , $feature_facilities_arr)){
			?>
          	<li class="guide"><?php echo $this->translator->translator('tours_front_page_list_assist_allow'); ?></li>
          	<?php 
				}
				if (in_array ('Snacks / Drinks' , $feature_facilities_arr)){
			?>
          	<li class="snacks"><?php echo $this->translator->translator('tours_front_page_list_hot_snacks_availability'); ?></li>
          	<?php 
				}	  
			?>
        </ul>
  	</div>
    
  	<div class="products-info right">
    	<div class="products-price"><?php echo $this->translator->translator('tours_front_page_label_price'); ?><?php echo $this->currency->getSymbol().'&nbsp;'.$this->price($this->escape($this->tours_Form->tours_price->getValue())); ?></div>
    	<div class="products-review">
        	<span class="products-write-review"><?php if(!empty($this->group_datas['review_id'])){ $review_no = (!empty($this->review_datas)) ? htmlentities($this->review_datas['review_no']) : htmlentities('0'); ?><a href="<?php echo $this->url( array('module' => 'Review','controller' => 'frontend', 'action'     => 'write', 'group_id' => $this->escape($this->group_datas['review_id']), Eicra_File_Constants::ITEM_ID => $this->view_datas['id'] ), 'Review-Write/:group_id/:item_id',    true); ?>"><?php echo $this->translator->translator('common_write_review'); ?></a></span> &nbsp; <span class="products-review-count"><a href="javascript:void(0);" class="review_btn" rel="#tabs-8"><?php echo $this->translator->translator('common_review_no',$review_no); ?></a></span><?php } ?>
    	</div>
    	
        <div class="products-vote"> 
        	<p><?php echo $this->translator->translator('tours_front_page_label_voting'); ?></p>
            <span><?php  $vote->showButton($this->view_datas['id'] , $this->escape($this->view_datas['tours_name'])); ?></span>
		</div>
    	<?php
			if($global_conf['payment_system'] == 'On'){
		?>
    	<div class="clear"><span class="form-button"><a href="<?php echo $this->url(array('module' => 'Tours','controller' =>'book', 'action' => 'booking','tours_title' => $this->escape($this->view_datas['tours_title']) ),'Book-Tours/:tours_title',true); ?>"><?php echo $this->translator->translator('tours_front_page_book_btn'); ?></a></span></div>
    	<?php } ?>
  	</div>
  	<!-- Tour Info End --> 
  
  	<!-- Tour Details Middle Tab Start -->
  	<div class="products-middle-tab">
    	<ul>
      		<li><a class="print_vr" href="javascript:void(0)" rel="0"><?php echo $this->translator->translator('common_print'); ?></a></li>
          	<li><a href="<?php echo $this->url(array('module' => 'Tours','controller' =>'emails', 'action' => 'friend','tours_title' => $this->escape($this->tours_Form->tours_title->getValue()), 'form_id' => $this->translator->translator('email_to_friend_form_id') ),'Tours-Email-To-Friend/:tours_title/:form_id',true); ?>"><?php echo $this->translator->translator('common_email_to_friend'); ?></a></li>
          	<li><a href="<?php echo $this->url(array('module' => 'Tours','controller' =>'emails', 'action' => 'appointment','tours_title' => $this->escape($this->tours_Form->tours_title->getValue()), 'form_id' => $this->translator->translator('appointment_form_id') ),'Tours-Appointment/:tours_title/:form_id',true); ?>"><?php echo $this->translator->translator('common_appointment'); ?></a></li>
          	<li><a href="<?php echo $this->url(array('module' => 'Tours','controller' =>'emails', 'action' => 'owner','tours_title' => $this->escape($this->tours_Form->tours_title->getValue()), 'form_id' => $this->translator->translator('contact_operator_form_id') ),'Tours-Contact-Owner/:tours_title/:form_id',true); ?>"><?php echo $this->translator->translator('common_contact'); ?></a></li>
    	</ul>
  	</div>
    
  	<div class="products-middle-tab-area">	
        <!-- Slide Show Start -->
        <div class="products-slideshow">
            <?php
                $tours_image_val_arr = explode(',',$this->tours_Form->tours_image->getValue());
                if($this->escape($this->tours_Form->traveler_photos->getValue()))
                { 
                    $thumb_image = 'data/frontImages/tours/tours_image/'.$this->escape($this->tours_Form->traveler_photos->getValue()); 
                }
                else
                { 
                    if($this->escape($this->tours_Form->tours_image->getValue()))
                    {								
                        $thumb_image = 'data/frontImages/tours/tours_image/'.$this->escape($tours_image_val_arr[0]); 
                    }
                    else
                    {
                        $thumb_image = 'application/layouts/scripts/'.$front_template['theme_folder'].'/images/mod_tour_img/no_image.png'; 
                    }		
                }
                if($this->group_datas['img_big_width'] && ($this->group_datas['img_big_resize_func'] == 'resizeToWidth' || $this->group_datas['img_big_resize_func'] == 'resize' ))
                { 
                    $width = 'width="'.$this->escape($this->group_datas['img_big_width']).'"'; 
                }
                else
                {
                    $width = '';
                } 
                if($this->group_datas['img_big_height'] && ( $this->group_datas['img_big_resize_func'] == 'resizeToHeight' || $this->group_datas['img_big_resize_func'] == 'resize' ))
                { 
                    $height = 'height="'.$this->escape($this->group_datas['img_big_height']).'"'; 
                } 
                else
                {
                    $height = '';
                }
            ?>
              <div id="container">
                <div id="gallery" class="ad-gallery">
                  <div class="ad-image-wrapper"></div>
                  <div class="ad-controls"></div>
                  <div class="ad-nav">
                    <div class="ad-thumbs">
                      <ul class="ad-thumb-list" style="min-width:100%;">
                        <li> <a href="<?php echo $thumb_image; ?>"> <img src="<?php echo $thumb_image; ?>"  width="70" height="50" title="<?php echo $this->escape($this->tours_Form->tours_name->getValue()); ?>" alt="<?php echo $this->escape($area_info['city']).', '.$this->escape($country_info['value']); ?>"  class="image0"> </a> </li>
                        <?php	
                                                    foreach($tours_image_val_arr as $key=>$value)
                                                    {			
                                                        if('data/frontImages/tours/tours_image/'.$value != $thumb_image)
                                                        {
                                                 ?>
                        <li> <a href="data/frontImages/tours/tours_image/<?php echo $value; ?>"> <img src="data/frontImages/tours/tours_image/<?php echo $value; ?>"  width="70" height="50" title="<?php echo $this->escape($this->tours_Form->tours_name->getValue()); ?>" alt="<?php echo $this->escape($area_info['city']).', '.$this->escape($country_info['value']); ?>"  class="image0"> </a> </li>
                        <?php
                                                        }		
                                                    }
                                                    ?>
                      </ul>
                    </div>
                  </div>
                </div>
                <div class="switch">
                  <select id="switch-effect">
                    <option value="slide-hori">Slide horizontal</option>
                    <option value="slide-vert">Slide vertical</option>
                    <option value="resize">Shrink/grow</option>
                    <option value="fade">Fade</option>
                    <option value="">None</option>
                  </select>
                  <a href="#" id="toggle-slideshow">Toggle slideshow</a> | <a href="#" id="toggle-description">Toggle description outside image</a> </div>
              </div>
        </div>
        <!-- Slide Show End --> 
        
        <!-- Tour Match Start -->
        <div class="match-container">
            <div id="matchTabs">
                <ul>
                    <li><a href="<?php echo $tab_base_link; ?>#matchTabs-1"><?php echo $this->translator->translator('tours_front_page_match_related'); ?></a></li>
                    <li><a href="<?php echo $tab_base_link; ?>#matchTabs-2"><?php echo $this->translator->translator('tours_front_page_match_price'); ?></a></li>
                    <!--<li><a href="#matchTabs-3"><?php //echo $this->translator->translator('tours_front_page_match_region'); ?></a></li>-->
                    <li><a href="<?php echo $tab_base_link; ?>#matchTabs-4"><?php echo $this->translator->translator('tours_front_page_match_agent'); ?></a></li>
                </ul>
                <div class="match-tab-container" id="matchTabs-1">
                    <?php							
                        if(!empty($this->view_datas['related_items']))		
                        {									 			
                            $related_items_arr = explode(',',$this->view_datas['related_items']);
                            foreach($related_items_arr as $key=>$value)
                            {
                                $related_matched = $this->tours_database->getToursInfo($value);
                    ?>
                    <div class="products-match">
                        <span><a href="<?php echo $this->url(array('module' => 'Tours','controller' =>'frontend', 'action' => 'details','tours_title' => $this->escape($related_matched['tours_title']) ),'Tours-details/:tours_title',true); ?>" title="<?php echo $this->escape($related_matched['tours_name']); ?>"><?php echo $this->escape($related_matched['tours_name']); ?></a></span>
                        <div class="products-star">
                          <?php
                              $hotel_rating = (int) $this->escape($related_matched['rating']);
                              for($i = 1; $i < $maximum_rating_digit ; $i++)
                              {
                                  $print_rating = ($i <= $hotel_rating )  ? "<img src='application/layouts/scripts/".$front_template['theme_folder']."/images/mod_tour_img/star-small-active.png' border='0' />" : "<img src='application/layouts/scripts/".$front_template['theme_folder']."/images/mod_tour_img/star-small-inactive.png' border='0' />";
                                  echo $print_rating.'&nbsp;';
                              }
                          ?>
                        </div>
                        <?php
                            if(!empty($this->group_datas['review_id']))
                            { 
                                $review_match_no = htmlentities($this->review_helper->getNumOfReviews($related_matched['id'], $this->group_datas['review_id']));
                        ?>
                            <div class="products-review">
                                <div class="products-review-count"><a href="<?php echo $this->url(array('module' => 'Tours','controller' =>'frontend', 'action' => 'details','tours_title' => $this->escape($related_matched['tours_title']),'tab' => 7 ),'Tours-details/:tours_title/:tab',true); ?>"><?php echo $this->translator->translator('common_review_no',$review_match_no); ?></a>&nbsp;</div>
                                <div class="products-write-review"><a href="<?php echo $this->url( array('module' => 'Review','controller' => 'frontend', 'action'     => 'write', 'group_id' => $this->escape($this->group_datas['review_id']), Eicra_File_Constants::ITEM_ID => $related_matched['id'] ), 'Review-Write/:group_id/:item_id',    true); ?>"><?php echo $this->translator->translator('common_write_review'); ?></a></div>
                            </div>
                        <?php
                            }
                        ?>
                                                            
                        <div class="thumb">
                            <a href="<?php echo $this->url(array('module' => 'Tours','controller' =>'frontend', 'action' => 'details','tours_title' => $this->escape($related_matched['tours_title']) ),'Tours-details/:tours_title',true); ?>" class="preview" link="data/frontImages/tours/tours_image/<?php echo $related_matched['traveler_photos'] ; ?>" title="<?php echo $this->escape($related_matched['tours_name']); ?>" width="300"><img src="data/frontImages/tours/tours_image/<?php echo $related_matched['traveler_photos'] ; ?>"  width="70" height="50" border="0" alt="<?php echo strip_tags($this->escape($related_matched['traveler_photos'])); ?>" ></a>
                        </div>
                        <div class="products-desc"> 
                            <?php echo $this->tours_Form->tours_price->getAttrib('font_end_label') . $multi_space . $this->price($this->escape($related_matched['tours_price'])) ;?><br />
                            <?php echo $this->tours_Form->scheduled_on->getAttrib('font_end_label') . $multi_space . $this->escape($related_matched['scheduled_on']) ;?><br />
                            <?php echo $this->tours_Form->duration->getAttrib('font_end_label') . $multi_space . $this->escape($related_matched['num_of_days']) . $multi_space . $this->tours_Form->num_of_days->getAttrib('font_end_label')	.$this->escape($related_matched['num_of_nights']) . $multi_space .   $this->tours_Form->num_of_nights->getAttrib('font_end_label');?><br />
                            <?php echo $this->tours_Form->visiting_cities->getAttrib('font_end_label') . $multi_space . $this->escape($related_matched['visiting_cities']) ;?><br />
                        </div>
                    </div>
                    <?php
                            }
                        
                        }
                    ?>
                </div>
                <div class="match-tab-container" id="matchTabs-2">
                <?php
                    $toursMatchPrice = $this->tours_database->getToursMatchPrice($this->escape($item_id),$this->price($this->escape($this->tours_Form->tours_price->getValue())),$display_related_item_limit);
                    if($toursMatchPrice)
                    {
                        foreach($toursMatchPrice as $related_matched)
                        {							
                 ?>
                    <div class="products-match">
                        <span><a href="<?php echo $this->url(array('module' => 'Tours','controller' =>'frontend', 'action' => 'details','tours_title' => $this->escape($related_matched['tours_title']) ),'Tours-details/:tours_title',true); ?>" title="<?php echo $this->escape($related_matched['tours_name']); ?>"><?php echo $this->escape($related_matched['tours_name']); ?></a></span>
                        <div class="products-star">
                          <?php
                              $hotel_rating = (int) $this->escape($related_matched['rating']);
                              for($i = 1; $i < $maximum_rating_digit ; $i++)
                              {
                                  $print_rating = ($i <= $hotel_rating )  ? "<img src='application/layouts/scripts/".$front_template['theme_folder']."/images/mod_tour_img/star-small-active.png' border='0' />" : "<img src='application/layouts/scripts/".$front_template['theme_folder']."/images/mod_tour_img/star-small-inactive.png' border='0' />";
                                  echo $print_rating.'&nbsp;';
                              }
                          ?>
                        </div>
                        
                        <?php
                            if(!empty($this->group_datas['review_id']))
                            { 
                                $review_match_no = htmlentities($this->review_helper->getNumOfReviews($related_matched['id'], $this->group_datas['review_id']));
                        ?>
                        <div class="products-review">
                        	<div class="products-review-count"><a href="<?php echo $this->url(array('module' => 'Tours','controller' =>'frontend', 'action' => 'details','tours_title' => $this->escape($related_matched['tours_title']),'tab' => 7 ),'Tours-details/:tours_title/:tab',true); ?>" ><?php echo $this->translator->translator('common_review_no',$review_match_no); ?></a>&nbsp;</div>
                          	<div class="products-write-review"><a href="<?php echo $this->url( array('module' => 'Review','controller' => 'frontend', 'action'     => 'write', 'group_id' => $this->escape($this->group_datas['review_id']), Eicra_File_Constants::ITEM_ID => $related_matched['id'] ), 'Review-Write/:group_id/:item_id',    true); ?>"><?php echo $this->translator->translator('common_write_review'); ?></a></div>
                        </div>
                        <?php
                            }
                        ?>
                        
                        <div class="thumb"> 
                            <a href="<?php echo $this->url(array('module' => 'Tours','controller' =>'frontend', 'action' => 'details','tours_title' => $this->escape($related_matched['tours_title']) ),'Tours-details/:tours_title',true); ?>" class="preview" link="data/frontImages/tours/tours_image/<?php echo $related_matched['traveler_photos'] ; ?>" title="<?php echo $this->escape($related_matched['tours_name']); ?>" width="300"><img src="data/frontImages/tours/tours_image/<?php echo $related_matched['traveler_photos'] ; ?>"  width="70" height="50" border="0"  alt="<?php echo strip_tags($this->escape($related_matched['traveler_photos'])); ?>"></a>
                        </div>
                        <div class="products-desc"> 
                            <?php echo $this->tours_Form->tours_price->getAttrib('font_end_label') . $multi_space . $this->price($this->escape($related_matched['tours_price'])) ;?><br />
                            <?php echo $this->tours_Form->scheduled_on->getAttrib('font_end_label') . $multi_space . $this->escape($related_matched['scheduled_on']) ;?><br />
                            <?php echo $this->tours_Form->duration->getAttrib('font_end_label') . $multi_space . $this->escape($related_matched['num_of_days']) . $multi_space .    $this->tours_Form->num_of_days->getAttrib('font_end_label')	. $this->escape($related_matched['num_of_nights']) . $multi_space .  $this->tours_Form->num_of_nights->getAttrib('font_end_label');?><br />
                            <?php echo $this->tours_Form->visiting_cities->getAttrib('font_end_label') . $multi_space . $this->escape($related_matched['visiting_cities']) ;?><br />
                        </div>
              		</div>
              	 <?php	
                       }
                 
                  }
              	  ?>
            	</div>
                <!--<div class="match-tab-container" id="matchTabs-3">
                  <?php
                        /*$toursMatchRegion = $this->tours_database->getToursMatchRegion($this->escape($item_id), $this->escape( $state_id) , $this->escape( $area_id) ,$maximum_rating_digit);
                        if($toursMatchRegion)
                        {
                            foreach($toursMatchRegion as $related_matched)
                            { 
                    ?>
                  <div class="products-match">
                    <span><a href="<?php echo $this->url(array('module' => 'Tours','controller' =>'frontend', 'action' => 'details','tours_title' => $this->escape($related_matched['tours_title']) ),'Tours-details/:tours_title',true); ?>"><?php echo $this->escape($related_matched['tours_name']); ?></a></span>
                      <div class="products-star">
                          <?php
                              $hotel_rating = (int) $this->escape($related_matched['rating']);
                              for($i = 1; $i < $maximum_rating_digit ; $i++)
                              {
                                  $print_rating = ($i <= $hotel_rating )  ? "<img src='application/layouts/scripts/".$front_template['theme_folder']."/images/mod_tour_img/star-small-active.png' border='0' />" : "<img src='application/layouts/scripts/".$front_template['theme_folder']."/images/mod_tour_img/star-small-inactive.png' border='0' />";
                                  echo $print_rating.'&nbsp;';
                              }
                          ?>
                      </div>
                      
                      <?php
                            if(!empty($this->group_datas['review_id']))
                            { 
                                $review_match_no = htmlentities($this->review_helper->getNumOfReviews($related_matched['id'], $this->group_datas['review_id']));
                      ?>
                      <div class="products-review">	
                        <div class="products-review-count"><a href="<?php echo $this->url(array('module' => 'Tours','controller' =>'frontend', 'action' => 'details','tours_title' => $this->escape($related_matched['tours_title']),'tab' => 7 ),'Tours-details/:tours_title/:tab',true); ?>"><?php echo $this->translator->translator('common_review_no',$review_match_no); ?></a>&nbsp;</div>
                        <div class="products-write-review"><a href="<?php echo $this->url( array('module' => 'Review','controller' => 'frontend', 'action'     => 'write', 'group_id' => $this->escape($this->group_datas['review_id']), Eicra_File_Constants::ITEM_ID => $related_matched['id'] ), 'Review-Write/:group_id/:item_id',    true); ?>"><?php echo $this->translator->translator('common_write_review'); ?></a></div>
                      </div>
                      <?php
                        }
                      ?>
                      <div class="thumb"> 
                        <a href="<?php echo $this->url(array('module' => 'Tours','controller' =>'frontend', 'action' => 'details','tours_title' => $this->escape($related_matched['tours_title']) ),'Tours-details/:tours_title',true); ?>" class="preview" link="data/frontImages/tours/tours_image/<?php echo $related_matched['traveler_photos'] ; ?>" title="<?php echo $this->escape($related_matched['tours_name']); ?>" width="300"><img src="data/frontImages/tours/tours_image/<?php echo $related_matched['traveler_photos'] ; ?>"  width="70" height="50" border="0" title="<?php echo $this->escape($related_matched['traveler_photos']); ?>" alt="<?php echo strip_tags($this->escape($related_matched['traveler_photos'])); ?>"></a>
                      </div>
                      <div class="products-desc"> 
                        <?php echo $this->tours_Form->tours_price->getAttrib('font_end_label') . $multi_space . $this->price($this->escape($related_matched['tours_price'])) ;?><br />
                        <?php echo $this->tours_Form->scheduled_on->getAttrib('font_end_label') . $multi_space . $this->escape($related_matched['scheduled_on']) ;?><br />
                        <?php echo $this->tours_Form->duration->getAttrib('font_end_label') . $multi_space . $this->escape($related_matched['num_of_days']) . $multi_space . $this->tours_Form->num_of_days->getAttrib('font_end_label')	. $this->escape($related_matched['num_of_nights']) . $multi_space .  $this->tours_Form->num_of_nights->getAttrib('font_end_label') ;?><br />
                        <?php echo $this->tours_Form->visiting_cities->getAttrib('font_end_label') . $multi_space . $this->escape($related_matched['visiting_cities']) ;?><br />
                      </div>
                    </div> 
                    <?php				
                            }
                            
                        }*/
                    ?>
                  </div>-->
                  <div class="match-tab-container" id="matchTabs-4">
                    <?php
                        $toursMatchAgent = $this->tours_database->getToursMatchAgent($this->escape($item_id),$this->escape($this->view_datas['tours_operator']),10);
                        if($toursMatchAgent){
                            foreach($toursMatchAgent as $related_matched)
                            {
                    ?>
                    <div class="products-match">
                        <span><a href="<?php echo $this->url(array('module' => 'Tours','controller' =>'frontend', 'action' => 'details','tours_title' => $this->escape($related_matched['tours_title']) ),'Tours-details/:tours_title',true); ?>" title="<?php echo $this->escape($related_matched['tours_name']); ?>"><?php echo $this->escape($related_matched['tours_name']); ?></a></span>
                        <div class="products-star">
                        <?php
                          $hotel_rating = (int) $this->escape($related_matched['rating']);
                          for($i = 1; $i < $maximum_rating_digit ; $i++)
                          {
                              $print_rating = ($i <= $hotel_rating )  ? "<img src='application/layouts/scripts/".$front_template['theme_folder']."/images/mod_tour_img/star-small-active.png' border='0' />" : "<img src='application/layouts/scripts/".$front_template['theme_folder']."/images/mod_tour_img/star-small-inactive.png' border='0' />";
                              echo $print_rating.'&nbsp;';
                          }
                        ?>
                      </div>
                      
                      <?php
                        if(!empty($this->group_datas['review_id']))
                            { 											
                        $review_match_no = htmlentities($this->review_helper->getNumOfReviews($related_matched['id'], $this->group_datas['review_id']));
                        ?>
                          <div class="products-review">
                                <div class="products-review-count"><a href="<?php echo $this->url(array('module' => 'Tours','controller' =>'frontend', 'action' => 'details','tours_title' => $this->escape($related_matched['tours_title']),'tab' => 7 ),'Tours-details/:tours_title/:tab',true); ?>"><?php echo $this->translator->translator('common_review_no',$review_match_no); ?></a>&nbsp;</div>
                                <div class="products-write-review"><a href="<?php echo $this->url( array('module' => 'Review','controller' => 'frontend', 'action'     => 'write', 'group_id' => $this->escape($this->group_datas['review_id']), Eicra_File_Constants::ITEM_ID => $related_matched['id'] ), 'Review-Write/:group_id/:item_id',    true); ?>"><?php echo $this->translator->translator('common_write_review'); ?></a></div>
                          </div>
                        <?php
                            }
                        ?>
                                                        
                        <div class="thumb"> 
                            <a href="<?php echo $this->url(array('module' => 'Tours','controller' =>'frontend', 'action' => 'details','tours_title' => $this->escape($related_matched['tours_title']) ),'Tours-details/:tours_title',true); ?>" class="preview" link="data/frontImages/tours/tours_image/<?php echo $related_matched['traveler_photos'] ; ?>" title="<?php echo $this->escape($related_matched['tours_name']); ?>" width="300"><img src="data/frontImages/tours/tours_image/<?php echo $related_matched['traveler_photos'] ; ?>" alt="<?php echo strip_tags($this->escape($related_matched['traveler_photos'])); ?>"  width="70" height="50" border="0" ></a>
                       </div>
                       <div class="products-desc">
                            <?php echo $this->tours_Form->tours_price->getAttrib('font_end_label') . $multi_space . $this->price($this->escape($related_matched['tours_price'])) ;?><br />
                            <?php echo $this->tours_Form->scheduled_on->getAttrib('font_end_label') . $multi_space . $this->escape($related_matched['scheduled_on']) ;?><br />
                            <?php echo $this->tours_Form->duration->getAttrib('font_end_label') . $multi_space . $this->escape($related_matched['num_of_days']) . $multi_space .    $this->tours_Form->num_of_days->getAttrib('font_end_label')	. $this->escape($related_matched['num_of_nights']) . $multi_space .   $this->tours_Form->num_of_nights->getAttrib('font_end_label');?><br />
                            <?php echo $this->tours_Form->visiting_cities->getAttrib('font_end_label') . $multi_space . $this->escape($related_matched['visiting_cities']) ;?><br />
                       </div>
                    </div>
                    <?php						
                            }
                            
                        }
                    ?>
                  </div>
            </div>
        </div>
   		<!-- Tour Match End --> 
	</div> 
    <!-- Tour Details Middle Tab End --> 
    
    <!-- Tour Bottom Tab Start -->
    <div id="tabs">
          <ul>
                <li><a href="<?php echo $tab_base_link; ?>#tabs-1"><?php echo $this->translator->translator('tours_front_page_tours_details'); ?></a></li>
                <li><a href="<?php echo $tab_base_link; ?>#tabs-2"><?php echo $this->translator->translator('tours_front_page_tours_gallery'); ?> <span class="photo-no">
                    <?php if($this->tours_Form->tours_image->getValue()){ $photos_arr = explode(',', $this->tours_Form->tours_image->getValue() ); echo count($photos_arr); } else { echo '0'; } ?></span></a>
                </li>
                <li><a href="<?php echo $tab_base_link; ?>#tabs-3"><?php echo $this->translator->translator('tours_front_page_Other_exclusive_images'); ?> <span class="photo-no">
                    <?php if($this->tours_Form->spots_photo_gallery->getValue()){ $photos_other_arr = explode(',', $this->tours_Form->spots_photo_gallery->getValue() ); echo count($photos_other_arr); } else { echo '0'; } ?></span></a>
                </li>
                <li><a href="<?php echo $tab_base_link; ?>#tabs-4"><?php echo $this->translator->translator('tours_front_page_Title_payment_amenities'); ?></a></li>
                <li><a href="<?php echo $tab_base_link; ?>#tabs-5"><?php echo $this->translator->translator('tours_front_page_details_itinerary'); ?></a></li>
                <li><a href="<?php echo $tab_base_link; ?>#tabs-6"><?php echo $this->translator->translator('tours_front_page_Title_payment_process'); ?></a></li>
                <li><a href="<?php echo $tab_base_link; ?>#tabs-7"><?php echo $this->translator->translator('tours_front_page_tours_map'); ?></a></li>
                <?php
                    if(!empty($this->group_datas['review_id']))
                        {
                            echo '<li><a href="'.$tab_base_link.'#tabs-8">'.$this->translator->translator('tours_front_page_tours_review').'</a></li>';
                        }
    
                        if(!empty($this->group_datas['dynamic_form']))
                        {									
                            $staticGroupsObj = $this->tours_Form->getDisplayGroups();
    
                            if($staticGroupsObj)
                            {
                                $tabs = (!empty($this->group_datas['review_id'])) ? 9 : 8;
    
                                foreach($staticGroupsObj as $staticGroup)
                                {
                                    echo '<li><a href="'.$tab_base_link.'#tabs-'.$tabs.'">'.$this->translator->translator($staticGroup->getAttrib('title')).'</a></li>';
                                    $tabs++;
                                }
                            }
                        }
                        else
                        {
                            $staticGroupsObj = null;
                        }
                ?>
        </ul>
      	<div id="tabs-1"> 
        <!-- Tour Left Feature Start -->
        <div class="products-feature">
          	<div class="products-details">
            <div class="products-details-header"><h4 class="icon"><?php echo $this->translator->translator('tours_front_page_Title_detail'); ?></h4></div>
            <div class="content feature-content">
              <?php 
									$_visiting_cities = $this->escape($this->tours_Form->visiting_cities->getValue()); 
									if (!empty($_visiting_cities)) {	
									?>
              <div class="label"><?php echo $this->tours_Form->visiting_cities->getAttrib('font_end_label'); ?></div>
              <div class="value"><?php echo $_visiting_cities  ?></div>
              <?php
									}
									$_scheduled_on = $this->escape($this->tours_Form->scheduled_on->getValue()); 
									if (!empty($_scheduled_on)) {								
									?>
              <div class="label"><?php echo $this->tours_Form->scheduled_on->getAttrib('font_end_label'); ?></div>
              <div class="value"><?php echo $_scheduled_on; ?></div>
              <?php
									}
									$_location_type = $this->escape($this->tours_Form->location_type->getValue()); 
									if (!empty($_location_type)) {								
									?>
              <div class="label"><?php echo $this->tours_Form->location_type->getAttrib('font_end_label');  ?></div>
              <div class="value"><?php echo $_location_type; ?></div>
              <?php
									}
									$_sightseeing = $this->escape($this->tours_Form->sightseeing->getValue()); 
									if (!empty($_sightseeing)) {
									?>
              <div class="label"><?php echo $this->tours_Form->sightseeing->getAttrib('font_end_label');  ?></div>
              <div class="value"><?php echo $_sightseeing; ?></div>
              <?php
									}
									$_accommodates = $this->escape($this->tours_Form->accommodates->getValue());
									if (!empty($_accommodates)) {
									?>
              <div class="label"><?php echo $this->tours_Form->accommodates->getAttrib('font_end_label');  ?></div>
              <div class="value"><?php echo $_accommodates; ?></div>
              <?php
									}
									$_num_of_days = $this->escape($this->tours_Form->num_of_days->getValue());
									if (!empty($_num_of_days)) {								
									?>
              <div class="label"><?php echo $this->tours_Form->num_of_days->getAttrib('font_end_label');  ?></div>
              <div class="value"><?php echo $_num_of_days; ?></div>
              <?php
									}
									$_num_of_nights = $this->escape($this->tours_Form->num_of_nights->getValue());
									if (!empty($_num_of_nights)) {
									?>
              <div class="label"><?php echo  $this->tours_Form->num_of_nights->getAttrib('font_end_label'); ?></div>
              <div class="value"><?php echo  $_num_of_nights ; ?></div>
              <?php
									}
									$_costs_of_children = $this->escape($this->tours_Form->costs_of_children->getValue()); 
		
									if (!empty($_costs_of_children)) {								
									?>
              <div class="label"><?php echo $this->tours_Form->costs_of_children->getAttrib('font_end_label');  ?></div>
              <div class="value"><?php echo $_costs_of_children; ?></div>
              <?php
									}
									$_Pickup_service = $this->escape($this->tours_Form->Pickup_service->getValue()); 
		
									if (!empty($_Pickup_service)) {
									?>
              <div class="label"><?php echo $this->tours_Form->Pickup_service->getAttrib('font_end_label');  ?></div>
              <div class="value"><?php echo $_Pickup_service; ?></div>
              <?php
									}
									$_supplementary_room = $this->escape($this->tours_Form->supplementary_room->getValue());
									if (!empty($_supplementary_room)) {
									?>
              <div class="label"><?php echo $this->tours_Form->supplementary_room->getAttrib('font_end_label');  ?></div>
              <div class="value"><?php echo $_supplementary_room; ?></div>
              <?php
									}
									$_drop_off_service = $this->escape($this->tours_Form->drop_off_service->getValue());
									if (!empty($_drop_off_service)) {
									?>
              <div class="label"><?php echo $this->tours_Form->drop_off_service->getAttrib('font_end_label');  ?></div>
              <div class="value"><?php echo $_drop_off_service; ?></div>
              <?php
									}
									$_entertainments = $this->escape($this->tours_Form->entertainments->getValue()); 
									if (!empty($_entertainments)) {
									?>
              <div class="label"><?php echo $this->tours_Form->entertainments->getAttrib('font_end_label');  ?></div>
              <div class="value"><?php echo $_entertainments; ?></div>
              <?php
									}
									$_multilingual_guide = $this->escape($this->tours_Form->multilingual_guide->getValue()); 
									if (!empty($_multilingual_guide)) {
									?>
              <div class="label"><?php echo $this->tours_Form->multilingual_guide->getAttrib('font_end_label');  ?></div>
              <div class="value"><?php echo $_multilingual_guide; ?></div>
              <?php
									}
									$_tour_highlights = $this->escape($this->tours_Form->tour_highlights->getValue()); 
									if (!empty($_tour_highlights)) {
									?>
              <div class="label"><?php echo $this->tours_Form->tour_highlights->getAttrib('font_end_label');  ?></div>
              <div class="value"><span class="jTruncate">
                <?php  echo strip_tags ($_tour_highlights); ?>
                </span>
              </div>
              <?php 
										}
									?>
            </div>
          </div>
        </div>
        
        <!-- Tour Left Feature End --> 
        
        <!-- Tour Summary Start -->
        <div class="products-feature summary">
          <div class="products-details">
            <div class="products-details-header"><h4 class="icon"><?php echo $this->translator->translator('tours_front_page_Title_summary'); ?></h4></div>
            <div class="content feature-content">
              <div class="summary-label"><?php echo $this->tours_Form->tours_code->getAttrib('font_end_label') ;  ?></div>
              <div class="summary-value"><?php echo $this->tours_Form->tours_code->getValue()?></div>
              <div class="summary-label"><?php echo $this->tours_Form->duration->getAttrib('font_end_label');  ?></div>
              <div class="summary-value"><?php echo $this->escape($this->tours_Form->duration->getValue()); ?></div>
              <div class="summary-label"><?php echo $this->tours_Form->starting_city->getAttrib('font_end_label') ?></div>
              <div class="summary-value"><?php echo $this->escape($this->tours_Form->starting_city->getValue() ); ?></div>
              <div class="summary-label"><?php echo $this->tours_Form->ending_city->getAttrib('font_end_label') ; ?></div>
              <div class="summary-value"><?php echo $this->escape( $this->tours_Form->ending_city->getValue() ); ?></div>
              <div class="summary-label"><?php echo $this->tours_Form->country_id->getAttrib('font_end_label');  ?></div>
              <div class="summary-value"><?php echo $this->escape($country_info['value']); ?></div>
              <div class="summary-label"><?php echo $this->tours_Form->state_id->getAttrib('font_end_label');  ?></div>
              <div class="summary-value"><?php echo $this->escape( $state_info['state_name']); ?></div>
              <div class="summary-label"><?php echo $this->tours_Form->num_of_days->getAttrib('font_end_label');  ?></div>
              <div class="summary-value"><?php echo $this->escape($this->tours_Form->num_of_days->getValue()); ?></div>
              <div class="summary-label"><?php echo $this->tours_Form->num_of_nights->getAttrib('font_end_label'); ?></div>
              <div class="summary-value"><?php echo $this->escape($this->tours_Form->num_of_nights->getValue()); ?></div>
            </div>
          </div>
        </div>
        <!-- Tour Summary End --> 
        
        <!-- Tour Agent Start-->
        <?php
							//Checking Membership Package Option
							$packages = new Members_Controller_Helper_Packages();
							$general_db = new Members_Model_DbTable_General();
							$forms_db = new Members_Model_DbTable_Forms();
							$mem_info = (isnot_int($this->view_datas['tours_operator'])) ? $this->agent_list->getMemberInfo($this->view_datas['entry_by']) : $this->agent_list->getMemberInfo($this->view_datas['tours_operator']);	
							$module = $this->module;
							$controller = $this->controller;
							$action = $this->action;
							if($packages->checkFormAvailable('Default Info'))
							{
								$default_form_id  = $forms_db->getFormId('Default Info');
								$default_form_info['form_id'] = 	$default_form_id[0]['id'];
								$default_general_info = $general_db->getAllValues($default_form_id[0]['id']);												
								$dynamic_valu_db = new Members_Model_DbTable_FieldsValue();	
								if($default_general_info)
								{								
									$default_general_info = (!empty($default_general_info[0]) && !empty($default_general_info[0]['id'])) ? $default_general_info :  $default_general_info->toArray();
									$default_form_info	=	$dynamic_valu_db->getFieldsValueInfo($default_form_info,$default_general_info[0]['id']);									
								}
								else
								{
									$default_form_info = null;
								}
		
							}
							else
							{
								$default_form_info = null;
							}
		
							if($packages->isPackageFrontend($mem_info['user_id'],$mem_info['role_id']))
							{								
								if($packages->isPackageFrontendField($module,$controller,$action,$mem_info['user_id'],$mem_info['role_id']))
								{
									$package_no = $packages->getPackageFrontendFieldValue($module,$controller,$action,$mem_info['user_id'],$mem_info['role_id']);
								}
								else
								{
									$package_no = 'Off';
								}
							}
		
							else
							{
								$package_no = 'On';
							}
		
							if($package_no == 'On')
							{		
						?>
        <div class="products-agent">
          <div class="products-details">
            <div class="products-details-header"><h4 class="icon"><?php echo $this->translator->translator('tours_front_page_Title_realtor'); ?></h4></div>
            <div class="content">
              <?php
					if($this->escape($this->view_datas['tours_operator']))
					{
						$this->agent_list = new Members_Model_DbTable_MemberList();
						$owner_info = (isnot_int($this->view_datas['tours_operator'])) ? $this->escape($this->view_datas['tours_operator']) : $this->agent_list->getMemberInfo($this->escape($this->view_datas['tours_operator']));
						$owner_name = (is_array($owner_info)) ? $owner_info['title'].' '.$owner_info['firstName'].' '.$owner_info['lastName'] : $owner_info;	
						//echo $this->escape($owner_name);
						$mem_user_id = (is_array($owner_info)) ? $owner_info['user_id'] : $mem_info['user_id'];
						$mem_role_id = (is_array($owner_info)) ? $owner_info['role_id'] : $mem_info['role_id'];
						if(is_array($owner_info))
						{
							$role_db = new Members_Model_DbTable_Role();
							$role_info = $role_db->getRoleInfo($owner_info['role_id']);
							$owner_info['form_id'] = 	$role_info['form_id'];
							$dynamic_valu_db = new Members_Model_DbTable_FieldsValue();	
							$owner_info	=	$dynamic_valu_db->getFieldsValueInfo($owner_info,$owner_info['user_id']);
							foreach($owner_info as $key=>$value)
							{
								$field_name_arr = explode('_',$key);
								if(in_array('package',$field_name_arr))
								{
									$package_info = $packages->getFormAllDatas($value);
								}
							}
						}
						else
						{
							$mem_user_id = $mem_info['user_id'];
							$mem_role_id = $mem_info['role_id'];
							$role_db = new Members_Model_DbTable_Role();
							$role_info = $role_db->getRoleInfo($mem_role_id);
							$mem_info['form_id'] = 	$role_info['form_id'];
							$dynamic_valu_db = new Members_Model_DbTable_FieldsValue();	
							$mem_info	=	$dynamic_valu_db->getFieldsValueInfo($mem_info,$mem_user_id);
							foreach($mem_info as $key=>$value)
							{
								$field_name_arr = explode('_',$key);
								if(in_array('package',$field_name_arr))
								{
									$package_info = $packages->getFormAllDatas($value);
								}
							}
						}
					}
					else
					{
						$mem_user_id = $mem_info['user_id'];
						$mem_role_id = $mem_info['role_id'];
						$role_db = new Members_Model_DbTable_Role();
						$role_info = $role_db->getRoleInfo($mem_role_id);
						$mem_info['form_id'] = 	$role_info['form_id'];
						$dynamic_valu_db = new Members_Model_DbTable_FieldsValue();	
						$mem_info	=	$dynamic_valu_db->getFieldsValueInfo($mem_info,$mem_user_id);
						foreach($mem_info as $key=>$value)
						{
							$field_name_arr = explode('_',$key);
							if(in_array('package',$field_name_arr))
							{
								$package_info = $packages->getFormAllDatas($value);
							}
						}
					}
					?>
              <?php
				if(is_array($owner_info))
				{
					if($owner_info['member_photo'])
					{
						$owner_forms_info = $forms_db->getFormsInfo($role_info['form_id']);
						$member_photo_path = $owner_forms_info['attach_file_path'];
						$member_photo = $member_photo_path.'/'.$owner_info['member_photo'];
						$member_photo_width = 'width="'.$default_form_info['member_photo_width_default'].'"';
						$member_photo_height = 'height="'.$default_form_info['member_photo_height_default'].'"';
					}
					else
					{												
							if(!empty($default_form_info))
							{
									$member_photo = $this->serverUrl().$this->baseUrl().'/'. $default_form_id[0]['attach_file_path'].'/'.$default_form_info['member_photo_default'];
									$member_photo_width = 'width="'.$default_form_info['member_photo_width_default'].'"';
									$member_photo_height = 'height="'.$default_form_info['member_photo_height_default'].'"';
							}
							else
							{
									$member_photo = 'data/frontImages/tours/design_images/no_user_image.gif';
									$member_photo_width = 'width="75"';
									$member_photo_height = 'height="87"';
							}
					}
				}
				else
				{
					if(!empty($default_form_info))
					{
							$member_photo = $this->serverUrl().$this->baseUrl().'/'. $default_form_id[0]['attach_file_path'].'/'.$default_form_info['member_photo_default'];
							$member_photo_width = 'width="'.$default_form_info['member_photo_width_default'].'"';
							$member_photo_height = 'height="'.$default_form_info['member_photo_height_default'].'"';
					}
					else
					{
							$member_photo = 'data/frontImages/tours/design_images/no_user_image.gif';
							$member_photo_width = 'width="75"';
							$member_photo_height = 'height="87"';
					}
				}
			?>
              <img src="<?php echo $member_photo; ?>" <?php echo $member_photo_width.' '.$member_photo_height; ?> class="avatar" />
              <div> 
              	<span class="label"><?php echo $this->translator->translator('tours_front_page_label_presented'); ?></span>&nbsp;
				<span class="value"><?php echo $this->escape($owner_name); ?></span> 
			  </div>
              <div>
              
              <div class="pkg-img">
                  <?php												
					if($packages->isPackageFrontendField($module,$controller,$action.'_pic',$mem_user_id,$mem_role_id))
					{		
						$package_pic_info = $packages->getPackageFrontendFieldDetailsValue($module,$controller,$action.'_pic',$mem_user_id,$mem_role_id);				
						if(!empty($package_pic_info))
						{
							$forms_info = $forms_db->getFormsInfo($package_pic_info['form_id']);
							if(!empty($package_pic_info['field_value']))
							{
								$package_pic = $this->serverUrl().$this->baseUrl().'/'. $forms_info['attach_file_path'].'/'.$package_pic_info['field_value'];
								$package_pic_width = $packages->getPackageFrontendFieldValue($module,$controller,$action.'_pic_width',$mem_user_id,$mem_role_id);
								$package_pic_height = $packages->getPackageFrontendFieldValue($module,$controller,$action.'_pic_height',$mem_user_id,$mem_role_id);
								$package_pic_width_field = ($package_pic_width) ? 'width="'.$package_pic_width.'"' : '';
								$package_pic_height_field = ($package_pic_width) ? 'height="'.$package_pic_height.'"' : '';
							}
							else
							{
								$package_pic = $this->serverUrl().$this->baseUrl().'/'. $default_form_id[0]['attach_file_path'].'/'.$default_form_info['property_frontend_details_pic_default'];
								$package_pic_width_field = (!empty($default_form_info['property_frontend_details_pic_width_default'])) ? 'width="'.$default_form_info['property_frontend_details_pic_width_default'].'"' : '';
								$package_pic_height_field = (!empty($default_form_info['property_frontend_details_pic_height_default'])) ? 'height="'.$default_form_info['property_frontend_details_pic_height_default'].'"' : '';
							}
						}
						else
						{
							$package_pic = $this->serverUrl().$this->baseUrl().'/'. $default_form_id[0]['attach_file_path'].'/'.$default_form_info['property_frontend_details_pic_default'];
							$package_pic_width_field = (!empty($default_form_info['property_frontend_details_pic_width_default'])) ? 'width="'.$default_form_info['property_frontend_details_pic_width_default'].'"' : '';
							$package_pic_height_field = (!empty($default_form_info['property_frontend_details_pic_height_default'])) ? 'height="'.$default_form_info['property_frontend_details_pic_height_default'].'"' : '';
						}
					}

					else
					{
						$package_pic = $this->serverUrl().$this->baseUrl().'/'. $default_form_id[0]['attach_file_path'].'/'.$default_form_info['property_frontend_details_pic_default'];
						$package_pic_width_field = (!empty($default_form_info['property_frontend_details_pic_width_default'])) ? 'width="'.$default_form_info['property_frontend_details_pic_width_default'].'"' : '';
						$package_pic_height_field = (!empty($default_form_info['property_frontend_details_pic_height_default'])) ? 'height="'.$default_form_info['property_frontend_details_pic_height_default'].'"' : '';
					}												
					if($package_pic)
					{
				?>
                  <img src="<?php echo $package_pic; ?>" <?php echo $package_pic_width_field.' '.$package_pic_height_field; ?> />
                  <?php
					}
				?>
                </div>
                <span class="label">
                <?php if(($package_info[0]['field_value'])){ echo $this->translator->translator('common_package_name_title'); } ?>
                </span><br />
                <div class="pkg-title"><?php echo $this->escape($package_info[0]['field_value']); ?></div>
                <hr />
              	<?php
					if($packages->isPackageFrontendField($module,$controller,$action.'_certified',$mem_user_id,$mem_role_id))
					{
						$allow_certified = $packages->getPackageFrontendFieldValue($module,$controller,$action.'_certified',$mem_user_id,$mem_role_id);				
					}
					else
					{
						$allow_certified = 'No';
					}
	
					if($packages->isPackageFrontendField($module,$controller,$action.'_allow_logo',$mem_user_id,$mem_role_id))
					{
	
						$allow_logo = $packages->getPackageFrontendFieldValue($module,$controller,$action.'_allow_logo',$mem_user_id,$mem_role_id);				
					}
					else
					{
						$allow_logo = 'No';
					}
				?>
               <div>
                <?php
													if($allow_logo == 'Yes')
													{									
														if(is_array($owner_info))
														{
															if($owner_info['company_logo'])
															{
																$company_logo_path = $owner_forms_info['attach_file_path'];
																$company_logo = $member_photo_path.'/'.$owner_info['company_logo'];
																$company_logo_width = ($default_form_info['company_logo_width_default']) ? 'width="'.$default_form_info['company_logo_width_default'].'"' : '';
																$company_logo_height = ($default_form_info['company_logo_height_default']) ? 'height="'.$default_form_info['company_logo_height_default'].'"' : '';
															}
															else
															{
																if(!empty($default_form_info))
																{
																	$company_logo = $this->serverUrl().$this->baseUrl().'/'. $default_form_id[0]['attach_file_path'].'/'.$default_form_info['company_logo_default'];
																	$company_logo_width = ($default_form_info['company_logo_width_default']) ? 'width="'.$default_form_info['company_logo_width_default'].'"' : '';
																	$company_logo_height = ($default_form_info['company_logo_height_default']) ? 'height="'.$default_form_info['company_logo_height_default'].'"' : '';
																}
																else
																{
																	$company_logo = 'data/frontImages/tours/design_images/no_company_logo.gif';
																	$company_logo_width = 'width="80"';
																	$company_logo_height = 'height="60"';
																}
															}
														}
														else
														{
															if(!empty($default_form_info))
															{
																$company_logo = $this->serverUrl().$this->baseUrl().'/'. $default_form_id[0]['attach_file_path'].'/'.$default_form_info['company_logo_default'];
																$company_logo_width = ($default_form_info['company_logo_width_default']) ? 'width="'.$default_form_info['company_logo_width_default'].'"' : '';
																$company_logo_height = ($default_form_info['company_logo_height_default']) ? 'height="'.$default_form_info['company_logo_height_default'].'"' : '';
															}
															else
															{
																$company_logo = 'data/frontImages/tours/design_images/no_company_logo.gif';
																$company_logo_width = 'width="80"';
																$company_logo_height = 'height="60"';
															}
														}
												?>
                <img src="<?php echo $company_logo; ?>" <?php echo $company_logo_width.' '.$company_logo_height; ?> class="company-logo" />
                <?php
													}
												?>
              </div>
              <?php
													if($packages->isPackageFrontendField($module,$controller,$action.'_contact_directly',$mem_user_id,$mem_role_id))
													{
														$contact_directly = $packages->getPackageFrontendFieldValue($module,$controller,$action.'_contact_directly',$mem_user_id,$mem_role_id);				
													}
													else
													{
														$contact_directly = 'No';
													}
													if($contact_directly == 'Yes')
													{
												 ?>
              <div class="company-info"> 
                <!-- Company Name -->
                <div> <span class="label"><?php echo $this->translator->translator('tours_front_page_label_company'); ?></span>
                  <?php if(is_array($owner_info)){ echo $this->escape($owner_info['companyName']); } ?>
                </div>
                <!-- Company Name --> 
                
                <!-- Address -->
                <div> <span class="label"><?php echo $this->translator->translator('tours_front_page_label_contact'); ?></span><br />
                  
                  <?php 
														if(is_array($owner_info) && $owner_info['city'])
														{	
															echo $this->translator->translator('tours_front_page_label_city'); 											
															echo " ".$this->escape($owner_info['city']);
														}
													?>
                  <br />
                  <?php  
														if($owner_info['state'])
														{
															echo $this->translator->translator('tours_front_page_label_state');
															echo " ".$this->escape($owner_info['state']);
														}
													?>
                  <br />
                  <?php 
														if(is_array($owner_info) && $owner_info['country'])
														{
															echo $this->translator->translator('tours_front_page_label_country');
															$owner_country_info = $country_db->getCountryName($owner_info['country']);
															echo " ".$this->escape($owner_country_info['value']);
														}
													?>
                  <br />
                  <?php 
														if(is_array($owner_info) && !empty($owner_info['postalCode']))
														{
															echo $this->translator->translator('tours_front_page_label_postcode'); 
															echo " ".$this->escape($owner_info['postalCode']);	
														}
													?>
                </div>
                <!-- Address --> 
                
                <!-- Tel -->
                <?php
												if(is_array($owner_info) && !empty($owner_info['phone']))
												{
												?>
                <div> <span class="label"><?php echo $this->translator->translator('tours_front_page_label_phone'); ?></span> <?php echo $this->escape($owner_info['phone']); ?> </div>
                <?php
												}
												?>
                <!-- Tel --> 
                
                <!-- Fax -->
                <?php
												if(is_array($owner_info) && !empty($owner_info['fax']))
												{
												?>
                <div> <span class="label"><?php echo $this->translator->translator('tours_front_page_label_fax'); ?></span> <?php echo $this->escape($owner_info['fax']); ?> </div>
                <?php
												}
												?>
                <!-- Fax --> 
                
                <!-- Email -->
                <div> <a href="<?php if(is_array($owner_info)){ echo 'mailto:'.$this->escape($owner_info['username']); }else{ echo 'mailto:'.$this->escape($this->view_datas['house_email']) ;} ?>" class="agent-email"><?php echo $this->translator->translator('tours_front_page_label_email_lang'); ?></a> </div>
                <!-- Email --> 
                
                <!-- Web -->
                <?php
												if(is_array($owner_info) && !empty($owner_info['website']))
												{
												?>
                <div> <span class="label"><?php echo $this->translator->translator('tours_front_page_label_web'); ?></span> <a href="<?php if(is_array($owner_info)){ echo 'http://'.$this->escape($owner_info['website']); } ?>" target="_blank" class="agent-web">
                  <?php if(is_array($owner_info)){ echo $this->escape($owner_info['website']); } ?>
                  </a> </div>
                <?php
												}
												?>
                <!-- Web --> 
                
              </div>
              <hr />
              <?php
												}
											 ?>
              
              <!-- Certifdicate -->
              <div class="certificate">
                <?php														
													if($allow_certified == 'Yes')
													{
														if($packages->isPackageFrontendField($module,$controller,$action.'_pic_certi',$mem_user_id,$mem_role_id))
														{
															$package_pic_certi_info = $packages->getPackageFrontendFieldDetailsValue($module,$controller,$action.'_pic_certi',$mem_user_id,$mem_role_id);				
															if(!empty($package_pic_certi_info))
															{
																$forms_info = $forms_db->getFormsInfo($package_pic_certi_info['form_id']);
																if(!empty($package_pic_certi_info['field_value']))
																{
																	$package_pic_certi = $this->serverUrl().$this->baseUrl().'/'. $forms_info['attach_file_path'].'/'.$package_pic_certi_info['field_value'];
																	$package_pic_certi_width = $packages->getPackageFrontendFieldValue($module,$controller,$action.'_pic_certi_width',$mem_user_id,$mem_role_id);
																	$package_pic_certi_height = $packages->getPackageFrontendFieldValue($module,$controller,$action.'_pic_certi_height',$mem_user_id,$mem_role_id);
																	$package_pic_certi_width_field = ($package_pic_certi_width) ? 'width="'.$package_pic_certi_width.'"' : '';
																	$package_pic_certi_height_field = ($package_pic_certi_height) ? 'height="'.$package_pic_certi_height.'"' : '';
																}
																else
																{
																	$certi_pic_arr = explode(',',$default_form_info['property_frontend_details_pic_certi_default']);
																	$package_pic_certi = $this->serverUrl().$this->baseUrl().'/'. $default_form_id[0]['attach_file_path'].'/'.$certi_pic_arr[0];
																	$package_pic_certi_width_field = ($default_form_info['property_frontend_details_pic_certi_width_default']) ? 'width="'.$default_form_info['property_frontend_details_pic_certi_width_default'].'"' : '';
																	$package_pic_certi_height_field = ($default_form_info['property_frontend_details_pic_certi_height_default']) ? 'height="'.$default_form_info['property_frontend_details_pic_certi_height_default'].'"' : '';
																}
															}
															else
															{
																$certi_pic_arr = explode(',',$default_form_info['property_frontend_details_pic_certi_default']);
																$package_pic_certi = $this->serverUrl().$this->baseUrl().'/'. $default_form_id[0]['attach_file_path'].'/'.$certi_pic_arr[0];
																$package_pic_certi_width_field = ($default_form_info['property_frontend_details_pic_certi_width_default']) ? 'width="'.$default_form_info['property_frontend_details_pic_certi_width_default'].'"' : '';
																$package_pic_certi_height_field = ($default_form_info['property_frontend_details_pic_certi_height_default']) ? 'height="'.$default_form_info['property_frontend_details_pic_certi_height_default'].'"' : '';
															}
														}
														else
														{
															$package_pic_certi = null;
														}
														if($package_pic_certi)
														{
													?>
                <img src="<?php echo $package_pic_certi; ?>" <?php echo $package_pic_certi_width_field.' '.$package_pic_certi_height_field; ?> />
                <?php
															}
														}
													?>
                <p>
                  <?php if($allow_certified == 'Yes'){ echo $this->translator->translator('tours_front_page_label_verified'); } ?>
                </p>
              </div>
              <!-- Certificate --> 
            </div>
          </div>
        </div>
        </div>
        <?php
						}
						?>
        <!-- Tour Agent End-->
        
        <div class="products-details">
          <div class="products-details-header"><h4 class="icon"><?php echo $this->translator->translator('tours_front_page_tours_details'); ?></h4></div>
          <div class="content">
          	<div class="details-info"><?php echo stripslashes($this->tours_Form->tours_desc->getValue()); ?></div>
          </div>
        </div>
      	</div>
        
      	<div id="tabs-2">
        <h2><?php echo $this->translator->translator('tours_front_page_Title_images'); ?></h2>
        <?php
							if($this->group_datas['file_thumb_width'] && ($this->group_datas['file_thumb_resize_func'] != 'resizeToHeight' || $this->group_datas['file_thumb_resize_func'] != 'resize' ))
							{ 	
								$width_img = 'width="'.$this->escape($this->group_datas['file_thumb_width']).'"'; 
							}
							else
							{
								$width_img = '';
							} 
							if($this->group_datas['file_thumb_height'] && ( $this->group_datas['file_thumb_resize_func'] != 'resizeToWidth' || $this->group_datas['file_thumb_resize_func'] != 'resize' ))
							{ 	
								$height_img = 'height="'.$this->escape($this->group_datas['file_thumb_height']).'"'; 
							} 
							else
							{
								$height_img = '';
							}
							$img_arr = explode(',',$this->tours_Form->tours_image->getValue());
							$i = 1;
							foreach($img_arr as $key => $value)
							{
						?>
        <div><a href="javascript:void(0);" class="change_img preview" link="data/frontImages/tours/tours_image/<?php echo $value; ?>" title="<?php echo $this->escape($this->tours_Form->tours_name->getValue()); ?>" width="300"><img src="data/frontImages/tours/tours_image/<?php echo $value; ?>" <?php echo $width_img.' '.$height_img; ?> border="0" class="thumb additional-thumb" /></a> </div>
        <?php                                   
							 $i++;
						  }
						?>
      </div>
      
      	<div id="tabs-3">
        <h2><?php echo $this->translator->translator('tours_front_page_Title_floorplan'); ?></h2>
        <?php
							if($this->group_datas['file_thumb_width'] && ($this->group_datas['file_thumb_resize_func'] != 'resizeToHeight' || $this->group_datas['file_thumb_resize_func'] != 'resize' ))
							{ 
								$width_img = 'width="'.$this->escape($this->group_datas['file_thumb_width']).'"'; 
							}
							else
							{
								$width_img = '';
							} 
							if($this->group_datas['file_thumb_height'] && ( $this->group_datas['file_thumb_resize_func'] != 'resizeToWidth' || $this->group_datas['file_thumb_resize_func'] != 'resize' ))
							{ 
								$height_img = 'height="'.$this->escape($this->group_datas['file_thumb_height']).'"'; 
							} 
							else
							{
								$height_img = '';
							}
							if($this->tours_Form->spots_photo_gallery->getValue())
							{
								$img_froor_arr = explode(',',$this->tours_Form->spots_photo_gallery->getValue());
								$i = 1;
								foreach($img_froor_arr as $key => $value)
								{
						?>
        <div> <a href="javascript:void(0);" class="change_img preview" link="data/frontImages/tours/other_images/<?php echo $value; ?>" title="<?php echo $this->escape($this->tours_Form->tours_name->getValue()); ?>" width="300"><img src="data/frontImages/tours/other_images/<?php echo $value; ?>" <?php echo $width_img.' '.$height_img; ?> border="0" class="thumb additional-thumb" /></a> </div>
        <?php                                   
							 $i++;
						  }
							 }
						?>
      </div>
      
        <div id="tabs-4">
        <h2><?php echo $this->translator->translator('tours_page_inclusions'); ?></h2>
        <?php 
							foreach($feature_facilities_arr as $key=>$value)
							{
								echo '<div class="products-features"> &bull; '.$this->escape($value).'</div>';
							}
						  ?>
        <hr/>
        <h4><?php echo $this->translator->translator('tours_page_exclusions'); ?></h4>
        <?php 
							$feature_sports_recreations_arr = explode(',', $this->view_datas['exclusions']); 
							foreach($feature_sports_recreations_arr as $key=>$value)
							{
								echo '<div class="products-features"> &bull; '.$this->escape($value).'</div>';
							}						  
						?>
      </div>
      
      	<div id="tabs-5">
        <h2><?php echo $this->translator->translator('tours_front_page_Title_brochure_feature'); ?></h2>
        <?php 
							$_itinerary_desc = $this->escape( $this->tours_Form->itinerary_desc->getValue()); 
							if (!empty($_itinerary_desc)) {												
						?>
        <div class="products-details">
          	<div class="products-details-header"><h4 class="icon"><?php echo $this->escape($this->tours_Form->itinerary_title->getValue());  ?></h4></div>
            <div class="content">
                <?php echo $_itinerary_desc ;  ?>
            </div>
        </div>
        <?php 
							}						
							$_tour_highlights = stripslashes($this->tours_Form->tour_highlights->getValue()); 
							if (!empty($_tour_highlights)) {												
						?>
        <div class="products-details">
          <div class="products-details-header"><h4 class="icon"><?php echo $this->translator->translator('tours_front_page_Title_features'); ?></h4></div>
          <div class="content"><?php echo  $_tour_highlights; ?></div>
        </div>
        <?php 
							}
							$_transportation = stripslashes($this->tours_Form->transportation->getValue()); 
							if (!empty($_transportation)) {
						?>
        <div class="products-details">
          <div class="products-details-header"><h4 class="icon"><?php echo $this->tours_Form->transportation->getAttrib('font_end_label'); ?></h4></div>
          <div class="content"><?php echo $_transportation; ?></div>
        </div>
        <?php 
							}
						?>
      </div>
      
      	<div id="tabs-6">
            <div class="products-chart">
              <div class="products-details">
                <div class="products-details-header"><h4 class="icon"><?php echo $this->translator->translator('tours_page_page_payment'); ?></h4></div>
                    <div class="content">
                    <div class="chart-desc">
                      <?php 
                                                $_costs_of_children = $this->escape($this->tours_Form->costs_of_children->getValue()); 
                                                if (!empty($_costs_of_children)) {	
                                            ?>
                      <div class="label"><?php echo $this->tours_Form->costs_of_children->getAttrib('font_end_label');  ?></div>
                      <div class="value">
                        <?php  echo $this->currency->getSymbol() . $_costs_of_children ; ?>
                      </div>
                      <?php 
                                                }
                            
                                                $_single_Room = $this->escape($this->tours_Form->single_Room->getValue()); 
                                                if (!empty($_single_Room)) {												
                                            ?>
                      <div class="label"><?php echo $this->tours_Form->single_Room->getAttrib('font_end_label');  ?></div>
                      <div class="value"><?php echo $this->currency->getSymbol() . $_single_Room ; ?></div>
                      <?php
                                                }
                                                $_double_room = $this->escape($this->tours_Form->double_room->getValue()); 
                                                if (!empty($_double_room)) {																			
                                            ?>
                      <div class="label"><?php echo $this->tours_Form->double_room->getAttrib('font_end_label'); ?></div>
                      <div class="value"><?php echo $this->currency->getSymbol() . $_double_room; ?></div>
                      <?php
                                                }
                                                $_triple_rooms = $this->escape($this->tours_Form->triple_rooms->getValue()); 
                                
                                                if (!empty($_triple_rooms)) {
                                            ?>
                      <div class="label"><?php echo $this->tours_Form->triple_rooms->getAttrib('font_end_label'); ?></div>
                      <div class="value"><?php echo $this->currency->getSymbol() . $_triple_rooms; ?></div>
                      <?php
                                                }
                                                $_extra_nights_per_person = $this->escape($this->tours_Form->extra_nights_per_person->getValue()); 
                                                if (!empty($_extra_nights_per_person)) {																			
                                            ?>
                      <div class="label"><?php echo $this->tours_Form->extra_nights_per_person->getAttrib('font_end_label'); ?></div>
                      <div class="value"><?php echo $this->currency->getSymbol() .$_extra_nights_per_person; ?></div>
                      <?php 
                                            }
                                            ?>
                    </div>
                    </div>
               	</div>
            </div>
            
              <h2><?php echo $this->translator->translator('tours_front_page_Title_payment'); ?></h2>
              <?php 
                                $_payment_desc =  stripslashes( $this->tours_Form->payment_desc->getValue()); 
                                    if (!empty($_payment_desc)) {												
                                ?>
              <div class="products-details">
                <div class="products-details-header"><h4 class="icon"><?php echo $this->translator->translator('tours_front_page_Title_payment_process'); ?></h4></div>
                <div class="content"><?php echo $_payment_desc; ?></div>
              </div>
              <?php 
                                }
                                ?>
      </div>
      
        <div id="tabs-7">
        <h2><?php echo $this->translator->translator('tours_front_page_Title_map'); ?></h2>
        <?php
							$_feature_google_map = $this->escape($this->tours_Form->feature_google_map->getValue()); 
							if (!empty($_feature_google_map)) {
						?>
        <div class="products-details">
          <div class="products-details-header"><h4 class="icon"><?php echo $this->tours_Form->feature_google_map->getAttrib('font_end_label'); ?></h4></div>
          <div class="content products-map"><?php echo $_feature_google_map; ?></div>
        </div>
        <?php
							}																			
						?>
        <?php 
						$_tour_policy =  stripslashes( $this->tours_Form->tour_policy->getValue()); 
							if (!empty($_tour_policy)) {
						?>
        <div class="products-details">
          <div class="products-details-header"><h4 class="icon"><?php echo $this->translator->translator('tours_front_page_title_policy'); ?></h4></div>
          <div class="content"><?php echo $_tour_policy; ?></div>
        </div>
        <?php }?>
      </div>
      	
		<?php
						if(!empty($this->group_datas['review_id']))
						{
		?>
      	
        <div id="tabs-8">
        <?php 
							if(!empty($this->review_datas['review_info']))
							{							
								foreach($this->review_datas['review_info'] as $key => $infos)
								{	
									$div_class = ($key % 2 == 0) ? 'review-box' : 'review-box2';							
						?>
        <div class="<?php echo $div_class; ?>">
          <div class="review-box-img">
            <?php										
									$primary_image_field = (!empty($this->review_datas['review_settings_info']['primary_image_field'])) ? $this->review_datas['review_settings_info']['primary_image_field'] : '';
									$primary_images = (!empty($primary_image_field) && !empty($infos[$primary_image_field])) ? $infos[$primary_image_field] : '' ;
									if(empty($primary_images))
									{
										$img_path = 'application/layouts/scripts/'.$front_template['theme_folder'].'/images/mod_tour_img/avatar.png';
									}
									else
									{
										$files_arr = explode(',',$primary_images);
										$img_path = $this->escape($this->review_datas['form_info']['attach_file_path']).'/'.$this->escape($files_arr[0]);
									}
								?>
            <img src= "<?php echo $img_path ?>" width="80" /> </div>
          <div>
            <div class="review-box-title"> <span>
              <?php 
												if(!empty($this->review_datas['review_settings_info']['name_title_field']))
												{ 
													$name_title_field  = $this->review_datas['review_settings_info']['name_title_field'];
													if(!empty($infos[$name_title_field]))
													{
														echo $this->escape($infos[$name_title_field]); 
													}
												} 
											?>
              </span>
              <div>
                <?php 
												if(!empty($this->review_datas['review_settings_info']['rating_fields']))
												{ 												
													$rating_fields_arr  = explode(',',$this->review_datas['review_settings_info']['rating_fields']);
													if(!empty($infos[$rating_fields_arr[0]]))
													{	
														$cnt = $this->escape($infos[$rating_fields_arr[0]]) - 1;                                                    											
														
											?>
                <div class="review-box-rate"><?php echo str_replace("'",'',$hint_arr[$cnt]); ?></div>
                <div class="review-box-star">
                  <div id="<?php echo $this->escape($rating_fields_arr[0]).$infos['id']; ?>_star"  class="review-box-rate-star"></div>
                  <script type="text/javascript">
																$(function() {
																	raty ('<?php echo $this->escape($rating_fields_arr[0]).$infos["id"]; ?>','<?php echo $this->escape($infos[$rating_fields_arr[0]]); ?>');
																});
															</script> 
                </div>
                <?php 
														}
													} 
												?>
              </div>
            </div>
            <div class="review-box-desc">
              <?php 
												if(!empty($this->review_datas['review_settings_info']['short_desc_field']))
												{ 
													$short_desc_field  = $this->review_datas['review_settings_info']['short_desc_field'];
													if(!empty($infos[$short_desc_field]))
													{
														echo $this->escape($infos[$short_desc_field]); 
													}
												} 
											?>
              <div class="review-box-date">
                <?php 											
														if(!empty($infos['g_date']))
														{
															echo $this->escape($infos['g_date']); 
														}											
													?>
              </div>
            </div>
          </div>
        </div>
        <?php 								
							}							
						}
						?>
      </div>
      <?php
						}
						if(!empty($staticGroupsObj))
						{
							$tab = (!empty($this->group_datas['review_id'])) ? 9 : 8;
							foreach($staticGroupsObj as $staticGroup)
							{
								$elementsObj = $staticGroup->getElements();
					?>
      <div id="tabs-<?php echo $tab; ?>">
        <?php																
										foreach($elementsObj as $element)
										{
											if($element->getAttrib('frontend') == '1')
											{	
												if($element->getType() != 'Zend_Form_Element_File')
												{	
													if($element->getValue())
													{														
									?>
        <div class="tab-element"> <?php echo $element->getLabel();  ?> </div>
        <div class="tab-value">
          <?php 										
															$id_f = $element->getAttrib('id');
															$id_arr = explode('_',$id_f);	
															if(($element->getType() == 'Zend_Form_Element_MultiCheckbox') || ($element->getType() == 'Zend_Form_Element_Multiselect'))
															{	
																$val_arr = $element->getValue();														
																echo implode(', ',$val_arr);
															}
															else
															{													
																echo stripslashes($element->getValue());	
															}														
														?>
        </div>
        <?php
													}
												}
											}
										}
									?>
      </div>
      <?php
								$tab++;
							 }
						 }
						?>
    </div>
    <!-- Tour Bottom Tab End --> 
    
    <!-- Bottom Bar Start -->
    <div class="nav-bar bottom">
        <div class="nav-row">
            <div class="nav-col first"> 
            <?php
				if(!empty($prevTours))
				{
			?>
            <span class="prev"><a href="<?php echo 'Tours-details/'.$this->escape($prevTours['tours_title']); ?>"><?php echo $this->translator->translator('tours_front_page_prev_tours'); ?></a></span>
            <?php
				}
				else
				{
			?>
            <span class="no-link"><?php echo $this->translator->translator('tours_front_page_prev_tours'); ?></span>
            <?php
                }
            ?>
            </div>
            <div class="nav-col"><span class="search"><a href="#" class="slick-slidetoggle"><?php echo $this->translator->translator('tours_front_page_new_search'); ?></a></span></div>
            <div class="nav-col">
            <?php
			if ($hasIdentity)
				{
			?>
            <span class="save"><a  href="javascript:void(0);" class="save_tours_btn" rel="<?php echo $this->escape($item_id); ?>"><?php echo $this->translator->translator('tours_front_page_save_tours'); ?></a></span>
            <?php
                }
            ?>
            </div>
            <div class="nav-col last">
            <?php
				if(!empty($nextTours))
				{
			?>
            <span class="next"><a href="<?php echo 'Tours-details/'.$this->escape($nextTours['tours_title']); ?>"><?php echo $this->translator->translator('tours_front_page_next_tours'); ?></a></span>
            <?php
                }
                else
                {
            ?>
            <span class="no-link"><?php echo $this->translator->translator('tours_front_page_next_tours'); ?></span>
            <?php
                }
            ?>
            </div>
        </div>
    </div>
    <!-- Bottom Bar End --> 
   
  	<div id="dialog_container" title="<?php echo $this->translator->translator('common_dialog_msg','Message'); ?>"></div>
</div>
<?php else : ?>
<h2><?php echo $this->translator->translator('common_not_approved'); ?></h2>
<?php endif; ?>
<?php endif; ?>