<?php
$version = Zend_Registry::get('version');
if(!empty($this->group_datas['meta_keywords'])) { $this->headMeta()->setName('keywords',$this->group_datas['meta_keywords']);}
if(!empty($this->group_datas['meta_desc'])) { $this->headMeta()->setName('description',$this->group_datas['meta_desc']); }
if(!empty($this->group_datas['tours_name'])) { $this->headTitle()->headTitle($this->group_datas['tours_name'],'SET')->setSeparator(' - ')->headTitle($this->group_datas['meta_title']); }
$front_template = Zend_Registry::get('front_template'); 
$maximum_rating_digit = $this->translator->translator('maximum_rating_digit');
function tours_truncate($phrase,$start_words, $max_words)
{
   $phrase_array = explode(' ',$phrase);
   if(count($phrase_array) > $max_words && $max_words > 0)
	  $phrase = implode(' ',array_slice($phrase_array, $start_words, $max_words)).'...';  
   return $phrase;
}

$global_conf = Zend_Registry::get('global_conf');
$auth = Zend_Auth::getInstance ();
Eicra_Global_Variable::getSession()->returnLink = ($auth->hasIdentity ()) ? '' : $this->url(array('module'=> 'Tours','controller'=>'Backendpro', 'action'=>'add','group_id' => $this->group_datas['id']),'adminrout',true);
$url = ($auth->hasIdentity ()) ? $this->url(array('module'=> 'Tours','controller'=>'Backendpro', 'action'=>'add','group_id' => $this->group_datas['id']),'adminrout',true)  : $this->serverUrl().$this->baseUrl().'/Frontend-Login';

$tours_helper = new Tours_View_Helper_ToursGroup();
$num_tours = $tours_helper->getNumOfProduct($this->group_datas['id']);

$popular_tours = $tours_helper->getPopularTours($this->group_datas['id']); 
$business_type_db = new Tours_Model_DbTable_BusinessType();
$tours_types = $business_type_db->getBusinessTypeByGroup($this->group_datas['id']);
?>

<script type="text/javascript">
$(document).ready(function() {		
		autoSugg();
		
		$('#country_id_H').change(function() {	
			if($('#country_id_H option:selected').val() == 'any' || $('#country_id_H option:selected').val() =='')
			{
				$('#area_id_H').html('<option value="any"><?php echo $this->translator->translator("tours_select_area"); ?></option>');	
				$('#state_id_H').html('<option value="any"><?php echo $this->translator->translator("tours_select_state"); ?></option>');
			}
			else
			{	
				$.ajax({
					  url: "<?php echo $this->url( array('module' =>'Tours','controller' => 'frontend', 'action'     => 'states' ), 'adminrout',    true) ?>",
					  type: 'POST',
					  data: { id: $('#country_id_H option:selected').val() },
					  beforeSend: function(){						
								$('#state_id_H').html('<option value="any"><?php echo $this->translator->translator("common_loading_language"); ?></option>');
								$('#area_id_H').html('<option value="any"><?php echo $this->translator->translator("tours_select_area"); ?></option>');			
								$('#state_id_err').html('<img src="application/layouts/scripts/<?php echo $front_template['theme_folder']; ?>/images/loader/mod-loader.gif" width="15" border="0" />');	
							 },
					  success: function(response){
						//alert(response);
						var json_arr = eval("("+response+")");
						var option = '<option value="any"><?php echo $this->translator->translator("tours_select_state"); ?></option>';				
						if(json_arr.status == 'ok')
						{
							for(var i = 0;i<json_arr.states.length;i++)
							{
								option += '<option value="'+json_arr.states[i].state_id+'" >'+stripslashes(json_arr.states[i].state_name)+'</option>';
							}
							$('#state_id_H').html(option);
						}
						else
						{
							$('#state_id_H').html('<option value="any">'+json_arr.msg+'</option>');
						}
						$('#state_id_err').html('');
					  }
				});
			}
		});
		
		$('#state_id_H').change(function() {		
					
			if($('#state_id_H option:selected').val() == 'any' || $('#state_id_H option:selected').val() == '')
			{
				$('#area_id_H').html('<option value="any"><?php echo $this->translator->translator("tours_select_area"); ?></option>');
			}
			else
			{
				$.ajax({
					  url: "<?php echo $this->url( array('module' => 'Tours', 'controller' => 'frontend', 'action'     => 'areas' ), 'adminrout',    true) ?>",
					  type: 'POST',
					  data: { id: $('#state_id_H option:selected').val() },
					  beforeSend: function(){						
							$('#area_id_H').html('<option value="any"><?php echo $this->translator->translator("common_loading_language"); ?></option>');
							$('#area_id_err').html('<img src="application/layouts/scripts/<?php echo $front_template['theme_folder']; ?>/images/loader/mod-loader.gif" width="15" border="0" />');	
							},
					  success: function(response){
						//alert(response);
						var json_arr = eval("("+response+")");
						var option = '<option value="any"><?php echo $this->translator->translator("tours_select_area"); ?></option>';				
						if(json_arr.status == 'ok')
						{
							for(var i = 0;i<json_arr.cities.length;i++)
							{
								option += '<option value="'+json_arr.cities[i].city_id+'" >'+stripslashes(json_arr.cities[i].city)+'</option>';
							}
							$('#area_id_H').html(option);
						}
						else
						{
							$('#area_id_H').html('<option value="any">'+json_arr.msg+'</option>');
						}
						$('#area_id_err').html('');
					  }
				});
			}
		});	
			
		$('input.search_btn').click(function(){
			var self = this;
			$('#formSearch').submit();
		});
});

function openMsgDialog(msg)
{
$('#dialog_container').html(msg).dialog({
			autoOpen: true,
			modal: false,
			show: 'fade',
			resizable: 'false',				
			buttons: { "<?php echo html_entity_decode($this->translator->translator('common_ok'), ENT_QUOTES, 'UTF-8'); ?>": function() { $(this).dialog('option', 'hide', 'explode').dialog("close"); } },
			open: function(event, ui)
				 {
					setTimeout(function() 
					{									
						if($('#' + event.target.id).dialog('isOpen'))
						{
							//$('#' + event.target.id).dialog('option', 'hide', 'explode').dialog('close');										
						}
					}, 10000);
				  }
		});
}

function autoSugg()
{	
		autoSuggestion('post_code', "<?php echo $this->url( array('module'=> 'Tours', 'controller' => 'backendpro', 'action'     => 'searchname' ), 'adminrout',    true) ?>", {'post_code': ''}, ['tours_primary_image', 'tours_image', 'tours_name', 'post_code', 'owner_name', 'num_of_days','tours_postcode' ,'ending_city', 'tours_location'], 'data/frontImages/tours/tours_image', 2);	
}

function stripslashes(str) 
{
	str=str.replace(/\\'/g,'\'');
	str=str.replace(/\\"/g,'"');
	str=str.replace(/\\0/g,'\0');
	str=str.replace(/\\\\/g,'\\');
	return str;
}
</script>

<div id="dialog_container" title="<?php echo $this->translator->translator('common_dialog_msg',$this->translator->translator('tours_front_page_dialog_name')); ?>"></div>

<div>
	<!-- Banner Start -->
    <div id="banner">
    	<?php echo $this->partial('blocks/home_banner_slideshow.phtml'); ?>
        <?php echo $this->partial('blocks/tours_home_banner_search.phtml'); ?>
    </div>
	<!-- Banner End -->
    
    <!--Left Sidebar Start-->
    <aside id="sidebar">    		
		<!--Top destination Start-->
        <div class="block block-top-dst">
            <div class="block-heading">
				<div class="symbol"><?php echo $this->translator->translator('tours_front_page_home_top_destination_title'); ?></div>
			</div>
        
            <div class="block-body">    
				<ul>
                    <?php
                        if($popular_tours)
                        {
							$city_arr = array();
                            foreach($popular_tours as $i => $entry)
                            {	
								if(!in_array($entry['city'], $city_arr))
								{							
                    ?>
                        <li><a href="<?php echo $this->url(array('module' => 'Tours','controller' =>'frontend', 'action' => 'details','tours_title' => $this->escape($entry['tours_title']) ),'Tours-details/:tours_title',true); ?>"><?php echo $this->escape($entry['city']).', '.$this->escape($entry['country_name']); ?></a></li>
                    <?php
								}
								$city_arr[$i] = $entry['city'];
								$i++;
                            }
                        }
                    ?>                            	
				</ul>       
			</div>
      	</div>
		<!--Top destination End-->
		
        <!--Tour Type Start-->
        <div class="block block-top-dst">
            <div class="block-heading">
				<div class="symbol"><?php echo $this->translator->translator('tours_front_page_home_by_type_title'); ?></div>
            </div>
            
          	<div class="block-body">    
                <ul>
					<?php
                    if($tours_types)
                    {
                        foreach($tours_types as $entry)
                        {
                    ?>
                            <li><a href="<?php echo $this->url(array('module' => 'Tours','controller' =>'frontend', 'action' => 'view', 'type'  => $this->escape($entry['id']) ),'Tours-List-Type/*',true); ?>"><?php echo $this->escape($entry['business_type']); ?></a></li>
                    <?php
                        }
                    }
                    ?>
                </ul>
			</div>
        </div>
		<!--Tour Type End-->     
    </aside>
    <!--Left Sidebar End-->
    
    <!-- Content Start -->
    <article id="content">
    	<?php if($this->group_datas['featured_file_on'] == '1'){ ?> 
		<div class="block block-grid">
        	<div class="block-body">
        		<h2><?php echo $this->translator->translator('tours_block_featured_list_title'); ?></h2>
                <div id="featured_list">
                        <?php						  
                        if($this->view_featured_datas)
                        {
                            $j = 1;	
                            foreach($this->view_featured_datas as $entry)
                            {
                                $tours_image_val_arr = explode(',',$entry['tours_image']);
                                $tours_image_no = count($tours_image_val_arr);
                                if($this->escape($entry['traveler_photos']))
                                { 
                                    $thumb_image = 'data/frontImages/tours/tours_image/'.$this->escape($entry['traveler_photos']); 
                                }
                                else
                                { 
                                    if($this->escape($entry['tours_image']))
                                    {											
                                        $thumb_image = 'data/frontImages/tours/tours_image/'.$this->escape($tours_image_val_arr[0]); 
                                    }
                                    else
                                    {
                                        $thumb_image = 'application/layouts/scripts/'.$front_template['theme_folder'].'/images/mod_tour_img/no_image.png';
                                    }		
                                }
                                if($this->group_datas['file_thumb_width'] && $this->group_datas['file_thumb_resize_func'] != 'resizeToHeight')
                                { 
                                    $width = 'width="'.$this->escape($this->group_datas['file_thumb_width']).'"'; 
                                }
                                else
                                {
                                    $width = '';
                                } 
                                if($this->group_datas['file_thumb_height'] && $this->group_datas['file_thumb_resize_func'] != 'resizeToWidth')
                                { 
                                    $height = 'height="'.$this->escape($this->group_datas['file_thumb_height']).'"'; 
                                } 
                                else
                                {
                                    $height = '';
                                }										
                      	?>
                        <div class="col">
                            <span class="block-title">
                                <a href="<?php echo $this->url(array('module' => 'Tours','controller' =>'frontend', 'action' => 'details','tours_title' => $this->escape($entry['tours_title']) ),'Tours-details/:tours_title',true); ?>" class="preview" link="" title="<?php echo $this->escape($entry['tours_name']); ?>"><?php echo tours_truncate($this->escape($entry['tours_name']), 0, 4); ?></a>
                            </span>
                            
                            <div class="clear">
                                <?php
                                    for($i = 1; $i < $maximum_rating_digit; $i++)
                                    {
                                        $tours_rating = ($i <= $this->escape($entry['rating'])) ? "<img src='application/layouts/scripts/".$front_template['theme_folder']."/images/mod_tour_img/star-small-active.png' border='0' />" : "<img src='application/layouts/scripts/".$front_template['theme_folder']."/images/mod_tour_img/star-small-inactive.png' border='0' />";
                                        echo $tours_rating.'&nbsp;';
                                    }
                                ?>
                            </div>
                            
                            <div class="img-wrapper">
                                <a href="<?php echo $this->url(array('module' => 'Tours','controller' =>'frontend', 'action' => 'details','tours_title' => $this->escape($entry['tours_title']) ),'Tours-details/:tours_title',true); ?>" class="preview" link="<?php echo $thumb_image; ?>"  title="<?php echo $this->escape($entry['tours_name']); ?>" width="300"><img src="<?php echo $thumb_image; ?>" <?php echo $width." ".$height; ?> border="0"  class="thumb"></a>
                                <div class="photo-count-container">
                                    <div class="photo-count">
                                        <a href="<?php echo $this->url(array('module' => 'Tours','controller' =>'frontend', 'action' => 'details',tours_title => $this->escape($entry['tours_title']),'tab' => 1 ),'Tours-details/:tours_title/:tab',true); ?>" title="<?php echo $this->translator->translator('tours_front_page_tours_click_view_listing'); ?>"><?php echo $this->translator->translator('tours_front_page_tours_photo_no',$tours_image_no); ?></a>
                                    </div>
                                </div>
                            </div>
                            
                            <div class="details">
                                <span><?php echo $this->translator->translator('tours_block_featured_label_price'); ?></span>&nbsp;<span class="price"><?php echo $this->price($this->escape($entry['tours_price'])).' '.$this->currency->getSymbol(); ?></span><br />
                                <span><?php echo $this->translator->translator('tours_block_featured_label_location', '', 'Tours'); ?></span> <?php echo $this->escape($entry['state_name'].' / '.$entry['city']); ?> <br />
                                <div class="duration"><?php if(!empty($entry['num_of_days'])){ echo (int)$this->escape($entry['num_of_days']);  echo ' '.$this->translator->translator('tours_num_of_nights'); } ?> <?php if(!empty($entry['num_of_nights'])){ echo (int)$this->escape($entry['num_of_nights']);  echo ' '.$this->translator->translator('tours_num_of_days'); } ?></div>
                                <span><?php if(!empty($entry['tours_desc'])){ echo $this->translator->translator('tours_block_featured_label_description', '', 'Tours'); ?></span> <?php echo tours_truncate($this->escape(strip_tags($entry['tours_desc'])), 0, 3); } ?>
                            </div>  
                        </div>
                        <?php
                                $j++;
                            }
                        }
                        ?>
                </div>
            </div>
  		</div>
    	<?php } ?>
 
    	<div class="block block block-listing">
        	<div class="block-body">
        		<h2><?php echo $this->translator->translator('tours_block_popular_list_title'); ?></h2>
                <div class="col">
                    <ul>
						<?php	
                            if($popular_tours)
                            {
                                $l =1;
                                foreach($popular_tours as $entry)						
                                {
                                
                                    if($this->escape($entry['traveler_photos']))
                                    { 
                                        $thumb_image = 'data/frontImages/tours/tours_image/'.$this->escape($entry['traveler_photos']); 
                                    }
                                    else
                                    { 
                                        if($this->escape($entry['tours_image']))
                                        {
                                            $tours_image_val_arr = explode(',',$entry['tours_image']);
                                            $thumb_image = 'data/frontImages/tours/tours_image/'.$this->escape($tours_image_val_arr[0]); 
                                        }
                                        else
                                        {
                                            $thumb_image = 'application/layouts/scripts/'.$front_template['theme_folder'].'/images/mod_tour_img/no_image.png'; 
                                        }		
                                    }
                                    if($this->group_datas['file_thumb_width'] && $this->group_datas['file_thumb_resize_func'] != 'resizeToHeight')
                                    { 
                                        $width = 'width="'.$this->escape($this->group_datas['file_thumb_width']).'"'; 
                                    }
                                    else
                                    {
                                        $width = '';
                                    } 
                                    if($this->group_datas['file_thumb_height'] && $this->group_datas['file_thumb_resize_func'] != 'resizeToWidth')
                                    { 
                                        $height = 'height="'.$this->escape($this->group_datas['file_thumb_height']).'"'; 
                                    } 
                                    else
                                    {
                                        $height = '';
                                    }
                        ?>
                        <li><a href="<?php echo $this->url(array('module' => 'Tours','controller' =>'frontend', 'action' => 'details','tours_title' => $this->escape($entry['tours_title']) ),'Tours-details/:tours_title',true); ?>" class="preview" link="<?php echo $thumb_image; ?>" title="<?php echo $this->escape($entry['tours_name']); ?>" width="300"><?php echo tours_truncate($this->escape($entry['tours_name']), 0, 3); ?></a></li>
                        
                        <?php
                                if($l % 4 == 0)
                                {
                                    echo '</ul></div><div class="col"><ul>';
                                }
                                    $l++;
                                }
                            }
                        ?>
                    </ul>
                </div>
            </div>
        </div>
        
        <?php if($this->group_datas['latest_file_on'] == '1'){ ?> 
        <div class="block block-listing">
        	<div class="block-body">
       			<h2><?php echo $this->translator->translator('tours_block_latest_list_title'); ?></h2>
                <div class="col">
                    <ul>
                        <?php	
							if($this->view_latest_datas)
							{
								$l =1;
								foreach($this->view_latest_datas as $entry)						
								{
								
									if($this->escape($entry['traveler_photos']))
									{ 
										$thumb_image = 'data/frontImages/tours/tours_image/'.$this->escape($entry['traveler_photos']); 
									}
									else
									{ 
										if($this->escape($entry['tours_image']))
										{
											$tours_image_val_arr = explode(',',$entry['tours_image']);
											$thumb_image = 'data/frontImages/tours/tours_image/'.$this->escape($tours_image_val_arr[0]); 
										}
										else
										{
											$thumb_image = 'application/layouts/scripts/'.$front_template['theme_folder'].'/images/mod_tour_img/no_image.png'; 
										}		
									}
									if($this->group_datas['file_thumb_width'] && $this->group_datas['file_thumb_resize_func'] != 'resizeToHeight')
									{ 
										$width = 'width="'.$this->escape($this->group_datas['file_thumb_width']).'"'; 
									}
									else
									{
										$width = '';
									} 
									if($this->group_datas['file_thumb_height'] && $this->group_datas['file_thumb_resize_func'] != 'resizeToWidth')
									{ 
										$height = 'height="'.$this->escape($this->group_datas['file_thumb_height']).'"'; 
									} 
									else
									{
										$height = '';
									}
                            ?>
                            
                            	<li><a href="<?php echo $this->url(array('module' => 'Tours','controller' =>'frontend', 'action' => 'details','tours_title' => $this->escape($entry['tours_title']) ),'Tours-details/:tours_title',true); ?>" class="preview" link="<?php echo $thumb_image; ?>" title="<?php echo $this->escape($entry['tours_name']); ?>" width="300"><?php echo tours_truncate($this->escape($entry['tours_name']), 0, 3); ?></a></li>
                            
                            <?php
                                    if($l % 5 == 0)
                                    {
                                        echo '</ul></div><div class="col"><ul>';
                                    }
                                        $l++;
                                    }
                                }
                            ?>
                    </ul>
                </div>
           	</div>
        </div>
	</article>
    <!-- Content End -->
   <?php } ?> 
</div>