<?php
	$frontController = Zend_Controller_Front::getInstance();
	$module = $frontController->getRequest()->getModuleName();
	$controller = $frontController->getRequest()->getControllerName();
	$action = $frontController->getRequest()->getActionName();
	$country_id = $frontController->getRequest()->getParam('country_id');
	$state_id = $frontController->getRequest()->getParam('state_id');
	$city_id = $frontController->getRequest()->getParam('city_id');
	$icao_code = $frontController->getRequest()->getParam('icao_code');
	$iata_code = $frontController->getRequest()->getParam('iata_code');
	$airport_name = $frontController->getRequest()->getParam('airport_name');
	$country_id_link = ($country_id)? '/country_id/'.$country_id : '';
	$state_id_link = ($state_id)? '/state_id/'.$state_id : '';
	$city_id_link = ($city_id)? '/city_id/'.$city_id : '';
	$icao_code_link = ($icao_code)? '/icao_code/'.$icao_code : '';
	$iata_code_link = ($iata_code)? '/iata_code/'.$iata_code : '';
	$airport_name_link = ($airport_name)? '/airport_name/'.$airport_name : '';
$translator = Zend_Registry::get('translator');
?>

<?php echo $translator->translator('pagination_total'); ?> <?php echo $this->totalItemCount; ?> <?php echo $translator->translator('pagination_records_found'); ?> &nbsp; | &nbsp; <?php echo $translator->translator('pagination_Page'); ?> <?php echo $this->current; ?> <?php echo $translator->translator('pagination_of'); ?> <?php echo $this->last; $sessions = Eicra_Global_Variable::getSession(); ?>
<div class="page-no">
	<?php echo $translator->translator('pagination_jump_page'); ?> 
    <select name="PageNum" id="PageNum" onChange="document.location.href='<?php echo $this->baseUrl().'/'.$module.'/'.$controller.'/'.$action.$country_id_link.$state_id_link.$city_id_link.$icao_code_link.$iata_code_link.$airport_name_link.'/page/'; ?>'+this.options[this.selectedIndex].value">
        <?php
            for($i=1;$i<=$this->pageCount;$i++)
            {
        ?>
        <option value="<?php echo $i; ?>" <?php if($this->current == $i){ ?>selected="selected"<?php } ?>><?php echo $i; ?></option>
        <?php
            }
        ?>							
    </select>
				  			                              
    <form id="form1" name="form1" method="post" action="<?php echo $this->url(array('module' => $module,'controller' => $controller,'action' => $action,'country_id' => $country_id, 'state_id' => $state_id, 'city_id' => $city_id, 'icao_code' => $icao_code, 'iata_code' => $iata_code, 'airport_name' => $airport_name),'adminrout',true);?>">
    <?php echo $translator->translator('pagination_view_result_per_page'); ?> 
        <select name="viewPageNum" id="viewPageNum" onChange="form.submit();">
            <option value="1" <?php if($sessions->viewPageNum == '1'){ ?>selected="selected"<?php } ?>>1</option>
            <option value="5" <?php if($sessions->viewPageNum == '5'){ ?>selected="selected"<?php } ?>>5</option>
            <option value="10" <?php if($sessions->viewPageNum == '10'){ ?>selected="selected"<?php } ?>>10</option>
            <option value="30" <?php if($sessions->viewPageNum == '30'){ ?>selected="selected"<?php } ?>>30</option>
            <option value="100" <?php if($sessions->viewPageNum == '100'){ ?>selected="selected"<?php } ?>>100</option>
        </select>
    </form> 			                              
</div>