<?php
if(!empty($this->view_datas[0]['meta_keywords'])) { $this->headMeta()->setName('keywords',$this->view_datas[0]['meta_keywords']);}
if(!empty($this->view_datas[0]['meta_desc'])) { $this->headMeta()->setName('description',$this->view_datas[0]['meta_desc']); }
if(!empty($this->view_datas[0]['tours_name'])) { $this->headTitle()->headTitle($this->view_datas[0]['tours_name'],'SET')->setSeparator(' - ')->headTitle($this->view_datas[0]['meta_title']); }

echo $this->headScript()->setFile($this->baseUrl().'/vendor/scripts/jtruncate/jquery.jtruncate.pack.js');
$version = Zend_Registry::get('version');  
$front_template = Zend_Registry::get('front_template');
$business_type_db = new Tours_Model_DbTable_BusinessType();
$cat_Info = new Tours_Model_DbTable_Category();
$mem_db = new Members_Model_DbTable_MemberList();
$state_db = new Tours_Model_DbTable_State();
$area_db = new Tours_Model_DbTable_Area();
$country_db = new Tours_Model_DbTable_Country();
$tours_db = new Tours_Model_DbTable_Tours();

$global_conf = Zend_Registry::get('global_conf');
$currency = new Zend_Currency($global_conf['default_locale']);
$review_helper = new Review_View_Helper_Review();

$maximum_rating_digit = $this->translator->translator('maximum_rating_digit');


function tours_truncate($phrase,$start_words, $max_words)
{
   $phrase_array = explode(' ',$phrase);
   if(count($phrase_array) > $max_words && $max_words > 0)
	  $phrase = implode(' ',array_slice($phrase_array, $start_words, $max_words)).'...';  
   return $phrase;
}
?>
<script type="text/javascript">

$(document).ready(function() {

		calender('check_in_book', 'check_out_book');
		calender('check_out_book', 'check_in_book');
			text_truncate();
		$('a.toggle_desc').click(function() {
			var self = this;
			var id = $(self).attr('rel');			
			$('#room_type_desc'+id).slideToggle(500,function () { });
				return false;
		  });
		  
		  $('#book_button').click(function() {
		  	/*if($('#check_in_book').val() == '' || $('#check_out_book').val() == '' )
			{
				var msg = "<?php //echo $this->translator->translator('tours_check_in_out_selected_err'); ?>";
				openMsgDialog(msg);
				$('#check_in_book').focus();
			}
			else
			{	
				if($('#check_status').val() == '')
				{
					var msg = "<?php //echo $this->translator->translator('tours_check_availability_do'); ?>";
					openMsgDialog(msg);
				}
				else
				{	
					if($('#check_status').val() == '1')
					{
						
					}
					else
					{
						var msg = "<?php //echo $this->translator->translator('tours_check_availability_err'); ?>";
						openMsgDialog(msg);
					}
				}
			}*/
			$('#formBook').submit();
		  });	
		  
		  $('#check_availability_btn').click(function() {
		  	if($('#check_in_book').val() == '' || $('#check_out_book').val() == '' )
			{
				var msg = "<?php echo $this->translator->translator('tours_check_in_out_selected_err'); ?>";
				openMsgDialog(msg);
				$('#check_in_book').focus();
			}
			else
			{					
				$.ajax({
					url: "<?php echo $this->url(array('module' => 'Tours','controller' =>'book', 'action' => 'availability' ),'adminrout',true); ?>",
						type: 'POST',
						data: { tours_id : $('#tours_id').val(), check_in : $('#check_in_book').val(), check_out : $('#check_out_book').val()},
						beforeSend: function(){
								$('#check_result').html('<img src="application/layouts/scripts/<?php echo $front_template['theme_folder']; ?>/images/loader/mod-loader.gif" width="15" border="0" />');							
							 },
						success: function(response){
							//alert(response);
							var json_arr = eval("("+response+")");
							$('#check_result').html('');
							if(json_arr.status == 'ok')
							{
								$('#check_result').html(json_arr.msg);	
								$('#check_status').val(json_arr.check_status);	
							}							
							else
							{
								openMsgDialog(json_arr.msg);
							}
						},
						error: function(xhr, status, error){	
							$('#check_result').html('');						
							var msg = "Error! " + xhr.status + " " + error;							
							openMsgDialog(msg);
						}
				});
			}
		  });	
		
			
});

function openMsgDialog(msg)
{
$('#dialog_container').html(msg).dialog({
			autoOpen: true,
			modal: false,
			show: 'explode',
			resizable: true,				
			buttons: [{ text: "<?php echo html_entity_decode($this->translator->translator('common_ok'), ENT_QUOTES, 'UTF-8'); ?>", click: function() { $(this).dialog('option', 'hide', 'explode').dialog("close"); } } ],
			open: function(event, ui)
				 {
					setTimeout(function() 
					{									
						if($('#' + event.target.id).dialog('isOpen'))
						{
							$('#' + event.target.id).dialog('option', 'hide', 'explode').dialog('close');										
						}
					}, 10000);
				  }
		});
}

function stripslashes(str) 
{
	str=str.replace(/\\'/g,'\'');
	str=str.replace(/\\"/g,'"');
	str=str.replace(/\\0/g,'\0');
	str=str.replace(/\\\\/g,'\\');
	return str;
}

function text_truncate()
{
	$('span.jTruncate').jTruncate({  
		length:  90,  
		minTrail: 0,  
		moreText: "[<?php echo html_entity_decode($this->translator->translator('common_see_all'), ENT_QUOTES, "UTF-8"); ?>]",  
		lessText: "[<?php echo html_entity_decode($this->translator->translator('common_hide'), ENT_QUOTES, "UTF-8"); ?>]",  
		ellipsisText: "",  
		moreAni: "fast",  
		lessAni: 2000  
	});
}

function calender(id,second_id)
{
	$("#"+id).datepicker({
		showOn: 'button',
		buttonImage: 'application/layouts/scripts/<?php echo $front_template['theme_folder']; ?>/images/mod_tour_img/calendar.png',
		buttonImageOnly: true,		
		monthNamesShort:<?php echo $this->translator->translator("common_calender_monthNamesShort"); ?>,
		monthNames:<?php echo $this->translator->translator("common_calender_monthNames"); ?>,
		dayNamesMin:<?php echo $this->translator->translator("common_calender_dayNamesMin"); ?>,
		showAnim: 'slide',
		buttonText: 'Calender',
		dateFormat:'yy-mm-dd',
		autoSize:false,
		showButtonPanel:false,
		changeMonth: true,
		changeYear: true,
		onSelect: function(dateText, inst) {
			$('#check_status').val('');
			$('#check_result').html('');
			var id_type_arr = id.split('_');
			var true_id = 		id_type_arr[0] + id_type_arr[1];			
			var currentTime = new Date();
			var currentDay = (currentTime.getDate() < 10) ? '0' + currentTime.getDate() : currentTime.getDate();
			var currentMonth = ((currentTime.getMonth() + 1) < 10) ? '0' + (currentTime.getMonth() + 1) : (currentTime.getMonth() + 1);
			var today = currentTime.getFullYear() + '-' + currentMonth + '-' + currentDay;				
			if(true_id == 'checkin')
			{
				if( (dateText != '') && ( (toTimestamp(dateText) >= toTimestamp($('#'+second_id).val())) || (toTimestamp(dateText) < toTimestamp(today)) )  )
				{					
					var msg = "<?php echo $this->translator->translator('tours_front_page_checkin_date_err'); ?>";
					openMsgDialog(msg);					
					$('#'+id).val('');
				}
				if(!is_30dayDiff(dateText, $('#'+second_id).val()))
				{
					var msg = "<?php echo $this->translator->translator('tours_front_page_date_difference_err'); ?>";
					openMsgDialog(msg);					
					$('#'+id).val('');
				}
			}
			else if(true_id == 'checkout')
			{
				if( (dateText != '') && ( (toTimestamp(dateText) <= toTimestamp($('#'+second_id).val())) || (toTimestamp(dateText) < toTimestamp(today)) )  )
				{
					var msg = "<?php echo $this->translator->translator('tours_front_page_checkout_date_err'); ?>";
					openMsgDialog(msg);
					$('#'+id).val('');
				}
				if(!is_30dayDiff($('#'+second_id).val(), dateText))
				{
					var msg = "<?php echo $this->translator->translator('tours_front_page_date_difference_err'); ?>";
					openMsgDialog(msg);					
					$('#'+id).val('');
				}
			}
		}
	});
	$("img[class='ui-datepicker-trigger']").each(function(){ 
			$(this).attr('style', '');
		 });
}

function is_30dayDiff(checkin, checkout)
{
	if(checkin != '' && checkout != '')
	{
		var checkin_arr = checkin.split('-');
		var checkout_arr = checkout.split('-');
		var checkin_obj =new Date(checkin_arr[0], (checkin_arr[1] - 1), checkin_arr[2]);
		var checkout_obj =new Date(checkout_arr[0], (checkout_arr[1] - 1), checkout_arr[2]);		
		var one_day=1000*60*60*24;
		var diff = Math.ceil((checkout_obj.getTime()-checkin_obj.getTime())/(one_day));	
		if(diff > 30)
		{
			return false;
		}	
	}
	return true;	
}

function toTimestamp(strDate){
	 var datum = Date.parse(strDate);
	 return datum/1000;
}

</script>

<?php 
$allow_obj = new Tours_View_Helper_Allow();
if (!$allow_obj->allowRule('view',null,null,$this->group_datas['role_id'])) : ?>
	<?php echo $this->translator->translator('Member_Access_deny_desc'); ?>
<?php else : ?>

<div class="mod mod-booking">
	<div class="booking-icon">
        <h1><?php echo $this->translator->translator('tours_front_page_booking_change'); ?></h1>
    </div>   
    
    <div class="social">
      	<!-- AddThis Button BEGIN -->
        <div class="addthis_toolbox addthis_default_style">
        <a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
        <a class="addthis_button_tweet"></a>
        <a class="addthis_button_google_plusone" g:plusone:size="medium"></a>
        <a class="addthis_counter addthis_pill_style"></a>
        </div>
        <script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=xa-4e89660c7edb029a"></script>
    	<!-- AddThis Button END -->
    </div>
	
    <div class="clear"></div>

 	<form id="formBook" name="formBook" method="post" action="<?php echo $this->url( array('module' => 'Tours', 'controller' => 'book', 'action'     => 'invoice' ), 'Tours-Invoice',    true); ?>">
    
	<?php  
	if($global_conf['payment_system'] != 'On')
	{
		echo '<div class="infoMess">'.$this->translator->translator('common_payment_system_disable').'</div>';	
	}
	else
	{
      if($this->view_datas)
      {
  	?>
  
  	<div>
    	<?php
			foreach($this->view_datas as $entry)
			{
				$tours_image_val_arr = explode(',',$entry['tours_image']);
				$tours_image_no = count($tours_image_val_arr);
				if($this->escape($entry['traveler_photos']))
				{ 
					$thumb_image = 'data/frontImages/tours/tours_image/'.$this->escape($entry['traveler_photos']); 
				}
				else
				{ 
					if($this->escape($entry['tours_image']))
					{							
						$thumb_image = 'data/frontImages/tours/tours_image/'.$this->escape($tours_image_val_arr[0]); 
					}
					else
					{
						$thumb_image = 'application/layouts/scripts/'.$front_template['theme_folder'].'/images/mod_tour_img/no_image.png'; 
					}		
				}
				if($this->group_datas['file_thumb_width'] && ($this->group_datas['file_thumb_resize_func'] == 'resizeToWidth' || $this->group_datas['file_thumb_resize_func'] == 'resize'))
				{ 
					$width = 'width="'.$this->escape($this->group_datas['file_thumb_width']).'"'; 
				}
				else
				{
					$width = '';
				} 
				if($this->group_datas['file_thumb_height'] && ($this->group_datas['file_thumb_resize_func'] == 'resizeToHeight' || $this->group_datas['file_thumb_resize_func'] == 'resize'))
				{ 
					$height = 'height="'.$this->escape($this->group_datas['file_thumb_height']).'"'; 
				} 
				else
				{
					$height = '';
				}
				
				$featured_class = ($entry['featured'] == '1') ? 'products-featured' : '';

			?>
           
            <table id="sortTable" width="100%" border="0" align="center" cellpadding="0" cellspacing="0" >			
				<tbody>
					<tr>
						<td>
                        	<div class="products-list">
                                <!-- list Header Start -->
                                <div class="list-header">
                                	<div class="header-row">
                                        <div class="header-left">
                                            <span class="title-small"><?php echo tours_truncate($this->escape($entry['tours_name']),0 ,7); ?></span><br />
                                            <span class="info">
                                            <?php 
                                                if(!empty($entry['duration'])){ echo (int)$this->escape($entry['duration']).' '. $this->translator->translator('tours_duration'); } 
                                                if(!empty($entry['num_of_days'])){ echo ' / ' . (int)$this->escape($entry['num_of_days']).' '.$this->translator->translator('tours_num_of_days' ); } 
                                                if(!empty($entry['num_of_nights'])){ echo  ' / ' . (int)$this->escape($entry['num_of_nights']).' '.$this->translator->translator('tours_num_of_nights'); }
                                            ?>
                                            </span>  
                                        </div>
                                    
                                        <div class="header-middle">
                                            <span class="products-mark"><?php $type_infos = $business_type_db->getBusinessTypeInfo($entry['tours_type']); echo $this->translator->translator('tours_front_page_tours_type'); ?></span>&nbsp;<span class="products-type"><?php echo $this->escape($type_infos['business_type']); ?></span>
                                        </div>
                                        
                                        <div class="header-right">                                                
                                            <?php 
                                                if(!empty($this->group_datas['review_id'])){ 
                                                $review_no = $review_helper->getNumOfReviews($entry['id'], $this->escape($this->group_datas['review_id']));
                                            ?><span class="products-write-review"><a href="<?php echo $this->url( array('module' => 'Review','controller' => 'frontend', 'action'     => 'write', 'group_id' => $this->escape($this->group_datas['review_id']), Eicra_File_Constants::ITEM_ID => $entry['id'] ), 'Review-Write/:group_id/:item_id',    true); ?>"><?php echo $this->translator->translator('common_write_review'); ?></a></span> &nbsp; <span class="products-review-count"><a href="<?php echo $this->url(array('module' => 'Tours','controller' =>'frontend', 'action' => 'details','tours_title' => $this->escape($entry['tours_title']),'tab' => 10 ),'Tours-details/:tours_title/:tab',true); ?>"><?php echo $this->translator->translator('common_review_no',htmlentities($review_no)); ?></a></span> <?php } ?>
                                        </div>
                                    </div>
                                </div>
                                <!-- list Header End -->
                                
                                <!-- list Body Start --> 
                                    <div class="body-container <?php echo $featured_class; ?>">
                                         	<div class="left-content">
                                                <div class="img-wrapper">
                                                    <a href="<?php echo $this->url(array('module' => 'Tours','controller' =>'frontend', 'action' => 'details',tours_title => $this->escape($entry['tours_title']) ),'Tours-details/:tours_title',true); ?>" class="preview" link="<?php echo $thumb_image; ?>" title="<?php echo $this->escape($entry['tours_name']); ?>" width="500"><img src="<?php echo $thumb_image; ?>" <?php echo $width; ?> <?php echo $height; ?> border="0" class="thumb"/></a>
                                                    <div class="photo-count-container">
                                                        <div class="photo-count">
                                                            <a href="<?php echo $this->url(array('module' => 'Tours','controller' =>'frontend', 'action' => 'details',tours_title => $this->escape($entry['tours_title']),'tab' => 1 ),'Tours-details/:tours_title/:tab',true); ?>" title="<?php echo $this->translator->translator('tours_front_page_tours_click_view_listing'); ?>"><?php echo $this->translator->translator('tours_front_page_tours_photo_no',$tours_image_no); ?></a>
                                                        </div>
                                                    </div>                                            
                                         	</div>
                                                
                                            <h2>
                                                <a href="<?php echo $this->url(array('module' => 'Tours','controller' =>'frontend', 'action' => 'details',tours_title => $this->escape($entry['tours_title']) ),'Tours-details/:tours_title',true); ?>" class="preview" link="" title="<?php echo $this->escape($entry['tours_name']); ?>"><?php echo tours_truncate($this->escape($entry['tours_name']), 0, 6); ?></a>
                                            </h2>
                                              
                                            <div class="products-stars">
                                             <?php
                                                $hotel_rating = (int) $entry['rating'];
                                                                                             
                                                for($i = 1; $i < $maximum_rating_digit ; $i++)
                                                {
                                                    $print_rating = ($i <= $this->escape($entry['rating'])) ? "<img src='application/layouts/scripts/".$front_template['theme_folder']."/images/mod_tour_img/star-active.png' border='0' />" : "<img src='application/layouts/scripts/".$front_template['theme_folder']."/images/mod_tour_img/star-inactive.png' border='0' />";
                                                    
                                                    echo $print_rating.'&nbsp;';
                                                }
                                                ?>     
                                            </div>
                                                
                                            <div class="products-desc">
                                                <p><?php echo $this->tours_Form->starting_city->getAttrib('font_end_label'); ?></p> <?php echo strip_tags($entry['starting_city']); ?><br />
                                                <p><?php echo $this->tours_Form->ending_city->getAttrib('font_end_label'); ?></p> <?php echo strip_tags($entry['ending_city']); ?><br />
                                                
                                                <p><?php echo $this->tours_Form->scheduled_on->getAttrib('font_end_label'); ?></p> <?php echo strip_tags($entry['scheduled_on']); ?><br />
                                                <p><?php echo $this->tours_Form->tour_highlights->getAttrib('font_end_label'); ?></p> <span class="jTruncate"><?php echo strip_tags($entry['tour_highlights']); ?></span><br />
                                                <p><?php echo $this->tours_Form->tours_desc->getAttrib('font_end_label'); ?></p> <span class="jTruncate"><?php echo strip_tags($entry['tours_desc']); ?></span>
                                            </div>
                                     </div>
                                         
                                     <div class="right-content">
                                        <span class="products-price"><?php  if(!empty($entry['tours_price'])){ echo $this->translator->translator('tours_front_page_price').$this->currency->getSymbol().''.$this->price($this->escape($entry['tours_price'])); } ?></span>
                                        <ul class="products-options">	
                                            <?php 
                                                $feature_facilities_arr = explode(',', $entry['inclusions']); 
                                                if (in_array ('Complimentary Breakfast' , $feature_facilities_arr)){
                                            ?>	
                                            <li class="breakfast"><?php echo $this->translator->translator('tours_front_page_list_allow_breakfast'); ?></li>
                                            <?php }?>
                                            
                                            <?php 
                                                if (in_array ('Cab Facilities' , $feature_facilities_arr)){
                                            ?>	
                                            
                                            <li class="cab"><?php echo $this->translator->translator('tours_front_page_list_cab_availability'); ?></li>
    
                                            <?php }
                                                   if (in_array ('Guides / Assistance' , $feature_facilities_arr)){
                                            ?>
                                            
                                            <li class="guide"><?php echo $this->translator->translator('tours_front_page_list_assist_allow'); ?></li>
    
                                            <?php
                                                }
                                                   
                                                if (in_array ('Snacks / Drinks' , $feature_facilities_arr)){
                                            ?>
                                            
                                            <li class="snacks"><?php echo $this->translator->translator('tours_front_page_list_hot_snacks_availability'); ?></li>
                                            <?php } ?>
                                        </ul>                              
                                     </div> 
                                </div>
                                <!-- list Body End -->
                            
                                <!-- list footer start -->
                                <div class="list-footer">
                                    <div class="footer-left">
                                        <a href="<?php echo $this->url(array('module' => 'Tours','controller' =>'frontend', 'action' => 'details',tours_title => $this->escape($entry['tours_title']),'tab' => 0 ),'Tours-details/:tours_title/:tab',true); ?>"><?php echo $this->translator->translator('tours_front_page_tours_view_details'); ?></a> | 
                                            <a href="<?php echo $this->url(array('module' => 'Tours','controller' =>'frontend', 'action' => 'details',tours_title => $this->escape($entry['tours_title']),'tab' => 5 ),'Tours-details/:tours_title/:tab',true); ?>"><?php echo $this->translator->translator('tours_front_page_itinerary'); ?></a>  | 
                                            <a href="<?php echo $this->url(array('module' => 'Tours','controller' =>'frontend', 'action' => 'details',tours_title => $this->escape($entry['tours_title']),'tab' => 1 ),'Tours-details/:tours_title/:tab',true); ?>"><?php echo $this->translator->translator('tours_front_page_tours_photo'); ?></a> |
                                            <a href="<?php echo $this->url(array('module' => 'Tours','controller' =>'frontend', 'action' => 'details',tours_title => $this->escape($entry['tours_title']),'tab' => 6 ),'Tours-details/:tours_title/:tab',true); ?>"><?php echo ucfirst(strtolower($this->translator->translator('tours_front_page_Title_payment_process'))); ?></a>  | 
                                            <a href="<?php echo $this->url(array('module' => 'Tours','controller' =>'frontend', 'action' => 'details',tours_title => $this->escape($entry['tours_title']),'tab' => 3 ),'Tours-details/:tours_title/:tab',true); ?>"><?php echo $this->translator->translator('tours_front_page_tours_facilities_features'); ?></a>
                                    </div>
                                
                                    <div class="footer-right">
                                        <span class="products-details-btn"><a href="<?php echo $this->url(array('module' => 'Tours','controller' =>'frontend', 'action' => 'details','tours_title' => $this->escape($entry['tours_title']) ),'Tours-details/:tours_title',true); ?>"><?php echo $this->translator->translator('tours_front_page_tours_more'); ?></a></span>
                                    </div>
                                </div>
                                <!-- list footer end --> 
                            </div>
                            <?php
							}
							?>	
                        </td>
					</tr>
              	</tbody>
         	</table>
	</div>  
	<?php
        }	
	}
    ?>
	<div class="btn-container"><input type="hidden" name="tours_id" id="tours_id" value="<?php echo $this->escape($entry['id']); ?>" /><input type="button" name="button" id="book_button" value="<?php echo $this->translator->translator('tours_invoice_book_now'); ?>" /></div>
</form>
</div>
<div>&nbsp;</div>
<div id="dialog_container" title="<?php echo $this->translator->translator('common_dialog_msg',$this->translator->translator('tours_front_page_dialog_name')); ?>"></div>
<?php endif; ?>	