<div id="container">
<?php  if (!$this->allow('list')) : ?>
	<div class="grid_12 t_a_bottom">
		<?php echo $this->translator->translator('Member_Access_deny_desc'); ?>
	</div>
<?php 
	else :  
$version = Zend_Registry::get('version');	
echo $this->headScript()->setFile($this->baseUrl().'/js/jquery/table-sorter/jquery.dataTables.js');

$check_num_flight = new Flight_View_Helper_Airlines();	


function type_truncate($phrase,$start_words, $max_words)
{
   $phrase_array = explode(' ',$phrase);
   if(count($phrase_array) > $max_words && $max_words > 0)
	  $phrase = implode(' ',array_slice($phrase_array, $start_words, $max_words)).'...';  
   return $phrase;
}

$mem_db = new Members_Model_DbTable_MemberList();
?>
<script type="text/javascript">
$(document).ready(function() {

	floatingbar('#floatingbar',"#button_top_bar",null);
	/****************************Sorting Table Start*********************/
	var oTable = $("#sortTable").dataTable({
				"bPaginate": false,
				"bLengthChange": true,
				"bSearchable": true,
				"bFilter": true,
				"bSort": true,
				"bInfo": false,
				"bAutoWidth": true,
				"bProcessing": false,
				"bSortClasses": true,
				"bStateSave": false,
				"bServerSide": false,
				"aaSorting": [[ 1, "asc" ]],				
				"aoColumnDefs": [ 
						{ "bSortable": false, "bSortClasses": false,  "aTargets": [ 0 ] }
					],
				"oLanguage" : { "sSearch": "<?php echo $this->translator->translator('jquery_filter'); ?>" }
			}); 	
	
	$('td', oTable.fnGetNodes()).hover( function() {		
		$(this).parents("tr:first").children('td').addClass( 'highlighted' );
	}, function() {
		$('td.highlighted').removeClass('highlighted');
	} );
	lastClassAdd(oTable);
	/****************************Sorting Table End*********************/
			
		function openLoaderDialog()
		{
			$('#dialog_loader').dialog({
						autoOpen: true,
						modal: true,
						show: 'fade',
						resizable: 'false',				
						open: function(event, ui)
							 {
								$("#progressbar").progressbar({
									value:100
					
								});							
							  }
					});
		}
		
		function closeLoaderDialog()
		{
			$('#dialog_loader').dialog('option','hide','explode').dialog('close');
		}
			
	
	$('input.checkAll_btn').click(function() {
		var self = this;
		if($(self).is(':checked'))
		{		
			$('input.check_btn').prop('checked', true);
		}
		else
		{
			$('input.check_btn').attr('checked', false);
		}
		$('input.check_btn:disabled').attr('checked', false);
	});
	
	$('a.delete_all').click(function() {
		var self = this;
		if($('input.check_btn:checked').length > 0)
		{
			$("#dialog-confirm").html("<?php echo addslashes($this->translator->translator('flight_list_delete_confirm')); ?>").dialog({
					resizable: true,
					width:400,
					height:'auto',
					modal: true,
					show: 'explode',
					hide: 'explode',
					buttons: [{
								text :'<?php echo html_entity_decode($this->translator->translator("common_delete_selected"), ENT_QUOTES, "UTF-8"); ?>', 
								click: function() {
										deleteAll(self);
										$(this).dialog('close');
									}
							},
							{
								text :'<?php echo html_entity_decode($this->translator->translator("common_cancel"), ENT_QUOTES, "UTF-8"); ?>',
								click: function() {
										$(this).dialog('close');
									}
							}]
				});		
		}
		else
		{
			var msg = "<?php echo $this->translator->translator('flight_selected_err'); ?>";
			openMsgDialog(msg);
		}
	});
	
	allFunctions();
});



function openMsgDialog(msg)
{
	$('#dialog_container').html(msg).dialog({
		autoOpen: true,
		modal: true,
		show: 'explode',
		resizable: true,				
		buttons: [{ text: "<?php echo html_entity_decode($this->translator->translator('common_ok'), ENT_QUOTES, 'UTF-8'); ?>", click: function() { $(this).dialog('option', 'hide', 'explode').dialog("close"); } } ],
		open: function(event, ui)
			 {
				setTimeout(function() 
				{									
					if($('#' + event.target.id).dialog('isOpen'))
					{
						$('#' + event.target.id).dialog('option', 'hide', 'explode').dialog('close');										
					}
				}, 10000);
			  }
	});
}

/* Get the rows which are currently selected */
function fnGetSelected( oTableLocal )
{
	var aReturn = new Array();
	var aTrs = oTableLocal.fnGetNodes();
	
	for ( var i=0 ; i<aTrs.length ; i++ )
	{
		if ( $(aTrs[i]).hasClass('row_selected') )
		{
			aReturn.push( aTrs[i] );
		}
	}
	return aReturn;
}

function checkNonDeletedId(id,id_arr)
{
	var tmp = false;
	for(var i = 0;i < id_arr.length;i++)
	{
		if(id_arr[i] == id)
		{
			tmp = true;
			break;
		}
	}
	return tmp;
}

function deleteThis(self)
{
	var arr = $(self).attr('rel').split('_');
	$.ajax({
		 url: "<?php echo $this->url( array('module'=> 'Flight', 'controller' => 'airlines', 'action'     => 'delete' ), 'adminrout',    true) ?>",
		 type: 'POST',
		 data: { id: arr[0]},
		 beforeSend: function(){
				$(self).html('<img src="application/modules/Administrator/layouts/scripts/images/loader/ajax_loader.gif" height="16" border="0" />');
			 },
		 success: function(response) 
		 {
			//alert(response);
			var json_arr = eval("("+response+")");
			if(json_arr.status == 'ok')
			{
				$(self).parents("li:first").parents("ul:first").parents("td:first").parents("tr:first").addClass('row_selected');
				var oTables = $('#sortTable').dataTable();
				var anSelected = fnGetSelected( oTables );
				oTables.fnDeleteRow( anSelected[0] );
				lastClassAdd(oTables);
			}
			else
			{
				openMsgDialog(json_arr.msg);
				$(self).html('<img src="application/modules/Administrator/layouts/scripts/images/tools/delete.png" title="<?php echo $this->translator->translator("common_delete_title"); ?>" border="0" />');
			}
		 },
		error: function(xhr, status, error){				
			var msg = "Error! " + xhr.status + " " + error;
			openMsgDialog(msg);
		}
	});
}

function deleteAll(self)
{
	var id_str = '';
	for(var i=0;i < $('input.check_btn:checked').length;i++)
	{
		if(i == 0)
		{
			 id_str += $('input.check_btn:checked:eq('+i+')').val();
		}
		else
		{
			id_str += ','+$('input.check_btn:checked:eq('+i+')').val();
		}
	}
	
	$.ajax({
			url: "<?php echo $this->url( array('module'=> 'Flight', 'controller' => 'airlines', 'action'     => 'deleteall' ), 'adminrout',    true) ?>",
			type: 'POST',
			data: { id_st: id_str},
			beforeSend: function(){
				$(self).html('<span class="icon loader"></span>');
			 },
			success: function(response) 
			{
				//alert(response);
				var json_arr = eval("("+response+")");
				if(json_arr.status == 'ok')
				{
					for(var i= ($('input.check_btn:checked').length-1);i >= 0;i--)
					{	
						if(!checkNonDeletedId($('input.check_btn:checked:eq('+i+')').val(),json_arr.non_del_arr))
						{							
							$('input.check_btn:checked:eq('+i+')').parents("td:first").parents("tr:first").addClass('row_selected');							
						var oTabled = $('#sortTable').dataTable();
						var anSelected = fnGetSelected( oTabled );
						oTabled.fnDeleteRow( anSelected[0] );								
						}
					}
					var oTabled = $('#sortTable').dataTable();
					var anSelected = fnGetSelected( oTabled );
					for(var k = 0; k < anSelected.length; k++)
					{
						oTabled.fnDeleteRow( anSelected[k] );
					}
					lastClassAdd(oTabled);
				}
				else
				{							
					openMsgDialog(json_arr.msg);
				}	
				$(self).html('<span class="icon delete"><?php echo html_entity_decode($this->translator->translator("common_delete_selected"), ENT_QUOTES, "UTF-8"); ?></span>');
			},
			error: function(xhr, status, error){				
				var msg = "Error! " + xhr.status + " " + error ;
				openMsgDialog(msg);
			}
	});	
}
		
function allFunctions()
{
		imageThumbnil();
		$('a.delete_btn').unbind('click');	
		$('a.delete_btn').click(function() {
			var self = this;
			$("#dialog-confirm").html("<?php echo addslashes($this->translator->translator('flight_list_delete_confirm')); ?>").dialog({
				resizable: true,
				width:400,
				height:'auto',
				modal: true,
				show: 'explode',
				hide: 'explode',
				buttons: [{
							text :'<?php echo html_entity_decode($this->translator->translator("common_delete_selected"), ENT_QUOTES, "UTF-8"); ?>', 
							click: function() {
									deleteThis(self);
									$(this).dialog('close');
								}
						},
						{
							text :'<?php echo html_entity_decode($this->translator->translator("common_cancel"), ENT_QUOTES, "UTF-8"); ?>',
							click: function() {
									$(this).dialog('close');
								}
						}]
			});
						
		});		
}

/************************************************IMAGE THUMBNIL************************************************/
function imageThumbnil()
{	
	$("span.thumb").hover(function() {
		$(this).css({'z-index' : '10'}); /*Add a higher z-index value so this image stays on top*/ 
		$(this).find('img').addClass("hover").stop() /* Add class of "hover", then stop animation queue buildup*/
			.animate({
				marginTop: '-110px', /* The next 4 lines will vertically align this image */ 
				marginLeft: '-110px',
				top: '50%',
				left: '50%',
				width: '174px', /* Set new width */
				height: '174px', /* Set new height */
				padding: '20px'
			}, 200); /* this value of "200" is the speed of how fast/slow this hover animates */
	
		} , function() {
		$(this).css({'z-index' : '0'}); /* Set z-index back to 0 */
		$(this).find('img').removeClass("hover").stop()  /* Remove the "hover" class , then stop animation queue buildup*/
			.animate({
				marginTop: '-4px', /* Set alignment back to default */
				marginLeft: '0',
				top: '0',
				left: '0',
				width: '30px', /* Set width back to default */
				height: '20px', /* Set height back to default */
				padding: '5px'
			}, 400);
	});
}
</script>
<div class="title-container">
    <div class="airlines"><h1><?php echo $this->translator->translator('flight_airlines_list_page_name'); ?></h1></div>
    <div class="button-container">
        <?php if ($this->allow('add','airlines','Flight')) : ?>
        <span class="button  ui-widget-content-1"><a href="<?php echo $this->url( array('module' => 'Flight','controller' => 'airlines', 'action'     => 'add' ), 'adminrout',    true) ?>" ><span class="icon add"><?php echo $this->translator->translator('common_add'); ?></span></a></span>
        <?php endif; ?>
        <?php if ($this->allow('delete','airlines','Flight')) : ?>
        <span class="button  ui-widget-content-1"><a href="javascript: void(0);" class="delete_all"><span class="icon delete"><?php echo html_entity_decode($this->translator->translator("common_delete_selected"), ENT_QUOTES, "UTF-8"); ?></span></a></span>
        <?php endif; ?>
	</div>
</div>
<div id="button_top_bar"></div>
<div class="content-container">
	<div id="sidebar-inner">
    	<?php echo $this->partial('nav_menu.phtml');  ?>
    </div>
    
    
    
    <div id="content-inner">
    	<div id="topPagination" class="pagination">
        	<?php echo $this->paginationControl($this->datas, 'Sliding', 'top_pagination.phtml'); ?>
        </div>
        
        <div class="chart">
			<div class="data-table">
            	<table id="sortTable" width="100%" align="center" cellpadding="0" cellspacing="0">
                	<thead>
                    	<tr>
                   		  	<th width="2%" class="center"><input type="checkbox" name="checkAll" id="checkAll" class="checkAll_btn" /></th>
                     		<th width="5%"><?php echo $this->translator->translator('common_id'); ?></th>
                   		  	<th width="6%"><?php echo $this->translator->translator('flight_airlines_list_thumb'); ?> </th>
                      		<th width="23%"><?php echo $this->translator->translator('common_entry_by'); ?> </th>
                   		  	<th width="28%"><?php echo $this->translator->translator('flight_airlines_list_airlines_name'); ?> </th>
                      		<th width="11%"><?php echo $this->translator->translator('flight_airlines_list_code'); ?> </th>
                      		<th width="14%"><?php echo $this->translator->translator('flight_airlines_list_entry_date'); ?> </th>
                      		<th width="11%"><?php echo $this->translator->translator('common_action'); ?></th>
                    	</tr>
                 	</thead>
                    <tbody>
                    <?php 	                                       
                    $j = 1;
                    foreach ($this->datas as $entry): 
                        if($j % 2 == 0)
                        {
                            $onmouseout = "this.bgColor='#FFFFFF';";
                            $background = '#FFFFFF';
                        }
                        else
                        {
                            $onmouseout = "this.bgColor='#F7F7F7';";
                            $background = '#F7F7F7';
                        }
                    ?>
                   	<tr bgcolor="<?php echo $background; ?>" onmouseover="this.bgColor='#FCF5DD';" onmouseout="<?php echo $onmouseout; ?>">
                   		<td class="center checkbox"><?php  $disabled = ($check_num_flight->getNumOfFlight($entry->id) > '0') ? 'disabled="disabled"' : ''; ?><input type="checkbox" name="checkbtn" id="checkbtn" <?php echo $disabled; ?> value="<?php echo $this->escape($entry->id); ?>" class="check_btn" /></td>
                      	<td class="center"><?php echo $this->escape($entry->id); ?></td>
                      	<td class="center"><?php if($entry->primary_image){ ?><div class="thumb"><img src="data/frontImages/flight/airlines/<?php echo $this->escape($entry->primary_image); ?>" width="30" height="20" /></span><?php } ?></td>
                      	<td>
						<?php 	
							if(!empty($entry->entry_by))
							{											  					 
									$mem_info = $mem_db->getMemberInfo($this->escape($entry->entry_by));
									echo '<span>'.$this->escape($mem_info['username']).'</span>';
							}															 
                       	?>
                        </td>												  
                      	<td><?php  echo $this->escape($entry->airlines_name);?></td>
                      	<td class="center"><?php  echo $this->escape($entry->airlines_code);?></td>
                      	<td class="center"><?php  echo $this->escape($entry->airlines_date);?></td>											  
                      	<td class="tools-list">
                        	<ul>
                                <?php if ($this->allow('edit','airlines','Flight')) : ?>
                                <li><a href="<?php echo $this->url( array('module' => 'Flight','controller' => 'airlines', 'action'     => 'edit', 'id' => $this->escape($entry->id)), 'adminrout',    true) ?>"><img src="application/modules/Administrator/layouts/scripts/images/tools/edit.png" title="<?php echo $this->translator->translator('common_edit_title'); ?>" alt="<?php echo $this->translator->translator('common_edit_title'); ?>"  border="0" /></a></li>
                                <?php endif; ?>
                     
                                <?php if ($this->allow('delete','airlines','Flight')) : ?>
                                <li><a href="javascript:void(0);" class="delete_btn"  rel="<?php echo $this->escape($entry->id); ?>"><img src="application/modules/Administrator/layouts/scripts/images/tools/delete.png" title="<?php echo $this->translator->translator('common_delete_title'); ?>" border="0" /></a></li>
                                <?php endif; ?>
							</ul>
						</td>
                    </tr>
                    <?php 													
                        $j++;
                        endforeach; 
                   	?>
                  	</tbody>
				</table>
            </div>
		</div>
        <div id="bottomPagination" class="pagination">
        	<?php echo $this->paginationControl($this->datas, 'Sliding', 'pagination.phtml'); ?>
        </div>
	</div>
</div>

<div id="floatingbar">
	<h1><?php echo $this->translator->translator('flight_airlines_list_page_name'); ?></h1>
    <div class="button-container">
        <?php if ($this->allow('add','airlines','Flight')) : ?>
        <span class="button  ui-widget-content-1"><a href="<?php echo $this->url( array('module' => 'Flight','controller' => 'airlines', 'action'     => 'add' ), 'adminrout',    true) ?>" ><span class="icon add"><?php echo $this->translator->translator('common_add'); ?></span></a></span>
        <?php endif; ?>
        <?php if ($this->allow('delete','airlines','Flight')) : ?>
        <span class="button  ui-widget-content-1"><a href="javascript: void(0);" class="delete_all"><span class="icon delete"><?php echo html_entity_decode($this->translator->translator("common_delete_selected"), ENT_QUOTES, "UTF-8"); ?></span></a></div>
        <?php endif; ?>
    </div>
</div>

<?php endif; ?>
<div id="dialog_container" title="<?php echo $this->translator->translator('common_dialog_msg',$this->translator->translator('flight_airlines_list_page_name')); ?>"></div>
<div id="dialog-confirm" title="<?php echo $this->translator->translator('common_confirmation', $this->translator->translator('common_delete')); ?>"></div>	
<div id="dialog_loader" style="display:none" title="<?php echo $this->translator->translator('common_processing_language'); ?>">
	<div id="progressbar" ></div>	
</div>
</div>