<?php
$this->headMeta()->setName('keywords',$this->translator->translator('flight_AirlineFlightSchedules_page_meta_keywords'));
$this->headMeta()->setName('description',$this->translator->translator('flight_AirlineFlightSchedules_page_meta_desc'));
$this->headTitle()->headTitle($this->translator->translator('flight_AirlineFlightSchedules_page_meta_title'),'SET');

echo $this->headScript()->setFile($this->baseUrl().'/js/jquery/table-sorter/jquery.dataTables.js');
echo $this->headScript()->setFile($this->baseUrl().'/vendor/scripts/jtruncate/jquery.jtruncate.pack.js');
echo $this->headLink()->setStylesheet($this->baseUrl().'/css/jqueryCSS/table-sorter/pagination_table.css');
$version = Zend_Registry::get('version');  
$front_template = Zend_Registry::get('front_template');
$global_conf = Zend_Registry::get('global_conf');
$currency = new Zend_Currency($global_conf['default_locale']);
?>
<script type="text/javascript">
$(document).ready(function() {

	checkSameData('flight_route_departure', 'flight_route_arrival', 0);	
		
		/****************************Sorting Table Start*********************/
		<?php if($this->result['status'] == 'ok'){ ?>
		var oTable = $("#sortTable").dataTable({
						"bPaginate": true,
						"aLengthMenu" : [ 2, 10, 25, 50, 100 ],
						"bDestroy":true,
						"bLengthChange": true,
						"bSearchable": true,
						"bFilter": true,
						"bSort": true,
						"bInfo": true,
						"sPaginationType": "full_numbers",
						"bAutoWidth": true,
						"bProcessing": false,
						"bSortClasses": true,
						"bStateSave": false,
						"bServerSide": false,
						"aaSorting": [[ 0, "asc" ]],
						"oLanguage" : { "sSearch": "<?php echo $this->translator->translator('jquery_filter'); ?>" }
					});	
				imageThumbnil();
		<?php }else{ ?>
			var oTable = $("#sortTable").dataTable({
						"bPaginate": false,
						"bDestroy":true,
						"bLengthChange": true,
						"bSearchable": false,
						"bFilter": false,
						"bSort": false,
						"bInfo": false,
						"bAutoWidth": true,
						"bProcessing": false,
						"bSortClasses": true,
						"bStateSave": false,
						"bServerSide": false,
						"aaSorting": [[ 0, "asc" ]],
						"oLanguage" : { "sSearch": "<?php echo $this->translator->translator('jquery_filter'); ?>" }
					});			
		<?php } ?>
		/****************************Sorting Table End*********************/	
		
		
		$('input.flight_search_btn').click(function(){
			var self = this;
			var formData = getFormData();
			if(checkRouteFieldValue())
			{
				$.ajax({
						 url: "<?php echo $this->url( array('module'=> 'Flight', 'controller' => 'frontend', 'action'     => 'airlineflightschedules' ), 'AirlineFlightSchedules',    true); ?>",
						 type: 'POST',
						 data: formData,
						 beforeSend: function(){				 	
							$('#loader_img').html('<div class="api-search-loader"><img src="application/layouts/scripts/<?php echo $front_template['theme_folder']; ?>/images/loader/ajax-loader.gif" border="0" height="31" />');
						 },
						 success: function(response) 
						 {
							//openMsgDialog(response);
							var json_arr = eval("("+response+")");
												
							if(json_arr.status == 'ok')
							{												
								putSearchResult(oTable,json_arr.result);											
							}
							else
							{
								oTable.fnClearTable();
								openMsgDialog(json_arr.msg);
							}
							$('#loader_img').html('');
						 },
						error: function(xhr, status, error){
							var msg = "Error! " + xhr.status + " " + error;
							openMsgDialog(msg);
						}				
				});
			}
		});
	
});

function getFormData()
{
	var fieldObj = {};
	var filename = '';
	var filevalue = '';
	$.each($('#formAirlineFlightSchedulesSearch').serializeArray(), function(i, field) {	
		if(field.name.match(/\[\]$/))
		{
			var filearr = field.name.split('[]');
			filename = filearr[0];
			filevalue = field.value;
		}
		else
		{
			filename 	= 	field.name;
			filevalue 	= 	field.value;
		}			
		fieldObj[filename] =  filevalue;			
	});
	return fieldObj;
}

function putSearchResult(oTable,search_result)
{ 	
	oTable.fnDestroy();
	oTable = $("#sortTable").dataTable({
				"bPaginate": true,
				"aLengthMenu" : [ 2, 10, 25, 50, 100 ],
				"bDestroy":true,
				"bLengthChange": true,
				"bSearchable": true,
				"bFilter": true,
				"bSort": true,
				"bInfo": true,
				"sPaginationType": "full_numbers",
				"bAutoWidth": true,
				"bProcessing": false,
				"bSortClasses": true,
				"bStateSave": false,
				"bServerSide": false,
				"aaSorting": [[ 0, "asc" ]],
				"oLanguage" : { "sSearch": "<?php echo $this->translator->translator('jquery_filter'); ?>" }
			});
	oTable.fnClearTable();
 	var route = '';
	var airline_logo = '';
	var airlines = '';
	var total_price = '';
	var total_price_value = '';
	var book_now = '<?php echo $this->translator->translator("flight_AirlineFlightSchedules_page_table_quote"); ?>';
	var filed_departuretime = '0000-00-00';
	var estimatedarrivaltime = '0000-00-00';
	var ident = '';
	for(var i =0; i < search_result.length; i++)
	{
		ident += '<br />'+search_result[i].ident;
		if(search_result[i].FlightInfoExResult)
		{
		     route = 		(search_result[i].FlightInfoExResult[0]) ? search_result[i].FlightInfoExResult[0].originName+', '+search_result[i].FlightInfoExResult[0].originCity+' --> '+search_result[i].FlightInfoExResult[0].destinationName+', '+search_result[i].FlightInfoExResult[0].destinationCity : '';
			 if(search_result[i].FlightInfoExResult[0])
			 {
				  filed_departuretime = (search_result[i].FlightInfoExResult[0].filed_departuretime) ? search_result[i].FlightInfoExResult[0].filed_departuretime : '0000-00-00';
				  estimatedarrivaltime       =		(search_result[i].FlightInfoExResult[0].estimatedarrivaltime) ? search_result[i].FlightInfoExResult[0].estimatedarrivaltime : '0000-00-00';
			 }
		}
		airlines = (search_result[i].airline_infos == null) ? '' : search_result[i].airline_infos.airlines;
		airline_logo = (search_result[i].airline_infos == null) ? search_result[i].airline_code : '<span class="thumbnail"><img src="data/frontImages/flight/airlines/'+search_result[i].airline_infos.airlines_pic+'" width="45" height="35" title="'+airlines+'" />';
		total_price = (search_result[i].airline_price_info == null) ? '0.00' : search_result[i].airline_price_info.total_price +search_result[i].airline_price_info.total_tax ;		
		total_price_value = '<span class="mod-title right">'+total_price+search_result[i].airline_price_info.currency_symbol+'</span>';
		if(total_price != '0.00'){ book_now = '<span class="products-book-btn"><a href="FlightBooking/'+i+'"><?php echo $this->translator->translator("flight_AirlineFlightSchedules_page_table_book"); ?></a></span>'; }else{ book_now = '<span class="products-details-btn"><a href="FlightQuoting/'+i+'"><?php echo $this->translator->translator("flight_AirlineFlightSchedules_page_table_quote"); ?></a></span>'; }
		oTable.fnAddData([
					airline_logo,					
					route,
					filed_departuretime,
					estimatedarrivaltime,
					total_price_value,
					book_now
					 ]);
	}
	//openMsgDialog(ident);
	var oSettings = oTable.fnSettings();
	var len = oSettings._iDisplayLength;
	i--;
	var totalPage = i/len;
	totalPage = Math.ceil(totalPage);
	for(var j = totalPage; j > 0; j-- )
	{
		oTable.fnPageChange( 'next' );			
		imageThumbnil();
	}
	oTable.fnPageChange( 'first' );	
	imageThumbnil();	
}

function removeError()
{		
	var filename = '';
	var filevalue = '';		
	$.each($('form').serializeArray(), function(i, field) {	
			if(field.name.match(/\[\]$/))
			{
				var filearr = field.name.split('[]');
				filename = filearr[0];					
			}
			else
			{
				filename 	= 	field.name;
			} 			
			$('input[name="'+filename+'[]"]').removeClass('ui-state-error');												
	});				
}

function checkRouteFieldValue()
{
	var check = true;
	var attr_id = '';
	var id_no_arr = [];
	removeError();
	
	for(var i=0; i < $('input.flight_route_departure').length; i++)
	{	
		attr_id  =	$('input.flight_route_departure:eq('+i+')').attr('id');
		id_no_arr = attr_id.split('flight_route_departure');
					
		if(jQuery.trim($('input.flight_route_departure:eq('+i+')').val()) == '' || jQuery.trim($('input.flight_route_arrival:eq('+i+')').val()) == '' || jQuery.trim($('input.flight_route_departure_date:eq('+i+')').val()) == '' || (jQuery.trim($('input.flight_route_arrival_date:eq('+i+')').val()) == '' ) )
		{			
			if(jQuery.trim($('input.flight_route_departure:eq('+i+')').val()) == '')
			{	
				$('input.flight_route_departure:eq('+i+')').addClass('ui-state-error');
			}
			
			if(jQuery.trim($('input.flight_route_arrival:eq('+i+')').val()) == '')
			{	
				$('input.flight_route_arrival:eq('+i+')').addClass('ui-state-error');
			}
			
			if(jQuery.trim($('input.flight_route_departure_date:eq('+i+')').val()) == '')
			{	
				$('input.flight_route_departure_date:eq('+i+')').addClass('ui-state-error');
			}
			
			if(jQuery.trim($('input.flight_route_arrival_date:eq('+i+')').val()) == '')
			{	
				$('input.flight_route_arrival_date:eq('+i+')').addClass('ui-state-error');
			}
				
			check = false;
		}
	}
	if(check == false)
	{
		msg = '<?php echo $this->translator->translator("flight_front_page_fields_empty"); ?>';
		openMsgDialog(msg);
	}
	return 	check;	
}

function checkSameData(from_id, to_id, id_no)
{
	$('#'+from_id+id_no).blur(function() {		
		if( ($('#'+from_id+id_no).val() != '') && ($('#'+from_id+id_no).val() == $('#'+to_id+id_no).val()) )
		{
			var msg = "<?php echo $this->translator->translator('flight_route_same_err'); ?>";
			openMsgDialog(msg);
			$('#'+from_id+id_no).val('');
			$('#'+from_id+id_no).focus();
		}
	});
	
	$('#'+to_id+id_no).blur(function() {		
		if( ($('#'+to_id+id_no).val() != '') && ($('#'+from_id+id_no).val() == $('#'+to_id+id_no).val()) )
		{
			var msg = "<?php echo $this->translator->translator('flight_route_same_err'); ?>";
			openMsgDialog(msg);
			$('#'+to_id+id_no).val('');
			$('#'+to_id+id_no).focus();
		}
	});	
	
	calendar(from_id+'_date'+id_no, to_id+'_date'+id_no);
	calendar(to_id+'_date'+id_no, from_id+'_date'+id_no);
	autoList(from_id+id_no);
	autoList(to_id+id_no);
}

function toTimestamp(strDate){
	 var datum = Date.parse(strDate);
	 return datum/1000;
}

function calendar(id, second_id)
{
	$("#"+id).datepicker({
		showOn: 'button',
		buttonImage: 'application/layouts/scripts/<?php echo $front_template['theme_folder']; ?>/images/mod_flight_img/calendar.png',
		buttonImageOnly: true,
		monthNamesShort:<?php echo $this->translator->translator("common_calender_monthNamesShort"); ?>,
		monthNames:<?php echo $this->translator->translator("common_calender_monthNames"); ?>,
		dayNamesMin:<?php echo $this->translator->translator("common_calender_dayNamesMin"); ?>,
		showAnim: 'slide',
		buttonText: 'Calender',
		dateFormat:'yy-mm-dd',
		onSelect: function(dateText, inst) {
			var id_type_arr = id.split('_');			
			var currentTime = new Date()
			var currentDay = (currentTime.getDate() < 10) ? '0' + currentTime.getDate() : currentTime.getDate();
			var currentMonth = ((currentTime.getMonth() + 1) < 10) ? '0' + (currentTime.getMonth() + 1) : (currentTime.getMonth() + 1);
			var today = currentTime.getFullYear() + '-' + currentMonth + '-' + currentDay;				
			if(id_type_arr[2] == 'departure')
			{				
				if( (dateText != '') && ( (toTimestamp(dateText) >= toTimestamp($('#'+second_id).val())) || (toTimestamp(dateText) < toTimestamp(today)) )  )
				{
					var msg = "<?php echo $this->translator->translator('flight_route_departure_date_err'); ?>";
					openMsgDialog(msg);
					$('#'+id).val('');
				}
			}
			else if(id_type_arr[2] == 'arrival')
			{
				if( (dateText != '') && ( (toTimestamp(dateText) <= toTimestamp($('#'+second_id).val())) || (toTimestamp(dateText) < toTimestamp(today)) )  )
				{
					var msg = "<?php echo $this->translator->translator('flight_route_arrival_date_err'); ?>";
					openMsgDialog(msg);
					$('#'+id).val('');
				}
			}
		},
		autoSize:false,
		showButtonPanel:false,
		changeMonth: true,
		changeYear: true
	});
	
	$("img[class='ui-datepicker-trigger']").each(function()
	 { 
	  	$(this).attr('style', '');
	 });
}

function autoList(id)
{
	autoSuggestion(id, "<?php echo $this->url( array('module'=> 'Flight', 'controller' => 'frontend', 'action'     => 'iata' ), 'adminrout',    true) ?>", {'datas': ''}, ['iata_code', 'iata_code', 'flight_label', 'flight_value', 'flight_location'], '', 3);
}

function openMsgDialog(msg)
{
$('#dialog_container').html(msg).dialog({
			autoOpen: true,
			modal: false,
			show: 'explode',
			resizable: true,				
			buttons: [{ text: "<?php echo html_entity_decode($this->translator->translator('common_ok'), ENT_QUOTES, 'UTF-8'); ?>", click: function() { $(this).dialog('option', 'hide', 'explode').dialog("close"); } } ],
			open: function(event, ui)
				 {
					setTimeout(function() 
					{									
						if($('#' + event.target.id).dialog('isOpen'))
						{
							$('#' + event.target.id).dialog('option', 'hide', 'explode').dialog('close');										
						}
					}, 9000);
				  }
		});
}
/************************************************IMAGE THUMBNIL************************************************/
function imageThumbnil()
{	
	$("span.thumbnail").hover(function() {
		$(this).css({'z-index' : '10'}); /*Add a higher z-index value so this image stays on top*/ 
		$(this).find('img').addClass("hover").stop() /* Add class of "hover", then stop animation queue buildup*/
			.animate({
				marginTop: '-110px', /* The next 4 lines will vertically align this image */ 
				marginLeft: '-10px',
				top: '50%',
				left: '50%',
				width: '174px', /* Set new width */
				height: '174px', /* Set new height */
				padding: '20px'
			}, 200); /* this value of "200" is the speed of how fast/slow this hover animates */
	
		} , function() {
		$(this).css({'z-index' : '0'}); /* Set z-index back to 0 */
		$(this).find('img').removeClass("hover").stop()  /* Remove the "hover" class , then stop animation queue buildup*/
			.animate({
				marginTop: '0', /* Set alignment back to default */
				marginLeft: '0',
				top: '-15px',
				left: '0',
				width: '50px', /* Set width back to default */
				height: '50px', /* Set height back to default */
				padding: '5px'
			}, 400);
	});
}
</script>

<div class="mod">
    <div class="flight-icon">
        <h1><?php echo $this->translator->translator('flight_front_page_AirlineFlightSchedules_name'); ?></h1>
    </div>
	<div class="clear"></div>   

	<div class="mod-container">
		<form id="formAirlineFlightSchedulesSearch" name="formAirlineFlightSchedulesSearch" method="post" action="<?php echo $this->url( array('module'=> 'Flight', 'controller' => 'frontend', 'action'     => 'airlineflightschedules' ), 'AirlineFlightSchedules',    true) ?>">		  
            <div class="flight-api-search">
                <div class="col">
                    <input type="hidden" name="submit_type" id="submit_type" value="ajax" /><input type="radio" name="trip_type" id="trip_type" value="round" /><span class="mod-title"><?php echo $this->translator->translator('flight_front_page_AirlineFlightSchedules_trip_type_round'); ?></span> &nbsp; 
                    <input type="radio" name="trip_type" id="trip_type" value="one_way" checked="checked" /><span class="mod-title"><?php echo $this->translator->translator('flight_front_page_AirlineFlightSchedules_trip_type_one'); ?></span>
                </div>
                    
                <div class="col clear">
                    <p><?php echo $this->translator->translator('flight_front_page_AirlineFlightSchedules_origin'); ?></p>
                    <input type="text" name="flight_route_departure[]" id="flight_route_departure0" size="50" value="KJFK" class="flight_route_departure route"/>    
                </div>
                    
                <div class="col clear">
                    <p><?php echo $this->translator->translator('flight_front_page_AirlineFlightSchedules_destination'); ?></p>
                    <input type="text" name="flight_route_arrival[]" id="flight_route_arrival0" value="KLAX" class="flight_route_arrival route"/>
                </div>
                    
                <div class="col clear">
                    <p><?php echo $this->translator->translator('flight_front_page_AirlineFlightSchedules_startDate'); ?></p>
                    <input name="flight_route_departure_date[]" type="text" id="flight_route_departure_date0" size="15" class="flight_route_departure_date"/>
                </div>
                    
                <div class="col">
                    <p><?php echo $this->translator->translator('flight_front_page_AirlineFlightSchedules_endDate'); ?></p>
                    <input type="text" name="flight_route_arrival_date[]" id="flight_route_arrival_date0"  class="flight_route_arrival_date"/>
                </div>
                    
                <div class="col clear">
                    <p><?php echo $this->translator->translator('flight_front_page_AirlineFlightSchedules_class_type'); ?></p>
                    <select name="class_type" id="class_type" class="medium">
                        <option value="Economy"><?php echo $this->translator->translator('flight_front_page_AirlineFlightSchedules_class_1'); ?></option>
                        <option value="Business"><?php echo $this->translator->translator('flight_front_page_AirlineFlightSchedules_class_2'); ?></option>
                        <option value="First"><?php echo $this->translator->translator('flight_front_page_AirlineFlightSchedules_class_3'); ?></option>											
                    </select>
                </div>
                    
                <div class="col">
                    <p><?php echo $this->translator->translator('flight_front_page_AirlineFlightSchedules_adult_no'); ?></p>
                    <select name="adult_no" id="adult_no" class="small">
						<?php for($i = 1; $i <= 12; $i++){ ?>
                        <option value="<?php echo $i; ?>"><?php echo $i; ?></option>
                        <?php } ?>										
                    </select>
                </div>
                    
                <div class="col">
                    <p><?php echo $this->translator->translator('flight_front_page_AirlineFlightSchedules_child_no'); ?></p>
                    <select name="child_no" id="child_no" class="small">
						<?php for($i = 0; $i <= 12; $i++){ ?>
                        <option value="<?php echo $i; ?>"><?php echo $i; ?></option>
                        <?php } ?>										
                    </select>
                </div>
                    
                <div class="col">
                    <p><?php echo $this->translator->translator('flight_front_page_AirlineFlightSchedules_infant_no'); ?></p>
                    <select name="infant_no" id="infant_no"  class="small">
                            <?php for($i = 0; $i <= 12; $i++){ ?>
                            <option value="<?php echo $i; ?>"><?php echo $i; ?></option>
                            <?php } ?>										
                    </select>
                </div>
                <div class="clear"></div>    
              	
                <input type="button" name="Submit" value="SEARCH FOR FLIGHT" class="flight_search_btn" id="" />
            </div>     
					
			<div class="block-api-ad"><?php echo $this->partial('blocks/ad_flight_banner.phtml'); ?></div>
        </form>    
</div>

<div id="loader_img"></div>

<div class="result-container">
    <table width="100%" border="0" align="center" cellpadding="0" cellspacing="0">
      <tr>
        <td>
            <table id="sortTable" width="100%" border="0" align="center" cellpadding="0" cellspacing="0" >
                <thead class="result-header"><tr>
                <th width="10%" align="center" class="first"><?php echo $this->translator->translator("flight_AirlineFlightSchedules_page_table_airline"); ?></th>
                <th width="34%" align="center"><?php echo $this->translator->translator("flight_AirlineFlightSchedules_page_table_stop"); ?></th>
                <th width="18%" align="center"><?php echo $this->translator->translator("flight_AirlineFlightSchedules_page_table_depart"); ?></th>
                <th width="18%" align="center"><?php echo $this->translator->translator("flight_AirlineFlightSchedules_page_table_arive"); ?></th>
                <th width="10%" align="center"><?php echo $this->translator->translator("flight_AirlineFlightSchedules_page_table_price"); ?></th>
                <th width="10%" align="center" class="last"><?php echo $this->translator->translator("flight_AirlineFlightSchedules_page_table_book"); ?></th>
                </tr>
            </thead>
                <tbody>
            
                <?php
                    if($this->result['status'] == 'ok')
                    {					
                        $ident = '';
                        foreach($this->result['result'] as $key => $search_result )
                        {						
                            $ident .= '<br />'.$search_result['ident'];
                            if($search_result['FlightInfoExResult'])
                            {
                                $route = 		($search_result['FlightInfoExResult'][0]) ? $search_result['FlightInfoExResult'][0]['originName'].', '.$search_result['FlightInfoExResult'][0]['originCity'].' --> '.$search_result['FlightInfoExResult'][0]['destinationName'].', '.$search_result['FlightInfoExResult'][0]['destinationCity'] : '';
                                if($search_result['FlightInfoExResult'][0])
                                {
                                     $filed_departuretime = ($search_result['FlightInfoExResult'][0]['filed_departuretime']) ? $search_result['FlightInfoExResult'][0]['filed_departuretime'] : '0000-00-00';
                                     $estimatedarrivaltime       =		($search_result['FlightInfoExResult'][0]['estimatedarrivaltime']) ? $search_result['FlightInfoExResult'][0]['estimatedarrivaltime'] : '0000-00-00';
                                }
                            }
                            $airlines = ($search_result['airline_infos'] == null) ? '' : $search_result['airline_infos']['airlines'];
                            $airline_logo = ($search_result['airline_infos'] == null) ? $search_result['airline_code'] : '<span class="thumbnail"><img src="data/frontImages/flight/airlines/'.$search_result['airline_infos']['airlines_pic'].'" width="45" height="35" title="'.$airlines.'" />';
                            $total_price = ($search_result['airline_price_info'] == null) ? '0.00' : ($search_result['airline_price_info']['total_price'] + $search_result['airline_price_info']['total_tax']) ;		
                            $total_price_value = $total_price.$search_result['airline_price_info']['currency_symbol'];
                            if($total_price != '0.00'){ $book_now = '<span class="products-book-btn"><a href="FlightBooking/'.$key.'">'.$this->translator->translator("flight_AirlineFlightSchedules_page_table_book").'</a></span>'; }else{ $book_now = '<span class="products-details-btn"><a href="FlightQuoting/'.$key.'">'.$this->translator->translator("flight_AirlineFlightSchedules_page_table_quote").'</a></span>'; }
                            echo '<tr>';
                                echo '<td>';
                                    echo $airline_logo;	
                                echo '</td>';
                                echo '<td>';				
                                    echo $route;
                                echo '</td>';
                                echo '<td>';
                                    echo $filed_departuretime;
                                echo '</td>';
                                echo '<td>';
                                    echo $estimatedarrivaltime;
                                echo '</td>';
                                echo '<td class="right">';
                                    echo '<span class="mod-title">'.$total_price_value.'</span>';
                                echo '</td>';
                                echo '<td class="right">';
                                    echo $book_now;
                                echo '</td>';
                            echo '</tr>';
                        }
                    }
                    else if($this->result['status'] == 'err')
                    {
                        echo '<tr class="odd" align="center"><td></td><td></td><td class="dataTables_empty" valign="top">'.$this->result['msg'].'</td><td></td><td></td><td></td></tr>';
                    }
                ?>
               
                </tbody>
            </table>
        </td>
      </tr>  
    </table>
</div>
</div>
<div id="dialog_container" title="<?php echo $this->translator->translator('common_dialog_msg',$this->translator->translator('flight_front_page_AirlineFlightSchedules_name')); ?>"></div>