<?php
$version = Zend_Registry::get('version');
$tab_base_link = Zend_Controller_Front::getInstance()->getRequest()->getRequestUri();
$front_template = Zend_Registry::get('front_template');
echo $this->headScript()->setFile($this->baseUrl().'/vendor/scripts/BookingCalendar/js/jquery.dop.BookingCalendar.js');
echo $this->headLink()->setStylesheet('application/layouts/scripts/'.$front_template['theme_folder'].'/css/jquery.dop.BookingCalendar.css');
echo $this->headScript()->setFile($this->baseUrl().'/js/jquery/raty/js/jquery.raty.js');
echo $this->headScript()->setFile($this->baseUrl().'/js/jquery/gallery/jquery.ad-gallery.js'); 
echo $this->headLink()->setStylesheet($this->baseUrl().'/js/jquery/gallery/jquery.ad-gallery.css');
echo $this->headScript()->setFile($this->baseUrl().'/js/jquery/jquery.scrollTo.js');

$meta_Title = $this->vacationrentals_Form->meta_title->getValue();
$meta_keywords = $this->vacationrentals_Form->meta_keywords->getValue();
$meta_description = $this->vacationrentals_Form->meta_desc->getValue();
$property_name = $this->vacationrentals_Form->vacationrentals_name->getValue();
$global_conf = Zend_Registry::get('global_conf');
// 1ist param options are : like, inline, plus_minus, horizontal, triangle
$vote = new Vote_Controller_Helper_ShowVoteButton('inline','vacationrentals_page' );
$group_db = new Vacationrentals_Model_DbTable_VacationrentalsGroup();

if(!empty($property_name)) { $this->headTitle()->headTitle($this->escape($property_name),'SET')->setSeparator(' - ')->headTitle($meta_Title); }
if(!empty($meta_keywords)){ $this->headMeta()->setName('keywords',$meta_keywords); }
if(!empty($meta_description)) { $this->headMeta()->setName('description',$meta_description); }


function isnot_int($vacationrentals_owner)
{
	$r = true;			
	if(is_numeric($vacationrentals_owner))
	{ 
		if(is_int((int)$vacationrentals_owner))
		{
			$r = false;
		}				
	}
	return $r;
}

$auth = Zend_Auth::getInstance ();
$hasIdentity = $auth->hasIdentity ();

$feature_facilities_arr = explode(',', $this->view_datas['feature_amenities']); 
$item_id = $this->vacationrentals_Form->id->getValue();
$group_id = $this->vacationrentals_Form->group_id->getValue();
$nextVacationrentals = $this->vacationrentals_database->getNextVacationrentals($item_id,$group_id, null);
$prevVacationrentals = $this->vacationrentals_database->getPrevVacationrentals($item_id,$group_id, null);
$country_id = $this->vacationrentals_Form->country_id->getValue();
$state_id = $this->vacationrentals_Form->state_id->getValue();
$area_id = $this->vacationrentals_Form->area_id->getValue();
$display_related_item_limit = 10 ;
$color_sign = ' ';
$maximum_stars_digit = $this->translator->translator('maximum_stars_digit');


if($area_id)
{												
	try
	{
		$area_db = new Vacationrentals_Model_DbTable_Area();
		$area_info = $area_db->getAreaInfo($area_id);		
	}
	catch(Exception $e)
	{
		echo $e->getMessage() ;
	}
}
if($state_id)
{
	try
	{
		$state_db = new Vacationrentals_Model_DbTable_State();
		$state_info = $state_db->getStateInfo($state_id);
	}
	catch(Exception $e)
	{
		echo $e->getMessage() ;
	}
}
if($country_id)
{
	try
	{
		$country_db = new Vacationrentals_Model_DbTable_Country();
		$country_info = $country_db->getCountryName($country_id);
	}
	catch(Exception $e)
	{
		echo $e->getMessage() ;
	}
} 
?>
<script type="text/javascript">
function scrolling(class_name)
{
	$.easing.elasout = function(x, t, b, c, d) {
		var s=1.70158;var p=0;var a=c;
		if (t==0) return b;  if ((t/=d)==1) return b+c;  if (!p) p=d*.3;
		if (a < Math.abs(c)) { a=c; var s=p/4; }
		else var s = p/(2*Math.PI) * Math.asin (c/a);
		return a*Math.pow(2,-10*t) * Math.sin( (t*d-s)*(2*Math.PI)/p ) + c + b;
	};
	$('a.'+class_name).click(function(){//$.scrollTo works EXACTLY the same way, but scrolls the whole screen
		var rel = $(this).attr('rel');
		var id_arr = rel.split('-');
		var id_no = parseInt(id_arr[1]);
		$('#tabs').tabs({ active: --id_no });
		$.scrollTo( rel , 1500, { easing:'swing' });		
		return false;
	});
}

function changeImageScrolling()
{
	$.easing.elasout = function(x, t, b, c, d) {
		var s=1.70158;var p=0;var a=c;
		if (t==0) return b;  if ((t/=d)==1) return b+c;  if (!p) p=d*.3;
		if (a < Math.abs(c)) { a=c; var s=p/4; }
		else var s = p/(2*Math.PI) * Math.asin (c/a);
		return a*Math.pow(2,-10*t) * Math.sin( (t*d-s)*(2*Math.PI)/p ) + c + b;
	};
	
	 
	 $("a.change_img").click(function(){
			var self = this;
			var src = $(self).children("img:nth-child(1)").attr('src');			
			$("div.ad-image").children("img:nth-child(1)").attr('src',src);							
			$.scrollTo( '#gallery' , 1500, { easing:'swing' });			
			return false;
		});
}

 $(function() {				
				var galleries = $('.ad-gallery').adGallery({
					slideshow: {
                       enable: true,
                       autostart: true,
                       speed: 5000,
                       start_label: 'Start',
                       stop_label: 'Stop',
                       stop_on_scroll: true,
                       countdown_prefix: '(',
                       countdown_sufix: ')',
                       onStart: false,
                       onStop: false
                     }
					 });
				$('#switch-effect').change(
				  function() {
					galleries[0].settings.effect = $(this).val();
					return false;
				  }
				);
				$('#toggle-slideshow').click(
				  function() {
					galleries[0].slideshow.toggle();
					return false;
				  }
				);
				$('#toggle-description').click(
				  function() {
					if(!galleries[0].settings.description_wrapper) {
					  galleries[0].settings.description_wrapper = $('#descriptions');
					} else {
					  galleries[0].settings.description_wrapper = false;
					}
					return false;
				  }
				);
			  });
$(function() {
		$('#slickbox').hide();
		
		$('a.slick-slidetoggle').click(function() {
			$('#slickbox').slideToggle(400);
			return false;
		  });
		  
		 <?php if($this->tab == '4'){ ?>			 
				$('#dialog_calendar').DOPBookingCalendar({'Type':'FrontEnd', 'DataURL':'<?php echo $this->url( array("module"=> "Vacationrentals", "controller" => "frontend", "action"     => "load", "id" => $this->escape($this->view_datas["id"]) ), "adminrout",    true) ?>','Currency':'<?php echo $this->currency->getSymbol(); ?>', 'AvailableText':"<?php echo $this->translator->translator("calerdar_AvailableText", '', '', $front_template['theme_folder']); ?>", 'BookedText':"<?php echo $this->translator->translator("calerdar_BookedText", '', '', $front_template['theme_folder']); ?>", 'UnavailableText':"<?php echo $this->translator->translator("calerdar_UnavailableText", '', '', $front_template['theme_folder']); ?>"});
		<?php  } ?>
		
		$("#tabs").tabs({ 
				active: <?php echo $this->tab; ?>,
				activate: function(event, ui) { 					  					      
						$('#dialog_calendar').DOPBookingCalendar({'Type':'FrontEnd', 'DataURL':'<?php echo $this->url( array("module"=> "Vacationrentals", "controller" => "frontend", "action"     => "load", "id" => $this->escape($this->view_datas["id"]) ), "adminrout",    true) ?>','Currency':'<?php echo $this->currency->getSymbol(); ?>', 'AvailableText':"<?php echo $this->translator->translator("calerdar_AvailableText", '', '', $front_template['theme_folder']); ?>", 'BookedText':"<?php echo $this->translator->translator("calerdar_BookedText", '', '', $front_template['theme_folder']); ?>", 'UnavailableText':"<?php echo $this->translator->translator("calerdar_UnavailableText", '', '', $front_template['theme_folder']); ?>"});
					}
				}).find(".ui-tabs-nav").sortable({axis:'xy'});
		$("#matchTabs").tabs().find(".ui-tabs-nav").sortable({axis:'xy'});
		
		changeImageScrolling();
		
		scrolling('review_btn');
		
		scrolling('calendar_btn');
	});
	


$(function() {
	$( "#vacationrentals_owner" ).combobox();	
	autoSuggestion('vacationrentals_name', "<?php echo $this->url( array('module'=> 'Vacationrentals', 'controller' => 'backendpro', 'action'     => 'searchname' ), 'adminrout',    true) ?>", {'vacationrentals_name': ''}, ['vacationrentals_primary_image', 'vacationrentals_image', 'vacationrentals_name', 'vacationrentals_name', 'owner_name','vacationrentals_postcode' ,'vacationrentals_room', 'vacationrentals_location'], 'data/frontImages/vacationrentals/vacationrentals_image', 2);	
	autoSuggestion('post_code', "<?php echo $this->url( array('module'=> 'Vacationrentals', 'controller' => 'backendpro', 'action'     => 'searchname' ), 'adminrout',    true) ?>", {'post_code': ''}, ['vacationrentals_primary_image', 'vacationrentals_image', 'vacationrentals_name', 'post_code', 'owner_name','vacationrentals_postcode' ,'vacationrentals_room', 'vacationrentals_location'], 'data/frontImages/vacationrentals/vacationrentals_image', 2);	
	autoSuggestion('vacationrentals_price', "<?php echo $this->url( array('module'=> 'Vacationrentals', 'controller' => 'backendpro', 'action'     => 'searchname' ), 'adminrout',    true) ?>", {'vacationrentals_price': ''}, ['vacationrentals_primary_image', 'vacationrentals_image', 'vacationrentals_name', 'price', 'owner_name','vacationrentals_postcode', 'vacationrentals_price' ,'vacationrentals_room', 'vacationrentals_location'], 'data/frontImages/vacationrentals/vacationrentals_image', 2);	
});

function stripslashes(str) 
{
	str=str.replace(/\\'/g,'\'');
	str=str.replace(/\\"/g,'"');
	str=str.replace(/\\0/g,'\0');
	str=str.replace(/\\\\/g,'\\');
	return str;
}

$(document).ready(function() {
	
	
	function openMsgDialog(msg)
	{
		$('#dialog_container').html(msg).dialog({
					autoOpen: true,
					modal: false,
					show: 'explode',
					resizable: true,				
					buttons: [{ text: "<?php echo html_entity_decode($this->translator->translator('common_ok'), ENT_QUOTES, 'UTF-8'); ?>", click: function() { $(this).dialog('option', 'hide', 'explode').dialog("close"); } } ],
					open: function(event, ui)
						 {
							setTimeout(function() 
							{									
								if($('#' + event.target.id).dialog('isOpen'))
								{
									$('#' + event.target.id).dialog('option', 'hide', 'explode').dialog('close');										
								}
							}, 10000);
						  }
				});
	}
	
	$('a.save_vacationrentals_btn').click(function() {
		var self = this;
		var id = $(self).attr('rel');
		$.ajax({
			  url: "<?php echo $this->url( array('module' =>'Vacationrentals','controller' => 'frontend', 'action'     => 'save' ), 'adminrout',    true) ?>",
			  type: 'POST',
			  data: { id: id },
			  beforeSend: function(){						
						$(self).html('<img src="application/layouts/scripts/<?php echo $front_template['theme_folder']; ?>/images/loader/mod-loader.gif" border="0" height="15" />');	
					 },
			  success: function(response){
				//alert(response);
				var json_arr = eval("("+response+")");							
				if(json_arr.status == 'ok')
				{
					openMsgDialog(json_arr.msg);
				}
				else
				{
					openMsgDialog(json_arr.msg);
				}
				$(self).html('<?php echo $this->translator->translator("vacationrentals_front_page_save_vacationrentals"); ?>');
			  }
		});
	});
	
	$('#country_id_H').change(function() {	
			if($('#country_id_H option:selected').val() == 'any' || $('#country_id_H option:selected').val() =='')
			{
				$('#area_id_H').html('<option value="any"><?php echo $this->translator->translator("vacationrentals_select_area"); ?></option>');	
				$('#state_id_H').html('<option value="any"><?php echo $this->translator->translator("vacationrentals_select_state"); ?></option>');
			}
			else
			{	
				$.ajax({
					  url: "<?php echo $this->url( array('module' =>'Vacationrentals','controller' => 'frontend', 'action'     => 'states' ), 'adminrout',    true) ?>",
					  type: 'POST',
					  data: { id: $('#country_id_H option:selected').val() },
					  beforeSend: function(){						
								$('#state_id_H').html('<option value="any"><?php echo $this->translator->translator("common_loading_language"); ?></option>');
								$('#area_id_H').html('<option value="any"><?php echo $this->translator->translator("vacationrentals_select_area"); ?></option>');			
								$('#state_id_H_err').html('<img src="application/layouts/scripts/<?php echo $front_template['theme_folder']; ?>/images/loader/mod-loader.gif" border="0" height="15" />');	
							 },
					  success: function(response){
						//alert(response);
						var json_arr = eval("("+response+")");
						var option = '<option value="any"><?php echo $this->translator->translator("vacationrentals_select_state"); ?></option>';				
						if(json_arr.status == 'ok')
						{
							for(var i = 0;i<json_arr.states.length;i++)
							{
								option += '<option value="'+json_arr.states[i].state_id+'" >'+stripslashes(json_arr.states[i].state_name)+'</option>';
							}
							$('#state_id_H').html(option);
						}
						else
						{
							$('#state_id_H').html('<option value="any">'+json_arr.msg+'</option>');
						}
						$('#state_id_H_err').html('');
					  }
				});
			}
		});
		
		$('#state_id_H').change(function() {		
					
			if($('#state_id_H option:selected').val() == 'any' || $('#state_id_H option:selected').val() == '')
			{
				$('#area_id_H').html('<option value="any"><?php echo $this->translator->translator("vacationrentals_select_area"); ?></option>');
			}
			else
			{
				$.ajax({
					  url: "<?php echo $this->url( array('module' => 'Vacationrentals', 'controller' => 'frontend', 'action'     => 'areas' ), 'adminrout',    true) ?>",
					  type: 'POST',
					  data: { id: $('#state_id_H option:selected').val() },
					  beforeSend: function(){						
							$('#area_id_H').html('<option value="any"><?php echo $this->translator->translator("common_loading_language"); ?></option>');
							$('#area_id_H_err').html('<img src="application/layouts/scripts/<?php echo $front_template['theme_folder']; ?>/images/loader/mod-loader.gif" border="0" height="15" />');	
							},
					  success: function(response){
						//alert(response);
						var json_arr = eval("("+response+")");
						var option = '<option value="any"><?php echo $this->translator->translator("vacationrentals_select_area"); ?></option>';				
						if(json_arr.status == 'ok')
						{
							for(var i = 0;i<json_arr.cities.length;i++)
							{
								option += '<option value="'+json_arr.cities[i].city_id+'" >'+stripslashes(json_arr.cities[i].city)+'</option>';
							}
							$('#area_id_H').html(option);
						}
						else
						{
							$('#area_id_H').html('<option value="any">'+json_arr.msg+'</option>');
						}
						$('#area_id_H_err').html('');
					  }
				});
			}
		});	
	
	
	
	$('a.print_vr').click(function (event){							
                       var width = 1200;
              		   var height = 700;
                       var left = parseInt((screen.availWidth/2) - (width/2));
                       var top = parseInt((screen.availHeight/2) - (height/2));
                       var windowSizeArray = ["width="+width+",height="+height+",left="+left+",top="+top+"screenX=" + left + ",screenY=" + top + ",scrollbars=yes","width="+width+",height="+height+",scrollbars=yes" ];
                       var url = "<?php echo $this->url(array('module' =>'Vacationrentals','controller' =>'frontend', 'action' => 'print','vacationrentals_title'=> $this->escape($this->vacationrentals_Form->vacationrentals_title->getValue())),'Vacationrentals-print/:vacationrentals_title',true); ?>";
                       var windowName = "popUp";
                       var windowSize = windowSizeArray[$(this).attr("rel")];
                       window.open(url, windowName, windowSize);
                       event.preventDefault();

             	});

		
});

function raty (id, start_point)
{
	$('#'+id+'_star').raty({
	  path: 'js/jquery/raty/img/',						  
	  hintList:		<?php echo html_entity_decode($this->translator->translator("common_rating_hintList"), ENT_QUOTES, 'UTF-8'); ?>,
	  number:     <?php $hint_arr = explode(', ',str_replace('[', '', str_replace(']', '', $this->translator->translator('common_rating_hintList')))); echo count($hint_arr); ?>,
	  start: start_point,
	  readOnly:   true					 
	});
}				

</script>
<style type="text/css">
#dialog_calendar{background-color: #f0f0f0; background: url('vendor/scripts/BookingCalendar/images/loader-big.gif') no-repeat center center;}
</style>
<?php 
$allow_obj = new Vacationrentals_View_Helper_Allow();
if (!$allow_obj->allowRule('details',null,null,$this->group_datas['role_id'])) : ?>
	<?php echo $this->translator->translator('Member_Access_deny_desc'); ?>
<?php else : ?>
<?php if($this->view_datas['active'] == '1') : ?>
<div class="mod mod-details">	
    <!-- Top Bar Start -->
    <div class="nav-bar">
        <div class="nav-row">
            <div class="nav-col first"> 
            <?php
				if(!empty($prevVacationrentals))
				{
			?>
            <span class="prev"><a href="<?php echo 'Vacationrentals-details/'.$this->escape($prevVacationrentals['vacationrentals_title']); ?>"><?php echo $this->translator->translator('vacationrentals_front_page_prev_vacationrentals'); ?></a></span>
            <?php
				}
				else
				{
			?>
            <span class="no-link"><?php echo $this->translator->translator('vacationrentals_front_page_prev_vacationrentals'); ?></span>
            <?php
                }
            ?>
            </div>
            <div class="nav-col"><span class="search"><a href="#" class="slick-slidetoggle"><?php echo $this->translator->translator('vacationrentals_front_page_new_search'); ?></a></span></div>
            <div class="nav-col">
            <?php
                if ($hasIdentity)
                {
			?>
            <span class="save"><a  href="javascript:void(0);" class="save_vacationrentals_btn" rel="<?php echo $this->escape($item_id); ?>"><?php echo $this->translator->translator('vacationrentals_front_page_save_vacationrentals'); ?></a></span>
            <?php
                }
            ?>
            </div>
            <div class="nav-col last">
            <?php
				if(!empty($nextVacationrentals))
				{
			?>
            <span class="next"><a href="<?php echo 'Vacationrentals-details/'.$this->escape($nextVacationrentals['vacationrentals_title']); ?>"><?php echo $this->translator->translator('vacationrentals_front_page_next_vacationrentals'); ?></a></span>
            <?php
                }
                else
                {
            ?>
            <span class="no-link"><?php echo $this->translator->translator('vacationrentals_front_page_next_vacationrentals'); ?></span>
            <?php
                }
            ?>
            </div>
        </div>
    </div>
    <!-- Top Bar End -->
    
    <!-- Vacation Slick Search Start -->
    <div id="slickbox" class="mod-container mod-advance-search">
        <form id="formSearch" name="formSearch" method="post" action="<?php echo $this->url( array('module' => 'Vacationrentals', 'controller' => 'search', 'action'     => 'items' ), 'Vacationrentals-Search',    true) ?>">
            <input type="hidden" name="group_id_=" id="group_id" value="<?php echo $this->escape($this->group_datas['id']); ?>" /><input type="hidden" name="active_=" id="active" value="1" />
            <div class="col clear">
                <p><?php echo $this->translator->translator('vacationrentals_list_page_search_name'); ?></p>
                <input type="text" name="vacationrentals_name_LIKE" id="vacationrentals_name" value="" class="big" />
            </div>
            
            <div class="col">
                <p><?php echo $this->translator->translator('vacationrentals_list_page_search_group'); ?></p>
                <select name="group_id_=" id="group_id" class="country_id">					 	
                    <?php
                    $group_list = $group_db->getGroupInfo();
                        foreach($group_list as $key => $value)
                        {
                            $selected = ($this->postValue['group_id_='] == $key) ? 'selected=""selected' : '';
                    ?>
                        <option value="<?php echo $key; ?>" <?php echo $selected; ?>><?php echo $this->escape($value); ?></option>
                    <?php	
                        }
                    ?>
                </select>
            </div>
            
            <div class="col">
                <p><?php echo $this->translator->translator('vacationrentals_list_page_search_price'); ?></p>
                <input type="text" name="vacationrentals_price_LIKE" id="vacationrentals_price" value="" class="mod-field vacation-field-small" />
                <span class="mod-title"><?php echo $this->currency->getSymbol(); ?></span>
            </div>
            
            <div class="col">
                <p><?php echo $this->translator->translator('vacationrentals_list_page_search_pro_type'); ?></p>
                <?php
                    $type_info = $this->business_type_db->getOptions($this->group_datas['id']);
                ?>
                <select name="vacationrentals_type_=" id="vacationrentals_type" class="small">
                <option value="any"><?php echo $this->translator->translator('common_any_language'); ?></option>
                <?php
                    
                    foreach($type_info as $info)
                    {
                ?>
                    <option value="<?php echo $info['id']; ?>"><?php echo $this->escape($info['business_type']); ?></option>
                <?php
                    }
                ?>
                </select>
            </div>
            
            <div class="col">
                <p><?php echo $this->translator->translator('vacationrentals_list_page_search_category'); ?></p>
                
                <?php
                    $cat_data = $this->cat_Info->getOptions($this->group_datas['id']);
                ?>
                <select name="category_id_=" id="category_id">
                <option value="any"><?php echo $this->translator->translator('common_any_language'); ?></option>
                <?php
                    
                    foreach($cat_data as $info)
                    {
                ?>
                    <option value="<?php echo $info['id']; ?>"><?php echo $this->escape($info['category_name']); ?></option>
                <?php
                    }
                ?>
                </select>
            </div>
            
            <div class="col">
                <p><?php echo $this->translator->translator('vacationrentals_list_page_search_price_min'); ?></p>
                
                <?php
                    $min_price_arr = $this->vacationrentals_database->getPrice('ASC');
                ?>
                <select name="vacationrentals_price_>=" id="vacationrentals_price"  class="small">
                    <option value="any"><?php echo $this->translator->translator('common_any_language'); ?></option>
                    <?php
                    
                    foreach($min_price_arr as $key=>$value)
                    {
                        if(!empty($value['vacationrentals_price']))
                        {										
                    ?>
                        <option value="<?php echo $this->price($value['vacationrentals_price']); ?>"><?php echo $this->price($this->escape($value['vacationrentals_price'])).' '.$this->currency->getSymbol(); ?></option>
                    <?php
                            }
                        }
                    ?>
                </select>
            </div>
            
            <div class="col">
                <p><?php echo $this->translator->translator('vacationrentals_list_page_search_price_max'); ?></p>
                
                <?php
                    $max_price_arr = $this->vacationrentals_database->getPrice('DESC');
                ?>
                <select name="vacationrentals_price_<=" id="vacationrentals_price" class="small">
                <option value="any"><?php echo $this->translator->translator('common_any_language'); ?></option>
                <?php
                
                foreach($max_price_arr as $key=>$value)
                {
                    if(!empty($value['vacationrentals_price']))
                    {
                        
                ?>
                    <option value="<?php echo $this->price($value['vacationrentals_price']); ?>"><?php echo $this->price($this->escape($value['vacationrentals_price'])).' '.$this->currency->getSymbol(); ?></option>
                <?php
                    }
                }
                ?>
                </select>
            </div>
                
            <div class="col">
                <p><?php echo $this->translator->translator('vacationrentals_list_page_search_postcode'); ?></p>
                <input type="text" name="post_code_=" id="post_code"  class="small" />
            </div>
            
            <div class="col">
                <p><?php echo $this->translator->translator('vacationrentals_list_page_search_country'); ?></p>
                
                <?php
                    $country_db = new Vacationrentals_Model_DbTable_Country();
                    $country_data = $country_db->getCountryInfo();
                ?>
                <select name="country_id_=" id="country_id_H"  class="country_id">
                <option value="any"><?php echo $this->translator->translator('common_any_language'); ?></option>
                <?php
                    
                    foreach($country_data as $key=>$value)
                    {
                ?>
                    <option value="<?php echo $key; ?>"><?php echo $this->escape($value); ?></option>
                <?php
                    }
                ?>
                </select>
            </div>
            
            <div class="col">
                <p><?php echo $this->translator->translator('vacationrentals_list_page_search_state'); ?></p>
                
                <select name="state_id_=" id="state_id_H" class="state_id mod-list state">
                    <option value="any"><?php echo $this->translator->translator('vacationrentals_select_state'); ?></option>																			
                </select><span id="state_id_H_err"></span>
            </div>
            
            <div class="col">
                <p><?php echo $this->translator->translator('vacationrentals_list_page_search_area'); ?></p>
                
                <select name="area_id_=" id="area_id_H" class="area_id area">
                    <option value="any"><?php echo $this->translator->translator('vacationrentals_select_area'); ?></option>																			
                </select><span id="area_id_H_err"></span>
            </div>
            
            <div class="col clear">
                <p><?php echo $this->translator->translator('vacationrentals_list_page_search_owner'); ?></p>
                
                <?php
                    $mem_data = $this->agent_list->getAllMembers();
                ?>
                <span class="ui-widget">
                <select name="vacationrentals_owner_=" id="vacationrentals_owner">
                <option value="any"><?php echo $this->translator->translator('common_any_language'); ?></option>
                <?php
                    
                    foreach($mem_data as $key=>$value)
                    {
                ?>
                    <option value="<?php echo $key; ?>"><?php echo $this->escape($value); ?></option>
                <?php
                    }
                ?>
                </select>
                </span>
            </div>
            
            <div class="col">
              <p><?php echo $this->translator->translator('vacationrentals_list_page_search_room'); ?></p>
                <select name="feature_bedroom_=" id="feature_bedroom_=" class="middle">
                <option value="any"><?php echo $this->translator->translator('common_any_language'); ?></option>
                <?php
                    
                    for($i = 1; $i<=200;$i++)
                    {
                ?>
                    <option value="<?php echo $i; ?>"><?php echo $this->escape($i); ?></option>
                <?php
                    }
                ?>
                </select>
            </div>
            
            <div class="col">
                <p><?php echo $this->translator->translator('vacationrentals_list_page_search_bathroom'); ?></p>                
                <select name="feature_bathroom_=" id="feature_bathroom_=" class="middle">
                <option value="any"><?php echo $this->translator->translator('common_any_language'); ?></option>
                <?php
                    
                    for($i = 1; $i<=200;$i++)
                    {
                        $selected = ($this->postValue['feature_bathroom_>='] == $i) ? ' selected="selected" ' : '';
                ?>
                    <option value="<?php echo $i; ?>"<?php echo $selected; ?>><?php echo $this->escape($i); ?></option>
                <?php
                    }
                ?>
                </select>
            </div>
            
            <div id="loader_img">&nbsp;</div>
            
            <div class="clear btn-container">
           		<input type="submit" name="Submit" class="search_btn" value="<?php echo $this->translator->translator('vacationrentals_front_page_search_button'); ?>" />
            </div>
        </form>
    </div>
    <!-- Vacation Slick Search End -->
    
    <div class="clear">&nbsp;</div>
    
    <h1><?php echo $this->escape($this->vacationrentals_Form->vacationrentals_name->getValue()); ?></h1>
    <div class="products-type"><?php echo strtoupper($this->escape($this->businessTypeInfo['business_type'])); ?></div>
    
    <div class="clear">&nbsp;</div>
    <!-- Vacation Info Start -->
    <div class="products-info">
            <div class="products-stars">
                <?php
                      $hotel_stars = (int) $this->escape($this->vacationrentals_Form->stars->getValue());
                                                                               
                      for($i = 1; $i < $maximum_stars_digit ; $i++)
                      {
                         $print_stars = ($i <= $hotel_stars )  ? "<img src='application/layouts/scripts/".$front_template['theme_folder']."/images/mod_vacation_img/star-active.png' border='0' />" : "<img src='application/layouts/scripts/".$front_template['theme_folder']."/images/mod_vacation_img/star-inactive.png' border='0' />";
                          echo $print_stars.'&nbsp;';
                      }
                ?>
            </div>
            <div><?php echo $this->vacationrentals_Form->feature_room_no->getAttrib('font_end_label'); ?>&nbsp;<?php echo (int)$this->escape( $this->vacationrentals_Form->feature_room_no->getValue()); ?>&nbsp;<?php echo $this->vacationrentals_Form->feature_bathroom->getAttrib('font_end_label'); ?>&nbsp;<?php echo (int)$this->escape($this->vacationrentals_Form->feature_bathroom->getValue()); ?>&nbsp;<?php echo $this->vacationrentals_Form->feature_bedroom->getAttrib('font_end_label'); ?>&nbsp;<?php echo $this->escape($this->vacationrentals_Form->feature_bedroom->getValue()); ?>&nbsp;<?php echo $this->vacationrentals_Form->number_of_sleeps->getAttrib('font_end_label'); ?>&nbsp;<?php echo $this->escape($this->vacationrentals_Form->number_of_sleeps->getValue()); ?></div>
            <div class="clear">&nbsp;</div>
                        
            <ul class="products-options">
                <li class="availability"><a class="calendar_btn" rel="#tabs-5" href="javascript:void(0);" title="Check Calendar for reservation"><?php echo $this->translator->translator('vacationrentals_front_page_label_check-availability'); ?></a></li>
                <?php 
                    if (in_array ('Smoking Allowed' , $feature_facilities_arr)){	  
                ?>
                
                <li class="smoking"><?php echo $this->translator->translator('vacationrentals_front_page_list_allow_smoking'); ?></li>
                <?php }?>
                
                <?php 
                  if (in_array ('Swimming Pool' , $feature_facilities_arr)){								  
                ?>
                
                <li class="swimming"><?php echo $this->translator->translator('vacationrentals_front_page_list_swwimming_pool_availability'); ?></li>            
                
                <?php 
                    }  
                      if (in_array ('Pets Allowed' , $feature_facilities_arr))
                    { 
                ?>
                
                <li class="pet"><?php echo $this->translator->translator('vacationrentals_front_page_list_pet_allow'); ?></li>
                
                <?php 
                    }   
                     if (in_array ('Hot Tub Available' , $feature_facilities_arr))
                    {
                ?>
                
                <li class="tub"><?php echo $this->translator->translator('vacationrentals_front_page_list_hot_tub_availability'); ?></li>
                
                <?php 
                    }	  
                ?>
            </ul>
    </div>
    
    <div class="products-info right">
        <div class="products-price"><?php echo $this->translator->translator('vacationrentals_front_page_label_price'); ?><?php echo $this->currency->getSymbol().'&nbsp;'.$this->price($this->escape($this->vacationrentals_Form->vacationrentals_price->getValue())); ?></div>
        
        <div class="products-review">
            <span class="products-write-review"><?php if(!empty($this->group_datas['review_id'])){ $review_no = (!empty($this->review_datas)) ? htmlentities($this->review_datas['review_no']) : htmlentities('0'); ?><a href="<?php echo $this->url( array('module' => 'Review','controller' => 'frontend', 'action'     => 'write', 'group_id' => $this->escape($this->group_datas['review_id']), Eicra_File_Constants::ITEM_ID => $this->view_datas['id'] ), 'Review-Write/:group_id/:item_id',    true); ?>"><?php echo $this->translator->translator('common_write_review'); ?></a></span> &nbsp; <span class="products-review-count"><a href="javascript:void(0);" class="review_btn" rel="#tabs-9"><?php echo $this->translator->translator('common_review_no',$review_no); ?></a></span><?php } ?>
        </div>
        
        <div class="products-vote">
            <p><?php echo $this->translator->translator('vacationrentals_front_page_label_voting'); ?></p>
            <span><?php  $vote->showButton($this->view_datas['id'] , $this->escape($this->view_datas['vacationrentals_name'])); ?></span>
        </div>
        
        <?php
          if($global_conf['payment_system'] == 'On'){
        ?> 
        <div class="clear">
            <span class="form-button"><a href="<?php echo $this->url(array('module' => 'Vacationrentals','controller' =>'book', 'action' => 'booking','vacationrentals_title' => $this->escape($this->view_datas['vacationrentals_title']) ),'Book-Vacationrentals/:vacationrentals_title',true); ?>"><?php echo $this->translator->translator('vacationrentals_front_page_book_btn'); ?></a></span>
        </div>
        <?php } ?>
    </div>
    <!-- Vacation Info End -->
    
    <!-- Vacation Details Middle Tab Start -->
    <div class="products-middle-tab">	
        <ul>
            <li><a class="print_vr" href="javascript:void(0)" rel="0"><?php echo $this->translator->translator('common_print'); ?></a></li>
            <li><a href="<?php echo $this->url(array('module' => 'Vacationrentals','controller' =>'emails', 'action' => 'friend','vacationrentals_title' => $this->escape($this->vacationrentals_Form->vacationrentals_title->getValue()), 'form_id' => $this->translator->translator('email_to_friend_form_id') ),'Vacationrentals-Email-To-Friend/:vacationrentals_title/:form_id',true); ?>"><?php echo $this->translator->translator('common_email_to_friend'); ?></a></li>
            <li><a href="<?php echo $this->url(array('module' => 'Vacationrentals','controller' =>'emails', 'action' => 'appointment','vacationrentals_title' => $this->escape($this->vacationrentals_Form->vacationrentals_title->getValue()), 'form_id' => $this->translator->translator('appointment_form_id') ),'Vacationrentals-Appointment/:vacationrentals_title/:form_id',true); ?>"><?php echo $this->translator->translator('common_appointment'); ?></a></li>
            <li><a href="<?php echo $this->url(array('module' => 'Vacationrentals','controller' =>'emails', 'action' => 'owner','vacationrentals_title' => $this->escape($this->vacationrentals_Form->vacationrentals_title->getValue()), 'form_id' => $this->translator->translator('contact_owner_form_id') ),'Vacationrentals-Contact-Owner/:vacationrentals_title/:form_id',true); ?>"><?php echo $this->translator->translator('common_contact'); ?></a></li>
        </ul>
    </div>
    
    <div class="products-middle-tab-area">
        <!-- Slide Show Start -->
        <div class="products-slideshow">
            <?php
                $vacationrentals_image_val_arr = explode(',',$this->vacationrentals_Form->vacationrentals_image->getValue());
                if($this->escape($this->vacationrentals_Form->vacationrentals_primary_image->getValue()))
                { 
                    $thumb_image = 'data/frontImages/vacationrentals/vacationrentals_image/'.$this->escape($this->vacationrentals_Form->vacationrentals_primary_image->getValue()); 
                }
                else
                { 
                    if($this->escape($this->vacationrentals_Form->vacationrentals_image->getValue()))
                    {								
                        $thumb_image = 'data/frontImages/vacationrentals/vacationrentals_image/'.$this->escape($vacationrentals_image_val_arr[0]); 
                    }
                    else
                    {
                        $thumb_image = 'application/layouts/scripts/'.$front_template['theme_folder'].'/images/mod_property_img/no_image.png'; 
                    }		
                }
                if($this->group_datas['img_big_width'] && ($this->group_datas['img_big_resize_func'] == 'resizeToWidth' || $this->group_datas['img_big_resize_func'] == 'resize' ))
                { 
                    $width = 'width="'.$this->escape($this->group_datas['img_big_width']).'"'; 
                }
                else
                {
                    $width = '';
                } 
                if($this->group_datas['img_big_height'] && ( $this->group_datas['img_big_resize_func'] == 'resizeToHeight' || $this->group_datas['img_big_resize_func'] == 'resize' ))
                { 
                    $height = 'height="'.$this->escape($this->group_datas['img_big_height']).'"'; 
                } 
                else
                {
                    $height = '';
                }
            ?>
        
            <div id="container">            
                <div id="gallery" class="ad-gallery">
                  <div class="ad-image-wrapper"></div>
                  <div class="ad-controls"></div>
                    <div class="ad-nav">
                        <div class="ad-thumbs">
                          <ul class="ad-thumb-list" style="min-width:100%;">
                                <li>
                                  <a href="<?php echo $thumb_image; ?>">
                                    <img src="<?php echo $thumb_image; ?>"  width="70" height="50" title="<?php echo $this->escape($this->vacationrentals_Form->vacationrentals_name->getValue()); ?>" alt="<?php echo $this->escape($area_info['city']).', '.$this->escape($country_info['value']); ?>"  class="image0">
                                  </a>
                                </li>
                                <?php	
                                    foreach($vacationrentals_image_val_arr as $key=>$value)
                                    {									
                                        if('data/frontImages/vacationrentals/vacationrentals_image/'.$value != $thumb_image)
                                        {
                                  ?>
                                <li>
                                  <a href="data/frontImages/vacationrentals/vacationrentals_image/<?php echo $value; ?>">
                                    <img src="data/frontImages/vacationrentals/vacationrentals_image/<?php echo $value; ?>"  width="70" height="50" title="<?php echo $this->escape($this->vacationrentals_Form->vacationrentals_name->getValue()); ?>" alt="<?php echo $this->escape($area_info['city']).', '.$this->escape($country_info['value']); ?>"  class="image0">
                                  </a>
                                </li>
                                <?php
                                        }
                                    }
                                ?>					
                            </ul>
                        </div>
                    </div>
                </div>
            
                <div class="switch">
                  <select id="switch-effect">
                    <option value="slide-hori">Slide horizontal</option>
                    <option value="slide-vert">Slide vertical</option>
                    <option value="resize">Shrink/grow</option>
                    <option value="fade">Fade</option>
                    <option value="">None</option>
                    </select> <a href="#" id="toggle-slideshow">Toggle slideshow</a> |
                  <a href="#" id="toggle-description">Toggle description outside image</a>
                </div>
            </div>
        </div>
        <!-- Slide Show End -->
        
        <!-- Vacation Match Start -->
        <div class="match-container">
            <div id="matchTabs">
                <ul>
                    <li><a href="<?php echo $tab_base_link; ?>#matchTabs-1"><?php echo $this->translator->translator('vacationrentals_front_page_match_related'); ?></a></li>                        
                    <li><a href="<?php echo $tab_base_link; ?>#matchTabs-2"><?php echo $this->translator->translator('vacationrentals_front_page_match_price'); ?></a></li>
                    <!--<li><a href="<?php echo $tab_base_link; ?>#matchTabs-3"><?php //echo $this->translator->translator('vacationrentals_front_page_match_region'); ?></a></li>-->
                    <li><a href="<?php echo $tab_base_link; ?>#matchTabs-4"><?php echo $this->translator->translator('vacationrentals_front_page_match_agent'); ?></a></li>
                </ul>
            	<div class="match-tab-container" id="matchTabs-1">
					<?php			
                        if(!empty($this->view_datas['related_items']))
                        {									 									
                            $related_items_arr = explode(',',$this->view_datas['related_items']);
                    
                            foreach($related_items_arr as $key=>$value)
                            {
                                
                                $related_matched = $this->vacationrentals_database->getVacationrentalsInfo($value);	
                                if($related_matched)
                                {				
                    ?>
                                  <div class="products-match">                         
                                        <span><a href="<?php echo $this->url(array('module' => 'Vacationrentals','controller' =>'frontend', 'action' => 'details','vacationrentals_title' => $this->escape($related_matched['vacationrentals_title']) ),'Vacationrentals-details/:vacationrentals_title',true); ?>" title="<?php echo $this->escape($related_matched['vacationrentals_name']); ?>"><?php echo $this->escape($related_matched['vacationrentals_name']); ?></a></span>
                                        <div class="products-star">
                                            <?php
                                                  $hotel_stars = (int) $this->escape($related_matched['stars']);
                                                                                                           
                                                  for($i = 1; $i < $maximum_stars_digit ; $i++)
                                                  {
                                                      $print_stars = ($i <= $hotel_stars )  ? "<img src='application/layouts/scripts/".$front_template['theme_folder']."/images/mod_vacation_img/star-small-active.png' border='0' />" : "<img src='application/layouts/scripts/".$front_template['theme_folder']."/images/mod_vacation_img/star-small-inactive.png' border='0' />";
                                                      echo $print_stars.'&nbsp;';
                        
                                                  }
                                              ?>										
                                        </div>
                                        
                                        <?php
                                        if(!empty($this->group_datas['review_id']))
                                        { 
                                            
                                            $review_match_no = htmlentities($this->review_helper->getNumOfReviews($related_matched['id'], $this->group_datas['review_id']));
                                        ?>
                                        <div class="products-review">											
                                            <div class="products-review-count"><a href="<?php echo $this->url(array('module' => 'Vacationrentals','controller' =>'frontend', 'action' => 'details','vacationrentals_title' => $this->escape($related_matched['vacationrentals_title']),'tab' => 8 ),'Vacationrentals-details/:vacationrentals_title/:tab',true); ?>"><?php echo $this->translator->translator('common_review_no',$review_match_no); ?></a>&nbsp;</div>
                                            <div class="products-write-review"><a href="<?php echo $this->url( array('module' => 'Review','controller' => 'frontend', 'action'     => 'write', 'group_id' => $this->escape($this->group_datas['review_id']), Eicra_File_Constants::ITEM_ID => $related_matched['id'] ), 'Review-Write/:group_id/:item_id',    true); ?>"><?php echo $this->translator->translator('common_write_review'); ?></a></div>
                                        </div>
                                        <?php
                                        }
                                        ?>
                                        
                                        <div class="thumb">
                                            <a href="<?php echo $this->url(array('module' => 'Vacationrentals','controller' =>'frontend', 'action' => 'details','vacationrentals_title' => $this->escape($related_matched['vacationrentals_title']) ),'Vacationrentals-details/:vacationrentals_title',true); ?>" class="preview" link="data/frontImages/vacationrentals/vacationrentals_image/<?php echo $related_matched['vacationrentals_primary_image'] ; ?>" title="<?php echo $this->escape($related_matched['vacationrentals_name']); ?>" width="300"><img src="data/frontImages/vacationrentals/vacationrentals_image/<?php echo $related_matched['vacationrentals_primary_image'] ; ?>"  width="70" height="50" border="0" alt="<?php echo strip_tags($this->escape($related_matched['vacationrentals_primary_image'])); ?>"></a>
                                        </div>
                                        
                                        <div class="products-desc">
                                            <?php echo $this->vacationrentals_Form->vacationrentals_price->getAttrib('font_end_label') . $color_sign . $this->escape($related_matched['vacationrentals_price']) ;?><br />
                                            <?php echo $this->vacationrentals_Form->feature_bedroom->getAttrib('font_end_label') . $color_sign . $this->escape($related_matched['feature_bedroom']) ;?><br />
                                            <?php echo $this->vacationrentals_Form->feature_bathroom->getAttrib('font_end_label') . $color_sign . $this->escape($related_matched['feature_bathroom']) ;?><br />
                                            <?php echo $this->vacationrentals_Form->feature_room_no->getAttrib('font_end_label') . $color_sign . $this->escape($related_matched['feature_room_no']) ;?><br />								
                                        </div>
                                   </div>				
                    <?php
                                }
                            }
                            
                        }
                    ?>
            	</div>
            
            	<div class="match-tab-container" id="matchTabs-2">
                            <?php
                                $vacationrentalsMatchPrice = $this->vacationrentals_database->getVacationrentalsMatchPrice($this->escape($item_id),$this->escape(  $this->vacationrentals_Form->vacationrentals_price->getValue()),$display_related_item_limit);
                                
                                if($vacationrentalsMatchPrice)
                                {
                                    
                                    foreach($vacationrentalsMatchPrice as $related_matched)
                                    {										
                            ?>	
                                <div class="products-match">
                                        <span><a href="<?php echo $this->url(array('module' => 'Vacationrentals','controller' =>'frontend', 'action' => 'details','vacationrentals_title' => $this->escape($related_matched['vacationrentals_title']) ),'Vacationrentals-details/:vacationrentals_title',true); ?>" title="<?php echo $this->escape($related_matched['vacationrentals_name']); ?>"><?php echo $this->escape($related_matched['vacationrentals_name']); ?></a></span>
                                        <div class="products-star">
                                            <?php
                                                  $hotel_stars = (int) $this->escape($related_matched['stars']);
                                                                                                           
                                                  for($i = 1; $i < $maximum_stars_digit ; $i++)
                                                  {
                                                      $print_stars = ($i <= $hotel_stars )  ? "<img src='application/layouts/scripts/".$front_template['theme_folder']."/images/mod_vacation_img/star-small-active.png' border='0' />" : "<img src='application/layouts/scripts/".$front_template['theme_folder']."/images/mod_vacation_img/star-small-inactive.png' border='0' />";
                                                      echo $print_stars.'&nbsp;';
                        
                                                  }
                                              ?>											
                                        </div>
                                        <?php
                                            if(!empty($this->group_datas['review_id']))
                                            { 
                                                $review_match_no = htmlentities($this->review_helper->getNumOfReviews($related_matched['id'], $this->group_datas['review_id']));
                                        ?>
                                        <div class="products-review">
                                            <div class="products-review-count"><a href="<?php echo $this->url(array('module' => 'Vacationrentals','controller' =>'frontend', 'action' => 'details','vacationrentals_title' => $this->escape($related_matched['vacationrentals_title']),'tab' => 8 ),'Vacationrentals-details/:vacationrentals_title/:tab',true); ?>"><?php echo $this->translator->translator('common_review_no',$review_match_no); ?></a>&nbsp;</div>
                                            <div class="products-write-review"><a href="<?php echo $this->url( array('module' => 'Review','controller' => 'frontend', 'action'     => 'write', 'group_id' => $this->escape($this->group_datas['review_id']), Eicra_File_Constants::ITEM_ID => $related_matched['id'] ), 'Review-Write/:group_id/:item_id',    true); ?>"><?php echo $this->translator->translator('common_write_review'); ?></a></div>
                                        </div>
                                        <?php
                                        }
                                        ?>
                                        <div class="thumb">
                                            <a href="<?php echo $this->url(array('module' => 'Vacationrentals','controller' =>'frontend', 'action' => 'details','vacationrentals_title' => $this->escape($related_matched['vacationrentals_title']) ),'Vacationrentals-details/:vacationrentals_title',true); ?>" class="preview" link="data/frontImages/vacationrentals/vacationrentals_image/<?php echo $related_matched['vacationrentals_primary_image'] ; ?>" title="<?php echo $this->escape($related_matched['vacationrentals_name']); ?>" width="300"><img src="data/frontImages/vacationrentals/vacationrentals_image/<?php echo $related_matched['vacationrentals_primary_image'] ; ?>"  width="70" height="50" border="0" alt="<?php echo strip_tags($this->escape($related_matched['vacationrentals_primary_image'])); ?>"></a>
                                        </div>
                                        
                                        <div class="products-desc">
                                            <?php echo $this->vacationrentals_Form->vacationrentals_price->getAttrib('font_end_label') . $color_sign . $this->escape($related_matched['vacationrentals_price']) ;?><br />
                                            <?php echo $this->vacationrentals_Form->feature_bedroom->getAttrib('font_end_label') . $color_sign . $this->escape($related_matched['feature_bedroom']) ;?><br />
                                            <?php echo $this->vacationrentals_Form->feature_bathroom->getAttrib('font_end_label') . $color_sign . $this->escape($related_matched['feature_bathroom']) ;?><br />
                                            <?php echo $this->vacationrentals_Form->feature_room_no->getAttrib('font_end_label') . $color_sign . $this->escape($related_matched['feature_room_no']) ;?><br />									
                                        </div>
                                   </div>
                
                        <?php	
                                }
                             
                            }
                        ?>    
            	</div>
            
            	<!--<div class="match-tab-container" id="matchTabs-3">
                              <?php
                                                
                                   /* $vacationrentalsMatchRegion = $this->vacationrentals_database->getVacationrentalsMatchRegion($this->escape($item_id), $this->escape( $state_id) , $this->escape( $area_id) ,$maximum_stars_digit);
                                    if($vacationrentalsMatchRegion)
                                    {
                                        foreach($vacationrentalsMatchRegion as $related_matched)
                                        { 
                                ?>		
                                  	<div class="products-match">               
                                            <span><a href="<?php echo $this->url(array('module' => 'Vacationrentals','controller' =>'frontend', 'action' => 'details','vacationrentals_title' => $this->escape($related_matched['vacationrentals_title']) ),'Vacationrentals-details/:vacationrentals_title',true); ?>"><?php echo $this->escape($related_matched['vacationrentals_name']); ?></a></span>
                                            <div class="products-star">
                                                <?php
                                                  $hotel_stars = (int) $this->escape($related_matched['stars']);
                                                                                                           
                                                  for($i = 1; $i < $maximum_stars_digit ; $i++)
                                                  {
                                                      $print_stars = ($i <= $hotel_stars )  ? "<img src='application/layouts/scripts/".$front_template['theme_folder']."/images/mod_vacation_img/star-small-active.png' border='0' />" : "<img src='application/layouts/scripts/".$front_template['theme_folder']."/images/mod_vacation_img/star-small-inactive.png' border='0' />";
                                                      echo $print_stars.'&nbsp;';
                                                  }
                                              ?>										
                                        </div>
                                        <?php
                                            if(!empty($this->group_datas['review_id']))
                                            { 
                                                $review_match_no = htmlentities($this->review_helper->getNumOfReviews($related_matched['id'], $this->group_datas['review_id']));
                                        ?>
                                        <div class="products-review">										
                                            <div class="products-review-count"><a href="<?php echo $this->url(array('module' => 'Vacationrentals','controller' =>'frontend', 'action' => 'details','vacationrentals_title' => $this->escape($related_matched['vacationrentals_title']),'tab' => 8 ),'Vacationrentals-details/:vacationrentals_title/:tab',true); ?>"><?php echo $this->translator->translator('common_review_no',$review_match_no); ?></a>&nbsp;</div>
                                            <div class="products-write-review"><a href="<?php echo $this->url( array('module' => 'Review','controller' => 'frontend', 'action'     => 'write', 'group_id' => $this->escape($this->group_datas['review_id']), Eicra_File_Constants::ITEM_ID => $related_matched['id'] ), 'Review-Write/:group_id/:item_id',    true); ?>"><?php echo $this->translator->translator('common_write_review'); ?></a></div>
                                        </div>
                                        <?php
                                        }
                                        ?>
                                        <div class="thumb">
                                            <a href="<?php echo $this->url(array('module' => 'Vacationrentals','controller' =>'frontend', 'action' => 'details','vacationrentals_title' => $this->escape($related_matched['vacationrentals_title']) ),'Vacationrentals-details/:vacationrentals_title',true); ?>" class="preview" link="data/frontImages/vacationrentals/vacationrentals_image/<?php echo $related_matched['vacationrentals_primary_image'] ; ?>" title="<?php echo $this->escape($related_matched['vacationrentals_name']); ?>" width="300"><img src="data/frontImages/vacationrentals/vacationrentals_image/<?php echo $related_matched['vacationrentals_primary_image'] ; ?>"  width="70" height="50" border="0" title="<?php echo $this->escape($related_matched['vacationrentals_primary_image']); ?>" alt="<?php echo strip_tags($this->escape($related_matched['vacationrentals_primary_image'])); ?>"></a>
                                        </div>
                                        
                                        <div class="products-desc">
                                            <?php echo $this->vacationrentals_Form->vacationrentals_price->getAttrib('font_end_label') . $color_sign . $this->escape($related_matched['vacationrentals_price']) ;?><br />
                                            <?php echo $this->vacationrentals_Form->feature_bedroom->getAttrib('font_end_label') . $color_sign . $this->escape($related_matched['feature_bedroom']) ;?><br />
                                            <?php echo $this->vacationrentals_Form->feature_bathroom->getAttrib('font_end_label') . $color_sign . $this->escape($related_matched['feature_bathroom']) ;?><br />
                                            <?php echo $this->vacationrentals_Form->feature_room_no->getAttrib('font_end_label') . $color_sign . $this->escape($related_matched['feature_room_no']) ;?><br />											
                                        </div>
                                   	</div>
                    <?php
                            
                            }
                            
                        }*/
                    ?>                    
            	</div>-->
            
            	<div class="match-tab-container" id="matchTabs-4">
                                <?php
                                $vacationrentalsMatchAgent = $this->vacationrentals_database->getVacationrentalsMatchAgent($this->escape($item_id),$this->escape($this->view_datas['vacationrentals_owner']),10);
                                    if($vacationrentalsMatchAgent){
                                                                            
                                            foreach($vacationrentalsMatchAgent as $related_matched)
                                            {
                                ?>		
                                 	<div class="products-match">
                                        <span><a href="<?php echo $this->url(array('module' => 'Vacationrentals','controller' =>'frontend', 'action' => 'details','vacationrentals_title' => $this->escape($related_matched['vacationrentals_title']) ),'Vacationrentals-details/:vacationrentals_title',true); ?>" title="<?php echo $this->escape($related_matched['vacationrentals_name']); ?>"><?php echo $this->escape($related_matched['vacationrentals_name']); ?></a></span>
                                        <div class="products-star">
                                             <?php
                                                  $hotel_stars = (int) $this->escape($related_matched['stars']);
                                                                                                           
                                                  for($i = 1; $i < $maximum_stars_digit ; $i++)
                                                  {
                                                      $print_stars = ($i <= $hotel_stars )  ? "<img src='application/layouts/scripts/".$front_template['theme_folder']."/images/mod_vacation_img/star-small-active.png' border='0' />" : "<img src='application/layouts/scripts/".$front_template['theme_folder']."/images/mod_vacation_img/star-small-inactive.png' border='0' />";
                                                      echo $print_stars.'&nbsp;';
                        
                                                  }
                                              ?>										
                                        </div>
                                        <?php
                                        if(!empty($this->group_datas['review_id']))
                                        { 
                                            $review_match_no = htmlentities($this->review_helper->getNumOfReviews($related_matched['id'], $this->group_datas['review_id']));
                                        ?>
                                        <div class="products-review">										
                                            <div class="products-review-count"><a href="<?php echo $this->url(array('module' => 'Vacationrentals','controller' =>'frontend', 'action' => 'details','vacationrentals_title' => $this->escape($related_matched['vacationrentals_title']),'tab' => 8 ),'Vacationrentals-details/:vacationrentals_title/:tab',true); ?>"><?php echo $this->translator->translator('common_review_no',$review_match_no); ?></a>&nbsp;</div>
                                            <div class="products-write-review"><a href="<?php echo $this->url( array('module' => 'Review','controller' => 'frontend', 'action'     => 'write', 'group_id' => $this->escape($this->group_datas['review_id']), Eicra_File_Constants::ITEM_ID => $related_matched['id'] ), 'Review-Write/:group_id/:item_id',    true); ?>"><?php echo $this->translator->translator('common_write_review'); ?></a></div>
                                        </div>
                                        <?php
                                        }
                                        ?>
                                        <div class="thumb">
                                            <a href="<?php echo $this->url(array('module' => 'Vacationrentals','controller' =>'frontend', 'action' => 'details','vacationrentals_title' => $this->escape($related_matched['vacationrentals_title']) ),'Vacationrentals-details/:vacationrentals_title',true); ?>" class="preview" link="data/frontImages/vacationrentals/vacationrentals_image/<?php echo $related_matched['vacationrentals_primary_image'] ; ?>" title="<?php echo $this->escape($related_matched['vacationrentals_name']); ?>" width="300"><img src="data/frontImages/vacationrentals/vacationrentals_image/<?php echo $related_matched['vacationrentals_primary_image'] ; ?>" border="0" width="70" height="50" alt="<?php echo strip_tags($this->escape($related_matched['vacationrentals_primary_image'])); ?>"></a>
                                        </div>
                                        
                                        <div class="products-desc">
                                            <?php echo $this->vacationrentals_Form->vacationrentals_price->getAttrib('font_end_label') . $color_sign . $this->escape($related_matched['vacationrentals_price']) ;?><br />
                                            <?php echo $this->vacationrentals_Form->feature_bedroom->getAttrib('font_end_label') . $color_sign . $this->escape($related_matched['feature_bedroom']) ;?><br />
                                            <?php echo $this->vacationrentals_Form->feature_bathroom->getAttrib('font_end_label') . $color_sign . $this->escape($related_matched['feature_bathroom']) ;?><br />
                                            <?php echo $this->vacationrentals_Form->feature_room_no->getAttrib('font_end_label') . $color_sign . $this->escape($related_matched['feature_room_no']) ;?><br />
                                        </div>
                                   	</div>
                    <?php
                            
                            }
                            
                        }
                    ?>                    
            	</div>
			</div>
		</div>
        <!-- Vacation Match End -->
    </div>
    <!-- Vacation Details Middle Tab End -->
    
    <!-- Vecation Bottom Tab Start -->
	<div id="tabs">
            <ul>
                <li><a href="<?php echo $tab_base_link; ?>#tabs-1"><?php echo $this->translator->translator('vacationrentals_front_page_vacationrentals_details'); ?></a></li>                    
                <li><a href="<?php echo $tab_base_link; ?>#tabs-2"><?php echo $this->translator->translator('vacationrentals_front_page_vacationrentals_gallery'); ?> <span class="photo-no"><?php if($this->vacationrentals_Form->vacationrentals_image->getValue()){ $photos_arr = explode(',', $this->vacationrentals_Form->vacationrentals_image->getValue() ); echo count($photos_arr); } else{ echo '0'; } ?></span></a></li>
                <li><a href="<?php echo $tab_base_link; ?>#tabs-3"><?php echo $this->translator->translator('vacationrentals_front_page_Other_exclusive_images'); ?> <span class="photo-no"><?php if($this->vacationrentals_Form->feature_others_exclusive_images->getValue()){ $photos_other_arr = explode(',', $this->vacationrentals_Form->feature_others_exclusive_images->getValue() ); echo count($photos_other_arr); } else{ echo '0'; } ?></span></a></li>
                <li><a href="<?php echo $tab_base_link; ?>#tabs-4"><?php echo $this->translator->translator('vacationrentals_front_page_Title_payment_amenities'); ?></a></li>
                <li><a href="<?php echo $tab_base_link; ?>#tabs-5"><?php echo $this->translator->translator('vacationrentals_front_page_vacationrentals_available'); ?></a></li>
                <li><a href="<?php echo $tab_base_link; ?>#tabs-6"><?php echo $this->translator->translator('vacationrentals_front_page_vacationrentals_brochure'); ?></a></li>
                <li><a href="<?php echo $tab_base_link; ?>#tabs-7"><?php echo $this->translator->translator('vacationrentals_front_page_Title_payment_process'); ?></a></li>
                <li><a href="<?php echo $tab_base_link; ?>#tabs-8"><?php echo $this->translator->translator('vacationrentals_front_page_vacationrentals_map'); ?></a></li>
                <?php
                        if(!empty($this->group_datas['review_id']))
                        {
                            echo '<li><a href="'.$tab_base_link.'#tabs-9">'.$this->translator->translator('vacationrentals_front_page_vacationrentals_review').'</a></li>';
                        }
                        if(!empty($this->group_datas['dynamic_form']))
                        {									
                            $staticGroupsObj = $this->vacationrentals_Form->getDisplayGroups();
                            if($staticGroupsObj)
                            {
                                $tabs = (!empty($this->group_datas['review_id'])) ? 10 : 9;
                                foreach($staticGroupsObj as $staticGroup)
                                {
                                    echo '<li><a href="'.$tab_base_link.'#tabs-'.$tabs.'">'.$this->translator->translator($staticGroup->getAttrib('title')).'</a></li>';
                                    $tabs++;
                                }
                            }
                        }
                        else
                        {
                            $staticGroupsObj = null;
                        }
                    ?>
            </ul>
            
            <div id="tabs-1">
                <!-- Vacation Left Feature Start -->
                <div class="products-feature">
                    <div class="products-details">
                       <div class="products-details-header"><h4 class="icon"><?php echo $this->translator->translator('vacationrentals_front_page_Title_detail'); ?></h4></div>
                       <div class="content feature-content">
                            <?php 
                                $_vacationrentals_price = $this->escape($this->vacationrentals_Form->vacationrentals_price->getValue()); 
                                if (!empty($_vacationrentals_price)) {	
                             ?>
                            <div class="label"><?php echo $this->vacationrentals_Form->vacationrentals_price->getAttrib('font_end_label'); ?></div>
                            <div class="value"><?php echo $_vacationrentals_price  ?></div>
                            
                            <?php 
                                }
                                $_vacationrentals_name = $this->escape($this->vacationrentals_Form->vacationrentals_name->getValue()); 
                                if (!empty($_vacationrentals_name)) {								
                            ?>
                            <div class="label"><?php echo $this->vacationrentals_Form->vacationrentals_name->getAttrib('font_end_label'); ?></div>
                            <div class="value"><?php echo $_vacationrentals_name; ?></div>
                            
                            <?php 
                                }
                                $_house_name = $this->escape($this->vacationrentals_Form->house_name->getValue()); 
                                if (!empty($_house_name)) {								
                            ?>          
                            <div class="label"><?php echo $this->vacationrentals_Form->house_name->getAttrib('font_end_label'); ?></div>
                            <div class="value"><?php echo $_house_name; ?></div>
                            
                            <?php 
                                }
                                $_location_type = $this->escape($this->vacationrentals_Form->location_type->getValue()); 
                                if (!empty($_location_type)) {								
                            ?>
                            <div class="label"><?php echo $this->vacationrentals_Form->location_type->getAttrib('font_end_label');  ?></div>
                            <div class="value"><?php echo $_location_type; ?></div>
                            
                            <?php 
                                }
                                $_feature_bedroom = $this->escape($this->vacationrentals_Form->feature_bedroom->getValue()); 
                                if (!empty($_feature_bedroom)) {								
                            ?>
                            <div class="label"><?php echo $this->vacationrentals_Form->feature_bedroom->getAttrib('font_end_label');  ?></div>
                            <div class="value"><?php echo $_feature_bedroom; ?></div>
                            
                            <?php 
                                }
                                $_feature_bathroom = $this->escape($this->vacationrentals_Form->feature_bathroom->getValue()); 
                                if (!empty($_feature_bathroom)) {								
                            ?>
                            
                            <div class="label"><?php echo $this->vacationrentals_Form->feature_bathroom->getAttrib('font_end_label');  ?></div>
                            <div class="value"><?php echo $_feature_bathroom; ?></div>
                            
                            <?php 
                                }
                                $_accommodates = $this->escape($this->vacationrentals_Form->accommodates->getValue()); 
                                if (!empty($_accommodates)) {								
                            ?>
                            <div class="label"><?php echo $this->vacationrentals_Form->accommodates->getAttrib('font_end_label');  ?></div>
                            <div class="value"><?php echo $_accommodates; ?></div>
                            
                            <?php 
                                }
                                $_property_size = $this->escape($this->vacationrentals_Form->property_size->getValue()); 
                                if (!empty($_property_size)) {								
                            ?>
                            <div class="label"><?php echo $this->vacationrentals_Form->property_size->getAttrib('font_end_label');  ?></div>
                            <div class="value"><?php echo $_property_size; ?></div>
                            
                            <?php 
                                }
                                $_feature_reception = $this->escape($this->vacationrentals_Form->feature_reception->getValue()); 
                                if (!empty($_feature_reception)) {								
                            ?>
                            <div class="label"><?php echo  $this->vacationrentals_Form->feature_reception->getAttrib('font_end_label'); ?></div>
                            <div class="value"><?php echo  $_feature_reception ; ?></div>
                            
                            <?php 
                                }
                                $_feature_kitchen = $this->escape($this->vacationrentals_Form->feature_kitchen->getValue()); 
                                if (!empty($_feature_kitchen)) {								
                            ?>
                            <div class="label"><?php echo $this->vacationrentals_Form->feature_kitchen->getAttrib('font_end_label');  ?></div>
                            <div class="value"><?php echo $_feature_kitchen; ?></div>
                            
                            <?php 
                                }
                                $_feature_garden = $this->escape($this->vacationrentals_Form->feature_garden->getValue()); 
                                if (!empty($_feature_garden)) {								
                            ?>
                            <div class="label"><?php echo $this->vacationrentals_Form->feature_garden->getAttrib('font_end_label');  ?></div>
                            <div class="value"><?php echo $_feature_garden; ?></div>
                            
                            <?php 
                                }
                                $_feature_conservatory = $this->escape($this->vacationrentals_Form->feature_conservatory->getValue()); 
                                if (!empty($_feature_conservatory)) {								
                            ?>
                            <div class="label"><?php echo $this->vacationrentals_Form->feature_conservatory->getAttrib('font_end_label');  ?></div>
                            <div class="value"><?php echo $_feature_conservatory; ?></div>
                            
                            <?php 
                                }
                                $_feature_garage = $this->escape($this->vacationrentals_Form->feature_garage->getValue()); 
                                if (!empty($_feature_garage)) {								
                            ?>
                            <div class="label"><?php echo $this->vacationrentals_Form->feature_garage->getAttrib('font_end_label');  ?></div>
                            <div class="value"><?php echo $_feature_garage; ?></div>
                            
                            <?php 
                                }
                                $_entertainments = $this->escape($this->vacationrentals_Form->entertainments->getValue()); 
                                if (!empty($_entertainments)) {								
                            ?>
                            <div class="label"><?php echo $this->vacationrentals_Form->entertainments->getAttrib('font_end_label');  ?></div>
                            <div class="value"><?php echo $_entertainments; ?></div>
                            
                            <?php 
                                }
                                $_gusts_allowed = $this->escape($this->vacationrentals_Form->gusts_allowed->getValue()); 
                                if (!empty($_gusts_allowed)) {								
                            ?>
                            <div class="label"><?php echo $this->vacationrentals_Form->gusts_allowed->getAttrib('font_end_label');  ?></div>
                            <div class="value"><?php echo $_gusts_allowed; ?></div>
                            
                            <?php 
                                }
                                $_number_of_sleeps = $this->escape($this->vacationrentals_Form->number_of_sleeps->getValue()); 
                                if (!empty($_number_of_sleeps)) {								
                            ?>
                            <div class="label"><?php echo $this->vacationrentals_Form->number_of_sleeps->getAttrib('font_end_label');  ?></div>
                            <div class="value"><?php echo $_number_of_sleeps; ?></div>
                            <?php 
                                }
                            ?>
                       </div>
                    </div>
                </div>
                    
                <!-- Vacation Left Feature End -->
                
                <!-- Vacation Summary Start -->
                <div class="products-feature summary">
                    <div class="products-details">
                        <div class="products-details-header"><h4 class="icon"><?php echo $this->translator->translator('vacationrentals_front_page_Title_summary'); ?></h4></div>
                            <div class="content feature-content">
                                <div class="summary-label"><?php echo $this->vacationrentals_Form->post_code->getAttrib('font_end_label') ;  ?></div>
                                <div class="summary-value"><?php echo $this->vacationrentals_Form->post_code->getValue()?></div>
                                
                                <div class="summary-label"><?php echo $this->vacationrentals_Form->feature_room_no->getAttrib('font_end_label');  ?></div>
                                <div class="summary-value"><?php echo (int)$this->escape($this->vacationrentals_Form->feature_room_no->getValue()); ?></div>
                                
                                <div class="summary-label"><?php echo $this->vacationrentals_Form->area_id->getAttrib('font_end_label') ?></div>
                                <div class="summary-value"><?php echo $this->escape( $area_info['city']); ?></div>
                                 
                                <div class="summary-label"><?php echo $this->vacationrentals_Form->feature_bathroom->getAttrib('font_end_label') ; ?></div>
                                <div class="summary-value"><?php echo $this->escape( $this->vacationrentals_Form->feature_bathroom->getValue() ); ?></div>
                                
                                <div class="summary-label"><?php echo $this->vacationrentals_Form->state_id->getAttrib('font_end_label');  ?></div>
                                <div class="summary-value"><?php echo $this->escape( $state_info['state_name']); ?></div>
                                
                                <div class="summary-label"><?php echo $this->vacationrentals_Form->feature_bedroom->getAttrib('font_end_label'); ?></div>
                                <div class="summary-value"><?php echo $this->escape($this->vacationrentals_Form->feature_bedroom->getValue()); ?></div>
                                 
                                <div class="summary-label"><?php echo $this->vacationrentals_Form->country_id->getAttrib('font_end_label');  ?></div>
                                <div class="summary-value"><?php echo $this->escape($country_info['value']); ?></div>
                                
                                <div class="summary-label"><?php echo $this->vacationrentals_Form->minimum_stay_nights->getAttrib('font_end_label');  ?></div>
                                <div class="summary-value"><?php echo $this->escape($this->vacationrentals_Form->minimum_stay_nights->getValue()); ?></div>
                            </div>
                    </div>                    
                </div>
                <!-- Vacation Summary End -->
                
                <!-- Vacation Agent Start-->
                <?php
                        //Checking Membership Package Option
                        $packages = new Members_Controller_Helper_Packages();
                        $general_db = new Members_Model_DbTable_General();
                        $forms_db = new Members_Model_DbTable_Forms();
                        $mem_info = (isnot_int($this->view_datas['vacationrentals_owner'])) ? $this->agent_list->getMemberInfo($this->view_datas['entry_by']) : $this->agent_list->getMemberInfo($this->view_datas['vacationrentals_owner']);	
                        $module = $this->module;
                        $controller = $this->controller;
                        $action = $this->action;
                        
                        if($packages->checkFormAvailable('Default Info'))
                        {
                            $default_form_id  = $forms_db->getFormId('Default Info');
                            $default_form_info['form_id'] = 	$default_form_id[0]['id'];
                            $default_general_info = $general_db->getAllValues($default_form_id[0]['id']);												
                            $dynamic_valu_db = new Members_Model_DbTable_FieldsValue();	
                            
                            if($default_general_info)
                            {								
                                $default_general_info = (!empty($default_general_info[0]) && !empty($default_general_info[0]['id'])) ? $default_general_info :  $default_general_info->toArray();
                                $default_form_info	=	$dynamic_valu_db->getFieldsValueInfo($default_form_info,$default_general_info[0]['id']);									
                            }
                            else
                            {
                                $default_form_info = null;
                            }							
                        }
                        else
                        {
                            $default_form_info = null;
                        }
                        if($packages->isPackageFrontend($mem_info['user_id'],$mem_info['role_id']))
                        {								
                            if($packages->isPackageFrontendField($module,$controller,$action,$mem_info['user_id'],$mem_info['role_id']))
                            {
                                $package_no = $packages->getPackageFrontendFieldValue($module,$controller,$action,$mem_info['user_id'],$mem_info['role_id']);				
                            }
                            else
                            {
                                $package_no = 'Off';
                            }
                        }
                        else
                        {
                            $package_no = 'On';
                        }
                    if($package_no == 'On')
                    {		
                ?>
                <div class="products-agent">
                    <div class="products-details">
                       		<div class="products-details-header"><h4 class="icon"><?php echo $this->translator->translator('vacationrentals_front_page_Title_realtor'); ?></h4></div>
                       		<div class="content">
                                 	<?php
                                    if($this->escape($this->view_datas['vacationrentals_owner']))
                                    {
                                        $this->agent_list = new Members_Model_DbTable_MemberList();
                                        $owner_info = (isnot_int($this->view_datas['vacationrentals_owner'])) ? $this->escape($this->view_datas['vacationrentals_owner']) : $this->agent_list->getMemberInfo($this->escape($this->view_datas['vacationrentals_owner']));
                                        $owner_name = (is_array($owner_info)) ? $owner_info['title'].' '.$owner_info['firstName'].' '.$owner_info['lastName'] : $owner_info;	
                                        
                                        $mem_user_id = (is_array($owner_info)) ? $owner_info['user_id'] : $mem_info['user_id'];
                                        $mem_role_id = (is_array($owner_info)) ? $owner_info['role_id'] : $mem_info['role_id'];
                                        if(is_array($owner_info))
                                        {
                                            $role_db = new Members_Model_DbTable_Role();
                                            $role_info = $role_db->getRoleInfo($owner_info['role_id']);
                                            $owner_info['form_id'] = 	$role_info['form_id'];
                                            $dynamic_valu_db = new Members_Model_DbTable_FieldsValue();	
                                            $owner_info	=	$dynamic_valu_db->getFieldsValueInfo($owner_info,$owner_info['user_id']);
                                            foreach($owner_info as $key=>$value)
                                            {
                                                $field_name_arr = explode('_',$key);
                                                if(in_array('package',$field_name_arr))
                                                {
                                                    $package_info = $packages->getFormAllDatas($value);
                                                }
                                            }
                                        }
                                        else
                                        {
                                            $mem_user_id = $mem_info['user_id'];
                                            $mem_role_id = $mem_info['role_id'];
                                            $role_db = new Members_Model_DbTable_Role();
                                            $role_info = $role_db->getRoleInfo($mem_role_id);
                                            $mem_info['form_id'] = 	$role_info['form_id'];
                                            $dynamic_valu_db = new Members_Model_DbTable_FieldsValue();	
                                            $mem_info	=	$dynamic_valu_db->getFieldsValueInfo($mem_info,$mem_user_id);
                                            foreach($mem_info as $key=>$value)
                                            {
                                                $field_name_arr = explode('_',$key);
                                                if(in_array('package',$field_name_arr))
                                                {
                                                    $package_info = $packages->getFormAllDatas($value);
                                                }
                                            }
                                        }
                                    }
                                    else
                                    {
                                        $mem_user_id = $mem_info['user_id'];
                                        $mem_role_id = $mem_info['role_id'];
                                        $role_db = new Members_Model_DbTable_Role();
                                        $role_info = $role_db->getRoleInfo($mem_role_id);
                                        $mem_info['form_id'] = 	$role_info['form_id'];
                                        $dynamic_valu_db = new Members_Model_DbTable_FieldsValue();	
                                        $mem_info	=	$dynamic_valu_db->getFieldsValueInfo($mem_info,$mem_user_id);
                                        foreach($mem_info as $key=>$value)
                                        {
                                            $field_name_arr = explode('_',$key);
                                            if(in_array('package',$field_name_arr))
                                            {
                                                $package_info = $packages->getFormAllDatas($value);
                                            }
                                        }
                                    }
                                    
                                    ?>
                                    <?php
                                        if(is_array($owner_info))
                                        {											
                                            if($owner_info['member_photo'])
                                            {
                                                $owner_forms_info = $forms_db->getFormsInfo($role_info['form_id']);
                                                $member_photo_path = $owner_forms_info['attach_file_path'];
                                                $member_photo = $member_photo_path.'/'.$owner_info['member_photo'];
                                                $member_photo_width = 'width="'.$default_form_info['member_photo_width_default'].'"';
                                                $member_photo_height = 'height="'.$default_form_info['member_photo_height_default'].'"';
                                            }
                                            else
                                            {												
                                                    if(!empty($default_form_info))
                                                    {
                                                            $member_photo = $this->serverUrl().$this->baseUrl().'/'. $default_form_id[0]['attach_file_path'].'/'.$default_form_info['member_photo_default'];
                                                            $member_photo_width = 'width="'.$default_form_info['member_photo_width_default'].'"';
                                                            $member_photo_height = 'height="'.$default_form_info['member_photo_height_default'].'"';
                                                    }
                                                    else
                                                    {
                                                            $member_photo = 'data/frontImages/vacationrentals/design_images/no_user_image.gif';
                                                            $member_photo_width = 'width="75"';
                                                            $member_photo_height = 'height="87"';
                                                    }
                                            }
                                        }
                                        else
                                        {
                                            if(!empty($default_form_info))
                                            {
                                                    $member_photo = $this->serverUrl().$this->baseUrl().'/'. $default_form_id[0]['attach_file_path'].'/'.$default_form_info['member_photo_default'];
                                                    $member_photo_width = 'width="'.$default_form_info['member_photo_width_default'].'"';
                                                    $member_photo_height = 'height="'.$default_form_info['member_photo_height_default'].'"';
                                            }
                                            else
                                            {
                                                    $member_photo = 'data/frontImages/vacationrentals/design_images/no_user_image.gif';
                                                    $member_photo_width = 'width="75"';
                                                    $member_photo_height = 'height="87"';
                                            }
                                        }
                                                                            
                                	?>
                                    <img src="<?php echo $member_photo; ?>" <?php echo $member_photo_width.' '.$member_photo_height; ?> class="avatar" />   
                                    <div>
                                        <span class="label"><?php echo $this->translator->translator('vacationrentals_front_page_label_presented');  ?></span>&nbsp;
										<span class="value"><?php echo $this->escape($owner_name); ?></span>
                                    </div>
                                    
                                   
                                  	<div class="pkg-img">
                                            <?php												
                                                if($packages->isPackageFrontendField($module,$controller,$action.'_pic',$mem_user_id,$mem_role_id))
                                                {		
                                                    $package_pic_info = $packages->getPackageFrontendFieldDetailsValue($module,$controller,$action.'_pic',$mem_user_id,$mem_role_id);				
                                                    if(!empty($package_pic_info))
                                                    {
                                                        $forms_info = $forms_db->getFormsInfo($package_pic_info['form_id']);
                                                        if(!empty($package_pic_info['field_value']))
                                                        {
                                                            $package_pic = $this->serverUrl().$this->baseUrl().'/'. $forms_info['attach_file_path'].'/'.$package_pic_info['field_value'];
                                                            $package_pic_width = $packages->getPackageFrontendFieldValue($module,$controller,$action.'_pic_width',$mem_user_id,$mem_role_id);
                                                            $package_pic_height = $packages->getPackageFrontendFieldValue($module,$controller,$action.'_pic_height',$mem_user_id,$mem_role_id);
                                                            $package_pic_width_field = ($package_pic_width) ? 'width="'.$package_pic_width.'"' : '';
                                                            $package_pic_height_field = ($package_pic_width) ? 'height="'.$package_pic_height.'"' : '';
                                                        }
                                                        else
                                                        {
                                                            $package_pic = $this->serverUrl().$this->baseUrl().'/'. $default_form_id[0]['attach_file_path'].'/'.$default_form_info['property_frontend_details_pic_default'];
                                                            $package_pic_width_field = (!empty($default_form_info['property_frontend_details_pic_width_default'])) ? 'width="'.$default_form_info['property_frontend_details_pic_width_default'].'"' : '';
                                                            $package_pic_height_field = (!empty($default_form_info['property_frontend_details_pic_height_default'])) ? 'height="'.$default_form_info['property_frontend_details_pic_height_default'].'"' : '';
                                                        }
                                                    }
                                                    else
                                                    {
                                                        $package_pic = $this->serverUrl().$this->baseUrl().'/'. $default_form_id[0]['attach_file_path'].'/'.$default_form_info['property_frontend_details_pic_default'];
                                                        $package_pic_width_field = (!empty($default_form_info['property_frontend_details_pic_width_default'])) ? 'width="'.$default_form_info['property_frontend_details_pic_width_default'].'"' : '';
                                                        $package_pic_height_field = (!empty($default_form_info['property_frontend_details_pic_height_default'])) ? 'height="'.$default_form_info['property_frontend_details_pic_height_default'].'"' : '';
                                                    }
                                                }
                                                else
                                                {
                                                    $package_pic = $this->serverUrl().$this->baseUrl().'/'. $default_form_id[0]['attach_file_path'].'/'.$default_form_info['property_frontend_details_pic_default'];
                                                    $package_pic_width_field = (!empty($default_form_info['property_frontend_details_pic_width_default'])) ? 'width="'.$default_form_info['property_frontend_details_pic_width_default'].'"' : '';
                                                    $package_pic_height_field = (!empty($default_form_info['property_frontend_details_pic_height_default'])) ? 'height="'.$default_form_info['property_frontend_details_pic_height_default'].'"' : '';
                                                }												
                                                if($package_pic)
                                                {
                                            ?>
                                            <img src="<?php echo $package_pic; ?>" <?php echo $package_pic_width_field.' '.$package_pic_height_field; ?> />
                                            <?php
                                                }
                                            ?>	
                                        </div>   
                                        <span class="label"><?php if(($package_info[0]['field_value'])){ echo $this->translator->translator('common_package_name_title'); } ?></span><br />
                                        <div class="pkg-title"><?php echo $this->escape($package_info[0]['field_value']); ?></div>
                                    	<hr />
                                    
										<?php									
                                            if($packages->isPackageFrontendField($module,$controller,$action.'_certified',$mem_user_id,$mem_role_id))
                                            {
                                                $allow_certified = $packages->getPackageFrontendFieldValue($module,$controller,$action.'_certified',$mem_user_id,$mem_role_id);													
                                            }
                                            else
                                            {
                                                $allow_certified = 'No';
                                            }
                                            if($packages->isPackageFrontendField($module,$controller,$action.'_allow_logo',$mem_user_id,$mem_role_id))
                                            {
                                                $allow_logo = $packages->getPackageFrontendFieldValue($module,$controller,$action.'_allow_logo',$mem_user_id,$mem_role_id);				
                                            }
                                            else
                                            {
                                                $allow_logo = 'No';
                                            }                                        
                                        ?>
                                    
                                    <div>
                                        <?php		
                                            if($allow_logo == 'Yes')
                                            {									
                                                if(is_array($owner_info))
                                                {
                                                    if($owner_info['company_logo'])
                                                    {
                                                        if(empty($owner_forms_info))
                                                        {
                                                            $owner_forms_info = $forms_db->getFormsInfo($role_info['form_id']);
                                                        }
                                                        $company_logo_path = $owner_forms_info['attach_file_path'];
                                                        $company_logo = $company_logo_path.'/'.$owner_info['company_logo'];
                                                        $company_logo_width = ($default_form_info['company_logo_width_default']) ? 'width="'.$default_form_info['company_logo_width_default'].'"' : '';
                                                        $company_logo_height = ($default_form_info['company_logo_height_default']) ? 'height="'.$default_form_info['company_logo_height_default'].'"' : '';
                                                    }
                                                    else
                                                    {
                                                        if(!empty($default_form_info))
                                                        {
                                                            $company_logo = $this->serverUrl().$this->baseUrl().'/'. $default_form_id[0]['attach_file_path'].'/'.$default_form_info['company_logo_default'];
                                                            $company_logo_width = ($default_form_info['company_logo_width_default']) ? 'width="'.$default_form_info['company_logo_width_default'].'"' : '';
                                                            $company_logo_height = ($default_form_info['company_logo_height_default']) ? 'height="'.$default_form_info['company_logo_height_default'].'"' : '';
                                                        }
                                                        else
                                                        {
                                                            $company_logo = 'data/frontImages/vacationrentals/design_images/no_company_logo.gif';
                                                            $company_logo_width = 'width="80"';
                                                            $company_logo_height = 'height="60"';
                                                        }
                                                    }
                                                }
                                                else
                                                {
                                                    if(!empty($default_form_info))
                                                    {
                                                        $company_logo = $this->serverUrl().$this->baseUrl().'/'. $default_form_id[0]['attach_file_path'].'/'.$default_form_info['company_logo_default'];
                                                        $company_logo_width = ($default_form_info['company_logo_width_default']) ? 'width="'.$default_form_info['company_logo_width_default'].'"' : '';
                                                        $company_logo_height = ($default_form_info['company_logo_height_default']) ? 'height="'.$default_form_info['company_logo_height_default'].'"' : '';
                                                    }
                                                    else
                                                    {
                                                        $company_logo = 'data/frontImages/vacationrentals/design_images/no_company_logo.gif';
                                                        $company_logo_width = 'width="80"';
                                                        $company_logo_height = 'height="60"';
                                                    }
                                                }
                                        ?>
                                        <img src="<?php echo $company_logo; ?>" <?php echo $company_logo_width.' '.$company_logo_height; ?> class="company-logo" />
                                        <?php
                                            }
                                        ?>
                                    </div>
                                    <?php													
                                        if($packages->isPackageFrontendField($module,$controller,$action.'_contact_directly',$mem_user_id,$mem_role_id))
                                        {
                                            $contact_directly = $packages->getPackageFrontendFieldValue($module,$controller,$action.'_contact_directly',$mem_user_id,$mem_role_id);				
                                        }
                                        else
                                        {
                                            $contact_directly = 'No';
                                        }
                                        if($contact_directly == 'Yes')
                                        {
                                     ?>
                                    <div class="company-info">
                                        <?php if(is_array($owner_info) && !empty($owner_info['companyName'])){ ?>
                                        <!-- Company Name -->
                                        <div>
                                            <span class="label"><?php echo $this->translator->translator('vacationrentals_front_page_label_company'); ?></span>
                                            <?php  echo $this->escape($owner_info['companyName']); ?>
                                        </div>
                                        <!-- Company Name -->
                                        <?php
                                            }													
                                         ?>
                                        <!-- Address -->
                                        <div>
                                            <span class="label"><?php echo $this->translator->translator('vacationrentals_front_page_label_contact'); ?></span><br />
                                            <?php //echo $this->translator->translator('vacationrentals_front_page_label_house_no'); ?><!--&nbsp; --><?php //echo $this->escape($this->view_datas['house_no']); ?><!--<br /> -->
                                            
                                            <?php echo $this->translator->translator('vacationrentals_front_page_label_city'); 
                                            if(is_array($owner_info) && $owner_info['city'])
                                            {												
                                                echo " ".$this->escape($owner_info['city']);
                                            }
                                            ?><br />
                                            
                                            <?php echo $this->translator->translator('vacationrentals_front_page_label_state'); 
                                            if(is_array($owner_info) && $owner_info['state'])
                                            {
                                                echo " ".$this->escape($owner_info['state']);
                                            }
                                            ?><br />
                                            
                                            <?php echo $this->translator->translator('vacationrentals_front_page_label_country'); 
                                            if(is_array($owner_info) && $owner_info['country'])
                                            {
                                                $owner_country_info = $country_db->getCountryName($owner_info['country']);
                                                echo " ".$this->escape($owner_country_info['value']);
                                            }
                                            ?><br />
                                            
                                            <?php echo $this->translator->translator('vacationrentals_front_page_label_postcode'); 
                                            echo " ".$this->escape($owner_info['postalCode']);	
                                            ?>
                                        </div>                                        
                                        <!-- Address -->
                                        
                                        <!-- Tel -->
                                        <?php											
                                            if(is_array($owner_info) && $owner_info['phone'])
                                            {
                                        ?>										
                                            <div>
                                                <span class="label"><?php echo $this->translator->translator('vacationrentals_front_page_label_phone'); ?></span>
                                                <?php echo $this->escape($owner_info['phone']); ?>
                                            </div>                                                                      
                                        <?php
                                            }
                                        ?>
                                        <!-- Tel --> 
                                        
                                        <!-- Fax -->
                                        <?php
                                            //$hotels_fax = $this->hotelsForm->hotels_fax->getValue();
                                            if(is_array($owner_info) && !empty($owner_info['fax']))
                                            {
                                        ?>                                        
                                            <div>
                                                <span class="label"><?php echo $this->translator->translator('vacationrentals_front_page_label_fax'); ?></span>
                                                <?php echo $this->escape($owner_info['fax']); ?>
                                            </div>										
                                        <?php
                                            }
                                        ?>
                                        <!-- Fax -->
                                        
                                        <!-- Email -->
                                        <div>
                                            <a href="<?php if(is_array($owner_info)){ echo 'mailto:'.$this->escape($owner_info['username']); }else{ echo 'mailto:'.$this->escape($this->view_datas['house_email']) ;} ?>" class="agent-email"><?php echo $this->translator->translator('vacationrentals_front_page_label_email_lang'); ?></a>
                                        </div>
                                        <!-- Email -->
                                        
                                        <!-- Web -->
                                        <?php								  		
                                        if(is_array($owner_info) && !empty($owner_info['website']))
                                        {
                                        ?>                                        
                                        <div>
                                            <span class="label"><?php echo $this->translator->translator('vacationrentals_front_page_label_web'); ?></span>
                                            <a href="<?php if(is_array($owner_info)){ echo 'http://'.$this->escape($owner_info['website']); } ?>" target="_blank" class="agent-web"><?php if(is_array($owner_info)){ echo $this->escape($owner_info['website']); } ?></a>
                                        </div>                                        
                                        <?php
                                        }
                                        ?>
                                        <!-- Web -->												
                                    </div>
                                    <?php
                                        }
                                    ?>
                                    <?php
                                        if($allow_certified == 'Yes')
                                        {
                                    ?>
                                   	<hr />                                    
                                  	<!-- Certifdicate -->
                                    <div class="certificate">
                                   	<?php						
                                            if($packages->isPackageFrontendField($module,$controller,$action.'_pic_certi',$mem_user_id,$mem_role_id))
                                            {
                                                $package_pic_certi_info = $packages->getPackageFrontendFieldDetailsValue($module,$controller,$action.'_pic_certi',$mem_user_id,$mem_role_id);				
                                                if(!empty($package_pic_certi_info))
                                                {
                                                    $forms_info = $forms_db->getFormsInfo($package_pic_certi_info['form_id']);
                                                    if(!empty($package_pic_certi_info['field_value']))
                                                    {
                                                        $package_pic_certi = $this->serverUrl().$this->baseUrl().'/'. $forms_info['attach_file_path'].'/'.$package_pic_certi_info['field_value'];
                                                        $package_pic_certi_width = $packages->getPackageFrontendFieldValue($module,$controller,$action.'_pic_certi_width',$mem_user_id,$mem_role_id);
                                                        $package_pic_certi_height = $packages->getPackageFrontendFieldValue($module,$controller,$action.'_pic_certi_height',$mem_user_id,$mem_role_id);
                                                        $package_pic_certi_width_field = ($package_pic_certi_width) ? 'width="'.$package_pic_certi_width.'"' : '';
                                                        $package_pic_certi_height_field = ($package_pic_certi_height) ? 'height="'.$package_pic_certi_height.'"' : '';
                                                    }
                                                    else
                                                    {
                                                        $certi_pic_arr = explode(',',$default_form_info['property_frontend_details_pic_certi_default']);
                                                        $package_pic_certi = $this->serverUrl().$this->baseUrl().'/'. $default_form_id[0]['attach_file_path'].'/'.$certi_pic_arr[0];
                                                        $package_pic_certi_width_field = ($default_form_info['property_frontend_details_pic_certi_width_default']) ? 'width="'.$default_form_info['property_frontend_details_pic_certi_width_default'].'"' : '';
                                                        $package_pic_certi_height_field = ($default_form_info['property_frontend_details_pic_certi_height_default']) ? 'height="'.$default_form_info['property_frontend_details_pic_certi_height_default'].'"' : '';
                                                    }
                                                }
                                                else
                                                {
                                                    $certi_pic_arr = explode(',',$default_form_info['property_frontend_details_pic_certi_default']);
                                                    $package_pic_certi = $this->serverUrl().$this->baseUrl().'/'. $default_form_id[0]['attach_file_path'].'/'.$certi_pic_arr[0];
                                                    $package_pic_certi_width_field = ($default_form_info['property_frontend_details_pic_certi_width_default']) ? 'width="'.$default_form_info['property_frontend_details_pic_certi_width_default'].'"' : '';
                                                    $package_pic_certi_height_field = ($default_form_info['property_frontend_details_pic_certi_height_default']) ? 'height="'.$default_form_info['property_frontend_details_pic_certi_height_default'].'"' : '';
                                                }
                                            }
                                            else
                                            {
                                                $package_pic_certi = null;
                                            }
                                            if($package_pic_certi)
                                            {
                                    ?>
                                            <img src="<?php echo $package_pic_certi; ?>" <?php echo $package_pic_certi_width_field.' '.$package_pic_certi_height_field; ?> />
                                    <?php
                                            }											
                                        ?>
                                        <p><?php if($allow_certified == 'Yes'){ echo $this->translator->translator('vacationrentals_front_page_label_verified'); } ?></p>
                                    </div>
                                   	<!-- Certificate -->
                                    <?php
                                        }
                                    ?>
                        	</div>
                 	</div>
                </div>
                <?php
                }
                ?>
                <!-- Vacation Agent End-->
                
                <div class="products-details">
                   	<div class="products-details-header"><h4 class="icon"><?php echo $this->translator->translator('vacationrentals_front_page_vacationrentals_details'); ?></h4></div>
                   	<div class="content">
				   		<div class="details-info"><?php echo stripslashes($this->vacationrentals_Form->vacationrentals_desc->getValue()); ?></div>
					</div>
                </div> 
            </div>
            
            <div id="tabs-2">
           		<h2><?php echo $this->translator->translator('vacationrentals_front_page_Title_images'); ?></h2>
                
					<?php
                        if($this->group_datas['file_thumb_width'] && ($this->group_datas['file_thumb_resize_func'] != 'resizeToHeight' || $this->group_datas['file_thumb_resize_func'] != 'resize' ))
                        { 
                            $width_img = 'width="'.$this->escape($this->group_datas['file_thumb_width']).'"'; 
                        }
                        else
                        {
                            $width_img = '';
                        } 
                        if($this->group_datas['file_thumb_height'] && ( $this->group_datas['file_thumb_resize_func'] != 'resizeToWidth' || $this->group_datas['file_thumb_resize_func'] != 'resize' ))
                        { 
                            $height_img = 'height="'.$this->escape($this->group_datas['file_thumb_height']).'"'; 
                        } 
                        else
                        {
                            $height_img = '';
                        }
                        $img_arr = explode(',',$this->vacationrentals_Form->vacationrentals_image->getValue());
                        $i = 1;
                        foreach($img_arr as $key => $value)
                        {
                    ?>
                <div>
                    <a href="javascript:void(0);" class="change_img preview" link="data/frontImages/vacationrentals/vacationrentals_image/<?php echo $value; ?>" title="<?php echo $this->escape($this->vacationrentals_Form->vacationrentals_name->getValue()); ?>" width="300"><img src="data/frontImages/vacationrentals/vacationrentals_image/<?php echo $value; ?>" <?php echo $width_img.' '.$height_img; ?> border="0" class="thumb additional-thumb" /></a>
                </div>
                <?php                                   
                     $i++;
                  }
                ?>            
            </div>
            
            <div id="tabs-3">
                <h2><?php echo $this->translator->translator('vacationrentals_front_page_Title_floorplan'); ?></h2>
                <?php
                    if($this->group_datas['file_thumb_width'] && ($this->group_datas['file_thumb_resize_func'] != 'resizeToHeight' || $this->group_datas['file_thumb_resize_func'] != 'resize' ))
                    { 
                        $width_img = 'width="'.$this->escape($this->group_datas['file_thumb_width']).'"'; 
                    }
                    else
                    {
                        $width_img = '';
                    } 
                    if($this->group_datas['file_thumb_height'] && ( $this->group_datas['file_thumb_resize_func'] != 'resizeToWidth' || $this->group_datas['file_thumb_resize_func'] != 'resize' ))
                    { 
                        $height_img = 'height="'.$this->escape($this->group_datas['file_thumb_height']).'"'; 
                    } 
                    else
                    {
                        $height_img = '';
                    }
                    if($this->vacationrentals_Form->feature_others_exclusive_images->getValue())
                    {
                        $img_froor_arr = explode(',',$this->vacationrentals_Form->feature_others_exclusive_images->getValue());
                        $i = 1;
                        foreach($img_froor_arr as $key => $value)
                        {
                ?>
                <div>
                    <a href="javascript:void(0);" class="change_img preview" link="data/frontImages/vacationrentals/other_images/<?php echo $value; ?>" title="<?php echo $this->escape($this->vacationrentals_Form->vacationrentals_name->getValue()); ?>" width="300"><img src="data/frontImages/vacationrentals/other_images/<?php echo $value; ?>" <?php echo $width_img.' '.$height_img; ?> border="0" class="thumb additional-thumb"/></a>
                </div>
                <?php                                   
                     $i++;
                  }
                     }
                ?>
            </div>
            
            <div id="tabs-4">
                <h4><?php echo $this->translator->translator('vacationrentals_front_page_Title_payment_amenities'); ?></h4>
                
                <?php						 
                    foreach($feature_facilities_arr as $key=>$value)
                    {
                        echo '<div class="products-features"> &bull; '.$this->escape($value).'</div>';
                    }						  
                ?>
                
                <hr/>
                
                <h4><?php echo $this->translator->translator('vacationrentals_front_page_Title_additional_features'); ?></h4>
                
                <?php 
                        $feature_sports_recreations_arr = explode(',', $this->view_datas['feature_other_facilities']); 
                        foreach($feature_sports_recreations_arr as $key=>$value)
                        {
                            echo '<div class="products-features"> &bull; '.$this->escape($value).'</div>';
                        }						  
                ?>
            </div>
            
            <div id="tabs-5">
                <h2><?php echo $this->translator->translator('vacationrentals_front_page_vacationrentals_available'); ?></h2>
                
                <div class="products-chart products-availability">
                    <div class="products-details">
                        <div class="products-details-header"><h4 class="icon"><?php echo $this->translator->translator('vacationrentals_front_page_Title_available'); ?></h4></div>
                        <div class="content">
                        	<div class="chart-desc">
                                <div class="label"><?php echo $this->translator->translator('vacationrentals_front_page_label_available_from'); ?></div>
                                <div class="value"><?php echo $this->escape($this->vacationrentals_Form->availabe_from->getValue()  ); ?></div>
                                
                                <div class="label"><?php echo $this->translator->translator('vacationrentals_front_page_label_available_to'); ?></div>
                                <div class="value"><?php echo $this->escape($this->vacationrentals_Form->available_to->getValue()); ?></div>
                                
                                <?php 	$available_activation_date = $this->vacationrentals_Form->available_activation_date->getValue();
                                        if($available_activation_date != '0000-00-00' && !empty($available_activation_date))
                                { 
                                ?>
                                        
                                <div class="label"><?php echo $this->translator->translator('vacationrentals_front_page_label_activation'); ?></div>
                                <div class="value"><?php echo $this->escape($this->vacationrentals_Form->available_activation_date->getValue()); ?></div>
                            </div>
                            <?php 
                            } 
                            ?>
                        </div>
                    </div>
                </div>
                
                <div class="products-legend">
                    <div class="legend-icon">
                        <img src="application/layouts/scripts/<?php echo $front_template['theme_folder']; ?>/images/mod_img/available.gif" />
                    </div>
                    <div class="legend-icon">
                        <img src="application/layouts/scripts/<?php echo $front_template['theme_folder']; ?>/images/mod_img/booked.gif"/>
                    </div>
                    <div class="legend-icon">
                        <img src="application/layouts/scripts/<?php echo $front_template['theme_folder']; ?>/images/mod_img/not-available.gif"/>
                    </div>
                    <div class="legend-icon">
                        <img src="application/layouts/scripts/<?php echo $front_template['theme_folder']; ?>/images/mod_img/blank.gif"/>
                    </div>
                </div>
                <div id="dialog_calendar" class="dialog-calendar"></div>

            </div>
            
            <div id="tabs-6">            	
				<h2><?php echo $this->translator->translator('vacationrentals_front_page_Title_brochure_feature'); ?></h2>
                
                <?php 
                    $_brochure_desc = $this->escape( $this->vacationrentals_Form->brochure_desc->getValue()); 
                    if (!empty($_brochure_desc)) {												
                ?>
                <div class="products-details">
                   <div class="products-details-header"><h4 class="icon"><?php echo $this->escape($this->vacationrentals_Form->brochure_title->getValue());  ?></h4></div>
                   <div class="content"><?php echo $_brochure_desc ;  ?></div>
                </div>
                
                <?php 
                    }						
                    $_feature_additional = stripslashes($this->vacationrentals_Form->feature_additional->getValue()); 
                    if (!empty($_feature_additional)) {												
                ?>
                <div class="products-details">
                   <div class="products-details-header"><h4 class="icon"><?php echo $this->translator->translator('vacationrentals_front_page_Title_features'); ?></h4></div>
                   <div class="content"><?php echo  $_feature_additional; ?></div>
                </div>
                
                <?php 
                    }
                    $_vacationrentals_address = stripslashes($this->vacationrentals_Form->vacationrentals_address->getValue()); 
                    if (!empty($_vacationrentals_address)) {												
                ?>
                <div class="products-details">
                   <div class="products-details-header"><h4 class="icon"><?php echo $this->vacationrentals_Form->vacationrentals_address->getAttrib('font_end_label'); ?></h4></div>
                   <div class="content"><?php echo $_vacationrentals_address; ?></div>
                </div>
                <?php 
                    }
                ?>
            </div>
            
            <div id="tabs-7">
                <h2><?php echo $this->translator->translator('vacationrentals_front_page_Title_payment'); ?></h2>
                
                <?php 
                    
                    $_payment_desc =  stripslashes( $this->vacationrentals_Form->payment_desc->getValue()); 
                    if (!empty($_payment_desc)) {												
                ?>
                <div class="products-details">
                   <div class="products-details-header"><h4 class="icon"><?php echo $this->translator->translator('vacationrentals_front_page_Title_payment_process'); ?></h4></div>
                   <div class="content"><?php echo $_payment_desc; ?></div>
                </div>
                <?php 
                }
                ?>
                
                <h2><?php echo $this->translator->translator('vacationrentals_front_page_Title_policy'); ?></h2>
                
                <?php 
                            
                    $_rentals_policy =  stripslashes( $this->vacationrentals_Form->rentals_policy->getValue()); 
                    if (!empty($_rentals_policy)) {												
                ?>
                <div class="products-details">
                   <div class="products-details-header"><h4 class="icon"><?php echo $this->translator->translator('vacationrentals_page_page_policy'); ?></h4></div>
                   <div class="content"><?php echo $_rentals_policy; ?></div>
                </div>
                <?php 
                }
                ?> 
                
                <h2><?php echo $this->translator->translator('vacationrentals_front_page_Title_policy'); ?></h2>
                <?php 
                    
                    $_trams_and_condition =  stripslashes( $this->vacationrentals_Form->trams_and_condition->getValue()); 
                    if (!empty($_trams_and_condition)) {												
                ?>
                
                <div class="products-details">
                   <div class="products-details-header"><h4 class="icon"><?php echo $this->translator->translator('vacationrentals_page_page_trams_and_condition'); ?></h4></div>
                   <div class="content"><?php echo $_trams_and_condition; ?></div>
                </div>
                <?php 
                 }
                ?>
            </div>
            
            <div id="tabs-8">
              	<div class="products-chart products-details">
                    <div class="products-details-header"><h4 class="icon"><?php echo $this->translator->translator('vacationrentals_front_page_Title_available'); ?></h4></div>
                    <div class="content">
                        <div class="chart-desc">
                        <?php 
                            $_feature_distance_from_airport = $this->escape($this->vacationrentals_Form->feature_distance_from_airport->getValue()); 
                            if (!empty($_feature_distance_from_airport)) {												
                        ?>
                        <div class="label"><?php echo $this->vacationrentals_Form->feature_distance_from_airport->getAttrib('font_end_label');  ?></div>
                        <div class="value"><?php echo $_feature_distance_from_airport ; ?></div>
                        
                        <?php
                            }
                            $_feature_distance_from_rail = $this->escape($this->vacationrentals_Form->feature_distance_from_rail->getValue()); 
                            if (!empty($_feature_distance_from_rail)) {																			
                        ?>
                        
                        <div class="label"><?php echo $this->vacationrentals_Form->feature_distance_from_rail->getAttrib('font_end_label'); ?></div>
                        <div class="value"><?php echo $_feature_distance_from_rail; ?></div>
                        
                        <?php
                            }
                            $_feature_distance_from_market = $this->escape($this->vacationrentals_Form->feature_distance_from_market->getValue()); 
                            if (!empty($_feature_distance_from_market)) {																			
                        ?>
                                
                        <div class="label"><?php echo $this->vacationrentals_Form->feature_distance_from_market->getAttrib('font_end_label'); ?></div>
                        <div class="value"><?php echo $_feature_distance_from_market; ?></div>
                        
                        <?php
                            }
                            $_feature_distance_from_city = $this->escape($this->vacationrentals_Form->feature_distance_from_city->getValue()); 
                            if (!empty($_feature_distance_from_city)) {																			
                        ?>
                        
                        <div class="label"><?php echo $this->vacationrentals_Form->feature_distance_from_city->getAttrib('font_end_label'); ?></div>
                        <div class="value"><?php echo $_feature_distance_from_city; ?></div>
                        <?php } ?>
                        </div>
                    </div>
                </div>
                
                <?php					
                    $_feature_google_map = $this->escape($this->vacationrentals_Form->feature_google_map->getValue()); 
                    if (!empty($_feature_google_map)) {																			
                ?>
                    
                <div class="products-details">
                   <div class="products-details-header"><h4 class="icon"><?php echo $this->translator->translator('vacationrentals_front_page_Title_map'); ?></h4></div>
                   <div class="content products-map">
                   		<?php echo $_feature_google_map; ?>
                   </div>
                </div>
                <?php
                    }																			
                ?>
            </div>
            
            <?php
                if(!empty($this->group_datas['review_id']))
                {
            ?>
            
            <div id="tabs-9">
                
                <?php 
                    if(!empty($this->review_datas['review_info']))
                    {							
                        foreach($this->review_datas['review_info'] as $key => $infos)
                        {	
                            $div_class = ($key % 2 == 0) ? 'review-box' : 'review-box2';							
                ?>
                    
                <div class="<?php echo $div_class; ?>">
                    <div class="review-box-img">
                        <?php										
                            $primary_image_field = (!empty($this->review_datas['review_settings_info']['primary_image_field'])) ? $this->review_datas['review_settings_info']['primary_image_field'] : '';
                            $primary_images = (!empty($primary_image_field) && !empty($infos[$primary_image_field])) ? $infos[$primary_image_field] : '' ;
                            if(empty($primary_images))
                            {
                                $img_path = 'application/layouts/scripts/'.$front_template['theme_folder'].'/images/mod_vacation_img/avatar.png';
                            }
                            else
                            {
                                $files_arr = explode(',',$primary_images);
                                $img_path = $this->escape($this->review_datas['form_info']['attach_file_path']).'/'.$this->escape($files_arr[0]);
                            }
                        ?>
                        <img src= "<?php echo $img_path ?>" width="80" />
                    </div>
                        
                    <div>
                        <div class="review-box-title">
                                    <span>
                                    <?php 
                                        if(!empty($this->review_datas['review_settings_info']['name_title_field']))
                                        { 
                                            $name_title_field  = $this->review_datas['review_settings_info']['name_title_field'];
                                            if(!empty($infos[$name_title_field]))
                                            {
                                                echo $this->escape($infos[$name_title_field]); 
                                            }
                                        } 
                                    ?>
                                    </span>
                                    
                                    <div>
                                    
                                    <?php 
                                        if(!empty($this->review_datas['review_settings_info']['rating_fields']))
                                        { 												
                                            $rating_fields_arr  = explode(',',$this->review_datas['review_settings_info']['rating_fields']);
                                            if(!empty($infos[$rating_fields_arr[0]]))
                                            {	
                                                $cnt = $this->escape($infos[$rating_fields_arr[0]]) - 1;                                                    											
                                                
                                    ?>                                         
                                        <div class="review-box-rate"><?php echo str_replace("'",'',$hint_arr[$cnt]); ?></div>
                                        <div class="review-box-star">
                                                    <div id="<?php echo $this->escape($rating_fields_arr[0]).$infos['id']; ?>_star"  class="review-box-rate-star"></div>
                                                    <script type="text/javascript">
                                                        $(function() {
                                                            raty ('<?php echo $this->escape($rating_fields_arr[0]).$infos["id"]; ?>','<?php echo $this->escape($infos[$rating_fields_arr[0]]); ?>');
                                                        });
                                                    </script>
                                        </div>
                                       
                                        <?php 
                                                }
                                            } 
                                        ?>
                                    </div>
                                    
                                    
                                </div>
                                <div class="review-box-desc">
                                    <?php 
                                        if(!empty($this->review_datas['review_settings_info']['short_desc_field']))
                                        { 
                                            $short_desc_field  = $this->review_datas['review_settings_info']['short_desc_field'];
                                            if(!empty($infos[$short_desc_field]))
                                            {
                                                echo $this->escape($infos[$short_desc_field]); 
                                            }
                                        } 
                                    ?>
                                    
                                        <div class="review-box-date">
                                            <?php 											
                                                if(!empty($infos['g_date']))
                                                {
                                                    echo $this->escape($infos['g_date']); 
                                                }											
                                            ?>
                                        </div>
                                </div>
                        </div>
                </div>
                <?php 								
                    }							
                }
                ?>
            </div>
            <?php
                }
                if(!empty($staticGroupsObj))
                {
                    $tab = (!empty($this->group_datas['review_id'])) ? 10 : 9;
                    foreach($staticGroupsObj as $staticGroup)
                    {
                        $elementsObj = $staticGroup->getElements();
            ?>
            
            <div id="tabs-<?php echo $tab; ?>">
                        
                        <?php																
                                foreach($elementsObj as $element)
                                {
                                    if($element->getAttrib('frontend') == '1')
                                    {	
                                        if($element->getType() != 'Zend_Form_Element_File')
                                        {	
                                            if($element->getValue())
                                            {														
                            ?>	
                                    
                                        <div class="tab-element">
                                            <?php echo $element->getLabel();  ?>
                                        </div>
                                        
                                        <div class="tab-value">
                                            <?php 										
                                                    $id_f = $element->getAttrib('id');
                                                    $id_arr = explode('_',$id_f);	
                                                    if(($element->getType() == 'Zend_Form_Element_MultiCheckbox') || ($element->getType() == 'Zend_Form_Element_Multiselect'))
                                                    {	
                                                        $val_arr = $element->getValue();														
                                                        echo implode(', ',$val_arr);
                                                    }
                                                    else
                                                    {													
                                                        echo stripslashes($element->getValue());	
                                                    }														
                                                ?>		
                                        </div>
                            <?php
                                            }
                                        }
                                    }
                                }
                            ?>
                    
                    </div>
                    <?php
                        $tab++;
                     }
                 }
                ?>
    </div>
    <!-- Vecation Bottom Tab End -->
    
    <!-- Bottom Bar Start -->
    <div class="nav-bar bottom">
        <div class="nav-row">
            <div class="nav-col first"> 
            <?php
				if(!empty($prevVacationrentals))
				{
			?>
            <span class="prev"><a href="<?php echo 'Vacationrentals-details/'.$this->escape($prevVacationrentals['vacationrentals_title']); ?>"><?php echo $this->translator->translator('vacationrentals_front_page_prev_vacationrentals'); ?></a></span>
            <?php
				}
				else
				{
			?>
            <span class="no-link"><?php echo $this->translator->translator('vacationrentals_front_page_prev_vacationrentals'); ?></span>
            <?php
                }
            ?>
            </div>
            <div class="nav-col"><span class="search"><a href="#" class="slick-slidetoggle"><?php echo $this->translator->translator('vacationrentals_front_page_new_search'); ?></a></span></div>
            <div class="nav-col">
            <?php
                if ($hasIdentity)
                {
			?>
            <span class="save"><a  href="javascript:void(0);" class="save_vacationrentals_btn" rel="<?php echo $this->escape($item_id); ?>"><?php echo $this->translator->translator('vacationrentals_front_page_save_vacationrentals'); ?></a></span>
            <?php
                }
            ?>
            </div>
            <div class="nav-col last">
            <?php
				if(!empty($nextVacationrentals))
				{
			?>
            <span class="next"><a href="<?php echo 'Vacationrentals-details/'.$this->escape($nextVacationrentals['vacationrentals_title']); ?>"><?php echo $this->translator->translator('vacationrentals_front_page_next_vacationrentals'); ?></a></span>
            <?php
                }
                else
                {
            ?>
            <span class="no-link"><?php echo $this->translator->translator('vacationrentals_front_page_next_vacationrentals'); ?></span>
            <?php
                }
            ?>
            </div>
        </div>
    </div>
    <!-- Bottom Bar End -->
</div>

<div id="dialog_container" title="<?php echo $this->translator->translator('common_dialog_msg','Message'); ?>"></div>
	<?php else : ?>
		<h2><?php echo $this->translator->translator('common_not_approved'); ?></h2>
	<?php endif; ?>	
<?php endif; ?>	