<?php
$version = Zend_Registry::get('version');  
$tab_base_link = Zend_Controller_Front::getInstance()->getRequest()->getRequestUri();
$this->headTitle()->headTitle($this->translator->translator('flight_AirlineFlightSchedules_page_meta_title_book'),'SET');
$global_conf = Zend_Registry::get('global_conf');
$front_template = Zend_Registry::get('front_template'); 
$currency = new Zend_Currency($global_conf['default_locale']);
$currencySymbol = $currency->getSymbol();
$currencyShortName = $currency->getShortName();
$post_data    = Eicra_Global_Variable::getSession()->post_data;
$route_helper = new Flight_View_Helper_Route();
$auth = Zend_Auth::getInstance ();
$this->tab = ($auth->hasIdentity ()) ? '1' : '0';
$redirect_msg = $this->translator->translator("member_loggin_redirecting", '', 'Members');
?>
<script type="text/javascript">
$(document).ready(function() {
		$("#tabs").tabs({ selected: <?php echo $this->tab; ?> }).find(".ui-tabs-nav").sortable({axis:'xy'});
		
		/**************************For Login Start *****************************************/
		
		$('a.remove_btn').click(function() {
			var self = this;			
				var cart_arr = $(self).attr('rel').split('-');	
				
				$.ajax({
					 url: "<?php echo $this->url( array('module'=> 'Flight', 'controller' => 'invoice', 'action'     => 'remove' ), 'adminrout',    true) ?>",
					 type: 'POST',
					 data: { cart_id: cart_arr[0], sub_cart_id: cart_arr[1] },
					 beforeSend: function(){						
						$(self).html('<img src="application/layouts/scripts/<?php echo $front_template['theme_folder']; ?>/images/loader/mod-loader.gif" width="15" border="0" />');				
					 },
					 success: function(response) 
					 {
						//alert(response);
						var json_arr = eval("("+response+")");
						if(json_arr.status == 'ok')
						{
							document.location.href = '<?php echo $this->serverUrl().$this->baseUrl().'/FlightBooking';  ?>';
						}
						else
						{
							openMsgDialog(json_arr.msg);
						}
					 }
				});				
		});	
		
		
		function resetLoginFields()
		{
			$( "#AdminLogin" )[ 0 ].reset();
		}
		
		function removeLoginError()
		{
			$('#actionLoginMessage').html('');
			$('#login_captcha_login_err').html('');
					
			$.each($('#AdminLogin').serializeArray(), function(i, field) {				
					$('#'+field.name).removeClass('ui-state-error');
					$('#'+field.name+'_login_err').html('');									
			});			
		}
		
		
		
		function getLoginFormData()
		{
			var fieldObj = {};
			$.each($('#AdminLogin').serializeArray(), function(i, field) {		 					
					fieldObj[field.name] = field.value;										
			});
			return fieldObj;
		}
		
	
		$('input.login_send_btn').click(function() {
			
			var formData = getLoginFormData();
			
			$.ajax({
				url: "<?php echo $this->url( array('module' => 'Members','controller' => 'frontend', 'action'     => 'auth' ), 'default',    false) ?>",
					type: 'POST',
					data: formData,
					beforeSend: function(){											
						removeLoginError();
						openLoaderDialog();										
					 },
					success: function(response){
						//alert(response);					
						var json_arr = eval("("+response+")");	
						refreshLoginCaptcha(json_arr);										
						if(json_arr.status == 'ok')
						{
							$('#actionLoginMessage').html(succMsgDesign(json_arr.msg));	
							resetLoginFields();
								
							$('#login_box').css('display','none');								
							
								$('#actionLoginMessage').html(succMsgDesign(json_arr.msg+'<?php echo $redirect_msg; ?>'));	
								document.location.href='<?php echo $this->serverUrl().$this->baseUrl().'/FlightBooking';  ?>';
																					
						}
						else if(json_arr.status == 'errV')
						{
							$('#actionLoginMessage').html(errMsgDesign("<?php echo $this->translator->translator('common_err'); ?>"));
													
							for(var i= 0; i < json_arr.msg.length; i++)
							{
								addLoginError(json_arr.msg[i].key,json_arr.msg[i].value);							
							}
						}
						else
						{
							$('#actionLoginMessage').html(errMsgDesign(json_arr.msg));
						}
						closeLoaderDialog();
					},
					error: function(xhr, status, error){
						closeLoaderDialog();
						var msg = "Error! " + xhr.status + " " + error;
						$('#actionLoginMessage').html(errMsgDesign(msg));
					}
			});
		});
		
		function addLoginError(key,errMsg)
		{
			var err_id = key+'_login_err';
			var field_name = key;
			$('#'+field_name).addClass('ui-state-error');
			$('#'+err_id).append(errMsg);
		}
		
		
		
		/**************************For Login End *****************************************/
			
			
		/**************************For Logout Start *****************************************/
		$('a.logout_btn').click(function() {
		
			$('div.member-login').css('display','inline');	
			$('#logout_box').css('display','none');	
		});
		$('a.login_cancel').click(function() {
		
			$('div.member-login').css('display','none');	
			$('#logout_box').css('display','inline');	
		});
		/**************************For Logout End *****************************************/	
				
		
				
		function openLoaderDialog()
		{
			$('#dialog_container').dialog({
						autoOpen: true,
						modal: true,
						show: 'explode',
						resizable: false,				
						open: function(event, ui)
							 {
								$("#progressbar").progressbar({
									value:100
					
								});							
							  }
					});
		}
		
		function closeLoaderDialog()
		{
			$('#dialog_container').dialog('option','hide','explode').dialog('close');
		}
		
		/****************************Registration Start********************************************/
		
		$('a.reset_btn').click(function() {			
			 resetFields();	
			 removeError();	
		});
		
		function resetFields()
		{
			$( "#MemberForm" )[ 0 ].reset();
			$('input.empty_class').each(function(){
				$(this).val('');
			});
			$.each($("input[type='file']"),function(index, obj){
				var upload_file_name = $(obj).attr('name');	
				var upload_file_name_err = upload_file_name.replace('_upload', '');		
				$('#'+upload_file_name_err+'_err').html('');
				$('#selected_file_'+upload_file_name_err).html('');
			});		
		}
		
		function removeError()
		{
			$('#actionMessage').html('');
			
			var filename = '';
			var filevalue = '';		
			$.each($('#MemberForm').serializeArray(), function(i, field) {	
					if(field.name.match(/\[\]$/))
					{
						var filearr = field.name.split('[]');
						filename = filearr[0];					
					}
					else if(field.name.match(/\[input\]$/))
					{
						var filearr = field.name.split('[input]');
						filename = filearr[0];					
					}
					else
					{
						filename 	= 	field.name;
					} 			
					$('#'+filename).removeClass('ui-state-error');	
					$('#'+filename+'-input').removeClass('ui-state-error');			
					$('#'+filename+'_err').html('');
					$('span.input-errors').html('');							
			});				
		}
		
		function addError(key,errMsg)
		{
			var err_id = key+'_err';
			var field_name = key;
			$('#'+field_name+'-input').addClass('ui-state-error');
			$('#'+field_name).addClass('ui-state-error');
			$('#'+err_id).append(errMsg);
		}
		
		function getFormData()
		{
			var fieldObj = {};
			var filename = '';
			var filevalue = '';
			$.each($('#MemberForm').serializeArray(), function(i, field) {	
				if(field.name.match(/\[\]$/))
				{
					var filearr = field.name.split('[]');
					filename = filearr[0];
					filevalue = $('#'+filename).val();
					if($('input[name="'+filename+'[]"]').is(':checkbox'))
					{
						var val_arr = [];
						$('input[name="'+filename+'[]"]:checkbox:checked').each(function(i){
						 val_arr[i] = $(this).val();
						});
						filevalue = (val_arr[0] != null) ? val_arr.join(',') : null;					
					}
				}
				else
				{
					filename 	= 	field.name;
					filevalue 	= 	field.value;
				}			
				fieldObj[filename] =  filevalue;			
			});
			return fieldObj;
		}
		
		$('a.add_user_btn').click(function() {
				var formData = getFormData();	
				if(!formData.role_id){ 	formData.role_id = '<?php echo $this->selected_role_id; ?>'; }		
			$.ajax({
				url: "<?php echo $this->url( array('module' => 'Flight','controller' => 'invoice', 'action'     => 'register' ), 'adminrout',    true) ?>",
					type: 'POST',
					data: formData,
					beforeSend: function(){
						removeError();
						openLoaderDialog();
					 },
					success: function(response){
						//alert(response);					
						var json_arr = eval("("+response+")");					
						refreshCaptcha(json_arr);				
						if(json_arr.status == 'ok')
						{
							document.location.href = '<?php echo $this->serverUrl().$this->baseUrl().'/FlightBooking';  ?>';
							$('#actionMessage').html(succMsgDesign(json_arr.msg));						
							resetFields();							
						}
						else if(json_arr.status == 'errV')
						{
							closeLoaderDialog();
							$('#actionMessage').html(errMsgDesign("<?php echo $this->translator->translator('common_err'); ?>"));
													
							for(var i= 0; i < json_arr.msg.length; i++)
							{
								addError(json_arr.msg[i].key,json_arr.msg[i].value);							
							}
						}
						else if(json_arr.status == 'errP')
						{
							closeLoaderDialog();
							$('#actionMessage').html(errMsgDesign("<?php echo $this->translator->translator('common_err'); ?>"));
							addError('confirmPassword',json_arr.msg);
						}
						else
						{
							closeLoaderDialog();
							$('#actionMessage').html(errMsgDesign(json_arr.msg));
						}
					},
					error: function(xhr, status, error){
						closeLoaderDialog();
						var msg = "Error! " + xhr.status + " " + error;
						$('#actionMessage').html(errMsgDesign(msg));
					}
			});
		});
		
		/*****************************Registration End********************************************/

});

function refreshLoginCaptcha(json_arr)
{
	if(json_arr.captcha && json_arr.captcha.status && json_arr.captcha.status == 'ok')
	{
		var captcha_name = json_arr.captcha.captcha_name;
		$('input[name="'+captcha_name+'[id]"]').prev('img').attr('src', json_arr.captcha.ImgUrl+json_arr.captcha.id+json_arr.captcha.Suffix);
		$('input[name="'+captcha_name+'[id]"]').val(json_arr.captcha.id);
		$('#'+captcha_name+'_err').html('');		
	}
}

function refreshCaptcha(json_arr)
{
	if(json_arr.captcha && json_arr.captcha.status && json_arr.captcha.status == 'ok')
	{
		var captcha_name = json_arr.captcha.captcha_name;
		$('input[name="'+captcha_name+'[id]"]').parents('span:first').children('img:first').attr('src', json_arr.captcha.ImgUrl+json_arr.captcha.id+json_arr.captcha.Suffix);
		$('input[name="'+captcha_name+'[id]"]').val(json_arr.captcha.id);
		$('#'+captcha_name+'_err').html('');		
	}
}

function openMsgDialog(msg)
{
	$('#dialog_msg').html(msg).dialog({
		autoOpen: true,
		modal: false,
		show: 'explode',
		resizable: true,				
		buttons: [{ text: "<?php echo html_entity_decode($this->translator->translator('common_ok'), ENT_QUOTES, 'UTF-8'); ?>", click: function() { $(this).dialog('option', 'hide', 'explode').dialog("close"); } } ],
		open: function(event, ui)
			 {
				setTimeout(function() 
				{									
					if($('#' + event.target.id).dialog('isOpen'))
					{
						$('#' + event.target.id).dialog('option', 'hide', 'explode').dialog('close');										
					}
				}, 10000);
			  }
	});
}

function calender(id)
{
	$("#"+id).datepicker({
		showOn: 'button',
		buttonImage: 'application/layouts/scripts/<?php echo $front_template['theme_folder']; ?>/images/mod_flight_img/calendar.png',
		buttonImageOnly: true,
		monthNamesShort:<?php echo $this->translator->translator("common_calender_monthNamesShort"); ?>,
		monthNames:<?php echo $this->translator->translator("common_calender_monthNames"); ?>,
		dayNamesMin:<?php echo $this->translator->translator("common_calender_dayNamesMin"); ?>,
		showAnim: 'slide',
		buttonText: 'Calender',
		dateFormat:'yy-mm-dd',
		autoSize:false,
		showButtonPanel:false,
		changeMonth: true,
		changeYear: true
	});
	
	$("img[class='ui-datepicker-trigger']").each(function()
	 { 
	  	$(this).attr('style', '');
	 });
}

/***********************************************************************UPLOAD FUNCTIONS START********************************************************/

function languageArray()
{
	var language_array = [];
	language_array['portfolio_upload_dy_text_select'] 					= "<?php echo html_entity_decode($this->translator->translator("portfolio_upload_dy_text_select", '', 'Portfolio'), ENT_QUOTES, 'UTF-8'); ?>";
	language_array['portfolio_upload_text_cancel'] 						= "<?php echo html_entity_decode($this->translator->translator("portfolio_upload_text_cancel", '', 'Portfolio'), ENT_QUOTES, 'UTF-8'); ?>";
	language_array['portfolio_upload_text_dropFilesHere'] 				= "<?php echo html_entity_decode($this->translator->translator("portfolio_upload_text_dropFilesHere", '', 'Portfolio'), ENT_QUOTES, 'UTF-8'); ?>";
	language_array['portfolio_upload_text_remove'] 						= "<?php echo html_entity_decode($this->translator->translator("portfolio_upload_text_remove", '', 'Portfolio'), ENT_QUOTES, 'UTF-8'); ?>";
	language_array['portfolio_upload_text_retry'] 						= "<?php echo html_entity_decode($this->translator->translator("portfolio_upload_text_retry", '', 'Portfolio'), ENT_QUOTES, 'UTF-8'); ?>";
	language_array['portfolio_upload_text_statusFailed'] 				= "<?php echo html_entity_decode($this->translator->translator("portfolio_upload_text_statusFailed", '', 'Portfolio'), ENT_QUOTES, 'UTF-8'); ?>";
	language_array['portfolio_upload_text_statusUploaded'] 				= "<?php echo html_entity_decode($this->translator->translator("portfolio_upload_text_statusUploaded", '', 'Portfolio'), ENT_QUOTES, 'UTF-8'); ?>";
	language_array['portfolio_upload_text_statusUploading'] 			= "<?php echo html_entity_decode($this->translator->translator("portfolio_upload_text_statusUploading", '', 'Portfolio'), ENT_QUOTES, 'UTF-8'); ?>";
	language_array['portfolio_upload_text_uploadSelectedFiles'] 		= "<?php echo html_entity_decode($this->translator->translator("portfolio_upload_text_uploadSelectedFiles", '', 'Portfolio'), ENT_QUOTES, 'UTF-8'); ?>";
	language_array['portfolio_file_extension_dy_support'] 				= "<?php echo $this->translator->translator("portfolio_file_extension_dy_support", '', 'Portfolio'); ?>";
	language_array['portfolio_file_no_ext_dy_support'] 					= "<?php echo $this->translator->translator("portfolio_file_no_ext_dy_support", '', 'Portfolio'); ?>";
	language_array['portfolio_file_extension_dy_not_supportable_ext1'] 	= "<?php echo $this->translator->translator("portfolio_file_extension_dy_not_supportable_ext1", '', 'Portfolio'); ?>";
	language_array['portfolio_file_extension_dy_not_supportable_ext2']  = "<?php echo $this->translator->translator("portfolio_file_extension_dy_not_supportable_ext2", '', 'Portfolio'); ?>";
	language_array['portfolio_file_size_dy_support'] 					= "<?php echo $this->translator->translator("portfolio_file_size_dy_support", '', 'Portfolio'); ?>";
	language_array['portfolio_file_upload_err'] 						= "<?php echo $this->translator->translator("portfolio_file_upload_err", '', 'Portfolio'); ?>";
	return language_array;
}


function successFileDecoretion(fileObj, serverData, upload_field, upload_value_field)
{
		var extension = fileObj.extension;
		var ext = extension.replace('.','');	
		
		var img_path = '';
		switch(ext)
		{
			case 'flv':
			case 'swf':
			case 'FLV':
			case 'SWF':
				img_path = '<?php echo $this->baseUrl(); ?>'+'/application/modules/Administrator/layouts/scripts/images/common/flash.png';
				break;
			case 'mp3':
			case 'MP3':
				img_path = '<?php echo $this->baseUrl(); ?>'+'/application/modules/Administrator/layouts/scripts/images/common/mp3.png';
				break;
			case 'avi':
			case 'wmv':
			case 'wma':
			case 'WMA':
			case 'AVI':
			case 'WMV':
				img_path = '<?php echo $this->baseUrl(); ?>'+'/application/modules/Administrator/layouts/scripts/images/common/avi_thumb.png';
				break;
			case 'pdf':
			case 'doc':
			case 'docx':
			case 'xls':
			case 'xlsx':
			case 'ppt':
			case 'pptx':
			case 'PDF':
			case 'DOC':
			case 'DOCX':
			case 'XLS':
			case 'XLSX':
			case 'PPT':
			case 'PPTX':
				img_path = '<?php echo $this->baseUrl(); ?>'+'/application/modules/Administrator/layouts/scripts/images/common/'+ext.toLowerCase()+'.png';
				break;
			default:
				if(isImage(fileObj))
				{				
					img_path = "<?php echo $this->baseUrl().'/'; ?>"+serverData.file_path+'/'+fileObj.name; 
				}
				else
				{	
					img_path = "<?php echo $this->baseUrl().'/'; ?>application/modules/Administrator/layouts/scripts/images/common/all_file_thumb.png";
				}	
				break;
		}		
		
		
		var img_code =  '<div class="thumb"><img src="'+img_path+'" title="'+fileObj.name+'" width="20" height="10" /></div>'
		var down_link = (!isImage(fileObj)) ? '<br /><a href="'+serverData.file_path+'/'+fileObj.name+'"><?php echo $this->translator->translator("common_download", "", "Projects"); ?></a>' : '';
		var checked = '';
		var primary = '&nbsp;&nbsp;&nbsp;';	
		var block = 'selected_file_'+upload_value_field;
		var img_type = '';			
		switch(upload_value_field)
		{
			case 'product_thumb':	
					checked = ($('#'+upload_value_field).val() == '') ? ' checked="checked" ' : '';	
					img_type = 	($('#'+upload_value_field).val() == '') ? "<span class='main'><?php echo $this->translator->translator('gallery_img_main', '', 'Gallery'); ?></span><br />" : "<span class='related'><?php echo $this->translator->translator('gallery_img_related', '', 'Gallery'); ?></span><br />";				
					primary = '<input class="radio_style" type="radio" name="product_thumb_primary" id="product_thumb_primary" '+checked+' value="'+fileObj.name+'" title="<?php echo $this->translator->translator("gallery_primary", '', 'Gallery'); ?>" />';
				break;
			case 'product_file':
					checked = ($('#'+upload_value_field).val() == '') ? ' checked="checked" ' : '';		
					img_type = 	($('#'+upload_value_field).val() == '') ? "<span class='main'><?php echo $this->translator->translator('gallery_img_main', '', 'Gallery'); ?></span><br />" : "<span class='related'><?php echo $this->translator->translator('gallery_img_related', '', 'Gallery'); ?></span><br />";		
					primary = '<input class="radio_style" type="radio" name="product_file_primary" id="product_file_primary" '+checked+' value="'+fileObj.name+'" title="<?php echo $this->translator->translator("gallery_primary", '', 'Gallery'); ?>" />';
				break;
		}
		
		var del_link = '<a href="javascript:void(0)" class="delete_uploaded_image_link" field_name="'+upload_value_field+'" file_name="'+fileObj.name+'" file_path="'+serverData.file_path+'"><?php echo $this->translator->translator("common_delete_title"); ?></a>'+primary+down_link;
				
		if(serverData.multi)
		{		
			$('#'+block).append('<div class="upload-img box">'+img_type+'<span>'+img_code+'<br />&nbsp;'+del_link+'</span></div>');				 
			var file_val = ($('#'+upload_value_field).val() == '') ? fileObj.name :  $('#'+upload_value_field).val()+','+fileObj.name;
		}
		else
		{
			$('#'+block).html('<div class="upload-img box">'+img_type+'<span>'+img_code+'<br />&nbsp;'+del_link+'</span></div>');				 
			var file_val = fileObj.name;	
		}		
		$('#'+upload_value_field).val(file_val);
		deleteFiles("<?php echo $this->translator->translator('gallery_img_main', '', 'Gallery'); ?>", "<?php echo $this->translator->translator('gallery_img_related', '', 'Gallery'); ?>", "<?php echo $this->url( array('module' => 'Portfolio','controller' => 'frontend', 'action'     => 'remove' ), 'adminrout',    true) ?>", "<?php echo $this->translator->translator('common_delete_title'); ?>");	
		imageThumbnil();	
}

function onComplete(e) {
			
}

function onCancel(e) {
	
}

function onProgress(e) {
					
}

/***********************************************************************UPLOAD FUNCTIONS END********************************************************/

/************************************************IMAGE THUMBNIL START************************************************/
function imageThumbnil()
{	
	$("span.thumb").hover(function() {
		$(this).css({'z-index' : '10'}); /*Add a higher z-index value so this image stays on top*/ 
		$(this).find('img').addClass("hover").stop() /* Add class of "hover", then stop animation queue buildup*/
			.animate({
				marginTop: '-110px', /* The next 4 lines will vertically align this image */ 
				marginLeft: '-110px',
				top: '50%',
				left: '50%',
				width: '174px', /* Set new width */
				height: '174px', /* Set new height */
				padding: '20px'
			}, 200); /* this value of "200" is the speed of how fast/slow this hover animates */
	
		} , function() {
		$(this).css({'z-index' : '0'}); /* Set z-index back to 0 */
		$(this).find('img').removeClass("hover").stop()  /* Remove the "hover" class , then stop animation queue buildup*/
			.animate({
				marginTop: '0', /* Set alignment back to default */
				marginLeft: '0',
				top: '0',
				left: '0',
				width: '30px', /* Set width back to default */
				height: '20px', /* Set height back to default */
				padding: '5px'
			}, 400);
	});
}
/************************************************IMAGE THUMBNIL END************************************************/

function is_image(filename)
{
	var ext = getFileExtension(filename);
	if(ext == 'jpg' || ext == 'JPG' || ext == 'png' || ext == 'PNG' || ext == 'bmp' || ext == 'BMP' || ext == 'gif' || ext == 'GIF')
	{
		return true;
	}
	else
	{
		return false;
	}
}
function getFileExtension(filename)
{
	return filename.replace(/^.*?\.([a-zA-Z0-9]+)$/, "$1");
}
</script>

<div class="mod mod-login">
    <div class="booking-icon">
    	<h1><?php echo $this->translator->translator('flight_front_page_book_page_name'); ?></h1>
    </div>
    <div class="clear">&nbsp;</div>
    <?php if($this->errMsg){ echo '<span class="errMess">'.$this->errMsg.'</span>'; } ?>
    <div class="clear">&nbsp;</div>
    
    <div class="invoice">
        <?php		
		if($this->root_invoice_arr && $this->root_invoice_arr['status'] == 'ok')
		{
			if($this->checkLimit)
			{
			?>
				<div class="flight-booking">
					<div class="flight-booking-row">
						<div class="flight-booking-header-col-1">
							<?php echo $this->translator->translator("flight_invoice_desc_title"); ?>
						</div>
						
						<div class="flight-booking-header-col-1 col-2">
							<?php echo $this->translator->translator("flight_invoice_amount_title"); ?>
						</div>
					</div>             
					
						 <?php
							$total_amount = 0;
							$total_tax = 0;
							if($this->cart_result)
							{
								foreach($this->cart_result as $cart_result_key => $flightInfo)
								{
									$route_info = $route_helper->getRoute($flightInfo[Eicra_File_Constants::MAIN_TABLE_ID]);
									$route_arr = $route_helper->getAbsoluteRoute($route_info,$post_data);
									$sub_total = $flightInfo['flight_adult_fair']*$post_data['adult_no']+$flightInfo['flight_child_fair']*$post_data['child_no']+$flightInfo['flight_infant_fair']*$post_data['infant_no'];
									$sub_total_tax =  ($flightInfo['flight_tax']/100) * $sub_total;			
						?>
							<div class="flight-booking-row2">
								<div class="row2-col">
									<div class="booking-details">
										<img src="data/frontImages/flight/airlines/<?php echo $flightInfo['primary_image']; ?>" height="60" border="0" title="<?php echo $flightInfo['airlines_name']; ?>" class="thumb" />
										
										<div class="flight-info">
											<?php
											if($post_data['trip_type'] == 'Multi City')
											{
												foreach($route_info as $route_key => $route_arr)
												{
													$flight_route_departure_date =  $route_helper->getNearestDate($post_data['flight_route_departure_date'][$route_key],$route_arr['departure_date']);
													$flight_route_arrival_date =  $route_helper->getNearestDate($flight_route_departure_date['raw_date'],$route_arr['arrival_date']);
													
													echo $this->escape($route_arr['departure_iata']).' - '.$this->escape($route_arr['arrival_iata']);
											?>
											<br />
											<?php echo '<span class="mod-title">'.$this->translator->translator("flight_route_flight_no").'</span>'.$flightInfo['flight_code']. '-'. $flightInfo['flight_number']; ?>
											<br />
											<?php echo '<span class="mod-title">'.$this->translator->translator("flight_AirlineFlightSchedules_page_table_depart").' :</span> '.$route_arr['departure_time']. ' '. $flight_route_departure_date['format_date']; ?>
											<br  />
											<?php echo '<span class="mod-title">'.$this->translator->translator("flight_AirlineFlightSchedules_page_table_arive").' :</span> '.$route_arr['arrival_time']. ' '. $flight_route_arrival_date['format_date']; ?>
											<br  />
											<?php					
												}
											}
											else
											{	
													$flight_route_departure_date =  $route_helper->getNearestDate($post_data['flight_route_departure_date'][0],$flightInfo['flight_route_departure_date']);
													$flight_route_arrival_date =  $route_helper->getNearestDate($flight_route_departure_date['raw_date'],$flightInfo['flight_route_arrival_date']);					
											?>
												<?php echo $route_arr['route_show']; ?>
												<br />
													<?php echo '<span class="mod-title">'.$this->translator->translator("flight_route_flight_no").'</span> '.$flightInfo['flight_code']. '-'. $flightInfo['flight_number']; ?>
												<br />
												<?php echo '<span class="mod-title">'.$this->translator->translator("flight_AirlineFlightSchedules_page_table_depart").' :</span> '.$flightInfo['departure_time']. ' '. $flight_route_departure_date['format_date']; ?>
												<br  />
												<?php echo '<span class="mod-title">'.$this->translator->translator("flight_AirlineFlightSchedules_page_table_arive").' :</span> '.$flightInfo['arrival_time']. ' ' .$flight_route_arrival_date['format_date']; ?>
												<br  />
											<?php 
											} 
											?>
											<?php echo '<span class="mod-title">'.$this->translator->translator("flight_AirlineFlightSchedules_page_table_class").' :</span> '.$flightInfo['flight_travel_class']; ?>
											<?php 
											if($post_data['trip_type'] == 'Round')
											{						
												$flight_route_round_departure_date	=	$route_helper->getNearestDate($post_data['flight_route_arrival_date'][0],$route_arr['filed_departuredate_round']);
												$flight_route_round_arrival_date	=	$route_helper->getNearestDate($flight_route_round_departure_date['raw_date'], $route_arr['filed_arrivaldate_round']);
											?>
												<br /><br /><?php echo $route_arr['route_show_round']; ?>
												<br />
													<?php echo '<span class="mod-title">'.$this->translator->translator("flight_route_flight_no").' </span> '.$flightInfo['flight_code']. '-'. $flightInfo['flight_number']; ?>
												<br />
												<span class="mod-title"><?php echo $this->translator->translator("flight_AirlineFlightSchedules_page_table_depart"); ?> :</span><?php echo $route_arr['filed_departuretime_round']. ' '. $flight_route_round_departure_date['format_date']; ?>
												<br  />
												<span class="mod-title"><?php echo $this->translator->translator("flight_AirlineFlightSchedules_page_table_arive"); ?> :</span><?php echo $route_arr['filed_arrivaltime_round']. ' '. $flight_route_round_arrival_date['format_date']; ?>
												<br  />
												<span class="mod-title"><?php echo $this->translator->translator("flight_AirlineFlightSchedules_page_table_class"); ?> : </span><?php echo $flightInfo['flight_travel_class']; ?>
											<?php
											}
											?>
                                            <a href="javascript:void(0);" class="remove_btn remove-btn" rel="<?php echo $this->escape($cart_result_key); ?>"><?php echo $this->translator->translator("flight_invoice_room_remove"); ?></a>
										</div>
										
									</div>
								</div>
							
								<div class="row2-col">
									<div class="payment-details">
										<div class="departure"><?php echo $this->translator->translator("flight_front_page_search_details_going_title"); ?></div>
										
										<div class="item-label">
											<?php echo $this->translator->translator("flight_AirlineFlightSchedules_page_table_adult").' ('.$post_data['adult_no'].')'; ?> :
										</div>
										<div class="item-value">
											<?php echo $currencySymbol.' '.number_format(($flightInfo['flight_adult_fair']*$post_data['adult_no']), 2, '.', ',').' '.$currencyShortName; ?>
										</div>
										
										<div class="item-label">
											<?php echo $this->translator->translator("flight_AirlineFlightSchedules_page_table_child").' ('.$post_data['child_no'].')'; ?> :
										</div>
										
										<div class="item-value">
											<?php echo $currencySymbol.' '.number_format(($flightInfo['flight_child_fair']*$post_data['child_no']), 2, '.', ',').' '.$currencyShortName; ?>
										</div>
										
										<div class="item-label">
											<?php echo $this->translator->translator("flight_AirlineFlightSchedules_page_table_infant").' ('.$post_data['infant_no'].')'; ?> :	
										</div>
										
										<div class="item-value">
											<?php echo $currencySymbol.' '.number_format(($flightInfo['flight_infant_fair']*$post_data['infant_no']), 2, '.', ',').' '.$currencyShortName; ?>
										</div>
										
										<div class="item-label">
											<span class="tax-label"><?php echo $this->translator->translator("flight_invoice_total_tax_title"); ?></span>	
										</div>
										
										<div class="item-value">
											<span class="tax-label"><?php echo $currencySymbol.' '.number_format($sub_total_tax, 2, '.', ',').' '.$currencyShortName.' ( '.$flightInfo['flight_tax'].'% ) '; ?></span>
										</div>
										<?php 
											$sub_total_round = 0;
											$sub_total_tax_round = 0;
											if($post_data['trip_type'] == 'Round')
											{
												$sub_total_round = ($flightInfo['flight_adult_fair_round']*$post_data['adult_no']) + ($flightInfo['flight_child_fair_round']*$post_data['child_no']) + ($flightInfo['flight_infant_fair_round']*$post_data['infant_no']);
												$sub_total_tax_round = ($flightInfo['flight_tax_round'] / 100) * $sub_total_round;
										?>
										
										<div class="arrival"><?php echo $this->translator->translator("flight_front_page_search_details_come_title"); ?></div>
										
										<div class="item-label">
											<?php echo $this->translator->translator("flight_AirlineFlightSchedules_page_table_adult").' ('.$post_data['adult_no'].')'; ?> :	
										</div>
										
										<div class="item-value">
											<?php echo $currencySymbol.' '.number_format(($flightInfo['flight_adult_fair_round']*$post_data['adult_no']), 2, '.', ',').' '.$currencyShortName; ?>
										</div>
										
										<div class="item-label">
											<?php echo $this->translator->translator("flight_AirlineFlightSchedules_page_table_child").' ('.$post_data['child_no'].')'; ?> :
										</div>
										
										<div class="item-value">
											<?php echo $currencySymbol.' '.number_format(($flightInfo['flight_child_fair_round']*$post_data['child_no']), 2, '.', ',').' '.$currencyShortName; ?>
										</div>
										
										<div class="item-label">
											<?php echo $this->translator->translator("flight_AirlineFlightSchedules_page_table_infant").' ('.$post_data['infant_no'].')'; ?> :
										</div>
										
										<div class="item-value">
											<?php echo $currencySymbol.' '.number_format(($flightInfo['flight_infant_fair_round']*$post_data['infant_no']), 2, '.', ',').' '.$currencyShortName; ?>
										</div>
										
										<div class="item-label">
											<span class="tax-label"><?php echo $this->translator->translator("flight_invoice_total_tax_title"); ?></span>
										</div>
										
										<div class="item-value">
											<span class="tax-label"><?php echo $currencySymbol.' '.number_format($sub_total_tax_round, 2, '.', ',').' '.$currencyShortName.' ( '.$flightInfo['flight_tax_round'].'% ) '; ?></span>
										</div>
										<?php
											}
										?>
									</div>
									
									<!-- Sub Total -->
									<div class="payment-details subtotal-container">
										<div class="item-label">
											<?php echo $this->translator->translator("flight_invoice_sub_total_title"); ?>
										</div>
										
										<div class="item-value">
											<?php  echo $currencySymbol.' '.number_format(($sub_total + $sub_total_round ), 2, '.', ',').' '.$currencyShortName; ?>
										</div>
										<?php									
											$booking_fees = 0;				
											if(Settings_Service_Price::is_exists('3', $global_conf, ($sub_total + $sub_total_round)))
											{
												$booking_fee = Settings_Service_Price::getMargine('3');
												$booking_fee_amount	=	$this->price(($sub_total + $sub_total_round), null, '3');
												$booking_fees = ($sub_total + $sub_total_round ) + $booking_fee_amount;
												$booking_fee_show	=	(preg_match("/%/i", $booking_fee)) ? $currencySymbol.' '.number_format($booking_fee_amount, 2, '.', ',').' '.$booking_fee : $booking_fee;
												$item_details = '<div class="item-label">'.
														$this->translator->translator("flight_invoice_booking_fee").' :</div><div class="item-value">'.$booking_fee_show.'</div>';
												$item_details .= '<div class="item-label">'.$this->translator->translator("flight_invoice_sub_total_booking_title").' :</div><div class="item-value">'.$currencySymbol.' '.$booking_fees.' '.$currencyShortName.'</div>';
												echo $item_details;
											}
										?>
									</div>
									<!-- Sub Total -->                         
														 
								</div> 
							</div>
							<?php
									  $total_amount += $sub_total + $sub_total_round + $booking_fee_amount;
									  $total_tax += $sub_total_tax   + $sub_total_tax_round;
								  }
							  }
							 ?> 
							
							<div class="flight-booking-row2">
								<div class="row2-col">
                                	&nbsp;
								</div>
								
								<div class="row2-col">
								<!-- Grand Total --> 
								  <div class="payment-details amount-container">
								  	<div class="item-label">
										  <?php echo $this->translator->translator("flight_invoice_total_title"); ?>
									  </div>
									  
									  <div class="item-value">
										  <?php echo $currencySymbol.' '.number_format(($total_amount), 2, '.', ',').' '.$currencyShortName; ?>
									  </div>
									
									<?php
									  if(($total_amount) != $this->price($total_amount))
									  {
									  	$total_amount = $this->price($total_amount);
									  ?>
									  <div class="item-label">
										  <?php echo $this->translator->translator("flight_invoice_total_price_margine_title"); ?>
									  </div>
									  
									  <div class="item-value">
										  <?php echo $currencySymbol.' '.number_format(($total_amount), 2, '.', ',').' '.$currencyShortName; ?>
									  </div>
									  <?php
									  }	
									  ?>
									</div><br />
									<div class="payment-details amount-container"> 
									  <div class="item-label">
										  <?php echo $this->translator->translator("flight_invoice_total_tax_title"); ?>
									  </div>
									  
									  <div class="item-value">
										  <?php echo $currencySymbol.' '.number_format(($total_tax), 2, '.', ',').' '.$currencyShortName; ?>
									  </div>
									  
									  <div class="item-label">
										  <?php echo $this->translator->translator("flight_invoice_total_include_tax_title"); ?>
									  </div>
									  
									  <div class="item-value">
										  <?php echo $currencySymbol.' '.number_format(($total_amount+$total_tax), 2, '.', ',').' '.$currencyShortName; ?>
									  </div>
									 
									</div>
									
									  <?php								  
										if(Settings_Service_Price::is_exists('4', $global_conf, $total_amount))
										{	
											$services_charge_margine = Settings_Service_Price::getMargine('4');
											$services_charge_margine_show	=	(preg_match("/%/i", $services_charge_margine)) ? $currencySymbol.' '.number_format($this->invoice_arr[Eicra_File_Constants::INVOICE_SERVICE_CHARGE], 2, '.', ',').' '.$services_charge_margine : $services_charge_margine;										
											echo '<br /><div class="payment-details amount-container"><div class="item-label">'.
												$this->translator->translator("flight_invoice_service_charge").' :</div><div class="item-value"><strong>'.$services_charge_margine_show.'</strong>'.
											'</div></div>';
										}							
										
										
										if(Settings_Service_Price::is_exists('5', $global_conf, $total_amount))
										{	
											echo  '<br /><div class="payment-details amount-container"><div class="item-label">'.
												$this->translator->translator("flight_invoice_deposit_charge", Settings_Service_Price::getMargine('5')).' :</div><div class="item-value"><strong>'.$currencySymbol.' '.number_format($this->invoice_arr[Eicra_File_Constants::INVOICE_DEPOSIT_CHARGE], 2, '.', ',').' '.$currencyShortName.'</strong>'.
											'</div>';	
																
											echo '</div><br />
												<div class="payment-details amount-container">';
											
											echo    '<div class="item-label">'.
												$this->translator->translator("flight_invoice_deposit_payable").' :</div><div class="item-value"><strong>'.$currencySymbol.' '.number_format($this->invoice_arr[Eicra_File_Constants::INVOICE_NOW_PAYABLE], 2, '.', ',').' '.$currencyShortName.'</strong>'.
											'</div></div>';
										}
										
										if(Settings_Service_Price::is_exists('4', $global_conf, $total_amount))
										{	
											echo   '<br /><div class="payment-details amount-container"><div class="item-label">'.
												$this->translator->translator("flight_invoice_grand_total").' :</div><div class="item-value"><strong>'.$currencySymbol.' '.number_format(($total_amount+$total_tax+$this->invoice_arr[Eicra_File_Constants::INVOICE_SERVICE_CHARGE]), 2, '.', ',').' '.$currencyShortName.'</strong>'.
											'</div></div>';
										}
																	  
									  ?>
								  
								<!-- Grand Total -->
								</div>
							</div>
				</div>
                
				<?php
					if(Settings_Service_Price::is_exists('5', $global_conf, $total_amount) && !empty($this->invoice_arr[Eicra_File_Constants::INVOICE_NOW_PAYABLE]))
					{
					?>
					<div class="flight-booking bdr">
						<div class="flight-booking-row2">
							<div class="due-balance">
					<?php
							echo    '<div class="item-label">'.
								$this->translator->translator("flight_invoice_later_payable", $currencySymbol.' '.number_format((($total_amount+$total_tax+$this->invoice_arr[Eicra_File_Constants::INVOICE_SERVICE_CHARGE]) - $this->invoice_arr[Eicra_File_Constants::INVOICE_NOW_PAYABLE]), 2, '.', ',').' '.$currencyShortName  ).
							'</div>';
					?>
							</div>
						</div>
					</div>
					<?php
					}
				?>
                        
                
				<div class="clear">&nbsp;</div>
				
				<div id="tabs">
				<ul>
					<li><a href="<?php echo $tab_base_link; ?>#tabs-1"><?php echo $this->translator->translator('global_invoice_tab1'); ?></a></li>
					<li><a href="<?php echo $tab_base_link; ?>#tabs-2"><?php echo $this->translator->translator('global_invoice_tab2'); ?></a></li>
				</ul>
				<div id="tabs-1">	
						
							<div class="user-reg-icon">
								<h1><?php if(!empty($this->role_info)){ echo $this->role_info['role_name'].' '.$this->translator->translator('Member_frontend_register_title', '', 'Members'); }else{ echo $this->translator->translator('Member_frontend_register_title', '', 'Members'); } ?></h1>
							</div>
							
							<div class="clear">&nbsp;</div>
							
							<div id="actionMessage">&nbsp;</div>
							
							<form name="MemberForm" id="MemberForm">
								<?php 
									$file_type_arr = explode(',',$this->form_info['attach_file_type']);
									$j= 0;
									foreach($file_type_arr as $key => $value)
									{
										$file_type_arr[$j] = '*.'.$value;
										$j++;
									} 
									$file_format = implode(';',$file_type_arr);	
									$staticGroupsObj = $this->registrationForm->getDisplayGroups(); 
									$sorted_group_arr = array();
									foreach($staticGroupsObj as $staticGroup)
									{
										$sorted_group_arr[$staticGroup->getOrder()] = $staticGroup;
									}
									ksort($sorted_group_arr);																		
									$i=1;									
									foreach($sorted_group_arr as $staticGroup)
									{
										$elementsObj = $staticGroup->getElements();
								?>
								<fieldset>
                                    <legend><?php echo $this->translator->translator($staticGroup->getLegend(),'', 'Members');  ?></legend>                                    
                                        <div>
                                          <?php	
                                              $new_file_info = new Portfolio_Controller_Helper_File();															
                                              foreach($elementsObj as $element)
                                              {
                                                  if($element->getAttrib('frontend') == '1')
                                                  {	
                                                      $e_name_arr = explode('_',$element->getName());																				
                                                      $sumbol = (in_array(Eicra_File_Constants::PRICE,$e_name_arr,true)) ? '&nbsp;'.$currency->getSymbol() : '';							  
                                                      switch($element->getType())
                                                      {
                                                          case 'Zend_Form_Element_File':                                                    
                                                                      $image_file_arr = array();                                                                                                
                                                                  ?>
                                                                  
                                                                      <div class="form-label-container">
                                                                          <div class="label_class <?php echo $this->escape($this->form_info['label_class']); ?>" style="<?php echo $this->escape($this->form_info['label_style']); ?>">
                                                                              <?php echo $element->getLabel(); if($element->isRequired() ){ ?><span class="star_class <?php echo $this->escape($this->form_info['star_class']); ?>" style="<?php echo $this->escape($this->form_info['star_style']); ?>">*</span><?php } ?>
                                                                          </div>
                                                                       </div>
                                                              
                                                                       <div class="form-field-container">
                                                                          <div class="form-field">
                                                                              <script type="text/javascript">
                                                                              $(function(){
                                                                                  /**************************FILE UPLOAD START******************************/																					
                                                                                  dynamicUploader("<?php echo $element->getName().'_upload'; ?>", "<?php echo $element->getName(); ?>", <?php echo $this->settings_json_info; ?>, languageArray(), "<?php echo $this->url( array('module' => 'Portfolio','controller' => 'frontend', 'action'     => 'upload'), 'adminrout',    true) ?>", "<?php echo $this->url( array('module' => 'Portfolio','controller' => 'frontend', 'action'     => 'remove'), 'adminrout',    true) ?>", false);
                                                                                  /**************************FILE UPLOAD END*********************************/
                                                                              });
                                                                              </script>
                                                                              <span class="ui-widget"><input type="file" name="<?php echo $element->getName(); ?>_upload" id="<?php echo $element->getName(); ?>_upload" /><input type="hidden" name="<?php echo $element->getName(); ?>" id="<?php echo $element->getName(); ?>" class="<?php echo $element->getName(); ?>_class empty_class" value="" /></span>
                                                                              <br /><span class="input-errors" id="<?php echo $element->getName().'_err'; ?>"></span>
                                                                           </div>
                                                                           <div class="form-field-info">
                                                                              <?php if($element->getAttrib('info')){ ?><div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($element->getAttrib('info')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div><?php } ?>
                                                                           </div>                                                      									
                                                                       </div>
                                                                  
                                                                        <div class="form-label-container">
                                                                          <div class="label_class">&nbsp;</div>
                                                                        </div>
                                                                       
                                                                       <div class="form-field-container">
                                                                          <div class="form-field">
                                                                              <span id="selected_file_<?php echo $element->getName(); ?>">
                                                                                      <?php
                                                                                          $dynamic_image_view = '';
                                                                                          if(!empty($image_file_arr[0]))
                                                                                          {													
                                                                                              foreach($image_file_arr as $key => $value)
                                                                                              {	
                                                                                                  $show_file_path  =		$new_file_info->getFilePath($value, $this->settings_info);																												
                                                                                                  $img_code = '<div class="thumb"><img src="'.$show_file_path.'" title="'.$value.'" width="20" height="10" /></div>';
                                                                                                  $down_link = (!$new_file_info->isImage($value)) ? '<br /><a href="'.$this->settings_info[$this->settings_info['file_path_field']].'/'.$value.'">'.$this->translator->translator("common_download", "", "Projects").'</a>' : '';
                                                                                                  $del_link	=	'<a href="javascript:void(0)" class="delete_uploaded_image_link" field_name="'.$element->getName().'" file_name="'.$value.'" file_path="'.$this->settings_info[$this->settings_info['file_path_field']].'">'.$this->translator->translator("common_delete_title").'</a>'.$down_link;
                                                                                                  $dynamic_image_view .= '<div class="upload-img box"><span>'.$img_code.'<br /><br />&nbsp;&nbsp;'.$del_link.'&nbsp;&nbsp;&nbsp;</span></div>';
                                                                                              }															
                                                                                          }
                                                                                          echo $dynamic_image_view;
                                                                                      ?>
                                                                                  </span>&nbsp;
                                                                           </div>                                                     									
                                                                       </div>
                                                                  <?php	
                                                              break;
                                                          case 'Zend_Form_Element_MultiCheckbox':
                                                          case 'Zend_Form_Element_Radio':
                                                                  
                                                              ?>
                                                                      <div class="form-label-container">
                                                                          <div class="label_class <?php echo $this->escape($this->form_info['label_class']); ?>" style="<?php echo $this->escape($this->form_info['label_style']); ?>">
                                                                              <?php echo $element->getLabel(); if($element->isRequired() ){ ?><span class="star_class <?php echo $this->escape($this->form_info['star_class']); ?>" style="<?php echo $this->escape($this->form_info['star_style']); ?>">*</span><?php } ?>
                                                                          </div>
                                                                      </div>
                                                                      
                                                                      <div class="form-field-container">
                                                                          <div class="form-field">
                                                                              <span class="ui-widget"><div class="autos-features property-features vacationrental-features tours-features"><?php  echo $element; ?></div></span>
                                                                              <br /><span class="input-errors" id="<?php echo $element->getName().'_err'; ?>"></span>
                                                                          </div>
                                                                          <div class="form-field-info"><?php if($element->getAttrib('info')){ ?><div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($element->getAttrib('info')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div><?php } ?></div>
                                                                      </div>
                                                                      
                                                              <?php                                         
                                                              break;									
                                                          case 'Zend_Form_Element_Captcha':
                                                              ?>
                                                                    <div class="form-label-container">
                                                                          <div class="label_class <?php echo $this->escape($this->form_info['label_class']); ?>" style="<?php echo $this->escape($this->form_info['label_style']); ?>">
                                                                              <?php echo $element->getLabel(); if($element->isRequired() ){ ?><span class="star_class <?php echo $this->escape($this->form_info['star_class']); ?>" style="<?php echo $this->escape($this->form_info['star_style']); ?>">*</span><?php } ?>
                                                                          </div>
                                                                      </div>
                                                                      
                                                                      <div class="form-field-container">
                                                                          <div class="form-field">
                                                                              <div class="captcha">
                                                                                  <span class="ui-widget"><?php  echo $element; ?></span><br />
                                                                                  <span class="input-errors" id="<?php echo $element->getName().'_err'; ?>"></span>
                                                                              </div>
                                                                          </div>
                                                                          <div class="form-field-info"><?php if($element->getAttrib('info')){ ?><div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($element->getAttrib('info')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div><?php } ?></div>
                                                                      </div>
                                                              <?php	
                                                              break;
                                                          default:
                                                                                                                              
                                                              ?>
                                                              
                                                              <div class="form-label-container">
                                                                  <div class="label_class <?php echo $this->escape($this->form_info['label_class']); ?>" style="<?php echo $this->escape($this->form_info['label_style']); ?>" >
                                                                      <?php echo $element->getLabel(); if($element->isRequired() ){ ?><span class="star_class <?php echo $this->escape($this->form_info['star_class']); ?>" style="<?php echo $this->escape($this->form_info['star_style']); ?>">*</span><?php } ?>&nbsp;
                                                                  </div>
                                                              </div>
                                                      
                                                              <div class="form-field-container">
                                                                  <div class="form-field">
                                                                      <?php 										
                                                                              $id_f = $element->getAttrib('id');
                                                                              $id_arr = explode('_',$id_f);
                                                                              if(in_array(Eicra_File_Constants::DATE,$id_arr))
                                                                              {
                                                                              ?>
                                                                              <script type="text/javascript">
                                                                                  $(function() {
                                                                                      calender('<?php echo $id_f; ?>');
                                                                                  });
                                                                              </script>
                                                                              <?php
                                                                              }
                                                                              if($element->getType() == 'Zend_Form_Element_MultiCheckbox')
                                                                              {
                                                                                  echo '<span class="ui-widget">'.$element.$sumbol.'</span>';
                                                                              }
                                                                              else
                                                                              {
                                                                                  echo '<span class="ui-widget">'.$element.$sumbol.'</span>';
                                                                              }															
                                                                      ?><br />
                                                                      <span class="input-errors" id="<?php echo $element->getName().'_err'; ?>"></span>                                              
                                                                  </div>
                                                                  <div class="form-field-info"><?php if($element->getAttrib('info')){ ?><div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($element->getAttrib('info')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div><?php } ?></div>                                              
                                                               </div>                                     
                                                              <?php                                                 
                                                              break;										
                                                      }
                                                  }
                                              }
                                          ?>
                                          </div>
                                        <div class="clear">&nbsp;</div>
                                </fieldset>     
								<?php
									$group_no = ($this->escape($this->form_info['group_no'])) ? (int)$this->escape($this->form_info['group_no']) : 1;
									}
								?>    
							</form>
						
					<div class="clear btn-container">
						<span class="form-button ui-widget-content-1"><a href="AirlineFlightSchedules" ><?php echo $this->translator->translator('flight_cart_continue'); ?></a></span>
						<span class="form-button ui-widget-content-1"><a href="javascript:  void(0);" class="reset_btn"><?php echo $this->translator->translator('common_reset'); ?></a></span>
						<span class="form-button ui-widget-content-1"><a href="javascript: void(0);" class="add_user_btn"><?php echo $this->translator->translator('common_submit'); ?></a></span>
					</div>
				</div>
				
				<div id="tabs-2">
					<?php
					if ($auth->hasIdentity ())
					{
						if($this->mem_info)
						{
					?>
							<div class="member-login" style="display:none;">
								<div class="login-box">
								   	<h1><?php echo $this->translator->translator('Member_frontend_login_title', '', 'Members'); ?></h1>
                                   	<hr />
								  
                                    <div id="actionLoginMessage"><?php echo $this->logindetails->getDescription(); ?></div>
                                    <div class="login-img"></div>
										<div id="login_box" class="field-area">
											<form id="AdminLogin" name="AdminLogin" method="post" action="">
                                                <p><?php  echo $this->logindetails->username->getLabel();	?></p>
                                                <?php  echo $this->logindetails->username;?>
                                                <span class="input-errors" id="username_login_err"></span>
                                            
                                                <p><?php  echo $this->logindetails->password->getLabel();	?></p>
                                                <?php  echo $this->logindetails->password;?>
                                                <span class="input-errors" id="password_login_err"></span>
                                            
                                                <?php if($this->logindetails->login_captcha){ ?>
                                                    <p><?php  echo $this->logindetails->login_captcha->getLabel();	?></p>
                                                    <div class="captcha">
                                                        <?php  echo $this->logindetails->login_captcha;?>
                                                        <div class="form-field-info"><div class="ui-widget ui-helper-clearfix"><div class="ui-state-default ui-corner-all info-class" title="<?php echo $this->escape($this->logindetails->login_captcha->getAttrib('info')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div></div>
                                                        <span class="input-errors" id="login_captcha_login_err"></span>
                                                    </div>
                                                <?php } ?>
												
												<?php echo $this->logindetails->token; ?>
												
												<div class="clear btn-container" > 
												<span class="form-button ui-widget-content-1"><a href="javascript:void(0);" class="login_cancel"><?php echo $this->translator->translator('common_cancel'); ?></a></span>
												<span class="form-button ui-widget-content-1"><input type="button" name="login" value="<?php echo $this->translator->translator('Member_frontend_login_button', '', 'Members'); ?>" class="login_send_btn"/></span>
												</div>
											</form>
										</div>
								</div>
							</div>
							
							<div id="logout_box">
                            	<div class="customer-details"> 
                                    <div class="chart-row">
                                        <div class="chart-label mod-title">
                                            <?php echo $this->translator->translator('global_invoice_customer_first_name'); ?>
                                        </div>
                                        
                                        <div class="chart-value">
                                            <?php echo $this->escape($this->mem_info['firstName']); ?>
                                        </div>
                                    </div>
                                
                                    <div class="chart-row">
                                        <div class="chart-label mod-title">
                                            <?php echo $this->translator->translator('global_invoice_customer_last_name'); ?>
                                        </div>
                                        
                                        <div class="chart-value">
                                            <?php echo $this->escape($this->mem_info['firstName']); ?>
                                        </div>
                                    </div>
                                
									<?php if(!empty($this->mem_info['companyName'])){ ?>
                                    <div class="chart-row">
                                        <div class="chart-label mod-title">
                                            <?php echo $this->translator->translator('global_invoice_customer_company_name'); ?>
                                        </div>
                                        
                                        <div class="chart-value">
                                            <?php echo $this->escape($this->mem_info['companyName']); ?>
                                        </div>
                                    </div>
                                    <?php } ?>
                                
									<?php if(!empty($this->mem_info['address'])){ ?>
                                    <div class="chart-row">
                                        <div class="chart-label mod-title">
                                            <?php echo $this->translator->translator('global_invoice_customer_address'); ?>
                                        </div>
                                        
                                        <div class="chart-value">
                                            <?php echo $this->escape($this->mem_info['address']); ?>
                                        </div>
                                    </div>
                                    <?php } ?>
                                
									<?php if(!empty($this->mem_info['city'])){ ?>
                                    <div class="chart-row">
                                        <div class="chart-label mod-title">
                                            <?php echo $this->translator->translator('global_invoice_customer_city'); ?>
                                        </div>
                                        
                                        <div class="chart-value">
                                            <?php echo $this->escape($this->mem_info['city']); ?>
                                        </div>
                                    </div>
                                    <?php } ?>
                                
									<?php if(!empty($this->mem_info['state'])){ ?>
                                    <div class="chart-row">
                                        <div class="chart-label mod-title">
                                            <?php echo $this->translator->translator('global_invoice_customer_state'); ?>
                                        </div>
                                        
                                        <div class="chart-value">
                                            <?php echo $this->escape($this->mem_info['state']); ?>
                                        </div>
                                    </div>
                                    <?php } ?>
                                
                                	<?php if(!empty($this->mem_info['postalCode'])){ ?>
                                    <div class="chart-row">
                                        <div class="chart-label mod-title">
                                            <?php echo $this->translator->translator('global_invoice_customer_postcode'); ?>
                                        </div>
                                        
                                        <div class="chart-value">
                                            <?php echo $this->escape($this->mem_info['postalCode']); ?>
                                        </div>
                                    </div>
                                    <?php } ?>
                                
									<?php if(!empty($this->mem_info['country_name'])){ ?>
                                    <div class="chart-row">
                                        <div class="chart-label mod-title">
                                            <?php echo $this->translator->translator('global_invoice_customer_country'); ?>
                                        </div>
                                        
                                        <div class="chart-value">
                                            <?php echo $this->escape($this->mem_info['country_name']); ?>
                                        </div>
                                    </div>
                                    <?php } ?>
                                
									<?php if(!empty($this->mem_info['mobile'])){ ?>
                                    <div class="chart-row">
                                        <div class="chart-label mod-title">
                                            <?php echo $this->translator->translator('global_invoice_customer_phone'); ?> 
                                        </div>
                                        
                                        <div class="chart-value">
                                            <?php echo $this->escape($this->mem_info['mobile']); ?>
                                        </div>
                                    </div>
                                    <?php } ?>  
                                 </div>							
                            
                                <div  class="clear invoice-login-area"> 
                                    <span class="form-button ui-widget-content-1"><a href="javascript:void(0);" class="logout_btn"><?php echo $this->translator->translator('flight_invoice_login_another'); ?></a></span>  
                                </div>
                             </div>   
					<?php		
						}
					?>
                    	
                        <hr />
                        
						<div class="clear btn-container">
							<span class="form-button ui-widget-content-1"><a href="AirlineFlightSchedules" ><?php echo $this->translator->translator('flight_cart_continue'); ?></a></span>
							<span class="form-button ui-widget-content-1"><a href="Create-Invoice"><?php echo $this->translator->translator('flight_continue_next'); ?></a></span>
						</div>
					<?php
					
					}
					else
					{
					?>
						<div class="member-login">
                        	<div class="login-box">
                                <h1><?php echo $this->translator->translator('Member_frontend_login_title', '', 'Members'); ?></h1> 
                                <div id="actionLoginMessage"><?php echo $this->logindetails->getDescription(); ?></div>
                                <div class="login-img"></div>
                                        
                                <div id="login_box" class="field-area" style="display:<?php if(Zend_Auth::getInstance()->hasIdentity()){	?>none;<?php }?>">
                                    <form id="AdminLogin" name="AdminLogin" method="post" action="">
                                        <p><?php  echo $this->logindetails->username->getLabel();	?></p>
                                        <?php  echo $this->logindetails->username;?>
                                        <span class="input-errors" id="username_login_err"></span>
                                    
                                        <p><?php  echo $this->logindetails->password->getLabel();	?></p>
                                        <?php  echo $this->logindetails->password;?>
                                        <span class="input-errors" id="password_login_err"></span>
                                        
                                        <?php if($this->logindetails->login_captcha){ ?>
                                            <p><?php  echo $this->logindetails->login_captcha->getLabel();	?></p>
                                            <div class="captcha">
                                                <?php  echo $this->logindetails->login_captcha;?>
                                                <div class="form-field-info"><div class="ui-widget ui-helper-clearfix"><div class="ui-state-default ui-corner-all info-class" title="<?php echo $this->escape($this->logindetails->login_captcha->getAttrib('info')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div></div><br />
                                                <span class="input-errors" id="login_captcha_login_err"></span>
                                            </div>
                                        <?php } ?>
                                        
                                        <?php echo $this->logindetails->token; ?>
                                        
                                        <div class="clear"><input type="button" name="login" value="<?php echo $this->translator->translator('Member_frontend_login_button', '', 'Members'); ?>" class="login_send_btn"/></div>
                                    </form>
                                </div>
                            </div>
						</div>
					<?php
					}
					?>
				</div>
				</div>
			
			<?php
				}
				else
				{
			?>
				
				<?php echo $this->translator->translator('flight_invoice_seat_finished'); ?>				
				<div class="clear btn-container">
						<span class="form-button ui-widget-content-1">&nbsp; <a href="AirlineFlightSchedules"><?php echo $this->translator->translator('flight_invoice_search_flight_again'); ?></a></span>
				</div>
			<?php
			}
		}
		else
		{
		?>
				<span class="warning"><?php echo $this->translator->translator('flight_invoice_post_dats_empty'); ?></span>
				<div class="clear btn-container">
					<span class="form-button ui-widget-content-1">&nbsp; <a href="AirlineFlightSchedules"><?php echo $this->translator->translator('flight_invoice_search_flight_again'); ?></a></span>
				</div>
				
		<?php
		}
		?>
    </div>
</div>
<div id="dialog_msg" title="<?php echo $this->translator->translator('common_dialog_msg','Message'); ?>"></div>
<div id="dialog_container" style="display:none" title="<?php echo $this->translator->translator('common_processing_language'); ?>">
    <div id="progressbar" ></div>	
</div>
</div>