<?php
$version = Zend_Registry::get('version');
$global_conf = Zend_Registry::get('global_conf');
$currency = new Zend_Currency($global_conf['default_locale']);

?>

<script type="text/javascript">
$(document).ready(function() {	
	var route_field = 0;
	var route_field_round = 0;
	
	floatingbar('#floatingbar',"#button_top_bar",null);
	
	checkSameData('flight_route_departure', 'flight_route_arrival', route_field);
	
	$("input[name='flight_journey_type']").click(function() {
			var val = $(this).val();			
			switch(val)
			{
				case 'One way':
					$('#fair_round').css('display','none');					
				 break;
				 case 'Round':
					$('#fair_round').css('display','inline');
				 break;
				 case 'Multi City':
				 	$('#fair_round').css('display','none');
				 break;
			}
		});
	
	
	$('a.flight_route_add_more_btn').click(function() {
		route_field++;
		var hr = '';
		var mn = '';
		var field_html = generateDynamicFields(route_field, '');
			$('#route_fields').append(field_html);
			checkSameData('flight_route_departure', 'flight_route_arrival', route_field);
	});	
	
	$("input[name='flight_journey_type']").click(function() {
		if($(this).val() == 'Round')
		{
			checkSameData('flight_route_departure_round', 'flight_route_arrival_round', route_field_round);
			roundFunction(route_field_round);
		}
	});
		
	$('a.reset_btn').click(function() {			
		 resetFields();	
		 removeError();	
	});
	
	function resetFields()
	{
		$( "form" )[ 0 ].reset();		
		$('#selected_file').html('');
		$('#flight_route').val('');	
		$('#fair_round').css('display','none');				
	}
	
	function removeError()
	{
		$('#actionMessage').html('');
		$('#flight_route_err').html('');	
		
		var filename = '';
		var filevalue = '';		
		$.each($('form').serializeArray(), function(i, field) {	
				if(field.name.match(/\[\]$/))
				{
					var filearr = field.name.split('[]');
					filename = filearr[0];					
				}
				else
				{
					filename 	= 	field.name;
				} 			
				$('#'+filename).removeClass('ui-state-error');
				$('#'+filename+'_err').html('');									
		});				
	}		
	
	function addError(key,errMsg)
	{
		var err_id = key+'_err';
		var field_name = key;
		$('#'+field_name).addClass('ui-state-error');
		$('#'+err_id).append(errMsg);
	}
	
	function openLoaderDialog()
	{
		$('#dialog_container').dialog({
					autoOpen: true,
					modal: true,
					show: 'fade',
					resizable: 'false',				
					open: function(event, ui)
						 {
						 	$("#progressbar").progressbar({
								value:100
				
							});							
						  }
				});
	}
	
	function closeLoaderDialog()
	{
		$('#dialog_container').dialog('option','hide','explode').dialog('close');
	}
	
	function getFormData()
	{
		var fieldObj = {};
		var filename = '';
		var filevalue = '';
		$.each($('form').serializeArray(), function(i, field) {	
			if(field.name.match(/\[\]$/))
			{
				var filearr = field.name.split('[]');
				filename = filearr[0];								
				filevalue = $('#'+filename).val();
				if($('input[name="'+filename+'[]"]').is(':checkbox'))
				{
					var val_arr = [];
					$('input[name="'+filename+'[]"]:checkbox:checked').each(function(i){
					 val_arr[i] = $(this).val();
					});
					filevalue = (val_arr[0] != null) ? val_arr.join(',') : null;					
				}				
			}
			else
			{
				filename 	= 	field.name;
				filevalue 	= 	field.value;
			}			
			fieldObj[filename] = filevalue;			
		});
		return fieldObj;
	}
	
	$('a.add_flight_route_btn').click(function() {			
		
		checkRouteFieldValue('');
		if($("input[name='flight_journey_type']:checked").val() == 'Round')
		{
			checkRouteFieldValue('_round');			
		}	
		var formData = getFormData();	
		formData.route_field = route_field;	
		formData.route_field_round = ($('#route_fields_round').children().length - 1) ;	
		
		$.ajax({
				url: "<?php echo $this->url( array('module' => 'Flight','controller' => 'route', 'action'     => 'add' ), 'adminrout',    true) ?>",
			  	type: 'POST',
				beforeSend: function(){						
						removeError();
						openLoaderDialog();				
					 },
			  	data: formData,
				success: function(response){
					//alert(response);					
					var json_arr = eval("("+response+")");					
					closeLoaderDialog();					
					if(json_arr.status == 'ok')
					{
						$('#actionMessage').html(succMsgDesign(json_arr.msg));						
						resetFields();							
					}
					else if(json_arr.status == 'errV')
					{
						$('#actionMessage').html(errMsgDesign("<?php echo $this->translator->translator('common_err'); ?>"));
												
						for(var i= 0; i < json_arr.msg.length; i++)
						{
							addError(json_arr.msg[i].key,json_arr.msg[i].value);							
						}
					}
					else
					{
						$('#actionMessage').html(errMsgDesign(json_arr.msg));
					}
				},
				error: function(xhr, status, error){
					closeLoaderDialog();
					var msg = "Error! " + xhr.status + " " + error;
					$('#actionMessage').html(errMsgDesign(msg));
				}
		});
	});

});

function openMsgDialog(msg)
{
	$('#dialog_msg').html(msg).dialog({
		autoOpen: true,
		modal: true,
		show: 'fade',
		resizable: 'false',				
		buttons: { "<?php echo html_entity_decode($this->translator->translator('common_ok'), ENT_QUOTES, "UTF-8"); ?>": function() { $(this).dialog('option', 'hide', 'explode').dialog("close"); } },
		open: function(event, ui)
			 {
				setTimeout(function() 
				{									
					if($('#' + event.target.id).dialog('isOpen'))
					{
						$('#' + event.target.id).dialog('option', 'hide', 'explode').dialog('close');										
					}
				}, 10000);
			  }
	});
}

function roundFunction(route_field_round)
{
	$('a.flight_route_add_more_btn_round').unbind('click');
	$('a.flight_route_add_more_btn_round').click(function() {
		route_field_round++;
		var hr = '';
		var mn = '';
		var field_html = generateDynamicFields(route_field_round, '_round');
			$('#route_fields_round').append(field_html);
			checkSameData('flight_route_departure_round', 'flight_route_arrival_round', route_field_round);
	});	
}

function generateDynamicFields(route_field, round_value )
{
	var field_html = '<div class="route_box">'+
							'<div class="route_box_first_row">'+
							  '<?php echo $this->translator->translator("flight_route_departure_label"); ?>&nbsp;'+
								'<input name="flight_route_departure'+round_value+route_field+'" id="flight_route_departure'+round_value+route_field+'" class="flight_route_departure'+round_value+'" value="" />'+							
									'&nbsp;&nbsp;&nbsp;&nbsp;'+	
								'<?php echo $this->translator->translator("flight_route_departure_hour_label"); ?>&nbsp;'+	
								'<select name="flight_route_departure_date_hh'+round_value+route_field+'" id="flight_route_departure_date_hh'+round_value+route_field+'" class="flight_route_departure_date_hh'+round_value+'">'+	
									'<option value="00"><?php echo $this->translator->translator("flight_route_departure_hour_label"); ?></option>';	
									for(var i = 0; i <= 24; i++)
									{ 
										hr = (i < 10 ) ? '0'+i : i;
						field_html += '<option value="'+hr+'">'+hr+'</option>';
									} 
				field_html += 	'</select>'+	
								'&nbsp;&nbsp;&nbsp;&nbsp;'+	
								'<?php echo $this->translator->translator("flight_route_departure_min_label"); ?>&nbsp;'+	
								'<select name="flight_route_departure_date_mn'+round_value+route_field+'" id="flight_route_departure_date_mn'+round_value+route_field+'" class="flight_route_departure_date_mn'+round_value+'">'+	
								'<option value="00"><?php echo $this->translator->translator("flight_route_departure_min_label"); ?></option>';
								for(var i = 0; i <= 60; i++)
									{ 
										mn = (i < 10 ) ? '0'+i : i;
						field_html += '<option value="'+mn+'">'+mn+'</option>';
									}							
				field_html += 	'</select>'+
								'<br />'+
								  '<?php echo $this->translator->translator("flight_route_departure_date_label"); ?>&nbsp;'+
								  '<input type="checkbox" name="flight_route_departure_date'+round_value+route_field+'[]" id="flight_route_departure_date'+round_value+route_field+'" class="flight_route_departure_date'+round_value+'" value="Sun" />Sun&nbsp;&nbsp;'+
								  '<input type="checkbox" name="flight_route_departure_date'+round_value+route_field+'[]" id="flight_route_departure_date'+round_value+route_field+'" class="flight_route_departure_date'+round_value+'" value="Mon" />Mon&nbsp;&nbsp;'+
								  '<input type="checkbox" name="flight_route_departure_date'+round_value+route_field+'[]" id="flight_route_departure_date'+round_value+route_field+'" class="flight_route_departure_date'+round_value+'" value="Tue" />Tue&nbsp;&nbsp;'+
								  '<input type="checkbox" name="flight_route_departure_date'+round_value+route_field+'[]" id="flight_route_departure_date'+round_value+route_field+'" class="flight_route_departure_date'+round_value+'" value="Wed" />Wed&nbsp;&nbsp;'+
								  '<input type="checkbox" name="flight_route_departure_date'+round_value+route_field+'[]" id="flight_route_departure_date'+round_value+route_field+'" class="flight_route_departure_date'+round_value+'" value="Thu" />Thu&nbsp;&nbsp;'+
								  '<input type="checkbox" name="flight_route_departure_date'+round_value+route_field+'[]" id="flight_route_departure_date'+round_value+route_field+'" class="flight_route_departure_date'+round_value+'" value="Fri" />Fri&nbsp;&nbsp;'+
								  '<input type="checkbox" name="flight_route_departure_date'+round_value+route_field+'[]" id="flight_route_departure_date'+round_value+route_field+'" class="flight_route_departure_date'+round_value+'" value="Sat" />Sat&nbsp;&nbsp;'+
							'</div>'+
							'<div class="route_box_delete_row">'+
							 	'<a href="javascript:void(0)" class="delete_route_fields_btn"><img src="application/modules/Administrator/layouts/scripts/images/common/delete.png" title="<?php echo html_entity_decode($this->translator->translator("common_delete"), ENT_QUOTES, "UTF-8"); ?>" alt="<?php echo html_entity_decode($this->translator->translator("common_delete"), ENT_QUOTES, "UTF-8"); ?>" border="0" /></a>'+
							 '</div>'+
							'<div class="route_box_second_row">'+
							  '<?php echo $this->translator->translator("flight_route_arrival_label"); ?>&nbsp;'+
							  '<input name="flight_route_arrival'+round_value+route_field+'" id="flight_route_arrival'+round_value+route_field+'" class="flight_route_arrival'+round_value+'" value="" />'+
									'&nbsp;&nbsp;&nbsp;&nbsp;'+
							  '<?php echo $this->translator->translator("flight_route_arrival_hour_label"); ?>&nbsp;'+
							  '<select name="flight_route_arrival_date_hh'+round_value+route_field+'" id="flight_route_arrival_date_hh'+round_value+route_field+'" class="flight_route_arrival_date_hh'+round_value+'">'+
								'<option value="00"><?php echo $this->translator->translator("flight_route_arrival_hour_label"); ?></option>';
								for(var i = 0; i <= 24; i++)
									{ 
										hr = (i < 10 ) ? '0'+i : i;
						field_html += '<option value="'+hr+'">'+hr+'</option>';
									} 
				field_html += '</select>'+
								'&nbsp;&nbsp;&nbsp;&nbsp;'+
							  '<?php echo $this->translator->translator("flight_route_arrival_min_label"); ?>&nbsp;'+
							  '<select name="flight_route_arrival_date_mn'+round_value+route_field+'" id="flight_route_arrival_date_mn'+round_value+route_field+'" class="flight_route_arrival_date_mn'+round_value+'">'+
								'<option value="00"><?php echo $this->translator->translator("flight_route_arrival_min_label"); ?></option>';
								for(var i = 0; i <= 60; i++)
									{ 
										mn = (i < 10 ) ? '0'+i : i;
						field_html += '<option value="'+mn+'">'+mn+'</option>';
									}
				field_html += '</select>'+	
							  '<br />'+
							  '<?php echo $this->translator->translator("flight_route_arrival_date_label"); ?>&nbsp;'+
							  '<input type="checkbox" name="flight_route_arrival_date'+round_value+route_field+'[]" id="flight_route_arrival_date'+round_value+route_field+'" class="flight_route_arrival_date'+round_value+'" value="Sun" />Sun&nbsp;&nbsp;'+
							  '<input type="checkbox" name="flight_route_arrival_date'+round_value+route_field+'[]" id="flight_route_arrival_date'+round_value+route_field+'" class="flight_route_arrival_date'+round_value+'" value="Mon" />Mon&nbsp;&nbsp;'+
							  '<input type="checkbox" name="flight_route_arrival_date'+round_value+route_field+'[]" id="flight_route_arrival_date'+round_value+route_field+'" class="flight_route_arrival_date'+round_value+'" value="Tue" />Tue&nbsp;&nbsp;'+
							  '<input type="checkbox" name="flight_route_arrival_date'+round_value+route_field+'[]" id="flight_route_arrival_date'+round_value+route_field+'" class="flight_route_arrival_date'+round_value+'" value="Wed" />Wed&nbsp;&nbsp;'+
							  '<input type="checkbox" name="flight_route_arrival_date'+round_value+route_field+'[]" id="flight_route_arrival_date'+round_value+route_field+'" class="flight_route_arrival_date'+round_value+'" value="Thu" />Thu&nbsp;&nbsp;'+
							  '<input type="checkbox" name="flight_route_arrival_date'+round_value+route_field+'[]" id="flight_route_arrival_date'+round_value+route_field+'" class="flight_route_arrival_date'+round_value+'" value="Fri" />Fri&nbsp;&nbsp;'+
							  '<input type="checkbox" name="flight_route_arrival_date'+round_value+route_field+'[]" id="flight_route_arrival_date'+round_value+route_field+'" class="flight_route_arrival_date'+round_value+'" value="Sat" />Sat&nbsp;&nbsp;'+											  
							 '</div>'+							 
						   '</div>';
		return field_html;
}

function isCheckBoxValue(id,filename)
{
	var val_arr = [];
	var filevalue = false;
	$('input[name="'+filename+id+'[]"]:checkbox:checked').each(function(i){
	 val_arr[i] = $(this).val();
	});
	filevalue = (val_arr[0] != null) ? true : false;
	return filevalue;
}

function checkRouteFieldValue(round_value)
{
	var check = false;
	var attr_id = '';
	var id_no_arr = [];
	for(var i=0; i < $('input.flight_route_departure'+round_value).length; i++)
	{	
		attr_id  =	$('input.flight_route_departure'+round_value+':eq('+i+')').attr('id');
		id_no_arr = attr_id.split('flight_route_departure'+round_value);		
		if(jQuery.trim($('input.flight_route_departure'+round_value+':eq('+i+')').val()) != '' && jQuery.trim($('input.flight_route_arrival'+round_value+':eq('+i+')').val()) != '' && isCheckBoxValue(id_no_arr[1], 'flight_route_departure_date'+round_value) == true && isCheckBoxValue(id_no_arr[1], 'flight_route_arrival_date'+round_value)  == true  )
		{			
			check = true;
		}
	}	
	if(check == true)
	{
		$('#flight_route'+round_value).val(check);
	}
	else
	{
		$('#flight_route'+round_value).val('');
	}	
}

function checkSameData(from_id, to_id, id_no)
{
	$('#'+from_id+id_no).blur(function() {		
		if( ($('#'+from_id+id_no).val() != '') && ($('#'+from_id+id_no).val() == $('#'+to_id+id_no).val()) )
		{
			var msg = "<?php echo $this->translator->translator('flight_route_same_err'); ?>";
			openMsgDialog(msg);
			$('#'+from_id+id_no).val('');
			$('#'+from_id+id_no).focus();
		}
	});
	
	$('#'+to_id+id_no).blur(function() {		
		if( ($('#'+to_id+id_no).val() != '') && ($('#'+from_id+id_no).val() == $('#'+to_id+id_no).val()) )
		{
			var msg = "<?php echo $this->translator->translator('flight_route_same_err'); ?>";
			openMsgDialog(msg);
			$('#'+to_id+id_no).val('');
			$('#'+to_id+id_no).focus();
		}
	});	
	
	//calendar(from_id+'_date'+id_no, to_id+'_date'+id_no);
	//calendar(to_id+'_date'+id_no, from_id+'_date'+id_no);
	autoList(from_id+id_no);
	autoList(to_id+id_no);
	deleteRouteFields();
}

function deleteRouteFields()
{
	$('a.delete_route_fields_btn').click(function() {
		var self = this;
		$(self).parents('div:first').parents('div:first').remove();
	});
}

function autoList(id)
{
	autoSuggestion(id, "<?php echo $this->url( array('module'=> 'Flight', 'controller' => 'frontend', 'action'     => 'iata' ), 'adminrout',    true) ?>", {'datas': ''}, ['iata_code', 'iata_code', 'flight_label', 'iata_code', 'flight_location'], '', 3);
}

function toTimestamp(strDate){
	 var datum = Date.parse(strDate);
	 return datum/1000;
}

function calendar(id, second_id)
{
	$("#"+id).datepicker({
		showOn: 'button',
		buttonImage: 'application/modules/Administrator/layouts/scripts/images/common/calendar.png',
		buttonImageOnly: true,
		monthNamesShort:<?php echo $this->translator->translator("common_calender_monthNamesShort"); ?>,
		monthNames:<?php echo $this->translator->translator("common_calender_monthNames"); ?>,
		dayNamesMin:<?php echo $this->translator->translator("common_calender_dayNamesMin"); ?>,
		showAnim: 'slide',
		buttonText: 'Calender',
		dateFormat:'yy-mm-dd',
		onSelect: function(dateText, inst) {
			var id_type_arr = id.split('_');			
			var currentTime = new Date()
			var currentDay = (currentTime.getDate() < 10) ? '0' + currentTime.getDate() : currentTime.getDate();
			var currentMonth = ((currentTime.getMonth() + 1) < 10) ? '0' + (currentTime.getMonth() + 1) : (currentTime.getMonth() + 1);
			var today = currentTime.getFullYear() + '-' + currentMonth + '-' + currentDay;				
			if(id_type_arr[2] == 'departure')
			{				
				if( (dateText != '') && ( (toTimestamp(dateText) >= toTimestamp($('#'+second_id).val())) || (toTimestamp(dateText) <= toTimestamp(today)) )  )
				{
					var msg = "<?php echo $this->translator->translator('flight_route_departure_date_err'); ?>";
					openMsgDialog(msg);
					$('#'+id).val('');
				}
			}
			else if(id_type_arr[2] == 'arrival')
			{
				if( (dateText != '') && ( (toTimestamp(dateText) <= toTimestamp($('#'+second_id).val())) || (toTimestamp(dateText) <= toTimestamp(today)) )  )
				{
					var msg = "<?php echo $this->translator->translator('flight_route_arrival_date_err'); ?>";
					openMsgDialog(msg);
					$('#'+id).val('');
				}
			}
		},
		autoSize:false,
		showButtonPanel:false,
		changeMonth: true,
		changeYear: true
	});
	
	$("img[class='ui-datepicker-trigger']").each(function()
	 { 
	  	$(this).attr('style', '');
	 });
}

function getFileExtension(filename)
{
	return filename.replace(/^.*?\.([a-zA-Z0-9]+)$/, "$1");
}
</script>

<div id="container">
<?php if (!$this->allow()) : ?>
	<div class="grid_12 t_a_bottom">
		<?php echo $this->translator->translator('Member_Access_deny_desc'); ?>
	</div>
<?php else : ?>

<div class="title-container">
	<div class="flight-add"><h1><?php echo $this->translator->translator('flight_route_add_page_name'); ?></h1></div>
    
    <div class="button-container">
        <span class="button ui-widget-content-1"><a href="<?php echo $this->url( array('module' => 'Flight','controller' => 'route', 'action'     => 'list' ), 'adminrout',    true) ?>" class="back_btn_link"><span class="icon back"><?php echo $this->translator->translator('common_back'); ?></span></a></span>
        <span class="button ui-widget-content-1"><a href="javascript:  void(0);" class="reset_btn"><span class="icon reset"><?php echo $this->translator->translator('common_reset'); ?></span></a></span>
        <span class="button ui-widget-content-1"><a href="javascript: void(0);" class="add_flight_route_btn"><span class="icon save"><?php echo $this->translator->translator('common_save'); ?></span></a></span>
    </div>
</div>

<div class="content-container">
	<form name="formCategory" id="formCategory" method="post">
    	<div id="button_top_bar"></div>
    	<div id="actionMessage"></div>
        	<?php	
				$groupsObj = $this->routeForm->getDisplayGroups();
				 
				 foreach($groupsObj as $elementGroup)
				 {		
			?>
            <div id="<?php echo $elementGroup->getName(); ?>">
			<fieldset class="fieldset">
                <legend class="legend"><?php echo $elementGroup->getLegend ();  ?></legend>
                <div class="form">
                	<?php						 									
					$elements = $elementGroup->getElements();
					foreach($elements as $element)
					{
						if($element->getName() == 'airlines_logo')
						{
					?>
                	<div class="form-row">
                        <div class="label">
                        	<?php echo $element->getLabel();  if($element->isRequired()){ ?><span class="required">*</span><?php } ?>
                        </div>
                        
                        <div class="field">
                        	<div class="upload-img">
                                <span class="button ui-widget-content-1"><a href="javascript:  void(0);" class="upload_btn"><span class="icon upload"><?php echo $this->translator->translator('common_upload'); ?></span></a></span>
                                <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($element->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                            </div>
                            <?php echo $element; ?>&nbsp;&nbsp;<span id="selected_file"></span>
                            <div class="input-errors" id="<?php echo $element->getName().'_err'; ?>"></div>
                        </div>
                    </div>
                    <?php
						}								
						else if($element->getName() == 'flight_route')
						{
					?>
                    <div class="form-row">
                        <div class="label">
                        	<?php echo $element->getLabel();  if($element->isRequired()){ ?><span class="required">*</span><?php } ?><?php echo $element; ?>
                        </div>
                        
                        <div class="field">
                        	<div id="route_fields" class="route_fields">
                                <div class="route_box">
                                	<div class="route_box_first_row">
                                    	<?php echo $this->translator->translator('flight_route_departure_label'); ?>
                                      	<input name="flight_route_departure0" id="flight_route_departure0" class="flight_route_departure" value="" />													  	
                                      
                                      	&nbsp;&nbsp;
                                      	<?php echo $this->translator->translator('flight_route_departure_hour_label'); ?>
                                      	<select name="flight_route_departure_date_hh0" id="flight_route_departure_date_hh0" class="flight_route_departure_date_hh">
                                        	<option value="00"><?php echo $this->translator->translator('flight_route_departure_hour_label'); ?></option>
                                        	<?php $hr = 0; for($i = 0; $i <= 24; $i++){ $hr = ($i < 10 ) ? '0'.$i : $i; ?> 
                                        	<option value="<?php echo $hr; ?>"><?php echo $hr; ?></option>
                                        	<?php } ?>
                                      	</select>
                                      	&nbsp;&nbsp;
                                      	<?php echo $this->translator->translator('flight_route_departure_min_label'); ?>
                                      	<select name="flight_route_departure_date_mn0" id="flight_route_departure_date_mn0" class="flight_route_departure_date_mn">
                                        	<option value="00"><?php echo $this->translator->translator('flight_route_departure_min_label'); ?></option>
                                        	<?php $mn = 0; for($i = 0; $i <= 60; $i++){ $mn = ($i < 10 ) ? '0'.$i : $i; ?> 
                                        	<option value="<?php echo $mn; ?>"><?php echo $mn; ?></option>
                                        	<?php } ?>
                                      	</select>
                                      	<br />
                                      	<?php echo $this->translator->translator('flight_route_departure_date_label'); ?>
                                      	<input type="checkbox" name="flight_route_departure_date0[]" id="flight_route_departure_date0" class="flight_route_departure_date" value="Sun" />Sun&nbsp;
                                      	<input type="checkbox" name="flight_route_departure_date0[]" id="flight_route_departure_date0" class="flight_route_departure_date" value="Mon" />Mon&nbsp;
                                      	<input type="checkbox" name="flight_route_departure_date0[]" id="flight_route_departure_date0" class="flight_route_departure_date" value="Tue" />Tue&nbsp;
                                      	<input type="checkbox" name="flight_route_departure_date0[]" id="flight_route_departure_date0" class="flight_route_departure_date" value="Wed" />Wed&nbsp;
                                      	<input type="checkbox" name="flight_route_departure_date0[]" id="flight_route_departure_date0" class="flight_route_departure_date" value="Thu" />Thu&nbsp;
                                      	<input type="checkbox" name="flight_route_departure_date0[]" id="flight_route_departure_date0" class="flight_route_departure_date" value="Fri" />Fri&nbsp;
                                      	<input type="checkbox" name="flight_route_departure_date0[]" id="flight_route_departure_date0" class="flight_route_departure_date" value="Sat" />Sat&nbsp;
                                    </div>
                                   	<div class="route_box_delete_row">
                                    	<div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($element->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                  	</div>
                                    <div class="route_box_second_row">
                                    	<?php echo $this->translator->translator('flight_route_arrival_label'); ?>
                                      	<input name="flight_route_arrival0" id="flight_route_arrival0" class="flight_route_arrival" value="" />
                                      
                                      	&nbsp;&nbsp;
                                      	<?php echo $this->translator->translator('flight_route_arrival_hour_label'); ?>
                                      	<select name="flight_route_arrival_date_hh0" id="flight_route_arrival_date_hh0" class="flight_route_arrival_date_hh">
                                        	<option value="00"><?php echo $this->translator->translator('flight_route_arrival_hour_label'); ?></option>
                                        	<?php $hr = 0; for($i = 0; $i <= 24; $i++){ $hr = ($i < 10 ) ? '0'.$i : $i; ?> 
                                        	<option value="<?php echo $hr; ?>"><?php echo $hr; ?></option>
                                        	<?php } ?>
                                      	</select>
                                      	&nbsp;&nbsp;
                                      	<?php echo $this->translator->translator('flight_route_arrival_min_label'); ?>
                                      	<select name="flight_route_arrival_date_mn0" id="flight_route_arrival_date_mn0" class="flight_route_arrival_date_mn">
                                        	<option value="00"><?php echo $this->translator->translator('flight_route_arrival_min_label'); ?></option>
                                        	<?php $mn = 0; for($i = 0; $i <= 60; $i++){ $mn = ($i < 10 ) ? '0'.$i : $i; ?> 
                                        	<option value="<?php echo $mn; ?>"><?php echo $mn; ?></option>
                                        	<?php } ?>
                                      	</select>
                                      	<br />
                                     	<?php echo $this->translator->translator('flight_route_arrival_date_label'); ?>
                                      	<input type="checkbox" name="flight_route_arrival_date0[]" id="flight_route_arrival_date0" class="flight_route_arrival_date" value="Sun" />Sun&nbsp;
                                      	<input type="checkbox" name="flight_route_arrival_date0[]" id="flight_route_arrival_date0" class="flight_route_arrival_date" value="Mon" />Mon&nbsp;
                                      	<input type="checkbox" name="flight_route_arrival_date0[]" id="flight_route_arrival_date0" class="flight_route_arrival_date" value="Tue" />Tue&nbsp;
                                      	<input type="checkbox" name="flight_route_arrival_date0[]" id="flight_route_arrival_date0" class="flight_route_arrival_date" value="Wed" />Wed&nbsp;
                                      	<input type="checkbox" name="flight_route_arrival_date0[]" id="flight_route_arrival_date0" class="flight_route_arrival_date" value="Thu" />Thu&nbsp;
                                      	<input type="checkbox" name="flight_route_arrival_date0[]" id="flight_route_arrival_date0" class="flight_route_arrival_date" value="Fri" />Fri&nbsp;
                                      	<input type="checkbox" name="flight_route_arrival_date0[]" id="flight_route_arrival_date0" class="flight_route_arrival_date" value="Sat" />Sat&nbsp;												  
                                  	</div>																	 
                                </div>
							</div>
                            <div class="left-float">
                            	<span class="select-btn ui-widget-content-1"><a href="javascript: void(0);" class="flight_route_add_more_btn"><span class="icon add"><?php echo $this->translator->translator('flight_route_add_more'); ?></span></a></span>
                            </div>
                            <div class="input-errors" id="<?php echo $element->getName().'_err'; ?>"></div>
                        </div>
                    </div>
                    <?php
						}
						else if($element->getName() == 'flight_route_round')
						{
					?>
                    <div class="form-row">
                        <div class="label">
                        	<?php echo $element->getLabel();  if($element->isRequired()){ ?><span class="required">*</span><?php } ?><?php echo $element; ?>
                        </div>
                        
                        <div class="field">
                        	<div id="route_fields_round" class="route_fields">
								<div class="route_box">
                               		<div class="route_box_first_row">
                                   		<?php echo $this->translator->translator('flight_route_departure_label'); ?>
                                      	<input name="flight_route_departure_round0" id="flight_route_departure_round0" class="flight_route_departure_round" value="" />													  	
                                      
                                      	&nbsp;&nbsp;
                                      	<?php echo $this->translator->translator('flight_route_departure_hour_label'); ?>
                                      	<select name="flight_route_departure_date_hh_round0" id="flight_route_departure_date_hh_round0" class="flight_route_departure_date_hh_round">
                                        	<option value="00"><?php echo $this->translator->translator('flight_route_departure_hour_label'); ?></option>
                                        	<?php $hr = 0; for($i = 0; $i <= 24; $i++){ $hr = ($i < 10 ) ? '0'.$i : $i; ?> 
                                        	<option value="<?php echo $hr; ?>"><?php echo $hr; ?></option>
                                        	<?php } ?>
                                      	</select>
                                      	&nbsp;&nbsp;
                                      	<?php echo $this->translator->translator('flight_route_departure_min_label'); ?>
                                      	<select name="flight_route_departure_date_mn_round0" id="flight_route_departure_date_mn_round0" class="flight_route_departure_date_mn_round">
                                        	<option value="00"><?php echo $this->translator->translator('flight_route_departure_min_label'); ?></option>
                                        	<?php $mn = 0; for($i = 0; $i <= 60; $i++){ $mn = ($i < 10 ) ? '0'.$i : $i; ?> 
                                        	<option value="<?php echo $mn; ?>"><?php echo $mn; ?></option>
                                        <?php } ?>
                                      	</select>
                                      	<br />
                                      	<?php echo $this->translator->translator('flight_route_departure_date_label'); ?>
                                      	<input type="checkbox" name="flight_route_departure_date_round0[]" id="flight_route_departure_date_round0" class="flight_route_departure_date_round" value="Sun" />Sun&nbsp;
                                      	<input type="checkbox" name="flight_route_departure_date_round0[]" id="flight_route_departure_date_round0" class="flight_route_departure_date_round" value="Mon" />Mon&nbsp;
                                      	<input type="checkbox" name="flight_route_departure_date_round0[]" id="flight_route_departure_date_round0" class="flight_route_departure_date_round" value="Tue" />Tue&nbsp;
                                      	<input type="checkbox" name="flight_route_departure_date_round0[]" id="flight_route_departure_date_round0" class="flight_route_departure_date_round" value="Wed" />Wed&nbsp;
                                      	<input type="checkbox" name="flight_route_departure_date_round0[]" id="flight_route_departure_date_round0" class="flight_route_departure_date_round" value="Thu" />Thu&nbsp;
                                      	<input type="checkbox" name="flight_route_departure_date_round0[]" id="flight_route_departure_date_round0" class="flight_route_departure_date_round" value="Fri" />Fri&nbsp;
                                      	<input type="checkbox" name="flight_route_departure_date_round0[]" id="flight_route_departure_date_round0" class="flight_route_departure_date_round" value="Sat" />Sat&nbsp;
                                    </div>
                                   	<div class="route_box_delete_row">
                                    	<div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($element->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                  	</div>
                                    <div class="route_box_second_row">
                                    	<?php echo $this->translator->translator('flight_route_arrival_label'); ?>
                                      	<input name="flight_route_arrival_round0" id="flight_route_arrival_round0" class="flight_route_arrival_round" value="" />
                                      
                                      	&nbsp;&nbsp;
                                      	<?php echo $this->translator->translator('flight_route_arrival_hour_label'); ?>
                                      	<select name="flight_route_arrival_date_hh_round0" id="flight_route_arrival_date_hh_round0" class="flight_route_arrival_date_hh_round">
                                        	<option value="00"><?php echo $this->translator->translator('flight_route_arrival_hour_label'); ?></option>
                                        	<?php $hr = 0; for($i = 0; $i <= 24; $i++){ $hr = ($i < 10 ) ? '0'.$i : $i; ?> 
                                        	<option value="<?php echo $hr; ?>"><?php echo $hr; ?></option>
                                       		<?php } ?>
                                      	</select>
                                      	&nbsp;&nbsp;
                                      	<?php echo $this->translator->translator('flight_route_arrival_min_label'); ?>
                                      	<select name="flight_route_arrival_date_mn_round0" id="flight_route_arrival_date_mn_round0" class="flight_route_arrival_date_mn_round">
                                        	<option value="00"><?php echo $this->translator->translator('flight_route_arrival_min_label'); ?></option>
                                        	<?php $mn = 0; for($i = 0; $i <= 60; $i++){ $mn = ($i < 10 ) ? '0'.$i : $i; ?> 
                                        	<option value="<?php echo $mn; ?>"><?php echo $mn; ?></option>
                                        	<?php } ?>
                                      	</select>
                                      	<br />
                                      	<?php echo $this->translator->translator('flight_route_arrival_date_label'); ?>
                                      	<input type="checkbox" name="flight_route_arrival_date_round0[]" id="flight_route_arrival_date_round0" class="flight_route_arrival_date_round" value="Sun" />Sun&nbsp;
                                      	<input type="checkbox" name="flight_route_arrival_date_round0[]" id="flight_route_arrival_date_round0" class="flight_route_arrival_date_round" value="Mon" />Mon&nbsp;
                                      	<input type="checkbox" name="flight_route_arrival_date_round0[]" id="flight_route_arrival_date_round0" class="flight_route_arrival_date_round" value="Tue" />Tue&nbsp;
                                      	<input type="checkbox" name="flight_route_arrival_date_round0[]" id="flight_route_arrival_date_round0" class="flight_route_arrival_date_round" value="Wed" />Wed&nbsp;
                                      	<input type="checkbox" name="flight_route_arrival_date_round0[]" id="flight_route_arrival_date_round0" class="flight_route_arrival_date_round" value="Thu" />Thu&nbsp;
                                      	<input type="checkbox" name="flight_route_arrival_date_round0[]" id="flight_route_arrival_date_round0" class="flight_route_arrival_date_round" value="Fri" />Fri&nbsp;
                                      	<input type="checkbox" name="flight_route_arrival_date_round0[]" id="flight_route_arrival_date_round0" class="flight_route_arrival_date_round" value="Sat" />Sat&nbsp;												  
                                  </div>																	 
                                </div>
							</div>
                            <div class="left-float">
                           		<span class="select-btn ui-widget-content-1"><a href="javascript: void(0);" class="flight_route_add_more_btn_round"><span class="icon add"><?php echo $this->translator->translator('flight_route_add_more'); ?></span></a></span>
                            </div>
                            <div class="input-errors" id="<?php echo $element->getName().'_err'; ?>"></div>
                        </div>
                    </div>
                    <?php
						}
						else
						{
					?>
                    <div class="form-row">
                        <div class="label">
                        	<?php echo $element->getLabel();  if($element->isRequired()){ ?><span class="required">*</span><?php } ?>
                        </div>
                        
                        <div class="field">
                        	<?php echo $element; if($element->getName() == 'flight_adult_fair' || $element->getName() == 'flight_child_fair' || $element->getName() == 'flight_infant_fair' || $element->getName() == 'flight_adult_fair_round' || $element->getName() == 'flight_child_fair_round' || $element->getName() == 'flight_infant_fair_round') { echo '&nbsp;'.$currency->getSymbol(); } if($element->getName() == 'flight_tax' || $element->getName() == 'flight_tax_round'){ echo '&nbsp;%'; } ?>
                            <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($element->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                            <div class="input-errors" id="<?php echo $element->getName().'_err'; ?>"></div>
                        </div>
                    </div>
                    <?php
						}
					}
					?>
                </div>
			</fieldset>
			</div>
            <?php
				 }
			?>
	</form>
    <div class="button-container">
        <span class="button ui-widget-content-1"><a href="<?php echo $this->url( array('module' => 'Flight','controller' => 'route', 'action'     => 'list' ), 'adminrout',    true) ?>" class="back_btn_link"><span class="icon back"><?php echo $this->translator->translator('common_back'); ?></span></a></span>
        <span class="button ui-widget-content-1"><a href="javascript:  void(0);" class="reset_btn"><span class="icon reset"><?php echo $this->translator->translator('common_reset'); ?></span></a></span>
        <span class="button ui-widget-content-1"><a href="javascript: void(0);" class="add_flight_route_btn"><span class="icon save"><?php echo $this->translator->translator('common_save'); ?></span></a></span>
	</div>
</div>

<div id="floatingbar">
	<h1><?php echo $this->translator->translator('flight_route_add_page_name'); ?></h1>
    <div class="button-container">
        <span class="button ui-widget-content-1"><a href="<?php echo $this->url( array('module' => 'Flight','controller' => 'route', 'action'     => 'list' ), 'adminrout',    true) ?>" class="back_btn_link"><span class="icon back"><?php echo $this->translator->translator('common_back'); ?></span></a></span>
        <span class="button ui-widget-content-1"><a href="javascript:  void(0);" class="reset_btn"><span class="icon reset"><?php echo $this->translator->translator('common_reset'); ?></span></a></span>
        <span class="button ui-widget-content-1"><a href="javascript: void(0);" class="add_flight_route_btn"><span class="icon save"><?php echo $this->translator->translator('common_save'); ?></span></a></span>
	</div>
</div>

<?php endif; ?>
<div id="dialog_msg" title="<?php echo $this->translator->translator('common_dialog_msg',$this->translator->translator('flight_route_add_page_name')); ?>">
</div>
<div id="dialog_container" style="display:none" title="<?php echo $this->translator->translator('common_processing_language'); ?>">
	<div id="progressbar" ></div>	
</div>
</div>