<?php
$version = Zend_Registry::get('version');
$auth = Zend_Auth::getInstance ();

$image_value = $this->airlinesForm->airlines_logo->getValue();
if($image_value)
{
	$image_arr = explode(',',$image_value);
	foreach($image_arr as $key=>$value)
	{
		$checked = ($value == $this->airlinesForm->primary_image->getValue()) ? ' checked="checked" ' : '';
		$img_type = ($value == $this->airlinesForm->primary_image->getValue()) ? '<span class="main">'.$this->translator->translator('gallery_img_main', '', 'Gallery').'</span>' : '<span class="related">'.$this->translator->translator('gallery_img_related', '', 'Gallery').'</span>';
		$class_link = ($auth->getIdentity()->access_file_image_manager == '1') ? 'delete_image_lnk' : 'delete_uploaded_image_link';
		if(!empty($value))
		{
			$assign_image .=  '<div class="upload-img box">'.$img_type.'<br /><span><div class="thumb"><img src="data/frontImages/flight/airlines/'.$value.'" width="45" height="35" class="bdr" /></div><br /><br /><a href="javascript:void(0)" class="'.$class_link.'" field_name="airlines_logo" file_name="'.$value.'" file_path="data/frontImages/flight/airlines" rel="'.$value.'">'.$this->translator->translator('common_delete_title').'</a><input class="radio_style" type="radio" name="primary_image" id="primary_image" '.$checked.' value="'.$value.'" title="'.$this->translator->translator('flight_primary_image').'" />&nbsp;</span></div>';
		}
	}
}

?>

<script type="text/javascript">
$(document).ready(function() {	
	floatingbar('#floatingbar',"#button_top_bar",null);
	imageThumbnil();
	deleteFiles("<?php echo $this->translator->translator('gallery_img_main','', 'Gallery'); ?>", "<?php echo $this->translator->translator('gallery_img_related','', 'Gallery'); ?>", "<?php echo $this->url( array('module' => 'Portfolio','controller' => 'frontend', 'action'     => 'remove' ), 'adminrout',    true) ?>", "<?php echo $this->translator->translator('common_delete_title'); ?>");
	
	function openMsgDialog(msg)
	{
		$('#dialog_msg').html(msg).dialog({
			autoOpen: true,
			modal: true,
			show: 'explode',
			resizable: true,				
			buttons: [{ text: "<?php echo html_entity_decode($this->translator->translator('common_ok'), ENT_QUOTES, 'UTF-8'); ?>", click: function() { $(this).dialog('option', 'hide', 'explode').dialog("close"); } } ],
			open: function(event, ui)
				 {
					setTimeout(function() 
					{									
						if($('#' + event.target.id).dialog('isOpen'))
						{
							$('#' + event.target.id).dialog('option', 'hide', 'explode').dialog('close');										
						}
					}, 10000);
				  }
		});
	}
	
	$("#upload-form").dialog({
		autoOpen: false,
		width: 760,
		height: 610,
		show: 'fade',			
		modal: true
	});	

	$('a.upload_btn').click(function() {		
		var self = this;
		var src = $("#i-upload-form").attr("src");
		$("#i-upload-form").attr("src", '');
		
		$('input[name="primary_id_field_value"]').val('1');
		
		var rel = $(self).attr('rel');		
		var file_suffix = rel;	
		var file_content = $('#'+file_suffix).val();
		
		$('input[name="file_path_field"]').val('file_path_'+rel);
		$('input[name="file_content"]').val(file_content);		
		$('input[name="primary_file_field"]').val(file_suffix);			
		
		$("#popupForm").attr("action", "<?php echo $this->url( array('module' => 'Portfolio','controller' => 'frontend', 'action' => 'manager' ), 'adminrout',    true) ?>");			
		$('#upload-form').dialog('open');
		$('#popupForm').submit();	
		
	});	
	
	$('a.select_file_btn').click(function() {		 
		
			var currentIFrame = $('#i-upload-form');
			var selected_files = currentIFrame.contents().find("input[name='selected_files']").val();
			var primary_file_field = currentIFrame.contents().find("input[name='primary_file_field']").val();
			var file_path	=	currentIFrame.contents().find("input[name='file_path']").val();
			var selected_files_arr = (selected_files != '') ? selected_files.split(',') : new Array();	
			if(selected_files_arr.length == '0')
			{
				var msg = '<?php echo $this->translator->translator("insert_selected_file_err"); ?>';				
				openMsgDialog(msg);
			}
			else
			{
				var img_code = '';
				var file_name = '';
				for(var i=0;i < selected_files_arr.length;i++)
				{
					var ext = getFileExtension(selected_files_arr[i]);
					var img_path = '';
					switch(ext)
					{
						case 'flv':
						case 'swf':
						case 'FLV':
						case 'SWF':
							img_path = 'application/modules/Administrator/layouts/scripts/images/common/flash.png';
							break;
						case 'mp3':
						case 'MP3':
							img_path = 'application/modules/Administrator/layouts/scripts/images/common/mp3.png';
							break;
						case 'avi':
						case 'wmv':
						case 'wma':
						case 'WMA':
						case 'AVI':
						case 'WMV':
							img_path = 'application/modules/Administrator/layouts/scripts/images/common/avi_thumb.png';
							break;
						case 'pdf':
						case 'doc':
						case 'docx':
						case 'xls':
						case 'xlsx':
						case 'ppt':
						case 'pptx':
						case 'PDF':
						case 'DOC':
						case 'DOCX':
						case 'XLS':
						case 'XLSX':
						case 'PPT':
						case 'PPTX':
							img_path = 'application/modules/Administrator/layouts/scripts/images/common/'+ext.toLowerCase()+'.png';
							break;
						default:
							img_path = file_path +'/'+ selected_files_arr[i]; 
							break;
					}
					
					var checked = (i == 0)? ' checked="checked" ' : '';
					var img_type = 	(i == 0) ? "<span class='main'><?php echo $this->translator->translator('gallery_img_main', '', 'Gallery'); ?></span>" : "<span class='related'><?php echo $this->translator->translator('gallery_img_related', '', 'Gallery'); ?></span>";
					var primary_file_field_radio =	 'primary_image';						
					var primary =  '<input class="radio_style" type="radio" name="'+primary_file_field_radio+'" id="'+primary_file_field_radio+'" '+checked+' value="'+selected_files_arr[i]+'" title="<?php echo $this->translator->translator("traveler_photos"); ?>" />';
					var del_link = '<a href="javascript:void(0)" class="delete_image_lnk" rel="'+selected_files_arr[i]+'"><?php echo html_entity_decode($this->translator->translator("common_delete"), ENT_QUOTES, "UTF-8"); ?></a>'+primary;
					
					img_code += '<div class="upload-img box">'+img_type+'<br /><span><div class="thumb"><img src="'+img_path+'" width="45" height="35" class="bdr" /></div><br /><br />'+del_link+'&nbsp;</span></div>';
					file_name = (i == 0)? selected_files_arr[i] : file_name+','+selected_files_arr[i];					
				}			
				var file_suffix = primary_file_field;		
				$('#selected_file_'+file_suffix).html(img_code);		
				$('#'+file_suffix).val(file_name);		
				$("#i-upload-form").attr("src", ''); 						
				$("#upload-form").dialog('option','hide','explode').dialog('close');				
				deleteFiles("<?php echo $this->translator->translator('gallery_img_main', '', 'Gallery'); ?>", "<?php echo $this->translator->translator('gallery_img_related', '', 'Gallery'); ?>", "<?php echo $this->url( array('module' => 'Portfolio','controller' => 'frontend', 'action'     => 'remove' ), 'adminrout',    true) ?>", "<?php echo $this->translator->translator('common_delete_title'); ?>");	
				imageThumbnil();
			}
		});
	
	$('a.close_dialog_btn').click(function() {	
		$("#i-upload-form").attr("src", "");
		$("#i-upload-form").html('');		 
		$("#upload-form").dialog('option','hide','explode').dialog('close');			
	});
		
	$('a.reset_btn').click(function() {			
		 resetFields();	
		 removeError();	
	});
	
	function resetFields()
	{
		$( "form" )[ 0 ].reset();		
		$('#selected_file_airlines_logo').html('<?php echo $assign_image; ?>');		
		$('#primary_image').val('<?php echo $this->airlinesForm->primary_image->getValue(); ?>');
		$('#airlines_logo').val('<?php echo $this->airlinesForm->airlines_logo->getValue(); ?>');	
		imageThumbnil();
		deleteFiles("<?php echo $this->translator->translator('gallery_img_main','', 'Gallery'); ?>", "<?php echo $this->translator->translator('gallery_img_related','', 'Gallery'); ?>", "<?php echo $this->url( array('module' => 'Portfolio','controller' => 'frontend', 'action'     => 'remove' ), 'adminrout',    true) ?>", "<?php echo $this->translator->translator('common_delete_title'); ?>");
	}
	
	function removeError()
	{
		$('#actionMessage').html('');
		$('#primary_image_err').html('');
		
		var filename = '';
		var filevalue = '';		
		$.each($('form').serializeArray(), function(i, field) {	
				if(field.name.match(/\[\]$/))
				{
					var filearr = field.name.split('[]');
					filename = filearr[0];					
				}
				else
				{
					filename 	= 	field.name;
				} 			
				$('#'+filename).removeClass('ui-state-error');
				$('#'+filename+'_err').html('');									
		});				
	}		
	
	function addError(key,errMsg)
	{
		var err_id = key+'_err';
		var field_name = key;
		$('#'+field_name).addClass('ui-state-error');
		$('#'+err_id).append(errMsg);
	}
	
	function openLoaderDialog()
	{
		$('#dialog_container').dialog({
			  autoOpen: true,
			  modal: true,
			  show: 'explode',
			  resizable: false,				
			  open: function(event, ui)
				   {
					  $("#progressbar").progressbar({
						  value:100
		  
					  });							
					}
		  });
	}
	
	function closeLoaderDialog()
	{
		$('#dialog_container').dialog('option','hide','explode').dialog('close');
	}
	
	function getFormData()
	{
		var fieldObj = {};
		var filename = '';
		var filevalue = '';
		$.each($('form').serializeArray(), function(i, field) {	
			if(field.name.match(/\[\]$/))
			{
				var filearr = field.name.split('[]');
				filename = filearr[0];
				filevalue = $('#'+filename).val();
			}
			else
			{
				filename 	= 	field.name;
				filevalue 	= 	field.value;
			}			
			fieldObj[filename] = filevalue;			
		});
		return fieldObj;
	}
	
	$('a.edit_airlines_btn').click(function() {			
			
			var formData = getFormData();	
			formData.id = '<?php echo $this->id; ?>';				
		$.ajax({
				url: "<?php echo $this->url( array('module' => 'Flight','controller' => 'airlines', 'action'     => 'edit' ), 'adminrout',    true) ?>",
			  	type: 'POST',
				beforeSend: function(){						
						removeError();
						openLoaderDialog();				
					 },
			  	data: formData,
				success: function(response){
					//alert(response);					
					var json_arr = eval("("+response+")");					
					closeLoaderDialog();					
					if(json_arr.status == 'ok')
					{
						$('#actionMessage').html(succMsgDesign(json_arr.msg));													
					}
					else if(json_arr.status == 'errV')
					{
						$('#actionMessage').html(errMsgDesign("<?php echo $this->translator->translator('common_err'); ?>"));
												
						for(var i= 0; i < json_arr.msg.length; i++)
						{
							addError(json_arr.msg[i].key,json_arr.msg[i].value);							
						}
					}
					else
					{
						$('#actionMessage').html(errMsgDesign(json_arr.msg));
					}
				},
				error: function(xhr, status, error){
					closeLoaderDialog();
					var msg = "Error! " + xhr.status + " " + error;
					$('#actionMessage').html(errMsgDesign(msg));
				}
		});
	});
	
	
	
});


/************************************************IMAGE THUMBNIL************************************************/
function imageThumbnil()
{	
	$("span.thumb").hover(function() {
		$(this).css({'z-index' : '10'}); /*Add a higher z-index value so this image stays on top*/ 
		$(this).find('img').addClass("hover").stop() /* Add class of "hover", then stop animation queue buildup*/
			.animate({
				marginTop: '-110px', /* The next 4 lines will vertically align this image */ 
				marginLeft: '-110px',
				top: '50%',
				left: '50%',
				width: '174px', /* Set new width */
				height: '174px', /* Set new height */
				padding: '20px'
			}, 200); /* this value of "200" is the speed of how fast/slow this hover animates */
	
		} , function() {
		$(this).css({'z-index' : '0'}); /* Set z-index back to 0 */
		$(this).find('img').removeClass("hover").stop()  /* Remove the "hover" class , then stop animation queue buildup*/
			.animate({
				marginTop: '0', /* Set alignment back to default */
				marginLeft: '0',
				top: '0',
				left: '0',
				width: '30px', /* Set width back to default */
				height: '20px', /* Set height back to default */
				padding: '5px'
			}, 400);
	});
}

function getFileExtension(filename)
{
	return filename.replace(/^.*?\.([a-zA-Z0-9]+)$/, "$1");
}
</script>
<div id="container">
<?php if (!$this->allow()) : ?>
	<div class="grid_12 t_a_bottom">
		<?php echo $this->translator->translator('Member_Access_deny_desc'); ?>
	</div>
<?php else : ?>

<div class="title-container">
	<div class="airlines-edit"><h1><?php echo $this->translator->translator('flight_airlines_edit_page_name'); ?></h1></div>
    
    <div class="button-container">
        <span class="button ui-widget-content-1"><a href="<?php echo $this->url( array('module' => 'Flight','controller' => 'airlines', 'action'     => 'list' ), 'adminrout',    true) ?>" class="back_btn_link"><span class="icon back"><?php echo $this->translator->translator('common_back'); ?></span></a></span>
        <span class="button ui-widget-content-1"><a href="javascript:  void(0);" class="reset_btn"><span class="icon reset"><?php echo $this->translator->translator('common_reset'); ?></span></a></span>
        <span class="button ui-widget-content-1"><a href="javascript: void(0);" class="edit_airlines_btn"><span class="icon save"><?php echo $this->translator->translator('common_save'); ?></span></a></span>
    </div>
</div>

<div class="content-container">
	<form name="formCategory" id="formCategory" method="post">
    	<div id="button_top_bar"></div>
    	<div id="actionMessage"></div>
    	<div id="generalInfo">
        	<fieldset class="fieldset last">
                <legend class="legend"><?php echo $this->translator->translator('flight_airlines_add_page_info'); ?></legend>
                <div class="form">
                	<?php												
						$elements = $this->airlinesForm->getElements();
						foreach($elements as $element)
						{
							if($element->getName() == 'airlines_logo')
							{
					?>
                	<div class="form-row">
                        <div class="label">
                        	<?php echo $element->getLabel();  if($element->isRequired()){ ?><span class="required">*</span><?php } ?>
                        </div>
                        
                        <div class="field">
                        	<div class="upload-img">
                            	<span class="button ui-widget-content-1"><a href="javascript:  void(0);" class="upload_btn" rel="<?php echo $element->getName(); ?>"><span class="icon upload"><?php echo $this->translator->translator('common_upload'); ?></span></a></span>
                                <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($element->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                            </div>
                            <?php echo $element; ?>&nbsp;&nbsp;<span id="selected_file_airlines_logo"><?php echo $assign_image; ?></span>
                            <div class="input-errors" id="<?php echo $element->getName().'_err'; ?>"></div>                            
                        </div>
                    </div>
                    <?php
							}								
							else if($element->getName() == 'primary_image')
							{
					?>
                    
                    <div class="form-row">
                        <div class="label">
                        </div>
                        
                        <div class="field">
                        	<div class="input-errors" id="<?php echo $element->getName().'_err'; ?>"></div>
                        </div>
                    </div>
                    <?php
							}
							else
							{
					?>
                    <div class="form-row">
                        <div class="label">
                        	<?php echo $element->getLabel();  if($element->isRequired()){ ?><span class="required">*</span><?php } ?>
                        </div>
                        
                        <div class="field">
                        	<?php echo $element; if($element->getName() == 'basic_price' || $element->getName() == 'descount_price') { echo $currency->getSymbol(); }?>
                            <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($element->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                        	<div class="input-errors" id="<?php echo $element->getName().'_err'; ?>"></div>
                        </div>
                    </div>
                    <?php
							}
						}
					?>
                </div>
			</fieldset>
        </div>
	</form>
	<div class="button-container">
        <span class="button ui-widget-content-1"><a href="<?php echo $this->url( array('module' => 'Flight','controller' => 'airlines', 'action'     => 'list' ), 'adminrout',    true) ?>" class="back_btn_link"><span class="icon back"><?php echo $this->translator->translator('common_back'); ?></span></a></span>
        <span class="button ui-widget-content-1"><a href="javascript:  void(0);" class="reset_btn"><span class="icon reset"><?php echo $this->translator->translator('common_reset'); ?></span></a></span>
        <span class="button ui-widget-content-1"><a href="javascript: void(0);" class="edit_airlines_btn"><span class="icon save"><?php echo $this->translator->translator('common_save'); ?></span></a></span>
    </div>
</div>

<div id="floatingbar">
	<h1><?php echo $this->translator->translator('flight_airlines_edit_page_name'); ?></h1>
    
    <div class="button-container">
        <span class="button ui-widget-content-1"><a href="<?php echo $this->url( array('module' => 'Flight','controller' => 'airlines', 'action'     => 'list' ), 'adminrout',    true) ?>" class="back_btn_link"><span class="icon back"><?php echo $this->translator->translator('common_back'); ?></span></a></span>
        <span class="button ui-widget-content-1"><a href="javascript:  void(0);" class="reset_btn"><span class="icon reset"><?php echo $this->translator->translator('common_reset'); ?></span></a></span>
        <span class="button ui-widget-content-1"><a href="javascript: void(0);" class="edit_airlines_btn"><span class="icon save"><?php echo $this->translator->translator('common_save'); ?></span></a></span>
    </div>
</div>
<?php endif; ?>

<div id="dialog_msg" title="<?php echo $this->translator->translator('common_dialog_msg',$this->translator->translator('flight_airlines_edit_page_name')); ?>">
</div>
<div id="dialog_container" style="display:none" title="<?php echo $this->translator->translator('common_processing_language'); ?>">
	<div id="progressbar" ></div>	
</div>
<div id="upload-form" title="<?php echo $this->translator->translator('flight_upload_page_dialog'); ?>">
	<div>
    	<form id="popupForm" target="i-upload-form" method="post" action="" >
            <input type="hidden" name="table_name" value="flight_api"/>
            <input type="hidden" name="primary_id_field" value="id"/>
            <input type="hidden" name="primary_id_field_value" value="1"/>   
            <input type="hidden" name="primary_file_field" value="airlines_logo"/> 
           	<input type="hidden" name="file_content"  value=""/>       
            <input type="hidden" name="file_path_field" value="file_path_airlines_logo"/>
            <input type="hidden" name="file_extension_field" value="file_type"/>
            <input type="hidden" name="file_max_size_field" value="file_size_max"/>
    	</form>
    	<iframe id="i-upload-form" name="i-upload-form" src="" class="iframe-img-upload"></iframe>
    </div>
    <div class="button-container">
        <span class="button ui-widget-content-1"><a href="javascript:void(0);" class="select_file_btn"><span class="icon insert"><?php echo $this->translator->translator('flight_upload_page_insert'); ?></span></a></span>
        <span class="button ui-widget-content-1"><a href="javascript:void(0);" class="close_dialog_btn"><span class="icon close"><?php echo $this->translator->translator('common_close'); ?></span></a></span>
    </div>
</div>
</div>