<?php
$version = Zend_Registry::get('version');

echo $this->headScript()->setFile($this->baseUrl().'/js/jquery/jquery.scrollTo-min.js');

$global_conf = Zend_Registry::get('global_conf');
$currency = new Zend_Currency($global_conf['default_locale']);

$frontController = Zend_Controller_Front::getInstance();
?>

<script type="text/javascript">
$(function() {			
		autoSuggestion("airlines_code", "<?php echo $this->url( array('module'=> 'Flight', 'controller' => 'price', 'action'     => 'airlines' ), 'adminrout',    true) ?>", {'airlines_code': ''}, ['name', 'name', 'name', 'code', 'flight_value'], '', 3);			
});
$(document).ready(function() {	
	
	floatingbar('#floatingbar',"#button_top_bar",null);
	
	/**********Scrolling Tools Start****************/
	$.easing.elasout = function(x, t, b, c, d) {
		var s=1.70158;var p=0;var a=c;
		if (t==0) return b;  if ((t/=d)==1) return b+c;  if (!p) p=d*.3;
		if (a < Math.abs(c)) { a=c; var s=p/4; }
		else var s = p/(2*Math.PI) * Math.asin (c/a);
		return a*Math.pow(2,-10*t) * Math.sin( (t*d-s)*(2*Math.PI)/p ) + c + b;
	};
	
	$('#toc a').click(function(){//$.scrollTo works EXACTLY the same way, but scrolls the whole screen
		$.scrollTo( this.hash, 1500, { easing:'swing' });
		$(this.hash).find('span.message').text( this.title );
		return false;
	});
	
	$('span.top-go a').click(function(){//$.scrollTo works EXACTLY the same way, but scrolls the whole screen
		$.scrollTo( this.hash, 1500, { easing:'swing' });		
		return false;
	});
	
	/**********Scrolling Tools END****************/
	imageThumbnil();
	deleteFiles("<?php echo $this->translator->translator('gallery_img_main', '', 'Gallery'); ?>", "<?php echo $this->translator->translator('gallery_img_related', '', 'Gallery'); ?>", "<?php echo $this->url( array('module' => 'Portfolio','controller' => 'frontend', 'action'     => 'remove' ), 'adminrout',    true) ?>", "<?php echo $this->translator->translator('common_delete_title'); ?>");
		 
	function openMsgDialog(msg)
	{
		$('#dialog_msg').html(msg).dialog({
			autoOpen: true,
			modal: true,
			show: 'explode',
			resizable: true,				
			buttons: [{ text: "<?php echo html_entity_decode($this->translator->translator('common_ok'), ENT_QUOTES, 'UTF-8'); ?>", click: function() { $(this).dialog('option', 'hide', 'explode').dialog("close"); } } ],
			open: function(event, ui)
				 {
					setTimeout(function() 
					{									
						if($('#' + event.target.id).dialog('isOpen'))
						{
							$('#' + event.target.id).dialog('option', 'hide', 'explode').dialog('close');										
						}
					}, 10000);
				  }
		});
	}
	
	function stripslashes(str) 
	{
		str=str.replace(/\\'/g,'\'');
		str=str.replace(/\\"/g,'"');
		str=str.replace(/\\0/g,'\0');
		str=str.replace(/\\\\/g,'\\');
		return str;
	}
	
		
	$("#upload-form").dialog({
		autoOpen: false,
		width: 760,
		height: 610,
		show: 'fade',			
		modal: true
	});	

	$('a.upload_btn').click(function() {
		
		$("#i-upload-form").attr("src", '');
		$("#i-upload-form").html('');
				
		$('input[name="primary_id_field_value"]').val('1');
				
		var file_content = $('#airlines_pic').val();
		$('input[name="file_content"]').val(file_content);	
		
		$("#popupForm").attr("action", "<?php echo $this->url( array('module' => 'Portfolio','controller' => 'frontend', 'action' => 'manager' ), 'adminrout',    true) ?>");			
		$('#upload-form').dialog('open');
		$('#popupForm').submit();
		
	});	
	
	$('a.select_file_btn').click(function() {		 
		
			var currentIFrame = $('#i-upload-form');
			var selected_files = currentIFrame.contents().find("input[name='selected_files']").val();
			var primary_file_field = currentIFrame.contents().find("input[name='primary_file_field']").val();
			var file_path	=	currentIFrame.contents().find("input[name='file_path']").val();
			var selected_files_arr = (selected_files != '') ? selected_files.split(',') : new Array();	
			if(selected_files_arr.length == '0')
			{
				var msg = '<?php echo $this->translator->translator("insert_selected_file_err"); ?>';				
				openMsgDialog(msg);
			}
			else
			{
				var img_path = file_path +'/'+ selected_files_arr[0]; 	
				var del_link = '<a href="javascript:void(0)" class="delete_image_lnk" rel="'+selected_files_arr[0]+'"><?php echo html_entity_decode($this->translator->translator("common_delete"), ENT_QUOTES, "UTF-8"); ?></a>';						
				var img_code = '<div class="upload-img box"><span><div class="thumb"><img src="'+img_path+'" width="45" height="35" class="bdr" /></div><br /><br />'+del_link+'&nbsp;&nbsp;&nbsp;&nbsp;</span></div>';
				$('#selected_file_airlines_pic').html(img_code);
				$('#airlines_pic').val(selected_files_arr[0]);
				$("#i-upload-form").attr("src", '');
				$("#i-upload-form").html('');
				$("#upload-form").dialog('option','hide','explode').dialog('close');
				deleteFiles("<?php echo $this->translator->translator('gallery_img_main', '', 'Gallery'); ?>", "<?php echo $this->translator->translator('gallery_img_related', '', 'Gallery'); ?>", "<?php echo $this->url( array('module' => 'Portfolio','controller' => 'frontend', 'action'     => 'remove' ), 'adminrout',    true) ?>", "<?php echo $this->translator->translator('common_delete_title'); ?>");	
				imageThumbnil();
			}
		});
	
	$('a.close_dialog_btn').click(function() {	
		$("#i-upload-form").attr("src", "");
		$("#i-upload-form").html('');	 
		$("#upload-form").dialog('option','hide','explode').dialog('close');			
	});
		
	$('a.reset_btn').click(function() {			
		 resetFields();	
		 removeError();	
	});
	
	function resetFields()
	{
		$( "form" )[ 0 ].reset();
		var del_link = '&nbsp;<a href="javascript:void(0)" class="delete_image_lnk" rel="<?php echo $this->pricePlanForm->airlines_pic->getValue(); ?>"><?php echo html_entity_decode($this->translator->translator("common_delete"), ENT_QUOTES, "UTF-8"); ?></a>&nbsp;&nbsp;';
		var img_code = '<?php if($this->pricePlanForm->airlines_pic->getValue()){ ?><div class="upload-img box"><span><div class="thumb"><img src="<?php echo $this->img_path.'/'.$this->pricePlanForm->airlines_pic->getValue(); ?>" width="45" height="35" class="bdr" /></div><br /><br />'+del_link+'&nbsp;</span></div><?php } ?>';	
		$('#airlines_pic').val('<?php echo $this->pricePlanForm->airlines_pic->getValue(); ?>');
		$('#selected_file_airlines_pic').html(img_code);	
		imageThumbnil();
		deleteFiles("<?php echo $this->translator->translator('gallery_img_main', '', 'Gallery'); ?>", "<?php echo $this->translator->translator('gallery_img_related', '', 'Gallery'); ?>", "<?php echo $this->url( array('module' => 'Portfolio','controller' => 'frontend', 'action'     => 'remove' ), 'adminrout',    true) ?>", "<?php echo $this->translator->translator('common_delete_title'); ?>");
	}
	
	function removeError()
	{
		$('#actionMessage').html('');
		
		var filename = '';
		var filevalue = '';		
		$.each($('form').serializeArray(), function(i, field) {	
			if(field.name.match(/\[\]$/))
			{
				var filearr = field.name.split('[]');
				filename = filearr[0];					
			}
			else
			{
				filename 	= 	field.name;
			} 			
			$('#'+filename).removeClass('ui-state-error');
			$('#'+filename+'_err').html('');									
		});				
	}
	
	function addError(key,errMsg)
	{
		var err_id = key+'_err';
		var field_name = key;
		$('#'+field_name).addClass('ui-state-error');
		$('#'+err_id).append(errMsg);
	}
	
	function openLoaderDialog()
	{
		$('#dialog_container').dialog({
			autoOpen: true,
			modal: true,
			show: 'fade',
			resizable: 'false',				
			open: function(event, ui)
				 {
					$("#progressbar").progressbar({
						value:100
		
					});							
				  }
		});
	}
	
	function closeLoaderDialog()
	{
		$('#dialog_container').dialog('option','hide','explode').dialog('close');
	}
	
	function getFormData()
	{
		var fieldObj = {};
		var filename = '';
		var filevalue = '';
		$.each($('form').serializeArray(), function(i, field) {	
			if(field.name.match(/\[\]$/))
			{
				var filearr = field.name.split('[]');
				filename = filearr[0];
				filevalue = $('#'+filename).val();
			}
			else
			{
				filename 	= 	field.name;
				filevalue 	= 	field.value;
			}			
			fieldObj[filename] = filevalue;			
		});
		return fieldObj;
	}
	
	$('a.edit_flight_btn').click(function() {			
			
		var formData = getFormData();
		formData.id = '<?php echo $this->id; ?>';
		
		$.ajax({
			url: "<?php echo $this->url( array('module' => 'Flight','controller' => 'price', 'action'     => 'edit' ), 'adminrout',    true) ?>",
			  	type: 'POST',
			  	data: formData,
				beforeSend: function(){						
						removeError();
						openLoaderDialog();				
					 },
				success: function(response){
					//alert(response);					
					var json_arr = eval("("+response+")");					
					closeLoaderDialog();					
					if(json_arr.status == 'ok')
					{
						$('#actionMessage').html(succMsgDesign(json_arr.msg));								
					}
					else if(json_arr.status == 'errV')
					{
						$('#actionMessage').html(errMsgDesign("<?php echo $this->translator->translator('common_err'); ?>"));
												
						for(var i= 0; i < json_arr.msg.length; i++)
						{
							addError(json_arr.msg[i].key,json_arr.msg[i].value);							
						}
					}
					else
					{
						$('#actionMessage').html(errMsgDesign(json_arr.msg));
					}
				},
				error: function(xhr, status, error){
					closeLoaderDialog();
					var msg = "Error! " + xhr.status + " " + error;
					$('#actionMessage').html(errMsgDesign(msg));
				}
		});
	});
	
		
	
});


/************************************************IMAGE THUMBNIL************************************************/
function imageThumbnil()
{	
	$("span.thumb").hover(function() {
		$(this).css({'z-index' : '10'}); /*Add a higher z-index value so this image stays on top*/ 
		$(this).find('img').addClass("hover").stop() /* Add class of "hover", then stop animation queue buildup*/
			.animate({
				marginTop: '-110px', /* The next 4 lines will vertically align this image */ 
				marginLeft: '-110px',
				top: '50%',
				left: '50%',
				width: '174px', /* Set new width */
				height: '174px', /* Set new height */
				padding: '20px'
			}, 200); /* this value of "200" is the speed of how fast/slow this hover animates */
	
		} , function() {
		$(this).css({'z-index' : '0'}); /* Set z-index back to 0 */
		$(this).find('img').removeClass("hover").stop()  /* Remove the "hover" class , then stop animation queue buildup*/
			.animate({
				marginTop: '0px', /* Set alignment back to default */
				marginLeft: '0',
				top: '0',
				left: '0',
				width: '30px', /* Set width back to default */
				height: '20px', /* Set height back to default */
				padding: '5px'
			}, 400);
	});
}
function getFileExtension(filename)
{
	return filename.replace(/^.*?\.([a-zA-Z0-9]+)$/, "$1");
}

</script>

<div id="container">
<?php if (!$this->allow()) : ?>
	<div class="grid_12 t_a_bottom">
		<?php echo $this->translator->translator('Member_Access_deny_desc'); ?>
	</div>
<?php else : ?>

<div class="title-container">
	<div class="price-edit"><h1><?php echo $this->translator->translator('flight_page_edit_page_name'); ?></h1></div>
    
    <div class="button-container">
        <span class="button ui-widget-content-1"><a href="<?php echo $this->url( array('module' => 'Flight','controller' => 'price', 'action'     => 'list' ), 'adminrout',    true) ?>" class="back_btn_link"><span class="icon back"><?php echo $this->translator->translator('common_back'); ?></span></a></span>
        <span class="button ui-widget-content-1"><a href="javascript:  void(0);" class="reset_btn"><span class="icon reset"><?php echo $this->translator->translator('common_reset'); ?></span></a></span>
        <span class="button ui-widget-content-1"><a href="javascript: void(0);" class="edit_flight_btn"><span class="icon save"><?php echo $this->translator->translator('flight_page_add_page_save'); ?></span></a></span>
    </div>
</div>

<div class="content-container">
	<form name="formCategory" id="formCategory" method="post">
    	<div id="button_top_bar"></div>
    	<div id="actionMessage"></div>
    	<div id="generalInfo">
        	<fieldset class="fieldset last">
                <legend class="legend"><?php echo $this->translator->translator('flight_page_page_info'); ?></legend>
                <div class="form">
                	<?php
						$elements = $this->pricePlanForm->getElements();
						foreach($elements as $element)
						{
					?>
	
					<div class="form-row">
                        <div class="label">
                        	<?php echo $element->getLabel();  if($element->isRequired()){ ?><span class="required">*</span><?php } ?>
                        </div>
                        
                        <div class="field">
                        	<?php
								if( $element->getType() == 'Zend_Form_Element_Hidden')
								{ 
									$img_value_arr = explode(',',$element->getValue());
							?>
                        	<div class="upload-img">
                            	<span class="button ui-widget-content-1"><a href="javascript:  void(0);" class="upload_btn"><span class="icon upload"><?php echo $this->translator->translator('common_upload'); ?></span></a></span>
                            </div>
                            <?php echo $element; ?>&nbsp;&nbsp;<span id="selected_file_airlines_pic"><?php
							if(!empty($img_value_arr[0]))
							{
								foreach($img_value_arr as $img_value_key => $img_value_arr_value)
								{
							?>
                            	<div class="upload-img box"><span><div class="thumb"><img src="<?php echo $this->img_path.'/'.$img_value_arr_value; ?>" width="45" height="35" class="bdr"/></span><br /><br />&nbsp;<a href="javascript:void(0)" class="delete_image_lnk" rel="<?php echo $img_value_arr_value; ?>"><?php echo html_entity_decode($this->translator->translator("common_delete"), ENT_QUOTES, "UTF-8"); ?></a>&nbsp;&nbsp;&nbsp;</span></div>
                            <?php
								}
							}
							?></span>
							<div class="input-errors" id="<?php echo $element->getName().'_err'; ?>"></div>
                            <?php
								}
								else
								{
							?>                            
							<?php echo $element; ?>
							<?php if($element->getAttrib('info')){ ?><div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($elements->getAttrib('info')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div><?php } ?>
                            <div class="input-errors" id="<?php echo $element->getName().'_err'; ?>"></div>
                            <?php
								}
							?>
                        </div>
                        
                 	</div>
                    <?php
						}
					?>
                </div>
			</fieldset>
		</div>
	</form>
    <div class="button-container">
        <span class="button ui-widget-content-1"><a href="<?php echo $this->url( array('module' => 'Flight','controller' => 'price', 'action'     => 'list' ), 'adminrout',    true) ?>" class="back_btn_link"><span class="icon back"><?php echo $this->translator->translator('common_back'); ?></span></a></span>
        <span class="button ui-widget-content-1"><a href="javascript:  void(0);" class="reset_btn"><span class="icon reset"><?php echo $this->translator->translator('common_reset'); ?></span></a></span>
        <span class="button ui-widget-content-1"><a href="javascript: void(0);" class="edit_flight_btn"><span class="icon save"><?php echo $this->translator->translator('flight_page_add_page_save'); ?></span></a></span>
    </div>
</div>

<div id="dialog_msg" title="<?php echo $this->translator->translator('common_dialog_msg',$this->translator->translator('flight_page_edit_page_name')); ?>"></div>
<div id="dialog_container" style="display:none" title="<?php echo $this->translator->translator('common_processing_language'); ?>">
	<div id="progressbar" ></div>	
</div>
<div id="floatingbar">
	<h1><?php echo $this->translator->translator('flight_page_edit_page_name'); ?></h1>
    
    <div class="button-container">
        <span class="button ui-widget-content-1"><a href="<?php echo $this->url( array('module' => 'Flight','controller' => 'price', 'action'     => 'list' ), 'adminrout',    true) ?>" class="back_btn_link"><span class="icon back"><?php echo $this->translator->translator('common_back'); ?></span></a></span>
        <span class="button ui-widget-content-1"><a href="javascript:  void(0);" class="reset_btn"><span class="icon reset"><?php echo $this->translator->translator('common_reset'); ?></span></a></span>
        <span class="button ui-widget-content-1"><a href="javascript: void(0);" class="edit_flight_btn"><span class="icon save"><?php echo $this->translator->translator('flight_page_add_page_save'); ?></span></a></span>
    </div>
</div>
<div id="upload-form" title="<?php echo $this->translator->translator('flight_page_image_dialog'); ?>" align="center">	
	<div>
    	<form id="popupForm" target="i-upload-form" method="post" action="" >
            <input type="hidden" name="table_name" value="flight_api"/>
            <input type="hidden" name="primary_id_field" value="id"/>
            <input type="hidden" name="primary_id_field_value" value="1"/>   
            <input type="hidden" name="primary_file_field" value="airlines_pic"/> 
           	<input type="hidden" name="file_content"  value=""/>       
            <input type="hidden" name="file_path_field" value="file_path_airlines_pic"/>
            <input type="hidden" name="file_extension_field" value="file_type"/>
            <input type="hidden" name="file_max_size_field" value="file_size_max"/>
    	</form>
    	<iframe id="i-upload-form" name="i-upload-form" src="" class="iframe-img-upload"></iframe>
    </div>
    <div class="button-container">
        <span class="button ui-widget-content-1"><a href="javascript:void(0);" class="select_file_btn"><span class="icon insert"><?php echo $this->translator->translator('flight_page_insert'); ?></span></a></span>
        <span class="button ui-widget-content-1"><a href="javascript:void(0);" class="close_dialog_btn"><span class="icon close"><?php echo $this->translator->translator('common_close'); ?></span></a></div>
    </div>
</div>
<?php endif; ?>	
</div>