<?php
echo $this->headScript()->setFile($this->baseUrl().'/js/jquery/table-sorter/jquery.dataTables.js');
?>
<script type="text/javascript">
$(document).ready(function() {
		
	floatingbar('#floatingbar',"#button_top_bar",null);
	/****************************Sorting Table Start*********************/
	var oTable = $("#sortTable").dataTable({
				"bPaginate": false,
				"bLengthChange": true,
				"bSearchable": true,
				"bFilter": true,
				"bSort": true,
				"bInfo": false,
				"bAutoWidth": true,
				"bProcessing": false,
				"bSortClasses": true,
				"bStateSave": false,
				"bServerSide": false,	
				"aaSorting": [[ 1, "asc" ]],			
				"aoColumnDefs": [ 
						{ "bSortable": false, "bSortClasses": false,  "aTargets": [ 0 ] }
					],
				"oLanguage" : { "sSearch": "<?php echo $this->translator->translator('jquery_filter'); ?>" }
			}); 	
	
	$('td', oTable.fnGetNodes()).hover( function() {		
		$(this).parents("tr:first").children('td').addClass( 'highlighted' );
	}, function() {
		$('td.highlighted').removeClass('highlighted');
	} );
	
	/* Get the rows which are currently selected */
	function fnGetSelected( oTableLocal )
	{
		var aReturn = new Array();
		var aTrs = oTableLocal.fnGetNodes();
		
		for ( var i=0 ; i<aTrs.length ; i++ )
		{
			if ( $(aTrs[i]).hasClass('row_selected') )
			{
				aReturn.push( aTrs[i] );
			}
		}
		return aReturn;
	}
	
	/****************************Sorting Table End*********************/
	
					
});
</script>

<div id="container">
<?php if (!$this->allow()) : ?>
	<div class="grid_12 t_a_bottom">
		<?php echo $this->translator->translator('Member_Access_deny_desc'); ?>
	</div>
<?php else : ?>

<div class="title-container">
	<div class="vehicle-plan"><h1><?php echo $this->translator->translator('cost_package_plan_list'); ?></h1></div>
    
    <div class="button-container">
    	<?php if ($this->allow('add','backendplan','Costcalculator')) : ?>
        <span class="button  ui-widget-content-1"><a href="<?php echo $this->url(array('module'=> 'Costcalculator','controller'=>'backendplan', 'action'=>'add'),'adminrout',true);?>"><span class="icon add"><?php echo $this->translator->translator('cost_package_plan_add_title'); ?></span></a></span>
        <?php endif; ?>
        
        <?php if ($this->allow('delete','backendplan','Costcalculator')) : ?>
        <span class="button  ui-widget-content-1"><a href="javascript: void(0);" class="delete_all"><span class="icon delete"><?php echo html_entity_decode($this->translator->translator("common_delete_selected"), ENT_QUOTES, "UTF-8"); ?></span></a></span>
        <?php endif; ?>
    </div>
</div>
<div id="button_top_bar"></div>
<div class="content-container">
	<div id="sidebar-inner">
    	<?php echo $this->partial('nav_menu.phtml');  ?>
    </div>
    
    
    <div id="content-inner">
    	<div class="pagination">
        	<?php echo $this->paginationControl($this->datas, 'Sliding', 'top_pagination.phtml'); ?>
        </div>
        
        <div class="chart">
            <div class="data-table">
            	<table id="sortTable" width="100%" align="center" cellpadding="0" cellspacing="0">
                   	<thead>
                    	<tr>
                     		<th width="4%" align="center"><input type="checkbox" name="checkAll" id="checkAll" class="checkAll_btn" /></th>
                     		<th width="6%"><?php echo $this->translator->translator('cost_list_page_id'); ?></th>
                   		  	<th width="40%"><?php echo $this->translator->translator('cost_list_page_name'); ?></th>
                       	  	<th width="40%"><?php echo $this->translator->translator('cost_package_plan_title'); ?></th>
                      		<th width="10%"><?php echo $this->translator->translator('common_action'); ?></th>
                    	</tr>
                   	</thead>
                    <tbody>
                    <?php 
                    $j = 1;
                    $packageDbObj = new Costcalculator_Model_DbTable_Package();
                    foreach ($this->datas as $entry): 
                        if($j % 2 == 0)
                        {
                            $onmouseout = "this.bgColor='#FFFFFF';";
                            $background = '#FFFFFF';
                        }
                        else
                        {
                            $onmouseout = "this.bgColor='#F7F7F7';";
                            $background = '#F7F7F7';
                        }
                        $package_name = $packageDbObj->getInfo($entry->package_id);
                    ?>
                   		<tr bgcolor="<?php echo $background; ?>" onmouseover="this.bgColor='#FCF5DD';" onmouseout="<?php echo $onmouseout; ?>">
                     		<td class="center checkbox"><input type="checkbox" name="checkbtn" id="checkbtn" value="<?php echo $this->escape($entry->id); ?>" class="check_btn" /></td>
                      		<td class="center"><?php echo $this->escape($entry->id); ?></td>
                      		<td><?php echo $this->escape($package_name['package_name']);?></td>
                      		<td><?php echo $this->escape($entry->plan_title);?> </td>
                      		<td class="tools-list">
                            	<ul>
                                	<li>
                                	<?php if ($this->allow('edit','backendplan','Costcalculator')) : ?>
                                	<a href="<?php echo $this->url( array('module'=> 'Costcalculator', 'controller' => 'backendplan', 'action'     => 'edit', 'id' => $this->escape($entry->plan_id)), 'adminrout',    true) ?>"><img src="application/modules/Administrator/layouts/scripts/images/tools/edit.png" title="<?php echo $this->translator->translator('common_edit_title'); ?>" border="0" /></a>
                                	<?php endif; ?>
                                    </li>
                                    
                          			<li>
                                	<?php if ($this->allow('delete','backendplan','Costcalculator')) : ?>
                                	<a href="javascript:void(0);" class="delete_btn"  rel="<?php echo $this->escape($entry->id); ?>"><img src="application/modules/Administrator/layouts/scripts/images/tools/delete.png" title="<?php echo $this->translator->translator('common_delete_title'); ?>" border="0" /></a>
                                	<?php endif; ?>
                                    </li>
                              	</ul>
                          	</td>
                       	</tr>
                   	<?php 											
                        $j++;
                        endforeach;
                  	?>
                   </tbody>
				</table>
            </div>
      	</div>
        
        <div class="pagination">
        	<?php echo $this->paginationControl($this->datas, 'Sliding', 'pagination.phtml'); ?>
        </div>   
	</div>
</div>

<div id="floatingbar">
	<h1><?php echo $this->translator->translator('cost_package_plan_list'); ?></h1>
    
    <div class="button-container">
    	<?php if ($this->allow('add','backendplan','Costcalculator')) : ?>
        <span class="button  ui-widget-content-1"><a href="<?php echo $this->url(array('module'=> 'Costcalculator','controller'=>'backendplan', 'action'=>'add'),'adminrout',true);?>"><span class="icon add"><?php echo $this->translator->translator('cost_package_plan_add_title'); ?></span></a></span>
        <?php endif; ?>
        
        <?php if ($this->allow('delete','backendplan','Costcalculator')) : ?>
        <span class="button  ui-widget-content-1"><a href="javascript: void(0);" class="delete_all"><span class="icon delete"><?php echo html_entity_decode($this->translator->translator("common_delete_selected"), ENT_QUOTES, "UTF-8"); ?></span></a></span>
        <?php endif; ?>
    </div>
</div>
<?php endif; ?>
<div id="dialog_container" title="<?php echo $this->translator->translator('common_dialog_msg',$this->translator->translator('cost_package_plan_list')); ?>"></div>
<div id="dialog-confirm" title="<?php echo $this->translator->translator('common_confirmation',$this->translator->translator('common_delete')); ?>"></div>
</div>